hpcaitech/ColossalAI

docs/parallelization.md
Move the description of tensor parallel methods on top of the description of pipeline parallel method.
=> reoder parallelization methods in parallelization documentation

colossalai/nn/optimizer/_utils.py
All-reduce over tensor parallel nodes should be ignored when there are no tensor parallel parameters.
=> fix: gradient clipping of FP16 optimizer

colossalai/builder/builder.py, colossalai/engine/_base_engine.py, colossalai/engine/schedule/_base_schedule.py, colossalai/engine/schedule/_no_pipeline.py, colossalai/engine/schedule/_pipeline.py, colossalai/initialize.py, colossalai/trainer/_trainer.py, configs/vit/vit_2d.py, examples/run_trainer.py
- Added gradient accumulation in Engine which can be control by the parameter 'gradient_accumulation'. 
- Changed the way learning rate scheduler to update. Users can control learning rate scheduler in Engine by parameter 'lr_scheduler_step' to update learning rate with steps or epochs. 
- But users need to specify total steps and warm up steps in configuration file.
=> Add gradient accumulation, fix lr scheduler

docs/conf.py, docs/index.rst, docs/index_zh.rst
When generating documentation, we can change the language by setting the environment variable SPHINX_LANG. The default language of is English, and now Chinese is also supported. Run `SPHINX_LANG=zh make html` in ColossalAI/docs directory to generate the Chinese documentation.
=> use env to control the language of doc

docs/conf.py, docs/index.rst, docs/index_zh.rst
When generating documentation, we can change the language by setting the environment variable SPHINX_LANG. The default language of is English, and now Chinese is also supported. Run `SPHINX_LANG=zh make html` in ColossalAI/docs directory to generate the Chinese documentation.
=> use env to control the language of doc (#24)

colossalai/initialize.py, colossalai/utils/__init__.py, colossalai/utils/common.py, colossalai/zero/__init__.py, colossalai/zero/zero_redundancy_optimizer_level_3.py
1. ZeRO3 doesn't use NaiveAMP
2. ZeRO3 doesn't sync parameters over data parallel process group
3. Provide a context to build massive models when using ZeRO3
=> fix zero3 fp16 and add zero3 model context

colossalai/initialize.py, colossalai/zero/__init__.py, colossalai/zero/zero_redundancy_optimizer_level_3.py, docs/zero.md, docs/zero_zh.md
1. ZeRO3 doesn't use NaiveAMP
2. ZeRO3 doesn't sync parameters over data parallel process group
3. Provide a context to build massive models when using ZeRO3
=> fix zero3 fp16 and add zero3 model context (#61)

colossalai/builder/__init__.py, colossalai/builder/pipeline.py
We kept the original PipelineModelInitializer, but renamed it to build_pipeline_model_from_cfg. We add a new function to build the pipeline parallel model: build_pipeline_model. User must pass a `torch.nn.Sequential` to this function.
Usage:
```python
from colossalai.builder import build_pipeline_model_from_cfg, build_pipeline_model
model = build_pipeline_model_from_cfg(model_cfg, num_model_chunks)
model = build_pipeline_model(sequential_model, num_model_chunks)
```
=> update pipeline model initializer

colossalai/amp/naive_amp/__init__.py, colossalai/amp/naive_amp/_fp16_optimizer.py, colossalai/builder/__init__.py, colossalai/builder/pipeline.py, colossalai/communication/p2p.py, colossalai/communication/utils.py, colossalai/context/parallel_context.py, colossalai/engine/gradient_handler/_data_parallel_gradient_handler.py, colossalai/engine/schedule/__init__.py, colossalai/engine/schedule/_pipeline_schedule.py, colossalai/initialize.py, colossalai/utils/__init__.py, colossalai/utils/common.py, docs/parallelization.md, tests/test_data_pipeline_tensor_parallel/run_cifar10_vit2d_with_pipeline.py, tests/test_trainer/test_pipeline/test_partition.py, tests/test_trainer/test_pipeline/test_pipeline_schedule.py
1. We add interleaved pipeline schedule. 
2. Update pipeline model initializer.
3. Fix Naive AMP
We kept the original `PipelineModelInitializer`, but renamed it `to build_pipeline_model_from_cfg`. We add a new function to build the pipeline parallel model: `build_pipeline_model`. User must pass a `torch.nn.Sequential` to this function.
Usage:
```python
from colossalai.engine.schedule import InterleavedPipelineSchedule
from colossalai.builder import build_pipeline_model_from_cfg, build_pipeline_model
model = build_pipeline_model_from_cfg(model_cfg, num_model_chunks)
model = build_pipeline_model(sequential_model, num_model_chunks)
schedule = InterleavedPipelineSchedule(num_microbatches, num_model_chunks)
```
`build_pipeline_model` and `build_pipeline_model_from_cfg` can also receive a key …
=> Add interleaved pipeline and fix naive amp

colossalai/engine/gradient_handler/__init__.py, colossalai/engine/gradient_handler/_pipeline_parallel_gradient_handler.py, colossalai/engine/schedule/_base_schedule.py, colossalai/engine/schedule/_non_pipeline_schedule.py, colossalai/engine/schedule/_pipeline_schedule.py, colossalai/initialize.py, colossalai/nn/layer/wrapper/__init__.py, colossalai/nn/layer/wrapper/pipeline_wrapper.py
This feature is especially useful when train GPT/BERT whose word embedding layer is used at the first and the end.
Usage:
```python
pipeline_size = gpc.get_world_size(ParallelMode.PIPELINE)
pipeline_rank = gpc.get_local_rank(ParallelMode.PIPELINE)
rank = gpc.get_global_rank()
wrapper = PipelineSharedModuleWrapper([0, pipeline_size - 1])
if pipeline_rank == 0:
print(f'==> Rank{rank} build PipelineGPTEmbedding1D')
model = PipelineGPTEmbedding1D(**kwargs).to(device)
wrapper.register_module(model.embedding.wte)
elif pipeline_rank == pipeline_size - 1:
print(f'==> Rank{rank} build PipelineGPTLMHead1D')
model = PipelineGPTLMHead1D(**kwargs).to(device)
wrapper.register_module(model.head)
else:
parts = _partition_uniform(num_layers, pipeline_size - 2, num_chunks)[pipeline_rank - 1]
models = [] …
```
=> add pipeline shared module wrapper and update load batch

colossalai/context/parallel_mode.py, colossalai/context/process_group_initializer/initializer_pipeline.py, colossalai/engine/schedule/_pipeline_schedule.py, docs/add_your_parallel.md, docs/add_your_parallel_zh.md, tests/test_trainer/test_pipeline/test_p2p.py
`PIPELINE_PREV` and `PIPELINE_NEXT` process group are no longer needed, since we use P2P communication now.
=> remove pipeline_prev/next group

colossalai/engine/schedule/_base_schedule.py, colossalai/engine/schedule/_non_pipeline_schedule.py, colossalai/engine/schedule/_pipeline_schedule.py, colossalai/trainer/_trainer.py
Add a argument (`return_output_label`) in `schedule.forward_backward_step`, `trainer.fit` and `trainer.evaluate`. The output of model and labels won't be returned, which can further reduce GPU memory usage especially when using pipeline parallelism. 
Optimize  loss accumulation in pipeline schedule. Use `loss.detach()` when accumulating it to avoid unexpected large memory usage.
=> optimize pipeline gpu memory usage

colossalai/context/config.py, colossalai/logging/__init__.py
1. Replace the default logger name 'root' with 'colossalai'
2. Add `disable_existing_loggers()`. Call this function before `colossalai.launch()` to disable existing loggers (e.g. torch.distributed.distributed_c10d).
=> update default logger

colossalai/context/config.py, colossalai/logging/__init__.py
1. Replace the default logger name 'root' with 'colossalai'
2. Add `disable_existing_loggers()`. Call this function before `colossalai.launch()` to disable existing loggers (e.g. torch.distributed.distributed_c10d).
=> update default logger (#100)

.github/workflows/build.yml
The previous CI is only triggered when reviewer is requested. Now it will be triggered when reviewer is requested and synchronization occurs.
=> enable CI after PR sync

examples/vit_b16_imagenet_data_parallel/dataloader/imagenet_dali_dataloader.py, examples/vit_b16_imagenet_data_parallel/mixup.py, examples/vit_b16_imagenet_data_parallel/train.py
Since the `load_batch()` in schedule except the label which dataloader returns is `torch.Tensor` or `dict`, we update the Imagenet DALI dataloader. And we add a `MixupAccuracy`, as the label is a `dict`.
=> update vit example for new API (#98)

colossalai/communication/__init__.py, colossalai/communication/p2p.py, colossalai/communication/utils.py, colossalai/engine/schedule/_pipeline_schedule.py, colossalai/initialize.py
Add scatter/gather optimization for pipeline parallel, which can reduce the communication load over pipeline when using 1D tensor parallel.
Usage:
```python
schedule = PipelineSchedule(NUM_MICRO_BATCHES, scatter_gather_tensors=True)
schedule = InterleavedPipelineSchedule(NUM_MICRO_BATCHES, num_chunks, scatter_gather_tensors=True)
```
The default value of `scatter_gather_tensors` is `False`. Note that this optimization is only effective when using 1D tensor parallel.
=> add scatter/gather optim for pipeline

colossalai/engine/schedule/_pipeline_schedule.py, tests/test_trainer/test_pipeline/model/resnet.py
Pipeline parallelism supports multi outputs and labels now. We also log the tensor shape and dtype of the output of model when using pipeline, and set the logging level to DEBUG to print.
=> pipeline last stage supports multi output

colossalai/kernel/jit/__init__.py, colossalai/kernel/jit/option.py
The original code will set jit fusion options by default. However, these options may not work on the latest PyTorch and CUDA version. We tested these options on A100 and performance can be worse compared to the case where no jit fusion is set. Thus, jit fusion should be set to be optional and exposed to the user.
=> removed jit default setting

.github/workflows/submodule.yml
The `benchmark` and `examples` submodules only point to a commit ID which can be outdated very soon. This github action will update the submodule commits automatically and create a pull request for this update.
=> added github action to synchronize submodule commits automatically

colossalai/engine/paramhooks/__init__.py, colossalai/engine/paramhooks/_base_paramhook.py, colossalai/engine/paramhooks/_param_hookmgr.py, tests/test_engine/test_engine/test_param_hook.py
Extract hook logic to common utils.
Provides a mechanism to register hooks to params so that users don't need to know how to use hooks (which requires reading a lot of documentation to gain knowledge).
double check with @ver217 , that the backward hook registered on a parameter can only be fired once during BWD.
=> add a common util for hooks registered on parameter.

colossalai/zero/init_ctx/__init__.py, colossalai/zero/init_ctx/init_context.py, colossalai/zero/sharded_param/sharded_param.py, tests/test_zero_data_parallel/test_init_context.py
A context for model initialization.
1. shard the model during initialization on-the-fly. It can reduce peak GPU memory usage.
Now init a 8B model, requires 32 GB GPU memory (data fp16 + grad fp32). Use this context. It requires 32 GB/#GPU memory. Also we can offload the param to CPU on-the-fly.
2. convert param data/grad to fp16
3. adapt the param to ShardedParamV2.
=> [zero] zero init context

colossalai/zero/sharded_model/sharded_model_v2.py, tests/components_to_test/__init__.py, tests/components_to_test/bert.py, tests/test_engine/test_engine.py, tests/test_zero_data_parallel/common.py, tests/test_zero_data_parallel/test_shard_model_v2.py
After adding a huggingface bert to unitest, I found some issues.
1. the inputs to sharded model can be integer tensors. We shall not cast it fp16.
2. the FWD+BWD can not obtain correct grads in the bert cast.
```
python test_shard_model_v2.py
```
I have skipped the underdevelopment test cases of sharded model.
=> [test] add bert unittest

.github/workflows/build.yml, colossalai/zero/sharded_model/sharded_model_v2.py
Current code can handle ZeRO-3. However, if we don't shard param (ZeRO-2), current code will throw errors, because of wrong grad shape. I fix grad shape, so that we can handle both ZeRO-3 and ZeRO-2.
=> [zero] fix grad shape error for ShardededModelv2

colossalai/context/random/__init__.py, colossalai/context/random/_helper.py, colossalai/context/random/seed_manager.py, tests/test_utils/test_activation_checkpointing.py
Need to reset the seeds if we manually add seeds to seed manager as this will affect other tests when running collective tests.
=> fixed bug in activation checkpointing test

colossalai/engine/ophooks/zero_hook.py, colossalai/zero/shard_utils/__init__.py, colossalai/zero/shard_utils/bucket_tensor_shard_strategy.py, tests/test_zero_data_parallel/test_init_context.py, tests/test_zero_data_parallel/test_shard_model_v2.py, tests/test_zero_data_parallel/test_shard_param.py, tests/test_zero_data_parallel/test_sharded_optim_v2.py, tests/test_zero_data_parallel/test_sharded_optim_v2_with_cpu_adam.py, tests/test_zero_data_parallel/test_state_dict.py
Add a bucket tensor shard strategy, which will gather a group of sharded tensor together. For naive tensor shard strategy, `bias` will be gathered seperately, which doesn't utilize bandwidth well. For bucket tensor shard strategy, we can pack `weight` and `bias` and gather them together.
=> [zero] Add bucket tensor shard strategy

setup.py
This PR fixes missing license meta data when using `pip show`
=> add license meta to setup.py

colossalai/engine/ophooks/zero_hook.py, colossalai/zero/init_ctx/init_context.py, colossalai/zero/sharded_model/sharded_model_v2.py, colossalai/zero/sharded_param/sharded_param.py, tests/test_zero_data_parallel/test_shard_model_v2.py
In order to support partial offload, we use double buffers to handle grad (`fp16_grad` and `fp32_grad`). `fp16_grad` is always on GPU, and `fp32_grad` may be partially on GPU and CPU.
=> [zero] use double buffers to handle grad

.github/workflows/build.yml
This is part of the efforts to tackle #443  
- Remove `apex` and `deepspeed` from the dependency list in the build workflow so that they are no longer installed on the fly in the CI. `deepspeed` is no longer our dependency and `apex` is built-in in the Nvidia NGC docker.
- configure the checkout action to use ssh to shorten checkout time
=> [DevOps] remove unneeded dependency in build workflow

tests/test_utils/test_gradient_accumluation.py, tests/test_utils/test_zero_gradient_clippling.py, tests/test_zero_data_parallel/test_init_context.py, tests/test_zero_data_parallel/test_shard_model_v2.py, tests/test_zero_data_parallel/test_shard_param.py, tests/test_zero_data_parallel/test_sharded_optim_v2.py, tests/test_zero_data_parallel/test_state_dict.py
Optimized zero-related tests with `colossalai.testing.parameterize`. This is the last part of the efforts to tackle #443 . The overall CI time is reduced from 20 min to 12 min.
=> [test] optimized zero data parallel test

colossalai/initialize.py, colossalai/zero/__init__.py, colossalai/zero/init_ctx/init_context.py, colossalai/zero/sharded_model/sharded_model_v2.py, colossalai/zero/sharded_optim/sharded_optim_v2.py, tests/test_zero_data_parallel/common.py, tests/test_zero_data_parallel/test_shard_model_v2.py, tests/test_zero_data_parallel/test_sharded_optim_v2.py, tests/test_zero_data_parallel/test_sharded_optim_with_sync_bn.py, tests/test_zero_data_parallel/test_state_dict.py, tests/test_zero_data_parallel/test_zero_engine.py
1. `ShardedOptimizerV2` can receive an optimizer instance now.
2. `ShardedModelV2` must receive a module which is initialized by `ZeroInitContext`.
3. `ZeroInitContext` cast buffers.
4. Update related unit tests.
5. TODO: update `initialize()`.
6. TODO: update method to configure `sharded startegy`.
=> [zero] update sharded optim and fix zero init ctx

colossalai/engine/ophooks/zero_hook.py, colossalai/initialize.py, colossalai/zero/__init__.py, colossalai/zero/shard_utils/base_shard_strategy.py, colossalai/zero/shard_utils/bucket_tensor_shard_strategy.py, colossalai/zero/shard_utils/tensor_shard_strategy.py, colossalai/zero/sharded_model/sharded_model_v2.py, colossalai/zero/sharded_optim/sharded_optim_v2.py, tests/test_zero_data_parallel/common.py, tests/test_zero_data_parallel/test_init_context.py, tests/test_zero_data_parallel/test_shard_param.py, tests/test_zero_data_parallel/test_sharded_optim_with_sync_bn.py, tests/test_zero_data_parallel/test_zero_engine.py
1. `ShardStrategy` receives process group when calling `shard()` and `gather()`, which allows user to construct a `ShardStrategy` instance in config file.
2. Update initiallize for ZeRO with new API.
3. Update related unit tests.
=> [zero] Update initialize for ZeRO

model_zoo/gpt/gpt.py
GPT embedding receives and returns unneeded `attention_mask`, which may lead to error when using pipeline parallel. I just remove it.
=> [model zoo] gpt embedding remove attn mask

colossalai/nn/optimizer/cpu_adam.py, colossalai/zero/sharded_model/sharded_model_v2.py, colossalai/zero/sharded_optim/sharded_optim_v2.py, colossalai/zero/sharded_param/sharded_param.py, tests/test_zero_data_parallel/common.py, tests/test_zero_data_parallel/test_sharded_optim_v2.py, tests/test_zero_data_parallel/test_zero_engine.py
We can reuse fp16 shard for param and grad now. During forward and backward pass, fp16 shard saves param. After backward, fp16 shard saves grad. This can reduce GPU memory usage.
=> [zero] sharded model support the reuse of fp16 shard

.github/workflows/build.yml, .github/workflows/compatibility_test.yml
Using proxy inside a docker container will lead to connection error, so stick to using Tsinghua source.
=> [devops] recover tsinghua pip source due to proxy issue

colossalai/engine/ophooks/zero_hook.py, colossalai/utils/memory_tracer/memstats_collector.py, colossalai/utils/memory_tracer/model_data_memtracer.py, colossalai/utils/memory_tracer/test_memstats_collector.py, colossalai/utils/memory_utils/utils.py, colossalai/zero/init_ctx/init_context.py, colossalai/zero/shard_utils/bucket_tensor_shard_strategy.py, colossalai/zero/shard_utils/tensor_shard_strategy.py, colossalai/zero/sharded_model/sharded_model_v2.py, colossalai/zero/sharded_optim/sharded_optim_v2.py, colossalai/zero/sharded_param/sharded_param.py, tests/test_utils/test_commons.py, tests/test_utils/test_tensor_move.py, tests/test_zero_data_parallel/test_init_context.py, tests/test_zero_data_parallel/test_shard_param.py
I want to depict the cuda memory usage curve of the non-model data in a warmup iteration.
non-model = system cuda usage - model-data.
The old implementation, which has been removed, incrementally traces the model tensor moving, allocating and releasing.
So I can know the volume changing, and derive current model data memory by adding and deleting the changed tensor.
The idea is stupid.
Now, I just scan the model and calculate the model param usage.
=> [zero] refactor model data tracing

colossalai/engine/ophooks/__init__.py, colossalai/engine/ophooks/zero_hook.py, colossalai/zero/init_ctx/init_context.py, tests/components_to_test/__init__.py, tests/components_to_test/no_leaf_module.py, tests/test_zero_data_parallel/test_shard_model_v2.py, tests/test_zero_data_parallel/test_sharded_optim_v2.py
At present, we only add Zero hooks for leaf nn.modules.
When a nn.module has both subordinate nn.Module and nn.Parameter, those parameters belonging to itself won't get 
processed.
=> [Zero] process no-leaf-module in Zero

colossalai/zero/init_ctx/init_context.py, tests/test_zero_data_parallel/test_init_context.py, tests/test_zero_data_parallel/test_shard_model_v2.py, tests/test_zero_data_parallel/test_sharded_optim_v2.py, tests/test_zero_data_parallel/test_sharded_optim_with_sync_bn.py, tests/test_zero_data_parallel/test_state_dict.py, tests/test_zero_data_parallel/test_zero_engine.py
1. Remove `convert_to_fp16` argument. We don't support fp32 training, parameters must be converted to fp16.
2. Remove `shard_grad` argument. We only support ZeRO-2 and ZeRO-3. Gradients are always sharded.
3. Set the default dtype of `model_numel_tensor` to `torch.long`, in case of overflow.
4. Polish corresponding unit tests.
=> [zero] polish ZeroInitContext

colossalai/zero/sharded_model/sharded_model_v2.py, colossalai/zero/sharded_optim/sharded_optim_v2.py
When `reuse_fp16_shard` is `True`, grad is stored in `p.col_attr.sharded_data_tensor.payload` and we move all payload to CPU. This reduces max GPU memory usage during backward.
=> [zero] optimize grad offload

colossalai/zero/sharded_optim/sharded_optim_v2.py
When enabling `reuse_fp16_shard`, `p.colo_attr.sharded_data_tensor` stores grad. We have to recover it when overflow occurs.
=> [hotfix] fix sharded optim zero grad

.github/workflows/build.yml, .github/workflows/compatibility_test.yml
Fixed #696 by modifying the workflow script for rootless docker. The CI runs have now been executed by `gitact` instead of `root`.
=> [ci] remove ipc config for rootless docker

colossalai/nn/layer/parallel_3d/layers.py
`num_partitions` of vocab parallel embedding weight is wrong. Corrected `depth ** 2` to `depth ** 3`
=> Corrected 3d vocab parallel embedding

colossalai/nn/layer/parallel_2d/_operation.py, colossalai/nn/layer/parallel_2p5d/_operation.py
This fixed the issue #698 . As the CI uses PyTorch 1.10, I have pasted the screenshot for the unit testing `test_layers`.
=> [compatibility] fixed tensor parallel compatibility with torch 1.9

tests/test_zero_data_parallel/test_found_inf.py
The `test_found_inf` test case ran into an error due to change in the `get_current_device` function, which returns `cuda:<idx>` instead of `<idx>`.
=> [bug] fixed broken test_found_inf

tests/test_zero/test_shard_model_v2.py, tests/test_zero/test_sharded_optim_v2.py, tests/test_zero/test_zero_engine.py
Fixed #737  as part of the efforts to tackle #733 . 
The error only occurs in `test_zero_data_parallel` and the screenshot of the successful unit test is shown below.
=> [bug] fixed DDP compatibility with torch 1.8

colossalai/builder/pipeline.py
There is no unit test for this pr.
However, I print the build result for review.
It can be seen that the first list has two `Sequential`(layer0,1 and layer5,6 ) with a config num_chunk=2 and 10 layers ViT.
=> modefied the pp build for ckpt adaptation

colossalai/cli/__init__.py, requirements/requirements.txt, setup.py
I have added `click` to the requirement list. Meanwhile, the scope of cli module is modified to only expose the `cli` function to the outsider.
=> [cli] add missing requirement

colossalai/cli/cli.py, colossalai/cli/launcher/__init__.py, colossalai/cli/launcher/run.py, setup.py
- In the previous implementation, the user options can't be captured, e.g. `colossalai run train.py --arg 1` will raise exception as `arg` will be treated as an unknown thus invalid option. I have fixed this bug in this PR. 
- In addition, I have restructured the module structure. We don't have to define all commands in the `cli.py`. We can define the command in their respective folder and then import them in `cli.py`. This will make the structure look cleaner.
- I have added help message to each option
- The launch function fails at this moment, I will create a separate PR to fix it.
=> [cli] fixed a bug in user args and refactored the module structure

colossalai/cli/launcher/__init__.py, colossalai/cli/launcher/multinode_runner.py, colossalai/cli/launcher/run.py
I fixed the CLI launching function and it works on a single node now. Multi-node testing will be conducted on TACC later.
I tested with a simple script `test.py`:
```python
import os
print(f'rank: {os.environ['RANK']})
```
The testing commands are given below:
```shell
colossalai run test.py
> rank: 0
> rank: 1
> rank: 2
> rank: 3
> rank: 4
> rank: 5
> rank: 6
> rank: 7
colossalai run --nproc_per_node 4 test.py
> rank: 0
> rank: 1
> rank: 2
> rank: 3
```
On a side note, I also fixed the error message display in our CLI. Conventionally, we use `click.echo` to print any message instead of `print` `logger.info`. Meanwhile, `raise` should be avoided in CLI  implementation as normally CLI does not tell the user at which line the error occurs, but only gives a simple error message instead.
=> [cli] fixed single-node process launching

setup.py
Colossal-AI is compatible with Python 3.6.
=> [setup] allow installation with python 3.6

colossalai/registry/__init__.py, requirements/requirements-test.txt, requirements/requirements.txt, tests/test_data/test_cifar10_dataset.py, tests/test_data/test_data_parallel_sampler.py, tests/test_data/test_deterministic_dataloader.py
`torchvision` and some libraries are not necessary dependencies for `colossalai`. Therefore, they should be removed and only appear in tests. The registry is no longer needed except for a few, this will be cleaned in a separate PR.
=> [dependency] removed torchvision

setup.py
Fixed #836 , we should refactor the readme and doc in the next release.
=> [setup] use env var instead of option for cuda ext

colossalai/cli/launcher/__init__.py, colossalai/cli/launcher/hostinfo.py, colossalai/cli/launcher/multinode_runner.py, colossalai/cli/launcher/run.py, requirements/requirements.txt
The distributed launcher has been completed and tested on TACC.
The commands used to test the launcher are listed below:
```
colossalai run --nproc_per_node 4 test.py
colossalai run --nproc_per_node 4 --master_port 29505 test.py
colossalai run --nproc_per_node 4 --host host2 test.py
colossalai run --nproc_per_node 4 --host host1,host2 --master_addr host1 test.py
colossalai run --nproc_per_node 4 --hostfile ./hostfile --master_addr host1  test.py
colossalai run --nproc_per_node 4 --hostfile ./hostfile --master_addr host1  --include host1 test.py
colossalai run --nproc_per_node 4 --hostfile ./hostfile --master_addr host1  --exclude host2 test.py
```
=> [CLI] refactored the launch CLI and fixed bugs in multi-node launching

colossalai/gemini/memory_tracer/memstats_collector.py, colossalai/gemini/tensor_placement_policy.py, colossalai/zero/sharded_model/sharded_model_v2.py, colossalai/zero/sharded_optim/sharded_optim_v2.py
Use GeminiMemoryManager rather than GLOBAL_MODEL_DATA_TRACER when sampling model data.
=> [zero] use GeminiMemoryManager when sampling model data

.github/workflows/build.yml, tests/components_to_test/simple_net.py
I have set up the proxy for the CI runtime and cached the cuda extensions. This can shorten the non-testing time  from max 12 min to less than 1 min.
=> [ci] cache cuda extension

model_zoo/gpt/gpt.py
I am trying to load pre_trained parameters of hugging face gpt2.
And I found our qkv processing is different from [theirs](https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt2/modeling_gpt2.py#L312), maybe leading to bugs of loading ckpt.
=> [model_zoo] change qkv processing

setup.py
If building colossalai with cuda extension, the version can be `0.1.3+torch110cu113`. If not, the version is just `0.1.3`.
=> [setup] add local version label

colossalai/kernel/cuda_native/csrc/multi_tensor_lamb.cu
Change colossalai/kernel/cuda_native/csrc/multi_tensor_lamb.cu code style.
=> [NFC] Polish colossalai/kernel/cuda_native/csrc/multi_tensor_lamb.cu code style.

colossalai/kernel/cuda_native/csrc/moe_cuda_kernel.cu
[NFC] polish moe_cuda_kernel.cu code style
=> [NFC] polish moe_cuda_kernel.cu code style

colossalai/kernel/cuda_native/scaled_softmax.py
[NFC] polish colossalai/kernel/cuda_native/scaled_softmax.py code style
=> [NFC] polish colossalai/kernel/cuda_native/scaled_softmax.py code style

colossalai/tensor/_ops/addmm.py, colossalai/tensor/_ops/embedding.py, colossalai/tensor/_ops/linear.py, colossalai/tensor/_ops/loss.py, colossalai/tensor/dist_spec.py, colossalai/tensor/spec.py, tests/test_tensor/test_addmm_tp.py, tests/test_tensor/test_embedding_tp.py, tests/test_tensor/test_linear_tp.py, tests/test_tensor/test_model.py
Derive compute pattern from dist spec, and remove unneeded compute patterns. Only `TP1D`, `ZeRO` and `DP` are remained.
We don't need determine whether a parameter is computed as 1D Row or 1D Column, since they can be derived from dist spec. So as for 1D tensor parallel, we don't need to distinguish 1D Row and 1D Column w.r.t. compute pattern.
=> [tensor] derive compute pattern from dist spec

colossalai/engine/gradient_accumulation/_gradient_accumulation.py
Fixed #1028 .
Code to reproduce bug #1028 is given below:
```shell
from typing import Iterable, Union, Any, Tuple
from torch import Tensor
class GradAccumDataloader:
"""A wrapper for dataloader to enable gradient accumulation by dropping the last incomplete steps.
Note:
The dataloader would drop the last incomplete steps for gradient accumulation.
For example, if a dataloader has 10 batches of data and accumulate size is 4. The model parameters will
be updated only twice at step 4 and step 8. The last two batches of data do not form a complete 4-step cycle.
Thus, they will be automatically skipped by this class. If the dataloader is not standard PyTorch dataloader,
(e.g. Dali dataloader), this class will automatically consume (load data for nothing) the remaining 2 batches.
Args: …
```
=> [engine] fixed bug in gradient accumulation dataloader to keep the last step

colossalai/zero/init_ctx/init_context.py, colossalai/zero/sharded_model/sharded_model_v2.py
Support `state_dict()` and `load_state_dict()` for ShardedModelV2 now. You can load state dict in ZeroInitContext or after model being wrapped by ShardedModelV2:
```python
shard_strategy = TensorShardStrategy()
with ZeroInitContext(target_device=torch.cuda.current_device(), shard_strategy=shard_strategy, shard_param=True):
model = gpt2_s(checkpoint=True)
model.load_state_dict(torch.load('gpt.pt'))
model = BertModel.from_pretrained('bert-base-uncased')
model = ShardedModelV2(model, shard_strategy, tensor_placement_policy='cpu', reuse_fp16_shard=True)
model.load_state_dict(torch.load('gpt.pt'))
```
=> [zero] add load_state_dict for sharded model

colossalai/tensor/chunk.py
Add chunk size search:
```python
def search_chunk_size(module: torch.nn.Module,
search_range: int,
n_grids: int,
min_chunk_size: Optional[int] = None) -> int:
pass
```
Apply grid search in `[min_chunk_size, min_chunk_size+search_range]`. If `min_chunk_size=None`, it's set to the number of elements of the largest parameter.
Usage:
```python
best_chunk_size = ChunkManager.search_chunk_size(model, 128 * 1024**2, 4)
```
=> [zero] add chunk size search for chunk manager

colossalai/initialize.py
Fixed #1058 , set cudnn benchmark to false so that it will not repeatedly run benchmarking when inputs are of varying sizes.
If the user wants to turn on cudnn, they can have `cudnn_benchmark = True` in `config.py`.
=> [cudnn] set False to cudnn benchmark by default

colossalai/nn/parallel/data_parallel.py, tests/test_tensor/test_hybrid_device.py
CPU DP will meet segment fault because CPU is not protected by stream. Since torch has no CPU stream, I directly return grad for CPU grad.
=> [Tensor] fix optimizer for CPU parallel

colossalai/utils/model/utils.py
The `InsertPostInitMethodToModuleSubClasses` context manager does not return the object in `with` statement, this issue fixed this problem so that the attributes of the contexts can still be accessed after `with` statement.
Previous:
```python
>>> with InsertPostInitMethodToModuleSubClasses() as ctx:
>>>        model = resnet18()
>>> print(ctx)
None
```
Now:
```python
>>> with InsertPostInitMethodToModuleSubClasses() as ctx:
>>>        model = resnet18()
>>> print(ctx)
<colossalai.utils.model.colo_init_context.ColoInitContext at 0x7f75d031bcd0>
```
=> [context] maintain the context object in with statement

.github/workflows/build.yml, tests/components_to_test/gpt.py, tests/test_data_pipeline_tensor_parallel/test_cifar_with_data_pipeline_tensor.py, tests/test_layers/test_3d/test_3d.py, tests/test_tensor/test_model.py, tests/test_utils/test_checkpoint/test_checkpoint_1d.py, tests/test_utils/test_checkpoint/test_checkpoint_2d.py, tests/test_utils/test_checkpoint/test_checkpoint_2p5d.py, tests/test_utils/test_checkpoint/test_checkpoint_3d.py, tests/test_utils/test_memory.py, tests/test_zero/test_tensor_utils.py
We migrate CI runs to the 4 GPU machines temporarily, thus we ignore all tests which require 8 GPUs for now.
=> [test] ignore 8 gpu test

colossalai/gemini/memory_tracer/memstats_collector.py, colossalai/nn/parallel/data_parallel.py, colossalai/tensor/chunk.py, colossalai/zero/utils/zero_hook_v2.py, colossalai/zero/zero_optimizer.py, tests/test_tensor/test_chunk.py
Refactor chunk mgr for easily monitoring memory usage.
=> [tensor] refactor chunk mgr and impl MemStatsCollectorV2

colossalai/utils/model/lazy_init_context.py, tests/test_utils/test_lazy_init_ctx.py
The current ColoTensor does has not supported lazy initialization yet. This PR proposes a method for lazy initialization and it's currently experimental and subject to future changes.
In this PR, a context is implemented for lazy initialization, this context will do the following things.
1. hijack the module initialization so that all modules are created as meta tensors. This can have two benefits 1) super fast module initialization 2) make the module traceable for future integration with torch.fx
2. hijack the weight initialization calls and put them into cache
3. materialize the meta tensors to real-value tensors and apply weight initialization when `reset_parameters` is called.
=> [context] support lazy init of module

colossalai/nn/parallel/data_parallel.py, colossalai/tensor/chunk.py, colossalai/zero/zero_optimizer.py
While I read through the source for `chunk.py`, I found it lacks documentation so I just added it for better readability.
=> [doc] added documentation to chunk and chunk manager

colossalai/engine/_base_engine.py, colossalai/engine/ophooks/utils.py
Fixed #1095 . The bug in the issue is because that empty hooks are registered on the modules and these hooks seem to incur extra memory, perhaps there are some underlying tensor cloning. With this PR, this bug can be fixed. Some experiment results are shown below.
Model: ResNet101
Dataset: CIFAR10 (resize to 224)
Optim: Adam
Batch size: 128
#GPU: 1
| Experiment | Max CUDA memory allocated / GB | 
| -  | - |
| without engine | 8.25 |
| with engine (before fix) | 16.49 |
| with engine (after fix)  | 8.25 |
=> [engine] fixed empty op hook check

.github/workflows/build_gpu_8.yml, .github/workflows/release_nightly.yml
As the test CI triggered by pull request has been migrated to the 4-GPU machine, some tests are skipped due to the limited number of GPUs. This PR adds a CI which will be executed automatically at mid-night to test on 8-GPU machine. This test will only be run when the GPU is idle so that overnight experiments will not be affected.
The nightly build CI has also been fixed for consistency between two even triggers.
=> [workflow] added regular 8 GPU testing

colossalai/nn/parallel/data_parallel.py, colossalai/tensor/__init__.py, colossalai/tensor/colo_parameter.py, colossalai/tensor/param_op_hook.py
`torch.autograd.Function` ensures the device of original inputs and grads are the same. Since zero hook may change the device of input in pre fwd, we execute pre fwd out of `autograd.Function`.
=> [tensor] refactor param op hook

colossalai/engine/schedule/_base_schedule.py, colossalai/engine/schedule/_non_pipeline_schedule.py, colossalai/engine/schedule/_pipeline_schedule.py
Fixed #120  to support more data formats in the engine schedules and implemented a more flexible tensor-argument mapping mechanism in pipeline schedules.
- Data in the format of list and tuple is now supported as the model inputs and outputs.
- The data_process_func now accepts the stage output as well so that the user can write their own logic to map the tensors (outputs from the previous stage and those produced by dataloader on the current stage) to the arguments of the model forward function on the current stage.
=> [pipeline] supported more flexible dataflow control for pipeline parallel training

colossalai/fx/proxy.py
added coloproxy to resolve data-dependent control flow and some python build-in functions with the help of meta tensor.
=> [fx] added coloproxy

colossalai/nn/parallel/data_parallel.py, colossalai/zero/utils/zero_hook_v2.py, tests/test_utils/test_ddp_ignore_params.py
=> [ddp] add set_params_to_ignore for ColoDDP

colossalai/tensor/colo_parameter.py, colossalai/tensor/param_op_hook.py, tests/test_tensor/test_zero_optim.py
`torch.autograd.Function` will convert all return tensors of `forward()` to `torch.Tensor`. For `ColoTensor` and `ColoParameter`, `spec` will be lost. We have to store the specifications and reconstruct `ColoTensor`/`ColoParameter` after applying `torch.autograd.Function`.
ZeRO + TP is also supported.
=> [hotfix] fix param op hook

colossalai/utils/model/utils.py
The zero init context has a precondition that the module class has to be imported before entering the context. However, sometimes this is not always so. For example:
```
with ctx:
model = transformers.BertModel(...)
```
This example will raise exception because BertModel is only imported on the fly. This PR adds an error message for easier debugging.
=> [zero] added error message to handle on-the-fly import of torch Module class

colossalai/zero/sharded_model/sharded_model_v2.py, colossalai/zero/sharded_optim/sharded_optim_v2.py
Nested ZeRO is not supported. In case users use nested ZeRO and get wrong training results, assertations are added to prevent this usage.
=> [hotfix] prevent nested ZeRO

colossalai/gemini/__init__.py, colossalai/gemini/gemini_mgr.py, colossalai/gemini/placement_policy.py, colossalai/nn/parallel/data_parallel.py
1. Gemini manager breakdown PCIE moving volume into H2D volume and D2H volume.
2. `_get_layout_info()` uses LRU cache.
=> [gemini] refactor gemini mgr

colossalai/nn/_ops/addmm.py, colossalai/nn/_ops/embedding.py, colossalai/tensor/colo_parameter.py, colossalai/tensor/colo_tensor.py, tests/test_tensor/test_tensor.py
Revert the .view()/size() back to the local one.
I think it is too risky to override them as the global ones.
=> [tensor] revert local view back

colossalai/fx/proxy.py
This PR fixes the tracing problem of the latest timm library. The root cause is that the latest code contains if statements like `if x.ndim == 4`.
=> [fx] added ndim property to proxy

colossalai/nn/layer/vanilla/layers.py
[NFC] polish colossalai/nn/layer/vanilla/layers.py code style
=> [NFC] polish colossalai/nn/layer/vanilla/layers.py code style

.github/workflows/compatibility_test.yml
Remove the hardcoded version settings and supported arbitrary version inputs.
=> [workflow] updated pytorch compatibility test

colossalai/engine/gradient_handler/_pipeline_parallel_gradient_handler.py
=> [hotfix] fix PipelineSharedModuleGradientHandler

.github/workflows/build.yml, .github/workflows/release_bdist.yml, .github/workflows/scripts/build_colossalai_wheel.py
Updated the binary distribution release workflow to support arbitrary inputs. Meanwhile, the defautl build workflow will use the latest pytorch version.
=> [workflow] updated release bdist workflow

colossalai/fx/passes/shard_1d_pass.py, tests/test_fx/test_transform_mlp_pass.py
Still needs to handle special cases.
=> [fx] Add unit test and fix bugs for transform_mlp_pass

.github/workflows/build_gpu_8.yml
The condition for this test should be that memory used is less than 100 MB so it deems that the GPU is not in use.
=> [workflow] fixed trigger condition for 8-gpu unit test

colossalai/fx/tracer/_tracer_utils.py, requirements/requirements-test.txt, tests/test_fx/test_pipeline/test_hf_model/test_albert.py, tests/test_fx/test_pipeline/test_hf_model/test_bert.py, tests/test_fx/test_pipeline/test_hf_model/test_gpt.py, tests/test_fx/test_pipeline/test_hf_model/test_opt.py, tests/test_fx/test_pipeline/test_hf_model/test_t5.py, tests/test_fx/test_pipeline/test_timm_model/test_timm.py, tests/test_fx/test_pipeline/test_torchvision/test_torchvision.py, tests/test_fx/test_tracer/test_hf_model/test_hf_albert.py, tests/test_fx/test_tracer/test_hf_model/test_hf_bert.py, tests/test_fx/test_tracer/test_hf_model/test_hf_gpt.py, tests/test_fx/test_tracer/test_hf_model/test_hf_opt.py, tests/test_fx/test_tracer/test_hf_model/test_hf_t5.py, tests/test_fx/test_tracer/test_patched_module.py, tests/test_fx/test_tracer/test_timm_model/test_timm_model.py, tests/test_fx/test_tracer/test_torchvision_model/test_torchvision_model.py
=> [fx] fixed unit tests for torch 1.12

colossalai/zero/sharded_model/sharded_model_v2.py, tests/test_zero/test_state_dict.py
Aims to reduce cuda memory usage.
=> [hotfix] shared model returns cpu state_dict

colossalai/fx/passes/split_module.py, colossalai/fx/tracer/meta_patch/patched_function/arithmetic.py, colossalai/fx/tracer/tracer.py, tests/test_fx/test_pipeline/test_timm_model/test_timm.py, tests/test_fx/test_pipeline/test_torchvision/test_torchvision.py, tests/test_fx/test_tracer/test_timm_model/test_timm_model.py, tests/test_fx/test_tracer/test_torchvision_model/test_torchvision_model.py
Many fx unit tests failed with torch 1.10 according to the [CI Log](https://github.com/hpcaitech/ColossalAI/runs/7381211081?check_suite_focus=true). This PR fixed these bugs.
=> [fx] fixed compatiblity issue with torch 1.10

colossalai/gemini/chunk.py, colossalai/gemini/chunk_mgr.py, colossalai/nn/parallel/data_parallel.py, colossalai/tensor/process_group.py, tests/test_ddp/test_ddp_ignore_params.py, tests/test_ddp/test_ddp_state_dict.py, tests/test_tensor/test_chunk.py, tests/test_tensor/test_zero_optim.py, tests/test_zero/test_zero_optim_state_dict.py
Current ZeroDDP still uses `gpc` to get process group info. `ChunkManager` should receive a process group. After this update, `test_zero_optim` can pass.
=> [hotfix] ZeroDDP use new process group

colossalai/tensor/colo_tensor.py, colossalai/tensor/process_group.py, colossalai/utils/checkpoint/module_checkpoint.py, colossalai/utils/checkpoint/utils.py, tests/test_utils/test_colo_checkpoint.py, tests/test_utils/test_colo_checkpoint_tools.py
- only gathers tensors to rank0 to reduce memory usage
- corrected and polished colo_tensor's checkpointing unit test
=> [checkpoint] use gather_tensor in checkpoint and update its unit test

colossalai/fx/codegen/__init__.py, colossalai/fx/codegen/activation_checkpoint_codegen.py, tests/test_fx/test_codegen/test_activation_checkpoint_codegen.py
In the previous PR #1349 , we annotated the nodes if they are activation-checkpointed. In this PR, we utilize these annotations and generate model forward code with activation checkpoint. The new CodeGen inherits from the PyTorch CodeGen, the code change can be found by looking for the following multi-line comment.
```python
#########################################
#########################################
```
A unit test is added in this PR as well. Below are the different codes generated with/without activation checkpoint.
```python
def forward(self, x):
mlp1_linear1 = self.mlp1.linear1(x)
mlp1_linear1_1 = self.mlp1.linear1(x)
mlp2_linear1 = self.mlp2.linear1(x)
mlp2_linear1_1 = self.mlp2.linear1(x);  x = None
add = mlp1_linear1 + mlp1_linear1_1;  mlp1_linear1 = mlp1_linear1_1 = None …
```
=> [fx] added activation checkpoint codegen

colossalai/fx/codegen/__init__.py, colossalai/fx/codegen/activation_checkpoint_codegen.py, tests/test_fx/test_codegen/test_activation_checkpoint_codegen.py
The previous PR #1355  supported code generation with activation checkpoint only with torch 1.12. This PR extends the compatibility with lower versions which do not have the `CodeGen` class.
=> [fx] added activation checkpoint codegen support for torch < 1.12

colossalai/utils/checkpoint/module_checkpoint.py
`dire` means horrible, the parameter name is not well given and thus standardized in this PR.
=> [util] standardise checkpoint function naming

colossalai/zero/zero_optimizer.py, tests/test_zero/test_zero_optim_state_dict.py
Use `only_rank_0` to control `zero_optim.state_dict()`. If true, only DP rank 0 returns global state dict, and other ranks return None. This saves memory usage. Otherwise, all ranks return global state dict.
=> [zero] zero optim state_dict takes only_rank_0

colossalai/fx/tracer/meta_patch/patched_function/torch_ops.py
As Hugging Face Transformers library is updated from 4.20.0 to 4.21.0, the OPT model code is updated, leading to a CI error. This PR added the required function patch to fix this error.
=> [fx] patched torch.full for huggingface opt

colossalai/fx/codegen/activation_checkpoint_codegen.py
After the previous PR #1359 , the codegen for torch 1.12 was broken due to the indentation error, this PR fixed this problem.
The test with torch 1.12 is given below:
=> [fx] fixed indentation error in checkpointing codegen

colossalai/tensor/shape_consistency.py, colossalai/tensor/sharding_spec.py, tests/test_tensor/test_shape_consistency.py
This PR construct a ShapeConsistencyManager class to manage the shape consistency behaviour, it mainly does three things:
1. Give a pair of source spec and target spec, it will give you a valid transform path with greedy algorithm.
2. It will cached the transform path of all searched pairs, so most of time when you apply the shape consistency transform, the transform has already cached in manager, it won't cost additional time to search the path again.
3. It will give an apply function to implement the sharding spec to the tensor.
Note: The ShapeConsistencyManager class is just partially completed.
=> [tensor] add shape consistency feature to support auto spec transform

colossalai/fx/passes/meta_info_prop.py, tests/test_fx/test_meta_info_prop.py
I believe this change won't affect usage of node.meta['tensor_meta'], but I have adopted the expressions in https://github.com/pytorch/pytorch/blob/f9533560ccb2d789bc78caa360d021f72f5ebc7b/torch/fx/passes/graph_manipulation.py#L82 so as to compute the memory consumptions for activation and model parameters separately. This will make it easy for us to retrieve the activation memory cost directly and correctly.
```python
for node in graph.nodes:
node_size = getattr(node, 'node_size')    # node_size is a NamedTuple(output_size, param_size)
print(node_size.output_size)    # will get the memory cost of activation in bytes format
print(node_size.param_size)     # will get the memory cost of activation in bytes format
```
=> [fx] modify the calculation of node_size in MetaInfoProp for activation checkpointing usages

colossalai/utils/__init__.py, colossalai/utils/common.py, colossalai/zero/zero_optimizer.py, tests/test_utils/test_norm_gradient_clipping.py
```python
from colossalai.utils.common import clip_grad_norm
total_norm = clip_grad_norm(params, 1.0, norm_type=2.0)
```
Grads can be on CUDA and CPU. They can be either fp16 or fp32.
=> [utils] Impl clip_grad_norm for ColoTensor and ZeroOptimizer

colossalai/nn/_ops/linear.py, colossalai/tensor/sharding_spec.py, tests/test_tensor/test_sharded_linear.py, tests/test_tensor/test_sharded_mlp.py
The previous PR #1405  implemented the sharding spec. This PR implements the linear distributed computation using the new sharding spec API. Currently only the forward part is implemented. When checking the correctness of the gradients, I found that the backward part of the autograd function `reduce_input` is not executed for some reason, thus, the correctness of the gradient is not guaranteed.
I will send a separate PR to fix this problem.
=> [tensor] added linear implementation for the new sharding spec

colossalai/tensor/shape_consistency.py, colossalai/tensor/sharding_spec.py, colossalai/tensor/utils.py, tests/test_tensor/test_shape_consistency.py
In #1418 PR, I add ShapeConsistencyManager into colossalai to support auto parallel strategy search and runtime sharding spec apply. This PR complete the auto parallel strategy search supporting part, mainly do following things:
1. build a difference function for DimSpec and ShardingSpec based on 2D device mesh.
2. Build a CommSpec class to record the communication operation during the transform, and use it to compute communication cost.
3. Complete shape_consistency function development, which could generate transform path, communication action sequence and total transform cost for a given source spec and target spec pairs.
4. Build a solved spec pair cache to reduce the runtime searching time.
Note: The apply function is not completed, it may use the CommSpec convert_spec_to_action …
=> [tensor] shape consistency generate transform path and communication cost

colossalai/nn/parallel/layers/cache_embedding/cache_mgr.py, colossalai/nn/parallel/layers/cache_embedding/freq_aware_embedding.py, colossalai/nn/parallel/layers/cache_embedding/parallel_freq_aware_embedding.py, tests/test_layers/test_cache_embedding.py
1. Remove the redundant weight in FreqCacheEmbedding to resolve this issue: https://github.com/hpcaitech/ColossalAI/issues/1440
2. reorganize the inheritance structure of FreqCacheEmbedding to remove redundant code in ParallelFreqCacheEmbedding. 
3. I also leave an interface in CacheParamMgr, so that FreqCacheEmbedding is compatible with vanilla PyTorch EmbeddingBag. But this implementation should be delayed.
=> reorganize the inheritance struct of FreqCacheEmbedding

colossalai/auto_parallel/solver/conv_handler.py, colossalai/auto_parallel/solver/sharding_strategy.py, colossalai/tensor/sharding_spec.py, tests/test_auto_parallel/test_conv_handler.py
The Conv handler will generate all the possible strategies for conv node, and give costs information of the corresponding strategies. All strategies will be recorded into strategies_vector which will be fed into auto parallel solver.
Note: The sharding strategies containing 'S01' is not covered in this PR. Those cases will be implemented in future PR.
=> [autoparallel] Add conv handler to generate strategies and costs info

colossalai/auto_parallel/solver/conv_handler.py, colossalai/auto_parallel/solver/dot_handler.py, colossalai/auto_parallel/solver/operator_handler.py
This PR introduces the base class for the operator handler for better API consistency. The three `generate_sharding_sepc` API is merged into one to remove redundancy as well.
=> [autoparallel] introduced baseclass for op handler and reduced code redundancy

colossalai/auto_parallel/solver/__init__.py, colossalai/auto_parallel/solver/conv_handler.py, colossalai/auto_parallel/solver/dot_handler.py, colossalai/auto_parallel/solver/operator_handler.py, colossalai/auto_parallel/solver/sharding_strategy.py, tests/test_auto_parallel/test_conv_handler.py, tests/test_auto_parallel/test_dot_handler.py
In this PR, I have refactored the implementation of solver module to integrate with torch fx. Some changes are made in this PR and they will be explained below:
1. Use torch.fx Node to retrieve predecessor and successor nodes
The previous implementation requires us to manually key in the input and output nodes, this can be done automatically by accessing the `_input_nodes` and `users` attributes in the `Node` object.
2. Simplify the APIs
Some APIs are too long and they are simplified here. Some examples include:
- `OpeatorHandler.register_strategy_into_strategies_vector` -> `OpeatorHandler.register_strategy`, and this function now return the strategy vector directly.
- Make `StrategiesVector` a subclass of `list` instead of keep a list as an attribute, so we no longer need to keep …
=> [autoparallel] integrate auto parallel with torch fx

colossalai/nn/parallel/layers/cache_embedding/cache_mgr.py, colossalai/nn/parallel/layers/cache_embedding/freq_aware_embedding.py, colossalai/nn/parallel/layers/cache_embedding/parallel_freq_aware_embedding.py, tests/test_layers/test_cache_embedding.py
I change the interface for frequency statistics, so that all the data structures used by FreqCacheEmbedding, because I read the stat info as a Tensor.
The most merit of this update is that users could accelerate the initialization by asynchronously moving the frequency statistics to GPU in advance.
=> [FCE] update interface for frequency statistics in FreqCacheEmbedding

colossalai/auto_parallel/solver/conv_handler.py, colossalai/auto_parallel/solver/dot_handler.py, colossalai/auto_parallel/solver/operator_handler.py
Add `__all__` to files in the `auto_parallel` module for namespace standardization.
=> [autoparallel] added namespace constraints

colossalai/fx/tracer/meta_patch/patched_module/pooling.py, tests/test_fx/test_tracer/test_patched_module.py
Fixed the shape concatenation error in adapative pooling. This allows the torchvision ResNet to be traced successfully with meta args.
A sample test script is given below:
```python
import torch
import torchvision.models as tm
from colossalai.fx import ColoTracer
torch_model = tm.resnet152()
input = torch.rand(32, 3, 224, 224, device="meta")
tracer = ColoTracer()
graph = tracer.trace(torch_model, meta_args={"x": input})
```
=> [fx] fixed adapative pooling size concatenation error

colossalai/auto_parallel/solver/cost_graph.py, colossalai/auto_parallel/solver/operator_handler.py, colossalai/auto_parallel/solver/sharding_strategy.py, colossalai/fx/tracer/meta_patch/patched_function/arithmetic.py, tests/test_auto_parallel/test_conv_handler.py, tests/test_auto_parallel/test_dot_handler.py
A graph data structure to simplify the edge cost graph. It has two main functions:
1. To feed the quadratic resharding costs into solver, we need to linearize it. We build edge_cost in
CostGraph, and it stored every combinations of strategies for a src-dst node pair in an 1D list.
2. To reduce the searching space, we merge computationally-trivial operators, such as 
element-wise operators, transpose, and reduction, into their following nodes. The merging infomation will
be given by the StrategiesVector depending on the type of target node and following nodes.
Additional，some previous bugs has been fixed in this PR:
1. misspelling of variable name
2. fix bugs in handler tests
=> [autoparallel] add cost graph class

colossalai/nn/parallel/layers/cache_embedding/cache_mgr.py, tests/test_layers/test_cache_embedding.py
LFU eviction supports reordering with ids_freq_mapping.
LFU does not need to reorder the CPU weight idx.
=> [FAW] refactor reorder() for CachedParamMgr

colossalai/fx/profiler/_meta_registrations.py
When I experiment Colossal-AI's meta profiler on PyTorch 1.13.0 (nightly), an error occurred because of duplicate registration. So I used the try-except statement to ignore the conflicts.
This will not cause any error, so it can be safely merged.
=> [hotfix] avoid conflict of meta registry with torch 1.13.0.

colossalai/__init__.py, colossalai/_meta_registrations.py, colossalai/fx/__init__.py, colossalai/fx/profiler/__init__.py, colossalai/fx/tracer/__init__.py, colossalai/fx/tracer/_meta_trace.py
In this PR, I moved the _meta_registration.py in previous PR #1515 and #1530 to the root directory of Colossal-AI so that all meta atens can be registered in advance.
With the meta tracing, we can easily get the computation graph of any model just as what functorch does.
```python
>>> from colossalai.fx import meta_trace
>>> import torch
>>> import torchvision.models as tm
>>> model = tm.alexnet()
>>> graph = meta_trace(model, torch.rand(1000, 3, 224, 224))
```
You will get a complete graph.
```
opcode         name                                        target                                         args                                                                                                                                               kwargs
------------- …
```
=> [fx] support meta tracing for aten level computation graphs like functorch.

colossalai/fx/tracer/_meta_trace.py
The `namespace` for this tracer should be default as `graph._graph_namespace`, so that variable names are correct in the display.
=> [hotfix] change namespace for meta_trace.

colossalai/auto_parallel/solver/conv_handler.py, colossalai/auto_parallel/solver/operator_handler.py, tests/test_auto_parallel/test_conv_handler.py
This PR add backward information into conv strategies, the information including:
1. memory cost: I use a memory pair to store the memory cost, first element of pair is forward memory cost and second one is backward memory cost which is composed with activation grad cost and parameters grad cost.
2. computing cost: compute cost of backward has two parts, first is activation computing cost and second is parameter computing cost.
3. communication cost: In previous, we only count the communication cost during forward. In the PR, the communication cost of backward is counted. Additionally, in some no forward communication cost case, the communication may happen during backward phase.
4. resharding cost: resharding cost will also happen during backward, such as we convert the input sharding …
=> [autoparallel]add backward cost info into strategies

colossalai/auto_parallel/solver/__init__.py, colossalai/auto_parallel/solver/constants.py, colossalai/auto_parallel/solver/cost_graph.py, colossalai/auto_parallel/solver/graph_analysis.py, colossalai/auto_parallel/solver/op_handler/__init__.py, colossalai/auto_parallel/solver/op_handler/batch_norm_handler.py, colossalai/auto_parallel/solver/op_handler/conv_handler.py, colossalai/auto_parallel/solver/op_handler/dot_handler.py, colossalai/auto_parallel/solver/op_handler/operator_handler.py, colossalai/auto_parallel/solver/solver.py, colossalai/auto_parallel/solver/strategies_constructor.py, tests/test_auto_parallel/test_batch_norm_handler.py, tests/test_auto_parallel/test_cost_graph.py, tests/test_auto_parallel/test_dot_handler.py, tests/test_auto_parallel/test_liveness_analysis.py, tests/test_auto_parallel/test_solver.py, tests/test_auto_parallel/test_strategies_constructor.py
##What is new?
This PR change the following things:
1. The old version liveness analyser add the parameters and buffers into the memory cost, but it does not has enough information about the sharding strategy. Therefore, we only provide the liveness cycle of nodes, and leave the memory cost computation work to the op handler or strategy constructor.
2. implement the solver class with the pulp module. Now, it could find dp strategy for resnet with sufficient memory budget and mixed strategy if the memory budget is not enough for the dp strategy.
3. Add BatchNorm handler to search the strategy for resent.
4. add the weight and bias memory cost into total memory cost for all handlers.
=> [autoparallel] adapt solver with resnet

colossalai/auto_parallel/solver/__init__.py, colossalai/auto_parallel/solver/options.py, colossalai/auto_parallel/solver/strategies_constructor.py, tests/test_auto_parallel/test_cost_graph.py, tests/test_auto_parallel/test_solver.py, tests/test_auto_parallel/test_strategies_constructor.py
Added `SolverOptions` dataclass instead of using dictionary.
=> [autoparallel] added solver option dataclass

colossalai/auto_parallel/solver/_utils.py, colossalai/auto_parallel/solver/op_handler/batch_norm_handler.py, colossalai/auto_parallel/solver/op_handler/conv_handler.py, colossalai/auto_parallel/solver/op_handler/dot_handler.py, colossalai/auto_parallel/solver/op_handler/operator_handler.py, colossalai/auto_parallel/solver/strategies_constructor.py
`generate_sharding_spec` is defined twice in op handler and strategy constructor, this PR refactored the code to remove this redundancy.
=> [autoparallel] added generate_sharding_spec to utils

colossalai/auto_parallel/solver/op_handler/conv_handler.py, tests/test_auto_parallel/test_solver_with_resnet.py
This PR does two things:
1. Add resnet autoparallel unit test.
2. Add the weight grad communication cost for conv. Typically, the weight of convulotion network is much smaller than activation and the all reduce communication could be overlapped with the backward computing, so it is not counted in previous PR. However, in some extreme cases, the parameters could be much larger than activation, if the communication cost to computing backward parameter grad is still omitted, solver could not get a reasonable solution.
=> [autoparallel] add resnet autoparallel unit test

colossalai/auto_parallel/solver/_utils.py, colossalai/auto_parallel/solver/op_handler/batch_norm_handler.py, colossalai/auto_parallel/solver/op_handler/conv_handler.py, colossalai/auto_parallel/solver/op_handler/dot_handler.py, colossalai/auto_parallel/solver/op_handler/operator_handler.py, colossalai/auto_parallel/solver/strategies_constructor.py, colossalai/context/singleton_meta.py, colossalai/tensor/shape_consistency.py, tests/test_auto_parallel/test_batch_norm_handler.py, tests/test_auto_parallel/test_conv_handler.py, tests/test_auto_parallel/test_cost_graph.py, tests/test_auto_parallel/test_dot_handler.py, tests/test_auto_parallel/test_strategies_constructor.py
This PR refactored the usage of shape consistency manager. The details are described below.
Previously, each handler and strategy constructor requires a shape consistency manager object as input for initialization. However, this manager is only used in calculating the resharding cost and nowhere else. Meanwhile, calculating resharding cost is implemented twice in the op handler and strategy constructor. After moving this to utils, the handler and constructor do not need to keep the manager as a member any more.
The shape consistency manager is now a singleton class where there will only be one instance in the global namespace. The usage of resharding is now purely via function call (i.e. `generate_resharding_cost` and `set_shape_consistency_manager_options`, even though the latter is not …
=> [autoparallel] refactored shape consistency to remove redundancy

colossalai/fx/passes/algorithms/ckpt_solver_rotor.py, colossalai/fx/passes/algorithms/linearize.py, colossalai/fx/profiler/__init__.py, colossalai/fx/profiler/dataflow.py, colossalai/fx/profiler/memory.py, colossalai/fx/profiler/opcount.py, colossalai/fx/profiler/profiler.py
1. Change the backward memory estimation. (dependency calculations, free forward dependency)
2. Remove decay in the memory budget.
3. Fix error calculations in Normalizations.
4. Remove `Phase.LOSS` in op level estimation. Use torch.autograd.backward() instead.
Model | mem_limit | real_consumption | train step time | solver time
-- | -- | -- | -- | --
<function resnet18 at 0x7fc091b074c0> | mem_limit: None | real memory consumption: 2818.724 MB | train step time: 111.869 MS |  
<function resnet18 at 0x7fc091b074c0> | mem_limit: 900.0 MB | real memory consumption: 900.000 MB | train step time: inf MS | solver time: 0.000 MS
<function resnet18 at 0x7fc091b074c0> | mem_limit: 1140.0 MB | real memory consumption: 1140.000 MB | train step time: inf MS | solver time: 0.000 MS
<function resnet18 …
=> [fx/tuning] tune performance on rotor with meta info.

colossalai/auto_parallel/solver/_utils.py, colossalai/auto_parallel/solver/constants.py, colossalai/auto_parallel/solver/op_handler/__init__.py, colossalai/auto_parallel/solver/op_handler/batch_norm_handler.py, colossalai/auto_parallel/solver/op_handler/bcast_op_handler.py, colossalai/auto_parallel/solver/op_handler/conv_handler.py, colossalai/auto_parallel/solver/op_handler/dot_handler.py, colossalai/auto_parallel/solver/op_handler/reshape_handler.py, colossalai/auto_parallel/solver/sharding_strategy.py, colossalai/auto_parallel/solver/strategies_constructor.py, tests/test_auto_parallel/test_bcast_handler.py
Bcast op in this scenario means the arguments of this kind of operation can be automatically expanded to be of equal sizes (without making copies of the data). To keep the computing correctness, we should make sure on each dimension two arguments have the same DimSpec. Additionally, the BcastOpHandler will enumerate all the possible sharding specs for the output and generate the input sharding spec based on the output sharding spec and input tensor meta information.
=> [autoparallel] add bcast op handler

colossalai/auto_parallel/solver/constants.py, colossalai/auto_parallel/solver/op_handler/bcast_op_handler.py, colossalai/auto_parallel/solver/op_handler/dot_handler.py, colossalai/auto_parallel/solver/strategies_constructor.py, tests/test_auto_parallel/test_bcast_matmul.py
In previous PR #1600, the strategies of operators like operator.add is created by the BcastOpHandler. However, torch.matmul is not covered in previous PR, due to its extra matrix dimensions.
In this PR, BcastOpHandler will create strategies for the broadcast matmul operator and analyse the memory cost, computation cost, communication cost and resharding costs of those strategies.
=> [autoparallel]add bcast matmul strategies

colossalai/auto_parallel/solver/op_handler/node_handler.py, colossalai/auto_parallel/solver/op_handler/registry.py, colossalai/auto_parallel/solver/sharding_strategy.py
A new `NodeHandler` is implemented to replace the original `OperatorHandler`.  This new `NodeHandler` has several improvements over the `OperatorHandler`.
1. It defines the mapping between the logical operand and the actual tensor via the `get_operand_mapping` method. This unifies the way of writing handles for function/module nodes.
2. It has an additional abstraction of StrategyGenerator, which allows clear grouping and re-use of different sharding strategies.
3. It has a consistent template for `register_strategy` to avoid code redundancy.
=> [autoparallel] added new node handler

colossalai/auto_parallel/solver/op_handler/dot_handler_v2.py, colossalai/auto_parallel/solver/op_handler/node_handler.py, colossalai/auto_parallel/solver/sharding_strategy.py, tests/test_auto_parallel/test_linear_handler_v2.py
This PR implements the new version of linear module handler by inheriting the new node handler and the new data structures for sharding strategy. The various strategy generators are to be implemented in the next PR.
=> [autoparallel] added new linear module handler

colossalai/auto_parallel/solver/op_handler/__init__.py, colossalai/auto_parallel/solver/op_handler/unary_elementwise_handler.py, tests/test_auto_parallel/test_strategies_constructor.py
This PR changes the following nodes(nodes will be merged into other nodes) strategies generation logic, new version handlers for following nodes will **keep the duplicated strategies**. **To avoid the duplicated  check in StrategiesConstructor,** handler will **attatch the index of input strategy on new strategy name.** 
**This behavior will not increase the seaching space**, because no matter how many strategies generated by handler, **the following nodes will be merged and solver won't create a new variable for it.**
=> [autoparallel] change the following nodes strategies generation logic

colossalai/auto_parallel/solver/op_handler/dot_handler_v2.py, colossalai/auto_parallel/solver/op_handler/node_handler.py, colossalai/auto_parallel/solver/sharding_strategy.py, colossalai/auto_parallel/solver/strategy/matmul_strategy_generator.py, colossalai/auto_parallel/solver/strategy/strategy_generator.py, tests/test_auto_parallel/test_node_handler/test_linear_handler_v2.py, tests/test_fx/test_tracer/test_torchrec_model/test_deepfm_model.py, tests/test_fx/test_tracer/test_torchrec_model/test_dlrm_model.py
This PR implemented all matmul-related sharding strategy generators. On a side note, this PR also removes unused imports in two unit tests which can lead to import error with python38 and torch1.12.
=> [autoparallel] implemented all matmul strategy generator

colossalai/auto_parallel/solver/op_handler/__init__.py, colossalai/auto_parallel/solver/op_handler/registry.py, colossalai/auto_parallel/solver/sharding_strategy.py, colossalai/auto_parallel/solver/strategies_constructor.py
Added the template for the new strategy constructor, it has not been implemented yet, we will come back to this part after all the node handlers are migrated to the new version.
=> [autoparallel] added new strategy constructor template

colossalai/auto_parallel/solver/strategy/matmul_strategy_generator.py
The previous PR #1616  considers all matmul sharding strategy generation, however, it failed to consider the the communication action for the bias term. 
This bias term can only have one action which is `IDENTITY_FWD_ALLREDUCE_BWD` to make sure the gradient is synchronized. The mesh dimensions for all reduce depends on the sharding spec of the output. For example:
1. if the output is two dimensional and has sharding spec RS, then bias also has sharding spec S and thus has no all reduce oepratin.
2. if the output is SS, then the bias requires an allreduce in the backward to sync gradient.
This PR implemented these strategies for the bias term.
The `bias` term in ops like `torch.addmm` may not be 1D tensor, I will make the strategy broadcastable in a separate PR.
=> [autoparallel] added bias comm spec to matmul strategy

colossalai/auto_parallel/solver/_utils.py, colossalai/auto_parallel/solver/op_handler/bcast_op_handler.py, colossalai/auto_parallel/solver/strategy/strategy_generator.py, colossalai/tensor/__init__.py, colossalai/tensor/comm_spec.py, colossalai/tensor/shape_consistency.py, tests/test_tensor/test_shape_consistency.py
1. CommSpec and ShapeConsistencyManager module is used to compute the resharding cost in autoparallel. However, the value returned is a total cost. In this PR, **use a dictionary to contain all phases costs including forward, backward, and total cost.**
3. Previously, CommSpec is only used in ShapeConsistencyManager class, which could generate the communication costs and help to do the runtime apply. As CommSpec used in autoparallel module and potentially used in other modules, the CommSpec class is moved into a separate file in this PR.
=> [autoparallel] update CommSpec

colossalai/auto_parallel/solver/op_handler/broadcast.py, tests/test_auto_parallel/test_broadcast.py
This PR added some utils functions to handle broadcast operations, which can be useful when implementing node handlers for operations like matmul.
=> [autoparallel] added utils for broadcast operation

colossalai/nn/_ops/element_wise.py
hi, dev from biomap. Encountered this error with calling colotensor.type()
=> fix colotensor.type() raise NotImplementedError

colossalai/auto_parallel/solver/op_handler/reshape_handler_v2.py, colossalai/auto_parallel/solver/strategy/__init__.py, colossalai/auto_parallel/solver/strategy/batch_norm_generator.py, colossalai/auto_parallel/solver/strategy/conv_strategy_generator.py, colossalai/auto_parallel/solver/strategy/getitem_generator.py, colossalai/auto_parallel/solver/strategy/layer_norm_generator.py, colossalai/auto_parallel/solver/strategy/reshape_generator.py, colossalai/auto_parallel/solver/strategy/strategy_generator.py, tests/test_auto_parallel/test_node_handler/test_reshape_handler_v2.py
This PR add the reshape handler v2 using refactored api, and fix some previous bug which leads to compute cost not append to strategies.
=> [autoparallel] add reshape handler v2 and fix some previous bug

colossalai/auto_parallel/solver/op_handler/dot_handler_v2.py, colossalai/auto_parallel/solver/op_handler/node_handler.py, colossalai/auto_parallel/solver/op_handler/utils.py, colossalai/auto_parallel/solver/sharding_strategy.py, colossalai/tensor/sharding_spec.py, tests/test_auto_parallel/test_node_handler/test_linear_handler_v2.py
In the previous implementation of node handler for the linear module and function, the sharding strategy is for 2D tensors. This sharding strategy is indeed a logical one, however, the physical shape of the input tensor can be N-dimensional, thus, we must map the logical sharding strategy back to its physical shape.
This PR added the logical-to-physical sharding strategy conversion in the `postprocess` method of the node handler. The test case has also been rerfined to include checks for sharding strategies.
The overall sequence is given below.
=> [autoparallel] added sharding spec conversion for linear handler

colossalai/auto_parallel/solver/op_handler/where_handler_v2.py, colossalai/auto_parallel/solver/strategy/__init__.py, colossalai/auto_parallel/solver/strategy/layer_norm_generator.py, colossalai/auto_parallel/solver/strategy/where_generator.py, tests/test_auto_parallel/test_node_handler/test_where_handler_v2.py
1. simply, this PR add where_handler using refactored APIs.
2. In this PR, I overload post_process and register_strategy function to recover the logical strategy into physical strategy. The cost model rule is:
- using logical shape in compute_cost, memory_cost, and communication_cost computaion.
- using physical shape in resharding_cost computation.
Note: This rule may miscalculate some costs due to different kernel implement method, but it works fine for most of cases.
=> [autoparallel] where_handler_v2

colossalai/testing/pytest_wrapper.py, colossalai/testing/utils.py, tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_op_handler/test_deprecated_where_handler.py, tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_shape_consistency_pass.py, tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_solver.py, tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_solver_with_gpt.py, tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_solver_with_mlp.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bmm_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_norm_pooling_handler.py, tests/test_auto_parallel/test_tensor_shard/test_solver_with_resnet_v2.py
During development, we often need to temporarily skip some tests, either because they take too long or they are currently not working well. However, we can easily forget that these tests are in fact required to verify the correctness of each commit. To solve this problem, skipping a test should be controlled by a condition. Before we put up a pull request to the GitHub, we can set the condition flag locally and run a full range test without manually removing `pytest.mark.skip` in the code.
This PR added a util function `run_on_environment_flag` to `colossalai.testing`. This function receives a environment variable name and check if it is set to `'1'`. If so, this test is executed, otherwise skipped.
This PR also replaced `pytest.mark.skip` with `run_on_environment_flag` for the …
=> [unittest] supported condititonal testing based on env var

colossalai/testing/pytest_wrapper.py, tests/test_auto_parallel/test_shape_consistency_pass.py
The `pytest_wrapper.py` has insufficient documentation.
This PR added some documentation for the `pytest_wrapper.py` and replaced `pytest.mark.skip` in the new shape consistency test.
=> [unittest] added doc for the pytest wrapper

colossalai/auto_parallel/tensor_shard/node_handler/strategy/batch_norm_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/conv_strategy_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/getitem_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/layer_norm_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/matmul_strategy_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/strategy_generator.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bmm_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_norm_pooling_handler.py
Some node handlers were skipped previously and they are in fact broken.
This PR fixed the tests in the `test_node_handler` section. On a side note, this PR also move the `has_bias` method to the highest parent class to avoid redundant method definition.
No test in the `test_node_handler` section is skipped now and all can pass.
=> [autoparallel] fixed broken node handler tests

colossalai/auto_parallel/tensor_shard/node_handler/batch_norm_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/reshape_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/batch_norm_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/strategy_generator.py, colossalai/auto_parallel/tensor_shard/sharding_strategy.py, colossalai/auto_parallel/tensor_shard/solver/cost_graph.py, colossalai/auto_parallel/tensor_shard/solver/solver.py, colossalai/device/device_mesh.py, colossalai/fx/passes/experimental/adding_shape_consistency_pass_v2.py, tests/test_auto_parallel/test_resnet_block_runtime.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_batch_norm_handler.py
1. Previously, we do not consider the module buffers such as running mean and running variance. In this PR, **the module buffers is considered during strategy generating and runtime applying.**
2. **fix a bug in CostGraph** which leads to successors of node removed accidentally.
3. Build a runtime unit test for resnet Bottleneck Block.
=> [autoparallel] resnet block runtime apply

colossalai/fx/passes/experimental/adding_shape_consistency_pass_v2.py, colossalai/tensor/shape_consistency.py
1. In new version apply function, we do not have to set the sharding_spec attribute to tensor. Therefore, the getitem and setattr nodes disappear in new version graph.
2. **Fix a bug caused by mechanic of leaf nodes backward,** which leads to backward  of communicaion operation in leaf node not called during runtime.
=> [autoparallel] runtime_backward_apply

.github/workflows/release_bdist.yml
In newer-version git (> 2.25), the security feature is enhanced such that it will check the ownership of the current git repo. If the directory is not completely owned by the current user, the user cannot do anything e.g. `git checkout` . Therefore, to be safe, we need to add the current directory to the safe directory list.
This PR modified the script to build the binary wheels such that it will not raise ownership error when checking out to a different ref.
=> [workflow] handled the git directory ownership error

colossalai/fx/profiler/constants.py, colossalai/fx/profiler/memory.py, colossalai/fx/profiler/profiler.py, colossalai/fx/profiler/tensor.py, tests/test_fx/test_profiler/gpt_utils.py, tests/test_fx/test_profiler/test_meta_info_prop.py, tests/test_fx/test_profiler/test_profiler_meta_info_prop.py
I provide an example script for the `fx.profiler` performance test. It is marked as skip.
After I upgraded transformers to the newest version, GPT-2 of hugging face no longer uses `torch.nn.MultiheadAttention` for transformer blocks. So the `torch.nn.functional.softmax` caused some unexpecting problems. They also used `torch.finfo` object, which is weird. I managed to fix them.
=> [fx/profiler] debug the fx.profiler / add an example test script for fx.profiler

colossalai/auto_parallel/tensor_shard/node_handler/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/bmm_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/linear_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/matmul_strategy_generator.py, colossalai/auto_parallel/tensor_shard/utils/__init__.py, colossalai/auto_parallel/tensor_shard/utils/misc.py, colossalai/auto_parallel/tensor_shard/utils/sharding.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bmm_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_conv_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_getitem_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_linear_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_reshape_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_unary_element_wise_handler.py
The previous node handler lacks one correctness check which is to check whether the sharding spec's entire_shape attribute is the actual physical tensor shape.
This PR mainly does 3 things.
1. I added the shape check in the node handler to make sure the results of post-process is correct. Such stricter checks will help us identify some potential bugs in our implementation.
2. Thanks to the first point, I found that there are some bugs in the linear strategy generator and node handler. Thus, I fixed the broken unit testing.
3. Some other broken unit tests are skipped temporarily and I will fix them in a separate PR.
=> [autoparallel] fixed wrong generated strategy for dot op

colossalai/auto_parallel/tensor_shard/node_handler/conv_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/linear_handler.py, colossalai/auto_parallel/tensor_shard/utils/__init__.py, colossalai/auto_parallel/tensor_shard/utils/misc.py, colossalai/auto_parallel/tensor_shard/utils/sharding.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_conv_handler.py
The stricter sharding strategy checks make some bugs in the node handler surface as mentioned in the previous PR #1746 .
This PR fixed the bugs in the conv handler.
=> [autoparallel] fixed wrong sharding strategy in conv handler

tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_getitem_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_reshape_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_unary_element_wise_handler.py
This test recovered the skipped test. These tests were skipped previously due to the erroneous conv handler output. As the #1747 PR fixed the conv handler, these tests work fine now.
=> [autoparallel] recovered skipped test cases

requirements/requirements-test.txt, tests/test_fx/test_tracer/test_hf_model/test_hf_albert.py, tests/test_fx/test_tracer/test_hf_model/test_hf_bert.py, tests/test_fx/test_tracer/test_hf_model/test_hf_diffuser.py, tests/test_fx/test_tracer/test_hf_model/test_hf_gpt.py, tests/test_fx/test_tracer/test_hf_model/test_hf_opt.py, tests/test_fx/test_tracer/test_hf_model/test_hf_t5.py, tests/test_fx/test_tracer/test_hf_model/utils.py
I tested diffuser modules (i.e. Unet, CLIP, and VAE) on our `ColoTracer`. Sadly, we cannot trace unet currently. But the good news is that VAE and CLIP are able to trace.
=> [fx] test tracer on diffuser modules.

colossalai/fx/passes/experimental/adding_shape_consistency_pass_v2.py, colossalai/tensor/comm_spec.py, colossalai/tensor/shape_consistency.py, tests/test_auto_parallel/test_tensor_shard/test_resnet_block_runtime.py, tests/test_tensor/test_comm_spec_apply.py, tests/test_tensor/test_shape_consistency_apply.py
1. as PR(https://github.com/hpcaitech/ColossalAI/pull/1745) mentioned, the previous implementation may lead to autograd backward function not invoked, this problem has been solved in this PR.
2. Update the solution_annotation_pass to make sure Parameters and Buffers are shard as expected.
3. Refactor the runtime apply function and remove the previous autograd function.
=> [autoparallel] shard param and buffer as expected

colossalai/auto_parallel/tensor_shard/node_handler/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/bmm_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/matmul_strategy_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/strategy_generator.py, colossalai/auto_parallel/tensor_shard/utils/broadcast.py, colossalai/fx/tracer/meta_patch/patched_function/arithmetic.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_addbmm_handler.py
This PR added the handler for `torch.addbmm` and `torch.Tensor.addbmm`. This node handler involves the conversion from broadcast shape to its physical shape.
The `addbmm` is explained [here](https://pytorch.org/docs/stable/generated/torch.addbmm.html) and can be represented by 
out = addbmm(bias, mat1, mat2) where mat1 and mat2 are 2D, bias is 1D or 2D and out is 2D.
=> [autoparallel] added addbmm handler

colossalai/kernel/cuda_native/flash_attention.py, requirements/requirements-test.txt, requirements/requirements.txt, tests/test_utils/test_flash_attention.py
add cuda and triton flash attention
=> [feat] add flash attention

colossalai/auto_parallel/passes/runtime_apply_pass.py, colossalai/auto_parallel/passes/runtime_preparation_pass.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/conv_strategy_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/strategy_generator.py, colossalai/auto_parallel/tensor_shard/sharding_strategy.py, colossalai/device/device_mesh.py, colossalai/tensor/shape_consistency.py, colossalai/tensor/sharding_spec.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_conv_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py
This PR provides some apis to do numerical tests for node strategies. The function called numerical_test_for_node_strategy will check the **output of forward result, the gradient of the input activation and gradient of parameters if exist** with the original result of non-distributed version.
Note: only convolution handler tests updated with the above apis as an example, other handlers unit test will be updated in next PR.
=> [autoparallel] add numerical test for node strategies

colossalai/auto_parallel/tensor_shard/node_handler/linear_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/batch_norm_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/getitem_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/layer_norm_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/matmul_strategy_generator.py, colossalai/tensor/comm_spec.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_linear_handler.py
In previous PR #1735 , the sequential order has been added into CommSpec, which integrate into a CommAction object. In this PR, all the handlers using CommSpec wiil be updated to use CommAction.
1. **Add comm_type to CommAction object**, and if **the CommType is BEFORE**, **an identifier such as arg_index or key_for_kwarg will be added**.
2. **We distinguish the parameters and non-parameters tensor**. For Parameters grad, a hook function will be registered to param, however, a runtime communication node will be added for a non-parameter tensor.
=> [autoparallel] update CommSpec to CommActions

requirements/requirements-test.txt
Downgrade requirements for `fbgemm-gpu` because of errors in latest version.
https://github.com/pytorch/FBGEMM/issues/1401
=> [CI] downgrade requirements fbgemm.

colossalai/pipeline/utils.py
Instead of torch.Tensor, Huggingface will take their own structures as the output between layers. So we've to remove type check for torch.Tensor.
=> [Pipeline]Adapt to Pipelinable OPT

colossalai/auto_parallel/tensor_shard/node_handler/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/matmul_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/matmul_strategy_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/strategy_generator.py, colossalai/auto_parallel/tensor_shard/utils/broadcast.py, colossalai/tensor/sharding_spec.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_matmul_handler.py
We don't have a node handler to deal with `torch.matmul` operation. This makes it tough to parallelize modules like the self-attention module.
This PR implemented the matmul node handler to cover the strategy generation for all compute cases. This node handler has been tested against more than 10 test cases to ensure correctness.
- `sharding_spec.py`: the `ShardingSpec` class's `__init__` is updated such that it will convert `list` to `torch.Size` when `entire_size` is a list of integers.
- `matmul_strategy_generator.py`: fixed some bugs in the strategy and added the `ignore_sharding_exception` decorator.
- `test_matmul_handler.py`: test for all dot/matrix-matrix/matrix-vector/batched-matrix multiplication.
- `matmul_handler.py`: this file contains the main change in this PR. These …
=> [autoparallel] added matmul handler

colossalai/auto_parallel/tensor_shard/node_handler/binary_elementwise_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/bmm_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/matmul_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/where_handler.py, colossalai/auto_parallel/tensor_shard/utils/__init__.py, colossalai/auto_parallel/tensor_shard/utils/broadcast.py, colossalai/fx/tracer/bias_addition_patch/patched_bias_addition_module/conv.py, tests/test_auto_parallel/test_tensor_shard/test_broadcast.py, tests/test_fx/test_tracer/test_bias_addition_module.py
When we construct strategies for broadcast kernels, some oprands may lose information due to convertion from logical shape to physical shape. In this PR, the essential CommActions is added for computing correctness.
Note: I use unit test for binary handler as this PR test. Previously, the tests fails due to the reason mentioned above, and those cases pass with this PR work.
=> [autoparallel]add essential CommActions for broadcast oprands

colossalai/kernel/cuda_native/csrc/multihead_attention_1d.cpp, colossalai/kernel/cuda_native/csrc/multihead_attention_1d.h
According to [link1](https://github.com/pytorch/pytorch/commit/4f2d869095034301b903cd2ef807b416547c0d9c) and [link2](https://github.com/pytorch/pytorch/commit/089a64e99e2d2b937c72e25c0fa6e4f673b8a1a1),  c10d headers files were changed from `<c10d/*.h>`  to `${TORCH_INSTALL_INCLUDE_DIR}/torch/csrc/distributed/c10d`. 
This pr is for compatibility with upstream modifications.
=> fix build error when torch version >= 1.13

colossalai/auto_parallel/passes/runtime_apply_pass.py, colossalai/auto_parallel/passes/runtime_preparation_pass.py, colossalai/auto_parallel/tensor_shard/node_handler/reshape_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/reshape_generator.py, colossalai/fx/tracer/bias_addition_patch/patched_bias_addition_module/conv.py, colossalai/fx/tracer/meta_patch/patched_function/arithmetic.py, tests/test_auto_parallel/test_tensor_shard/test_bias_addition_forward.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bias_linear_module_node.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py
This PR mainly adds two features:
1. processes get_attr node in passes 
2. add a new numerical test mode for module with bias addition
Both features above are used to support bias addition module in PR, but they may also be useful features for other usages.
Additionally, two unit test are built to check the correctness.
=> [autoparallel] fix bias addition module

colossalai/auto_parallel/tensor_shard/node_handler/matmul_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/batch_norm_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/normal_pooling_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/strategy_generator.py, colossalai/tensor/__init__.py, colossalai/tensor/colo_parameter.py, colossalai/tensor/colo_tensor.py, colossalai/tensor/dist_spec_mgr.py, colossalai/tensor/param_op_hook.py, colossalai/tensor/sharding_spec.py, colossalai/tensor/tensor_spec.py, colossalai/tensor/utils.py
This PR converts the key of dim_partition_dict with negative value to positive value, which could avoid some bugs due to negative value pointing the same dimension as other key with positive value.
This PR also adds ignore_exception decorator to node handlers.
=> [autoparallel] fix bugs caused by negative dim key

colossalai/auto_parallel/passes/runtime_preparation_pass.py, colossalai/auto_parallel/tensor_shard/node_handler/linear_handler.py, colossalai/auto_parallel/tensor_shard/solver/solver.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py
This PR converts the logical last dim of linear input and output to physical last dim.
For example:
The input logical tensor for linear node is a 2d tensor. So if the last dim is sharded, the dim_partition_dict is {1: [0]}
However, if input is a 4d tensor physically, we should modify the dim_partition_dict to {3: [0]}
=> [autoparallel] fix linear logical convert issue

colossalai/auto_parallel/passes/runtime_apply_pass.py, colossalai/auto_parallel/passes/runtime_preparation_pass.py, colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/batch_norm_generator.py, colossalai/tensor/comm_spec.py
This PR mainly does two things:
1. remove redundancy comm node: if the sharding spec of node output is same as the user node required sharding spec, we will not insert any node between this pair of nodes.
2. The resharding costs just count the element numbers, size_per_elem_bytes is added in this PR.
=> [autoparallel] remove redundancy comm node

colossalai/auto_parallel/tensor_shard/node_handler/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/addmm_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/linear_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/matmul_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/matmul_strategy_generator.py, colossalai/fx/tracer/meta_patch/patched_function/arithmetic.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_addmm_handler.py
1. torch.addmm is patched to support symbolic tracer.
2. Add implementation of addmm handler, which reuses the LinearProjectionGenerator with some changes. The main difference between linear with bias addition and addmm is that the bias operand in addmm may have more than one dimension. The label named 'linear_projection_type' is used to distinguish this two pattern.
=> [autoparallel] support addmm in tracer and solver

.github/workflows/release_bdist.yml, .github/workflows/scripts/build_colossalai_wheel.sh
In some previous workflow runs, the wheels distributed do not have cuda extension even though the environment is correct as it uses the extension files from the previous build. In this PR, two things are done:
1. remove the build folder after each bdist build to enable compilation for each build run
2. added conda cache directory to save time on downloading the conda files
=> [workflow] added conda cache and fixed no-compilation bug in release

colossalai/device/device_mesh.py, colossalai/tensor/comm_spec.py, colossalai/tensor/shape_consistency.py, colossalai/tensor/utils.py, tests/test_tensor/test_mix_gather.py
**What's new?**
Add a one-step transformation called ***mix-gather*** for:
|Src|Dst|
|---|---|
|S0S1|RR|
|S1S0|RR|
|S01R|RR|
|RS01|RR|
**Why do we need this?**
Reduce the communication cost.
Assume $\beta_1 \gt \beta_0$, $M$ is the communication size.
Cost for S0S1=>S0R=>RR is $\frac{M}{n_1n_0}\times\frac{n_1-1}{n_1}\times\beta_1 + \frac{M}{n_1}\times\frac{n_0-1}{n_0}\times\beta_0$
Cost for S0S1=>RR is $\frac{M}{n_0n_1}\times\frac{n_0n_1-1}{n_0n_1}\times\beta_1$
**Pitfalls**
Peak memory increases by the size of a tensor for S0S1=>RR and S1S0=>RR
=> [autoparallel] mix gather

colossalai/auto_parallel/tensor_shard/node_handler/experimental/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/experimental/view_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/experimental/view_handler.py, colossalai/auto_parallel/tensor_shard/sharding_strategy.py, colossalai/auto_parallel/tensor_shard/solver/strategies_constructor.py, colossalai/auto_parallel/tensor_shard/utils/__init__.py, colossalai/auto_parallel/tensor_shard/utils/reshape.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_view_handler.py
Previously, to keep the computation correctness, the reshape handler force the input cast to the fully replicated status. This coarse action takes some extra unnecessary communication.
1. This PR defines some useful functions for all the reshape operation, such as detect_reshape_mapping, check_keep_sharding_status, and infer_output_dim_partition_dict.
2. Use above functions build view generator. It will keep shard spec if the check passes, otherwise it will convert input to fully replicated status for computation correctness.
3. Build a unit test to test the strategy generated by above generator.
Note: due to the runtime pass for view op not completed, the numerical test is not added into the unit test, but it has been done by offline test.
1. In this PR, runtime pass is not completed, it …
=> [autoparallel] add experimental view handler

colossalai/auto_parallel/passes/runtime_preparation_pass.py, colossalai/auto_parallel/tensor_shard/node_handler/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/experimental/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/experimental/permute_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/experimental/reshape_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/experimental/transpose_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/experimental/view_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/reshape_handler.py, colossalai/tensor/comm_spec.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_permute_and_transpose_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_permute_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_view_handler.py
1. This PR integrates torch.reshape, torch.Tensor.reshape into view handler, and add related runtime passes for them.
2. Complete the permute handler for torch.permute, torch.Tensor.permute, and transpose handler for torch.transpose, torch.Tensor.transpose.
3. Fix a bug in _all_gahter, which leads to unreported bugs in non-contiguous tensors communication.
4. Add unit test to test the numerical correctness for above handlers.
=> [autoparallel] add experimental permute handler

colossalai/auto_parallel/passes/runtime_apply_pass.py, colossalai/auto_parallel/passes/runtime_preparation_pass.py, colossalai/auto_parallel/tensor_shard/node_handler/experimental/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/experimental/reshape_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/experimental/split_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/reshape_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/output_generator.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_split_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py
Previously, input with any sharding_specs will force casting to replicated status to make sure the split operation correct. 
1. In this PR, we analysis the args and kwargs of the split node, we will **keep the sharding_spec if we can**, and **only recover the split dimension if we have to.**
2. Add related runtime passes to keep the computation correctness.
3. This PR also fix some bugs caused by tuple or list object fed into shape consistency manager.
4. Build unit test to check the strategies and numerical result.
=> [autoparallel] add split handler

tests/components_to_test/bert.py, tests/test_gemini/update/test_optim.py, tests/test_gemini/update/test_zeroddp_state_dict.py
add more tests for the optimizer test of Gemini. I find that `test_optim.py` can not work for simple_net! You can merge this PR. We should fix the simple_net bug in another PR.
=> [Gemini] more tests for Gemini

colossalai/cli/check/check_installation.py
We use `colossalai check -i` to debug whether the installation is correct. However, it does not check on the compatibility for PyTorch.
This PR added compatibility information for PyTorch thanks to #2048  which provides torch/cuda version info in colossalai version.
Before this PR:
After this PR:
=> [cli] updated installation cheheck with more inforamtion

colossalai/auto_parallel/passes/runtime_preparation_pass.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bias_linear_module_node.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_linear_handler.py
1. Fix bugs caused by too strict assertion in runtime preparation pass. The valid arguments for torch.Tensor.view should be (input, *dims), (input, tuple(dims)),  (input, list(dims)). In this PR, all cases has been covered.
2. Fix bugs caused by linear strategy name changing. The reason why the name changed is long story:
**To traverse all possible shard strategy in batch dimensions, the linear strategy will be expended to a series strategies from the base strategy which treat input as a 2-d tensor.** However, **these series strategies share the same name**, and will be removed in StrategyConstructor. To avoid this, index has been attached to the end of the strategy name.
=> [hotfix] update test for latest version

colossalai/auto_parallel/tensor_shard/node_handler/strategy/matmul_strategy_generator.py, colossalai/auto_parallel/tensor_shard/sharding_strategy.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bias_linear_module_node.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_linear_handler.py
1. fix a bug in Sharding_Strategy __deepcopy__. We need to deepcopy communication_actions when self.communication_actions is not None, instead of checking its __bool__ value. 
Consider the examples below:
If self.communication_actions is an empty dictionary {}, then self.communication_actions is not None, but its __bool__ value is False.
In this case, if we set None to the new object, program will crash when we try to access the communication_actions.items.
2. Add non_split linear strategy.
3. Add more strict assertions in linear related unit tests.
=> [autoparallel] add non_split linear strategy

colossalai/auto_parallel/tensor_shard/node_handler/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/reshape_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/tensor_constructor_generator.py, colossalai/auto_parallel/tensor_shard/node_handler/tensor_constructor_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_tensor_constructor.py
1. This PR creates TensorConstructorHandler for some tensor constructor operations such as torch.arange, torch.rand. These operations could share same node handler and generator, because they have **no tensor input and just create a new tensor depending on some int arguments.**
2. Construct unit test for them
Note: This PR just create a replicated strategy, **which means the handler is not able to create distributed tensor now.**
=> [autoparallel] add tensor constructor handler

colossalai/fx/tracer/bias_addition_patch/patched_bias_addition_function/__init__.py, colossalai/fx/tracer/bias_addition_patch/patched_bias_addition_function/addmm.py, colossalai/fx/tracer/bias_addition_patch/patched_bias_addition_function/bias_addition_function.py, colossalai/fx/tracer/tracer.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_addmm_handler.py
1. This PR implements BiasAdditionFunc class which is used to construct the restructure computation graph for call_func node with bias addition inside.
2. This PR uses the BiasAdditionFunc class as the base class to implement LinearBasedBiasFunc class which is used to construct the restructure computation graph for call_func node based on F.linear, such as torch.addmm, torch.addbmm.
3. This PR patchs the nodes with torch.addmm target to make sure the numerical correctness.
For example:
The formula for torch.addmm is output = alpha * input + beta * (m1 @ m2)
The origin node is:
%addmm: call_func[target=torch.addmm](args = (%input_1, m1, m2), kwargs = {beta=1, alpha=1})
Restructured graph is:
%transpose : [#users=1] = call_function[target=torch.transpose](args = (%m2, 0, 1), kwargs = {}) …
=> [autoparallel] add bias addtion function class

colossalai/fx/tracer/bias_addition_patch/patched_bias_addition_function/__init__.py, colossalai/fx/tracer/bias_addition_patch/patched_bias_addition_function/addbmm.py, colossalai/fx/tracer/bias_addition_patch/patched_bias_addition_function/addmm.py, colossalai/fx/tracer/bias_addition_patch/patched_bias_addition_function/bias_addition_function.py, colossalai/fx/tracer/registry.py, colossalai/fx/tracer/tracer.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_addbmm_handler.py
1. This PR patches the addbmm node to solve the compatibility issue with bias addition and all reduce. The restructured node looks like:
original one is:
%addbmm : [#users=1] = call_function[target=torch.addbmm](args = (%bias, %x1, %x2), kwargs = {})
Restructured graph is:
%bmm : [#users=1] = call_function[target=torch.bmm](args = (%x1, %x2), kwargs = {})
%sum_1 : [#users=1] = call_function[target=torch.sum](args = (%bmm, 0), kwargs = {})
%add : [#users=1] = call_function[target=operator.add](args = (%sum_1, %bias), kwargs = {})
2. Construct unit tests for it to cover most of the cases, such as different input dims, different function type(torch.addbmm or torch.Tensor.addbmm)
=> [autoparallel] support addbmm computation

tests/components_to_test/__init__.py, tests/components_to_test/beit.py, tests/test_gemini/update/test_optim.py, tests/test_tensor/common_utils/_utils.py, tests/test_zero/test_init_context.py
* added beit model for unit testings
* I didn't enable the checkpoint of the beit model, since it is incompatible with torch 0.1.12. It is a problem that should be blamed on timm liberary.
=> [testing] add beit model for unit testings

colossalai/auto_parallel/passes/runtime_preparation_pass.py, colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/strategy/getattr_generator.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_addmm_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_getattr_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py
Previously, the get_attr node is treated as a pending strategy, which mean the strategy of it depends on the user strategy. It works well in most of the cases, such as get_attr node followed by linear node. However, in addmm node, we need to transform the graph for the bias addition issue, the graph looks like:
%bias : [#users=1] = get_attr[target=bias]
%weight : [#users=1] = get_attr[target=weight]
%transpose : [#users=1] = call_function[target=torch.transpose](args = (%weight, 0, 1), kwargs = {})
%linear : [#users=1] = call_function[target=torch._C._nn.linear](args = (%m1, %transpose), kwargs = {})
%mul : [#users=1] = call_function[target=operator.mul](args = (%bias, 3), kwargs = {})
%mul_1 : [#users=1] = call_function[target=operator.mul](args = (2, %linear), kwargs = {})
%add : …
=> [autoparallel] update get_attr handler

colossalai/auto_parallel/passes/runtime_apply_pass.py
In the previous PR, the `construct_meta_info` function had incorrect usage of shape-consistency.
=> [autoparallel] fix construct meta info.

colossalai/kernel/cuda_native/csrc/multihead_attention_1d.cpp, colossalai/kernel/cuda_native/csrc/multihead_attention_1d.h, colossalai/tensor/colo_tensor.py
Some version determination options in Colossal-AI are incomplete when using Pytorch 2.0, resulting in build errors when compiling from source, as well as some unit testing errors
=> [Hotfix] Fix building error and runtime error for torch 2.0

colossalai/auto_parallel/passes/comm_metainfo_pass.py, colossalai/auto_parallel/tensor_shard/node_handler/binary_elementwise_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/reshape_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/unary_elementwise_handler.py
Append these few lines after SPMD solver. It works now.
Config:
ResNet50, bs = 512, device_mesh = [[0, 1], [2, 3]]
```python
solver = CheckpointSolverRotor(gm.graph, free_memory=10*1024**3)
solver.print_chain()
gm.graph = solver.solve()
print(gm.code)
```
=> [autockpt] make it work.

colossalai/auto_parallel/meta_profiler/constants.py, colossalai/auto_parallel/meta_profiler/meta_registry/binary_elementwise_ops.py, colossalai/auto_parallel/meta_profiler/metainfo.py, colossalai/auto_parallel/passes/constants.py, colossalai/auto_parallel/passes/meta_info_prop.py
In this PR, I modify the `MetaInfoProp` and some operations' meta registration, so that the `data_ptr` behavior could align with the previous auto activation checkpoint pipeline.
=> [autoparallel] align the data_ptr with the old version of auto activation checkpoint pipeline

colossalai/gemini/gemini_mgr.py, colossalai/gemini/placement_policy.py, colossalai/nn/parallel/data_parallel.py, colossalai/nn/parallel/utils.py
Previously, convert_to_torch_module dose not work. Because it can not find the correct place to store param.data. Now, I fix this bug.
You can test the feature with the following code.
torchrun --standalone --nproc_per_node=1 XXX.py
```
import colossalai
from colossalai.utils import get_current_device
from colossalai.nn.parallel import GeminiDDP
from transformers import BloomForCausalLM, AutoTokenizer
from colossalai.utils.model.colo_init_context import ColoInitContext, post_process_colo_init_ctx
from colossalai.tensor import ColoTensor, ProcessGroup
from colossalai.nn.parallel.utils import convert_to_torch_module
config = {
"BATCH": 4,
"gradient_accumulation_steps": 1,
"clip_grad_norm": 1,
}
colossalai.launch_from_torch(config=config)
pg = ProcessGroup()
with ColoInitContext():
model = …
```
=> [Gemini] fix the convert_to_torch_module bug

colossalai/auto_parallel/checkpoint/ckpt_solver_base.py, colossalai/auto_parallel/checkpoint/ckpt_solver_chen.py, colossalai/auto_parallel/checkpoint/ckpt_solver_rotor.py, colossalai/auto_parallel/meta_profiler/constants.py, colossalai/auto_parallel/meta_profiler/meta_registry/binary_elementwise_ops.py, colossalai/auto_parallel/meta_profiler/metainfo.py, colossalai/auto_parallel/passes/comm_metainfo_pass.py, colossalai/auto_parallel/passes/constants.py, colossalai/auto_parallel/passes/meta_info_prop.py, colossalai/auto_parallel/passes/runtime_apply_pass.py, colossalai/auto_parallel/tensor_shard/node_handler/binary_elementwise_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/reshape_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/unary_elementwise_handler.py, colossalai/fx/profiler/shard_utils.py, colossalai/tensor/shape_consistency.py
=> [autockpt] provide option for activation checkpoint search in SPMD solver

op_builder/__init__.py, op_builder/builder.py, op_builder/cpu_adam.py, op_builder/fused_optim.py, op_builder/moe.py, op_builder/multi_head_attn.py, op_builder/scaled_upper_triang_masked_softmax.py, op_builder/utils.py, setup.py
The `setup.py` failed if we directly execute `pip install .` without `pip install -r requirements/requirements.txt`. This will lead to build error when we release wheels. The root cause is that `setup.py` has dependency on `colossalai` which leads to a deadlock.
This PR copied the `op_builder` to the project root directory so that `setup.py` can work successfully. This is only a temporary fix since we still have a copy of `op_builder` inside `colossalai.kernel`. Refactoring will come in a separate PR.
1. Modify CI such that it tries to rebuild-kernel upon kernel/setup.py file change
2. Support cuda extension build in CLI as well
3. build kernel only when the op is used
=> [setup] removed the build dependency on colossalai

.github/workflows/build.yml
When we execute the build and unit testing for ColossalAI, we cache the built CUDA extension for shorter build time. However, when the kernel file is changed, the cache will still be used and no re-build is triggered.
This PR modified the workflow to detect the changes of extension-related files and re-build the cuda kernel when such files are found.
=> [workflow] rebuild cuda kernels when kernel-related files change

op_builder/builder.py, setup.py
The `setup.py` and `op_builder` both have dependencies on torch, however, during pypi wheel build, the environment is plain Python without torch, leading to build error.
Command to build pypi release: `python setup.py sdist build`
Fixed #2332 
This PR make the torch dependency optional in both `setup.py` and `op_builder`. With this PR, the command can run without failure.
=> [setup] remove torch dependency

.github/workflows/build.yml, .github/workflows/build_gpu_8.yml, setup.py
It will in the best interest of the user if they can install colossalai smoothly. Currently, we force the user to build CUDA extensions upon `pip install`, which leads to much convenience.
Fixed #2334 
This PR make building CUDA extension optional in the `setup.py`.
```
pip install colossalai
CUDA_EXT=1 pip install colossalai
```
=> [setup] make cuda extension build optional

colossalai/device/alpha_beta_profiler.py, tests/test_device/test_extract_alpha_beta.py, tests/test_device/test_search_logical_device_mesh.py
1. implement search_best_logical_mesh function, which could find best logical mesh for the given device list.
The best logical mesh is searched in following steps:
1. detect homogeneous device groups, we assume that the devices in the alpha_beta_dict are homogeneous if the beta value is close enough.
2. Find the best homogeneous device group contains all the physical devices. The best homogeneous device group means the lowest beta value in the groups which contains all the physical devices. And the reason we require the group contains all the physical devices is that the devices not in the group will decrease the bandwidth of the group.
3. If the best homogeneous device group is found, we will construct the largest ring for each device based on the best homogeneous device group, and the …
=> [device] find best logical mesh

.github/workflows/build.yml
Fixed #2386 
The root cause of the issue #2386 is that the job `detect` does not produce an output `anyChanged`, as a result, the step `restore cache` is always skipped. This PR added the missing output.
=> [workflow] added missing file change detection output

.github/workflows/release_nightly.yml, setup.py
This PR added the nightly release workflow to release the nightly version once a week to PyPI.
=> [workflow] added nightly release to pypi

colossalai/nn/optimizer/cpu_adam.py, colossalai/nn/optimizer/fused_adam.py, colossalai/nn/optimizer/fused_lamb.py, colossalai/nn/optimizer/fused_sgd.py, colossalai/nn/optimizer/hybrid_adam.py
This PR updated the docstring for the kernel-related optimizers as the kernel can be built during either installation or runtime now.
=> [doc] updated kernel-related optimisers' docstring

.github/workflows/release_docker.yml, docker/Dockerfile
The previous workflow did not work anymore and maintenance is urgently required. This PR fixed the workflow. It has been tested and successfully built and pushed the latest version to Dockerhub. Please see https://hub.docker.com/layers/hpcaitech/colossalai/0.2.0/images/sha256-eb2697411805d18b9cbc1b0c03d457a745f2f8467f7961da64b61a4d4cbb89fb?context=explore.
=> [docker] updated Dockerfile and release workflow

colossalai/context/parallel_context.py
This PR is related to [this issue](https://github.com/hpcaitech/ColossalAI/issues/2407).
=> Fix a typo in parallel_context.py

.github/workflows/translate_comment.yml
As we have more users, somer users prefer to post their issues/comments in their native languages. However, this can be difficult to understand for other users/developers. Thus, a workflow is added to translate non-English comments to English automatically for internationalization.
=> [workflow] added translation for non-english comments

setup.py
This PR updated the `setup.py` to put nightly version after the official release version, such that github will not treat `colossalai-nightly` as the package name.
=> [setup] refactored setup.py for dependency graph

.github/workflows/auto_example_check.yml, .github/workflows/build.yml, .github/workflows/comment.yml, .github/workflows/pre_commit.yml
As we have added pre-commit checks on the changed files, we should tell the contributor how to fix the format if the pre-commit check is not passed. This PR added a workflow file which will be triggered if the pre-commit workflow fails and post a comment to the PR automatically.
Meanwhile, I have updated the logic of changed file detection to ensure it detects all the changed files.
=> [workflow] auto comment if precommit check fails

.github/workflows/report_test_coverage.yml
Fixed #2429 
This PR fixed the workflow parameters such that test coverage is still reported even if the coverage rate is below 80%.
=> [workflow] report test coverage even if below threshold

colossalai/gemini/chunk/search_utils.py, colossalai/gemini/chunk/utils.py, colossalai/nn/optimizer/zero_optimizer.py, colossalai/nn/parallel/data_parallel.py, colossalai/utils/__init__.py, colossalai/utils/common.py, colossalai/zero/utils/gemini_hook.py
* replace `getattr(p, '_ddp_to_ignore', False)` with `is_ddp_ignored(p)`
=> [ddp] add is_ddp_ignored

.github/workflows/report_test_coverage.yml
Fixed #2435 
This PR modified the generated test coverage report in markdown and make the table collapsable. The result will look like this.
=> [workflow] make test coverage report collapsable

colossalai/auto_parallel/tensor_shard/node_handler/__init__.py, colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py, colossalai/auto_parallel/tensor_shard/node_handler/option.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_shard_option.py
This PR implements ShardOption class which could be used to filter some unshard or not fully shard strategies.
There are three level to choose:
STANDARD: We do not add any extra shard requirements.
SHARD: We require the node to be shard using at least one device mesh axis.
FULL_SHARD: We require the node to be shard using all device mesh axes.
=> [autoparallel] add shard option

colossalai/fx/graph_module.py, colossalai/fx/tracer/_symbolic_trace.py, colossalai/fx/tracer/experimental.py
Previously we neglect the possibility of tracing native ckpt using `ColoTracer` and applying that to `autoparallel`. It's compatible, however, to our current implementation.
=> [fx] allow native ckpt trace and codegen.

colossalai/cli/launcher/run.py, examples/tutorial/hybrid_parallel/README.md, examples/tutorial/hybrid_parallel/config.py, examples/tutorial/hybrid_parallel/requirements.txt, examples/tutorial/hybrid_parallel/test_ci.sh, examples/tutorial/hybrid_parallel/train.py
Fixed #2447 
This PR updated the hybrid parallel tutorial with the following changes:
1. update the `colossalai run` launcher to make it behave like a normal process
2. replace `torchrun` with `colossalai run` in `test_ci.sh`
3. only keep the usage of `synthetic dataset` since its aim is only to run a demo.
=> [example] updated the hybrid parallel tutorial

examples/tutorial/large_batch_optimizer/README.md, examples/tutorial/large_batch_optimizer/config.py, examples/tutorial/large_batch_optimizer/requirements.txt, examples/tutorial/large_batch_optimizer/test_ci.sh, examples/tutorial/large_batch_optimizer/train.py
This PR updated the tutorial of the large-batch optimizer with the following changes:
1. integrate this example with CI
2. only keep the usage of synthetic data as it is supposed to be a quick-start demo where users do not need to handle datasets
=> [example] updated large-batch optimizer tutorial

examples/images/dreambooth/train_dreambooth_colossalai.py
There exists a conflict between [gpc.set_seed(seed)](https://github.com/hpcaitech/ColossalAI/blob/169954f87e9d79af0990cd286d89a5308cb21532/colossalai/initialize.py#L113) and [gpc.set_seed(args.seed)](https://github.com/hpcaitech/ColossalAI/blob/main/examples/images/dreambooth/train_dreambooth_colossalai.py#L361) that leads to issue https://github.com/hpcaitech/ColossalAI/issues/2380.
This PR solves this problem.
=> Fix bug in dreambooth example

colossalai/auto_parallel/tensor_shard/node_handler/binary_elementwise_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_binary_elementwise_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py
Previously, the binary elementwise handler suppose all node type argument with Tensor type meta_data, however, the type of meta_data could be int or float. Additionally, the filter in post_process has conflict with the get_arg_value method.
In this PR, above issues in BinaryElementwiseHandler has been fixed.
=> [autoparallel] update binary elementwise handler

colossalai/initialize.py
It solves issue https://github.com/hpcaitech/ColossalAI/issues/2250
=> Fix False warning in initialize.py

examples/tutorial/auto_parallel/auto_parallel_with_resnet.py, examples/tutorial/auto_parallel/environment.yaml, examples/tutorial/auto_parallel/setup.py, examples/tutorial/auto_parallel/test_ci.sh
This PR updates the auto-parallel tutorial demo with the lastest api.
=> [examples] update autoparallel tutorial demo

colossalai/cli/launcher/hostinfo.py
Some users encountered errors when running `colossalai run` on localhost, such as the one in the [discussion](https://github.com/hpcaitech/ColossalAI/discussions/2160). This is because `socket.getfqdn("127.0.0.1")` does not always return `"localhost"`. As a result, Colossal-AI treats `127.0.0.1` as a remote host instead.
This PR fixed this issue by making sure it is always treated as localhost.
=> [cli] fixed hostname mismatch error

examples/images/vit/configs/vit_1d_tp2_ci.py, examples/images/vit/requirements.txt, examples/images/vit/test_ci.sh, examples/images/vit/train.py, examples/images/vit/vit.py
1. Refactor dummy dataloader
2. Add CI script and corresponding config.
=> [example] update vit ci script

examples/language/gpt/gemini/train_gpt_demo.py, examples/language/gpt/test_ci.sh
1. Update train gemini gpt script. CLI arguments receive number of steps.
2. Add test CI script, which cover 18 cases.
=> [example] update gpt gemini example ci test

.github/workflows/auto_example_check.yml
Fixed #2480 .
This PR fixed the skip condition of the example weekly check workflow such that it can work as expected this weekend.
=> [workflow] fixed the skip condition of  example weekly check workflow

colossalai/auto_parallel/passes/runtime_apply_pass.py, colossalai/auto_parallel/passes/runtime_preparation_pass.py, colossalai/auto_parallel/tensor_shard/initialize.py, tests/test_auto_parallel/test_tensor_shard/test_checkpoint.py, tests/test_auto_parallel/test_tensor_shard/test_gpt/test_checkpoint_trace.py
Previously, the communication nodes inserted by auto-parallel system will break the origin checkpoint structure, and the graphmodule generated by fx codegen will have a lot of unexpected checkpoint function.
In this PR, the activation annotation will be considered during the node insertion, and use the ColoGraphModule codegen feature to generate a new distributed model with activation checkpoint.
=> [autoparallel] support origin activation ckpt on autoprallel system

colossalai/zero/sharded_optim/bookkeeping/bucket_store.py, colossalai/zero/sharded_optim/low_level_optim.py, tests/test_tensor/common_utils/_utils.py, tests/test_zero/low_level_zero/test_zero_init.py, tests/test_zero/low_level_zero/test_zero_tp.py
I added a unit testing for hybrid parallelism. It makes sure that the combination of low-level zero and tensor parallelism works fine.  Currently, the testing fails when `overlap_communication` is set to `True`. I'm fixing this bug now.
I found that the gradient hook can't be triggered on `ColoParameter`. Thus, I use the function `register_hook` to add a gradient hook for each parameter. I also polished the code in the zero optimizer.
=> [zero] add unit testings for hybrid parallelism 

colossalai/fx/graph_module.py
Currently in ColoGraphModule, ActivationCheckpointCodeGen will be set automatically in __init__. But other codegen can't be set if so.  So I add an arg to control whether to set ActivationCheckpointCodeGen in __init__.
=> [fx] allow control of ckpt_codegen init

colossalai/autochunk/estimate_memory.py, colossalai/autochunk/trace_flow.py, colossalai/autochunk/trace_indice.py, colossalai/autochunk/utils.py, tests/test_autochunk/test_extramsa_codegen.py, tests/test_autochunk/test_simple_evoformer_codegen.py, tests/test_autochunk/test_simple_evoformer_search.py
Support extramsa, which is an another major module of Alphafold apart from evoformer.
1. support some new op in extramsa, including cat, sum and clone.
2. support using getitem as a slice function, and update some logic for it.
3. update some annotations.
4. update a test for extramsa.
=> [autochunk] support extramsa

.github/workflows/auto_example_check.yml, .github/workflows/build.yml, .github/workflows/pre_commit.yml
Fixed #2513 .
This PR added one more step to locate the base commit for the `origin/main` and the PR branch. This base commit is used as the `base_sha` for `git diff` such that only the PR branch commits are considered for changed file detection.
=> [workflow] fixed changed file detection

colossalai/gemini/chunk/search_utils.py, colossalai/gemini/chunk/utils.py, colossalai/nn/parallel/data_parallel.py, colossalai/nn/parallel/gemini_parallel.py, colossalai/tensor/colo_tensor.py, examples/language/gpt/gemini/train_gpt_demo.py, tests/test_ddp/test_ddp_ignore_params.py, tests/test_gemini/update/test_fwd_bwd.py, tests/test_gemini/update/test_gemini_use_rmt.py, tests/test_gemini/update/test_grad_clip.py, tests/test_gemini/update/test_inference.py, tests/test_gemini/update/test_optim.py, tests/test_gemini/update/test_search.py, tests/test_gemini/update/test_zeroddp_state_dict.py, tests/test_gemini/update/test_zerooptim_state_dict.py, tests/test_tensor/test_tp_with_zero.py
I added `strict_ddp_flag` for the search algorithm in the initialization of chunks. When enabling this mode, all parameters are asumed to replicated across all workers. Thus, all parameters can be created in a process group different from the DDP process group. In this way, parameters can be initlized in a shareded way to reduce the memory cost during initilization.
This can help users initilize large models from pre-trained weights. But it will cause some problems when initlizing from scratch.
=> [gemini] update ddp strict mode

colossalai/fx/profiler/tensor.py
In previous PR #2148, I modified the default device behavior of `MetaTensor`. It seems to have some bad cases in tracing.
=> [hotfix] meta tensor default device.

colossalai/autochunk/autochunk_codegen.py, colossalai/autochunk/estimate_memory.py, colossalai/autochunk/reorder_graph.py, colossalai/autochunk/search_chunk.py, colossalai/autochunk/select_chunk.py, colossalai/autochunk/trace_flow.py, colossalai/autochunk/trace_indice.py, colossalai/autochunk/utils.py, tests/test_autochunk/test_alphafold/test_alphafold_utils.py, tests/test_autochunk/test_alphafold/test_evoformer_block.py, tests/test_autochunk/test_alphafold/test_evoformer_stack.py, tests/test_autochunk/test_alphafold/test_extramsa_block.py, tests/test_autochunk/test_transformer/test_autochunk_gpt.py, tests/test_autochunk/test_transformer/test_transformer_utils.py
Support multi outputs chunk search. Previously we only support single output chunk search. It is more flexible and improve performance by a large margin. For transformer, we reduce memory by 40% than previous search strategy.
1. rewrite search strategy to support multi outputs chunk search
2. fix many, many bugs
3. update tests
=> [autochunk] support multi outputs chunk search

colossalai/gemini/gemini_mgr.py, colossalai/nn/parallel/data_parallel.py
`ZeroDDP`/`GeminiDDP` checks whether warmup when running forward. However, if placement policy is `"cpu"` or `"cuda"`, we don't need to warmup.
This is especially usefull when using `ZeroDDP`/`GeminiDDP` to infer. In inference mode, we cannot sample memory usage of the whole forward-backward step. That is to say, the warmup can be finished. So this will lead to unexpected error.
1. GeminiManager adds a property to indicate whether it needs warmup.
2. Only check whether the warmup is done if it needs warmup.
=> [hotfix] fix zero ddp warmup check

colossalai/kernel/cuda_native/__init__.py, colossalai/kernel/cuda_native/layer_norm.py, colossalai/kernel/cuda_native/scaled_softmax.py, op_builder/builder.py
Fixed #2548 
This PR fixed the kernel build spamming problem. This problem arises from two parts:
1. kernel builder will log on every process
2. kernel builder is called everytime when a module is created. For example, if a model has 5 fused layer norm modules, the kernel build log will display 5 times. 
As a result, the kernel build log will appear `num_process x num_module_created` times.
This PR added `print_rank_0` to print only on the master rank and refactored the kernel build such that it is called only once even if multiple modules are created.
The sample output when running the script in the issue is shown below：
=> [kernel] fixed repeated loading of kernels

.github/workflows/report_leaderboard_to_lark.yml, .github/workflows/scripts/generate_leaderboard_and_send_to_lark.py
>
Closed #2563 
This PR will generate report for both code contribution and user engagement and send this report to Lark. Code contribution is measured by the number of commits. User engagement is measured by the number of replies given by our team member to an issue/PR created by someone not from our organization.
The sample outcome will be like:
=> [workflow] added contributor and user-engagement report

setup.py
>
Fixed #2570 
The root cause of the issue #2570 is that the `setup.py` will set version to be something like `0.2.0+cu11.3+torch1.12` if built with CUDA_EXT=1 while the package uploaded has meta data `0.2.0` when doing `pythjon setup.py sdist build`. This inconsistency will lead to failure on the pypi side.
This PR remove the torch/cuda suffix from the version number, instead, the cuda/torch version used in pre-build will be kept in `colossalai.version.cuda` and `colossalai.version.torch`.
This has been tested on test-pypi …
=> [setup] fixed inconsistent version meta

.github/workflows/build_on_schedule.yml, .github/workflows/scripts/send_message_to_lark.py, test.sh
>
Fixed #2575 .
This PR added a script to send message to lark if the daily build and test fails.
**Better merge this after #2558**
=> [workflow] added notification if scheduled build fails

.github/workflows/compatiblity_test_on_schedule.yml
>
Fixed #2587 
This PR added the notification to lark if compatibility test fails.
=> [workflow] hook compatibility test failure to lark

.github/workflows/release_docker_after_merge.yml
>
Fixed #2593 
This PR added the notification of docker release status to lark.
A successful test is given below:
=> [workflow] hooked docker release with lark

.github/workflows/release_docker_after_merge.yml, .github/workflows/release_pypi_after_merge.yml, .github/workflows/scripts/generate_release_draft.py
>
Fixed #2603 .
This PR fixed the three release workflows. The root cause for each workflow error is:
1. draft release post: the github api response can have value None for the field author
2. release to pypi: the `needs` field has the wrong job name
3. release to docker: the job status has the wrong github actions context variable
=> [workflow] fixed broken release workflows

.github/workflows/build_on_pr.yml, colossalai/amp/apex_amp/apex_amp.py, requirements/requirements-test.txt
>
Fixed #2609 .
This PR updated the triton requirement to a valid triton release so that the build workflow can pass.
=> [test] fixed the triton version for testing

examples/tutorial/README.md
=> [tutorial] add video link

docs/conf.py, docs/requirements.txt
>
Fixed #2634 .
This PR replaced the default theme with the `book` theme, which looks more modern and clean.
=> [doc] updated the sphinx theme

README-zh-Hans.md, README.md
>
Fixed #2636 
This PR removed the content regarding installation from our project website in README.
=> [doc] removed pre-built wheel installation from readme

colossalai/auto_parallel/passes/runtime_preparation_pass.py, colossalai/auto_parallel/tensor_shard/initialize.py
=> [autoparallel] add overlap option

README-zh-Hans.md, README.md
>
BLOOM has 176B-parameter
https://arxiv.org/abs/2211.05100
=> [doc] fix typo of BLOOM

docs/source/en/sidebar_category_translation.json, docs/source/zh-Hans/sidebar_category_translation.json
>
Fixed #2655 
This PR is a continuation of #2670  as it fixed the sidebar key in the translation file.
=> [dooc] fixed the sidebar itemm key

.github/workflows/check_doc_on_pr.yml
>
Fixed #2676 
This PR added a job to check documentation build when there is any change in `docs`.
=> [workflow] added doc build test

applications/ChatGPT/README.md
=> [doc] add Quick Preview

.github/workflows/run_chatgpt_examples.yml, .github/workflows/run_chatgpt_unit_tests.yml, applications/ChatGPT/benchmarks/benchmark_gpt_dummy.py, applications/ChatGPT/benchmarks/benchmark_opt_lora_dummy.py, applications/ChatGPT/chatgpt/trainer/ppo.py, applications/ChatGPT/examples/train_dummy.py, applications/ChatGPT/examples/train_prompts.py
>
NA
Users must pass `prepare_inputs_fn` to `generation_kwargs` of trainer for each type of model.
For huggingface models, which have `prepare_inputs_for_generation()` method, we can set `prepare_inputs_fn` to this method if   this arg is not passed to `generation_kwargs`.
This will simplify usage.
=> [chatgpt] optimize generation kwargs

colossalai/utils/common.py, colossalai/zero/sharded_optim/_utils.py
This is a private API which is gone after https://github.com/pytorch/pytorch/pull/94709
Fixed https://github.com/hpcaitech/ColossalAI/issues/2774
Use `inf` from `torch`, rather than from `torch._six`
`s/from torch._six import inf/from torch import inf/`
=> Don't use `torch._six`

examples/images/dreambooth/train_dreambooth_colossalai_lora.py
This PR is motivated by [train_text_to_image_lora.py](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py). ColossalAI framework can further optimize the training.
=> [example] add LoRA support

examples/language/gpt/titans/README.md
Fix hpcaitech/ColossalAI#2851
>
Fix hpcaitech/ColossalAI#2851
=> doc: Remove "with slurm"

colossalai/nn/_ops/view.py, colossalai/tensor/colo_tensor.py
Fixed #2832
Removes dependency on the `math.prod` functionality and replaces it with `reduce` and `operator.mul` that are backward compatible with Python3.7.
=> [hotfix]: Remove math.prod dependency

colossalai/nn/layer/colossalai_layer/_utils.py, colossalai/nn/layer/colossalai_layer/dropout.py
Previous implementation of `ColossalaiModule` is a little rough, which may raise various attribute errors, especially when using zero with tensor parallelism. Changed to a safer way to make this module work properly.
Unit test results:
=> [hotfix] fixed using zero with tp cannot access weight correctly

colossalai/auto_parallel/tensor_shard/initialize.py, colossalai/auto_parallel/tensor_shard/solver/solver.py, colossalai/auto_parallel/tensor_shard/solver/strategies_constructor.py, tests/test_auto_parallel/test_tensor_shard/test_gpt/test_solver_with_gpt_module.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py, tests/test_auto_parallel/test_tensor_shard/test_solver_with_resnet_v2.py
>
- Build alias set in StrategyConstructor for all repeating blocks.
- Remove graph analysis from auto parallel workflow
- Using alias set to prune the solving space
=> [autoparallel] apply repeat block to reduce solving time

applications/ChatGPT/chatgpt/trainer/strategies/colossalai.py
>
Shard init is essential when traing large models, however, it's not compatible with `model.from_pretrained()`. Users can load model weights after `strategy.prepare()`. We will print a warning if users enable shard init.
=> [chatgpt] allow shard init and display warning

colossalai/engine/_base_engine.py, colossalai/fx/profiler/experimental/profiler_function/arithmetic.py, colossalai/fx/profiler/experimental/profiler_module/convolution.py, colossalai/fx/profiler/experimental/profiler_module/normalization.py, colossalai/gemini/ophooks/utils.py, colossalai/kernel/cuda_native/csrc/kernels/cublas_wrappers.cu, colossalai/kernel/cuda_native/csrc/kernels/include/cublas_wrappers.h, colossalai/kernel/cuda_native/csrc/kernels/include/feed_forward.h, colossalai/kernel/cuda_native/csrc/kernels/include/strided_batch_gemm.h, colossalai/kernel/cuda_native/csrc/multi_tensor_adam.cu, colossalai/kernel/cuda_native/csrc/multi_tensor_apply.cuh, colossalai/kernel/cuda_native/csrc/type_shim.h, colossalai/nn/optimizer/fused_adam.py, colossalai/nn/optimizer/zero_optimizer.py, colossalai/utils/model/utils.py, colossalai/zero/sharded_model/sharded_model_v2.py, colossalai/zero/sharded_optim/low_level_optim.py, colossalai/zero/sharded_optim/sharded_optim_v2.py, op_builder/builder.py
=> [doc] add deepspeed citation and copyright

.github/workflows/post_commit.yml
>
Fixed #3021 
This PR fixed the post-commit workflow such that it is still seen as successful if all files are well-formatted and there is nothing to commit. Have tested the new workflow file in https://github.com/hpcaitech/ColossalAI/actions/runs/4344828018.
=> [workflow] fixed the post-commit failure when no formatting needed

applications/ChatGPT/chatgpt/models/base/critic.py
> ## 📌 Checklist before creating the PR
> * [x]  I have created an issue for this PR for traceability
> * [x]  The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
> * [ ]  I have added relevant tags if possible for us to better distinguish different PRs
> 
> ## 🚨 Issue number
> > Link this PR to your issue with words like fixed to automatically close the linked issue upon merge
> > e.g. `fixed #1234`, `closed #1234`, `resolved #1234`
> > fixed #3042
> 
> ## 📝 What does this PR do?
> > Summarize your work here.
> > if you have any plots/diagrams/screenshots/tables, please attach them here.
> 
> This commit fix chatgpt critic input as state according to A2C RL algorithm.
> 
> ## 💥 Checklist before requesting a review
> * [x]  I have linked my PR to an …
=> [chatgpt] change critic input as state

examples/language/opt/train_gemini_opt.py
In the OPT 13B model there was an exception handler based on the presumption that Hggingface had a problem with this file binary. It is no longer the case as it properly downloads the model.
=> The Hugginface binary 13B file has been fixed... it properly downloads the file and starts the training process.

colossalai/booster/__init__.py, colossalai/booster/accelerator.py, colossalai/booster/booster.py, colossalai/booster/environment_table.py, colossalai/booster/plugin.py, colossalai/booster/precision.py
>
Fixed #3050 
This PR initialized the `booster` module with respect to #3046 . Some actions taken include:
1. migrate the class definition from the discussion to the Python files
2. added typing hinting for all methods
3. added `#TODO` annotation for methods to be implemented
4. added `__all__` for namescoping
=> [booster] init module structure and definition

docs/README.md, docs/source/en/features/nvme_offload.md, docs/source/en/get_started/installation.md, docs/source/zh-Hans/features/nvme_offload.md, docs/source/zh-Hans/get_started/installation.md
>
Fixed #3074 
This PR fixed the documentation sidebar name. The root cause is that `Docusaurus` takes the first line of the markdown file as the sidebar title. Therefore, we need to move `doc-test-command` declaration to the bottom of the file instead.
=> [doc] moved doc test command to bottom

tests/kit/model_zoo/__init__.py, tests/kit/model_zoo/registry.py, tests/kit/model_zoo/timm/__init__.py, tests/kit/model_zoo/timm/timm.py, tests/test_fx/test_tracer/test_timm_model/test_timm_model.py
>
part of efforts for #3049 
This PR added the model zoo for testing and documented the specifications. As a simple test, I have transformed the tracer testing on TIMM models so that it uses the latest kit.
=> [test] added timm models to test model zoo

colossalai/utils/model/experimental.py
>
Closes #3130 
Implement a single-process version of lazy initialization described in #3124 .
This code is tested locally, and as the model zoo is integrating, more tests will be added in the next PR.
=> [lazyinit] refactor lazy tensor and lazy init ctx

colossalai/tensor/d_tensor/d_tensor.py, colossalai/tensor/d_tensor/layout_converter.py, tests/test_tensor/test_dtensor/test_dtensor.py
resolved #3091 
We have already built a DTensor demo as described in https://github.com/hpcaitech/ColossalAI/issues/2957 using the components of automatic parallelism module. Recently, we refactor/implement some key compents for DTensor, we should refactor the DTensor with the fresh compents.
=> [DTensor] refactor dtensor with new components

requirements/requirements-test.txt, tests/kit/model_zoo/__init__.py, tests/kit/model_zoo/diffusers/__init__.py, tests/kit/model_zoo/diffusers/diffusers.py, tests/test_fx/test_tracer/test_hf_model/test_hf_diffuser.py
>
I added diffuser models in model zoo.
=> [tests] diffuser models in model zoo

README-zh-Hans.md, README.md, applications/ChatGPT/README.md, examples/README.md, examples/images/diffusion/README.md, examples/images/dreambooth/README.md
=> [doc] add community contribution guide

applications/ChatGPT/chatgpt/models/generation.py, applications/ChatGPT/examples/train_prompts.py
>
Closes #3161 
1. Update `examples/train_prompts.py` to ensure each process has the same generation steps.
2. Update generation early stopping condition by considering DDP scheme.
=> [chatgpt] fix ppo training hanging problem with gemini

applications/ChatGPT/chatgpt/dataset/__init__.py, applications/ChatGPT/chatgpt/dataset/reward_dataset.py, applications/ChatGPT/chatgpt/models/__init__.py, applications/ChatGPT/chatgpt/models/bloom/bloom_rm.py, applications/ChatGPT/chatgpt/models/gpt/gpt_rm.py, applications/ChatGPT/chatgpt/models/loss.py, applications/ChatGPT/chatgpt/models/opt/opt_rm.py, applications/ChatGPT/chatgpt/trainer/rm.py, applications/ChatGPT/examples/README.md, applications/ChatGPT/examples/test_ci.sh, applications/ChatGPT/examples/train_reward_model.py, applications/ChatGPT/examples/train_rm.sh
>
update reward model training process
=> [chatgpt]Reward Model Training  Process update

.github/workflows/build_on_pr.yml, tests/kit/model_zoo/torchrec/torchrec.py, tests/test_booster/test_mixed_precision/test_fp16_torch.py, tests/test_fx/test_tracer/test_torchrec_model/test_deepfm_model.py, tests/test_fx/test_tracer/test_torchrec_model/test_dlrm_model.py, tests/test_gemini/update/test_fwd_bwd.py
>
Fixed #3168 
This PR fixed the tests related to the torchrec model.
=> [test] fixed torchrec model test

colossalai/booster/accelerator.py, colossalai/booster/booster.py, tests/test_booster/test_accelerator.py, tests/test_fx/test_tracer/test_torchrec_model/test_dlrm_model.py
>
Fixed #3052 
This PR implemented the accelerator component for booster.
=> [booster] added the accelerator implementation

LICENSE, colossalai/kernel/cuda_native/flash_attention.py, tests/test_utils/test_flash_attention.py
Previous flash attention APIs are in a complete mess, and very hard to use in practice. The new API `ColoAttention` here only imports kernels from `xformers` rather than the multiple sources we previously used. It is able to cover the most common cases in Transformer models, such as:
- Causal attention (e.g. GPT, OPT)
- Bidirectional attention with padded mask (e.g. BERT)
- Bidirectional attention with no mask (e.g. VIT)
- Relative position embedding (e.g. Transformer-XL/BERT)
- Alibi (e.g. BLOOM)
- Cross attention
Test results are shown below:
=> [hotfix] Improved flash attention usage

colossalai/zero/sharded_model/sharded_model_v2.py
>
Fix doc str for zero state dict
=> [zero] Fix doc str for zero state dict

colossalai/zero/init_ctx/init_context.py
>
This PR refactors the `ZeroContextConfig` class to use the `dataclass` decorator from Python's standard library. This change simplifies the code, improves readability, and reduces the possibility of bugs due to human error.
The `dataclass` decorator provides a more concise way to define classes with simple attributes, such as the configuration class.
It automatically generates common special methods, such as `__init__`, `__repr__`, and `__eq__`, reducing the need for boilerplate code.
Using dataclass also makes the code more Pythonic and easier to maintain.
Refactor `ZeroContextConfig` class to use `dataclass` decorator
Update …
=> [zero] Refactor ZeroContextConfig class using dataclass

colossalai/tensor/d_tensor/layout_converter.py
=> [hotfix] layout converting issue

applications/ChatGPT/chatgpt/dataset/__init__.py, applications/ChatGPT/chatgpt/dataset/sft_dataset.py, applications/ChatGPT/chatgpt/models/base/__init__.py, applications/ChatGPT/chatgpt/models/base/lm.py, applications/ChatGPT/chatgpt/models/bloom/__init__.py, applications/ChatGPT/chatgpt/models/bloom/bloom_lm.py, applications/ChatGPT/chatgpt/models/gpt/__init__.py, applications/ChatGPT/chatgpt/models/gpt/gpt_lm.py, applications/ChatGPT/chatgpt/models/opt/__init__.py, applications/ChatGPT/chatgpt/models/opt/opt_lm.py, applications/ChatGPT/chatgpt/trainer/__init__.py, applications/ChatGPT/chatgpt/trainer/sft.py, applications/ChatGPT/examples/train_sft.py, applications/ChatGPT/examples/train_sft.sh
resolved #3182 
Add supervised learning fine-tune code as mentioned in InstructGPT(step 1)
=> [chatgpt] add supervised learning fine-tune code

colossalai/cluster/__init__.py, colossalai/cluster/device_mesh_manager.py, colossalai/cluster/dist_coordinator.py, colossalai/cluster/process_group_manager.py
>
Fixed #3051 
This PR implemented a `cluster` module to help to coordinate and manage the distributed information in the environment. The `DistCoordinator` is a singleton class which provides utility functions for the user and other modules. The two managers  will be used by the features such as hybrid parallelism/gemini/auto parallelism to manage the process group/device mesh etc.
@YuliangLiu0306 will work on a separate PR to implement  `DeviceMeshManager` .
=> [booster] implemented the cluster module

applications/ChatGPT/chatgpt/models/llama/__init__.py, applications/ChatGPT/chatgpt/models/llama/llama_actor.py, applications/ChatGPT/chatgpt/models/llama/llama_critic.py, applications/ChatGPT/chatgpt/models/llama/llama_rm.py
=> [chatgpt] support llama

colossalai/checkpoint_io/__init__.py, colossalai/checkpoint_io/checkpoint_io_base.py, colossalai/checkpoint_io/general_checkpoint_io.py, test.py, tests/test_checkpoint_io/test_general_checkpoint_io.py
>
Fixed #3053 
This PR added the checkpoint IO module for abstraction of the loading/saving logic for training and inference. Both unsharded/sharded checkpoint is supported. A test is provided to test the unsharded checkpoint saving/loading.
=> [api] implemented the checkpoint io module

applications/ChatGPT/examples/README.md
#issue 3189
>
fixed #3189 
modify the paper link
=> [doc] chatgpt README.md paper link update

applications/ChatGPT/chatgpt/trainer/strategies/colossalai.py
>
Add precision option for ColossalAI strategy.
=> [chatgpt] add precision option for colossalai

colossalai/cluster/device_mesh_manager.py, tests/test_cluster/test_device_mesh_manager.py
=> [API] implement  device mesh manager

colossalai/gemini/chunk/manager.py, colossalai/tensor/colo_tensor.py
> N/A
This pull request updates the `get_dp_world_size` method of the `ColoTensor` class to provide the distributed data parallel (DP) world size of the tensor (Similar to [get_tp_world_size](https://github.com/hpcaitech/ColossalAI/blob/bbac6760e59beed8be6d74f62f9589c8f7240cda/colossalai/tensor/colo_tensor.py#L138) method).
1. Added the `get_dp_world_size` method to the `ColoTensor` class
2. Updated the code that calls `tensor.process_group.dp_world_size()` to use the new method
=> [tensor] Add interface for colo tesnor dp size

colossalai/engine/gradient_handler/_moe_gradient_handler.py
=> [NFC] polish colossalai/engine/gradient_handler/_moe_gradient_handler.py

colossalai/fx/passes/split_module.py
=> [NFC] polish colossalai/fx/passes/split_module.py code style

colossalai/nn/_ops/addmm.py
=> [NFC] polish "colossalai/nn/_ops/addmm.py" code style

applications/Chat/inference/server.py, applications/Chat/inference/utils.py
>
Add profanity check for inference server. If input or response contains profanity, it will returns "The input/response contains inappropriate content, please rephrase your prompt."
=> [coati] inference supports profanity check

applications/Chat/README.md, applications/Chat/examples/README.md
=> [chat]Update Readme

README.md, docs/README-zh-Hans.md
=> [doc] add ColossalChat

applications/Chat/inference/requirements.txt, applications/Chat/inference/utils.py
>
If we simply use regexp to match bad words, we may find "hello" matches "hell", which is not expected.
Thus, we must tokenize sentences before matching. We use "jiebe" to tokenize.
=> [coati] fix inference profanity check

applications/Chat/README.md, applications/README.md
>
Updated README for applications.
=> [application] updated the README

colossalai/nn/layer/moe/__init__.py, colossalai/nn/layer/moe/checkpoint.py, colossalai/nn/layer/moe/experts.py, colossalai/nn/layer/moe/layers.py, tests/test_moe/test_moe_checkpoint.py
=> [moe] add checkpoint for moe models

examples/images/diffusion/README.md
Changed the suitable version of xformers from 0.12.0 to 0.0.12 (probably a typo).
=> [examples/images/diffusion]: README.md: malformed `xformers` version

README.md
Minor changes to improve grammar and punctuation.
Resolved #3397
Minor changes to grammar and punctuation in the README-file,
=> Improve grammar and punctuation

colossalai/auto_parallel/offload/base_offload_module.py, colossalai/auto_parallel/offload/mem_optimize.py, colossalai/auto_parallel/offload/runtime.py, colossalai/auto_parallel/offload/util.py, tests/test_auto_parallel/test_offload/test_perf.py, tests/test_booster/test_plugin/test_gemini_plugin.py, tests/test_zero/low_level_zero/test_zero1_2.py
>
Fixed #3413 
This PR fixed the memory leakage in the auto parallel module and unskipped the gemini plugin test.
=> [test] fixed gemini plugin test

applications/Chat/coati/trainer/strategies/ddp.py, applications/Chat/coati/trainer/strategies/naive.py
>
fixed #3357, fixed #3366 
Fix save_model in naive and ddp strategy
=> [chat] fix save_model in naive and ddp strategy

colossalai/zero/legacy/__init__.py, examples/language/roberta/configs/colossalai_ddp.py, examples/language/roberta/configs/colossalai_zero.py, examples/tutorial/opt/opt/colossalai_zero.py, examples/tutorial/opt/opt/requirements.txt, examples/tutorial/opt/opt/run_clm.py, examples/tutorial/opt/opt/test_ci.sh, examples/tutorial/opt/test_ci.sh
>
Closes #3430 
1. Update legacy zero imports
2. Fix imports of roberta example
3. Fix imports of opt tutorial and add test_ci.sh
=> [example] update examples related to zero/gemini

colossalai/tensor/param_op_hook.py
=> [tensor] Fix typo for param hook op docs

colossalai/booster/plugin/gemini_plugin.py, colossalai/booster/plugin/torch_ddp_plugin.py, examples/tutorial/new_api/torch_ddp/README.md
>
Fixed #3441 
This PR refactored the booster plugins with the new checkpointIO APIs. Tested for both TorchDDP and Gemini plugins.
=> [booster] fixed the torch ddp plugin with the new checkpoint api

applications/Chat/examples/README.md, applications/Chat/inference/README.md
=> [chat]fix readme

applications/Chat/coati/trainer/ppo.py
The function save_model should be a part of PPOTrainer.
save_model函数被错误地外置到模型外部，导致rlhf train阶段无法保存模型。
>
=> [chat]Move the function "save_model" into PPOTrainer

applications/Chat/examples/community/README.md, applications/Chat/examples/community/peft/README.md, applications/Chat/examples/community/peft/easy_dataset.py, applications/Chat/examples/community/peft/easy_models.py, applications/Chat/examples/community/peft/train_peft_prompts.py, applications/Chat/examples/community/peft/train_peft_sft.py
>
- add community example for chat
=> add community example dictionary

colossalai/checkpoint_io/general_checkpoint_io.py, colossalai/checkpoint_io/index_file.py, colossalai/checkpoint_io/utils.py, tests/test_checkpoint_io/test_general_checkpoint_io.py
- [ yes ] I have created an issue for this PR for traceability
- [ yes ] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [ yes ] I have added relevant tags if possible for us to better distinguish different PRs
> 
support loading from and saving as HF sharded checkpoint.
- [ yes ] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [ yes ] My issue clearly describes the …
=> [checkpoint] support huggingface style sharded checkpoint

README.md, docs/README-zh-Hans.md
>
N/A
This PR updated the contributor list with the help of https://[contrib.rocks](https://contrib.rocks/preview?repo=angular%2Fangular-ja)/preview?repo=angular%2Fangular-ja.
=> [doc] updated contributor list

examples/images/diffusion/configs/Teyvat/train_colossalai_teyvat.yaml, examples/images/diffusion/configs/train_colossalai.yaml, examples/images/diffusion/configs/train_colossalai_cifar10.yaml, examples/images/diffusion/configs/train_ddp.yaml, examples/images/diffusion/ldm/models/autoencoder.py, examples/images/diffusion/ldm/models/diffusion/classifier.py, examples/images/diffusion/ldm/models/diffusion/ddpm.py, examples/images/diffusion/main.py, examples/images/diffusion/scripts/img2img.py, examples/images/diffusion/scripts/inpaint.py, examples/images/diffusion/scripts/knn2img.py, examples/images/diffusion/scripts/sample_diffusion.py, examples/images/diffusion/scripts/tests/test_checkpoint.py, examples/images/diffusion/scripts/txt2img.py
=> [WIP] polish code style of stable diffusion example

applications/Chat/coati/models/llama/llama_critic.py
fixed #3428
mv LlamaForCausalLM to LlamaModel
=> [coati] Fix LlamaCritic

colossalai/zero/gemini/gemini_optimizer.py
=> [doc] Add docs for clip args in zero optim

applications/Chat/coati/models/loss.py, applications/Chat/coati/trainer/ppo.py
#3317 
1. Adding an argument vf_coef for value loss which is common in standard PPO implementation.
2. Setting default multiplier of value loss to 0.5 as shown in the original paper.
=> [coati] add vf_coef argument for PPOTrainer

applications/Chat/README.md
>
Add examples of training with limited resources in chat readme.
=> [Chat] add examples of training with limited resources in chat readme

applications/Chat/README.md
>
The main README is very similar to but different from the README under the example, which has caused misunderstandings for many users.
Summary hides some non-essential information to avoid the document being too lengthy.
=> [chat] polish tutorial doc

docs/source/zh-Hans/features/1D_tensor_parallel.md
>
> e.g. `fixed #3562 
Display format optimization, fix bug  #3562
Specific changes
1. "This is called a column-parallel fashion" Translate to Chinese
2. use the ```math code block syntax to display a math expression as a block, No modification of formula content
Please check that the math formula is displayed correctly If OK, I will Synchronize the en version
=> [doc] Update 1D_tensor_parallel.md

colossalai/booster/plugin/gemini_plugin.py, colossalai/zero/gemini/chunk/utils.py, colossalai/zero/gemini/gemini_ddp.py, colossalai/zero/gemini/gemini_optimizer.py, colossalai/zero/low_level/low_level_optim.py, colossalai/zero/wrapper.py, op_builder/builder.py, op_builder/utils.py
>
1. add verbose arg for zero/gemini and gemini plugin
2. add verbose arg for op builder. It's controlled by env `CAI_KERNEL_VERBOSE`
=> [misc] add verbose arg for zero and op builder

colossalai/zero/gemini/chunk/search_utils.py
> N/A
This PR adds missing docstrings to the `colossalai/zero/gemini/chunk/search_utils.py` file. The previous version lacked proper documentation for some functions, making it difficult for users to understand their purpose and usage.
The changes made in this PR include:
- Added detailed docstrings to `_filter_exlarge_params`, `_get_unused_byte`, `_tensor_numel`, and `search_chunk_configuration` functions.
- The docstrings now provide information about the function's purpose, input arguments, and return values.
- The added documentation will help users understand the implementation and usage of these functions better.
Please review and let me know if any modifications are required.
=> [doc] Add missing docstrings to zero3 chunk search utilities

applications/Chat/examples/README.md
>
add community models support guide for community users from PR:https://github.com/hpcaitech/ColossalAI/pull/3567
=> [coati] add costom model support guide

applications/Chat/coati/dataset/sft_dataset.py, applications/Chat/coati/trainer/sft.py, applications/Chat/examples/train_sft.py
>
1. Fix coati-sft-Instruction Tuning (applications/Chat/coati/dataset/sft_dataset.py)
- Multiple unnecessary `copy.deepcopy` leads to slow tokenizer
- Use tokenizer.eos_token instead of the fixed `<|endoftext|>`
- Fix input_ids
- Fix wrong attribute name `self.prompts`
- Fix NameError: name 'data_collator' is not defined (applications/Chat/examples/train_sft.py line 114)
2. Fix: log when `is_rank_0` (applications/Chat/coati/trainer/sft.py)
=> [chat] Fix coati-sft-Instruction Tuning

colossalai/_analyzer/_subclasses/_meta_registration.py
>
Meta registration for meta tensor is not compatible with torch>1.12.1. This PR fixes compatibility.
I tested on torch 1.12.0-2.0.0:
=> [fx] fix meta tensor registration

applications/Chat/benchmarks/benchmark_gpt_dummy.py, applications/Chat/benchmarks/benchmark_opt_lora_dummy.py, applications/Chat/coati/trainer/base.py, applications/Chat/coati/trainer/ppo.py, applications/Chat/coati/trainer/rm.py, applications/Chat/coati/trainer/sft.py, applications/Chat/examples/train_dummy.py, applications/Chat/examples/train_reward_model.py
>
Reconstruct chat trainer and training script.
=> [chat] reconstruct chat trainer and training script

colossalai/zero/gemini/gemini_ddp.py, tests/test_zero/test_gemini/test_zeroddp_state_dict.py
>
As discussed in https://huggingface.co/docs/transformers/main_classes/deepspeed#getting-the-model-weights-out, I think getting fp16 state dict is essential for saving memory.
I added an arg to control the precision of state dict of Gemini.
=> [gemini] state dict supports fp16

colossalai/booster/plugin/__init__.py, colossalai/booster/plugin/low_level_zero_plugin.py, colossalai/zero/low_level/low_level_optim.py, tests/kit/model_zoo/diffusers/diffusers.py, tests/kit/model_zoo/torchaudio/torchaudio.py, tests/kit/model_zoo/torchvision/torchvision.py, tests/test_booster/test_plugin/test_gemini_plugin.py, tests/test_booster/test_plugin/test_low_level_zero_plugin.py, tests/test_booster/test_plugin/test_torch_ddp_plugin.py
>
Add low level zero plugin and corresponding test
=> [booster] add low level zero plugin

applications/Chat/coati/trainer/callbacks/performance_evaluator.py
>
Polish performance evaluator and make the printed information clearer and more detailed.
E.g
=> [chat] polish performance evaluator

applications/Chat/README.md, applications/Chat/coati/models/base/__init__.py, applications/Chat/coati/trainer/ppo.py, applications/Chat/coati/trainer/rm.py, applications/Chat/coati/trainer/sft.py, applications/Chat/coati/trainer/strategies/base.py, applications/Chat/coati/trainer/strategies/colossalai.py, applications/Chat/coati/trainer/strategies/ddp.py, applications/Chat/coati/trainer/strategies/naive.py, applications/Chat/examples/README.md, applications/Chat/examples/train_prompts.py, applications/Chat/examples/train_reward_model.py, applications/Chat/examples/train_sft.py, applications/Chat/tests/test_checkpoint.py
>
1. Refactor `unwrap_xxx` method of strategy. Add a function `get_base_model()` to get base model. For Actor, the base model is the original lm model. For Critic and Reward model, the base model is itself. `Strategy.unwrap_model` is to get original lm model.
2. Refactor model save logic. `Strategy.save_model` always save in pytorch format. And `Strategy.save_pretrained` will save in HF format. However, ColossalAI strategy with stage-3 doesn't support `save_pretrained`.
3. Update examples and readme.
Tell us more if you don't …
=> [chat] refactor model save/load logic

applications/Chat/README.md, applications/Chat/examples/README.md
Not involved
fix spelling error applications/Chat/README.md
and applications/Chat/examples/README.md
=> fix spelling error applications/Chat/README.md

colossalai/booster/plugin/gemini_plugin.py, colossalai/checkpoint_io/checkpoint_io_base.py, colossalai/checkpoint_io/general_checkpoint_io.py, colossalai/checkpoint_io/index_file.py, colossalai/checkpoint_io/utils.py, colossalai/zero/gemini/gemini_ddp.py, examples/language/gpt/gemini/train_gpt_demo.py, pytest.ini, tests/test_checkpoint_io/test_general_checkpoint_io.py, tests/test_zero/test_gemini/test_zeroddp_state_dict_shard.py
>
gemini plugin support shard checkpoint to avoid large checkpoint files.
=> [booster] gemini plugin support shard checkpoint

applications/Chat/examples/README.md, applications/Chat/examples/community/peft/easy_dataset.py, applications/Chat/examples/community/peft/train_peft_prompts.py, applications/Chat/examples/community/peft/train_peft_sft.py, applications/Chat/examples/train_sft.py
Not involved
fix some spelling error with applications/Chat/examples/ 
please check my change 
=> fix some spelling error with applications/Chat/examples/ 

applications/Chat/coati/experience_maker/naive.py, applications/Chat/examples/train_prompts.py
Intial model and reward model are not wrapped by ZeroDDP wrapper，so they cannot accept ColoTensor as model input. Here we use .data as model input.
=> [chat] fix train_prompts.py gemini strategy bug

colossalai/booster/plugin/dp_plugin_base.py, colossalai/booster/plugin/gemini_plugin.py, colossalai/booster/plugin/low_level_zero_plugin.py, colossalai/booster/plugin/plugin_base.py, colossalai/booster/plugin/torch_ddp_plugin.py, examples/tutorial/new_api/cifar_resnet/train.py, examples/tutorial/new_api/cifar_vit/train.py, examples/tutorial/new_api/glue_bert/data.py, tests/test_booster/test_plugin/test_dp_plugin_base.py
>
Closes #3705 
1. Define prepare_train_dataloader() method in Plugin class.
2. Rename this method to prepare_dataloader().
3. Update corresponding examples.
=> [booster] update prepare dataloader method for plugin

colossalai/booster/plugin/gemini_plugin.py, colossalai/booster/plugin/low_level_zero_plugin.py, colossalai/booster/plugin/plugin_base.py, colossalai/booster/plugin/torch_ddp_plugin.py, tests/test_booster/test_plugin/test_dp_plugin_base.py, tests/test_booster/test_plugin/test_torch_ddp_plugin.py
>
Closes #3708 
1. Add no_sync() method in Plugin class.
2. Implement this method in subclasses.
3. Add test for torch DDP no_sync
=> [booster] fix no_sync method

colossalai/booster/plugin/__init__.py, colossalai/booster/plugin/torch_fsdp_plugin.py, colossalai/testing/utils.py, tests/test_booster/test_plugin/test_torch_fsdp_plugin.py
>
> Booster support torch FSDP plugin.
=> [booster] support torch fsdp plugin in booster

tests/test_booster/test_plugin/test_torch_fsdp_plugin.py
> removed modes that fsdp not support in test.
>
=> [booster] removed models that  fsdp not support in test

.github/workflows/README.md, .github/workflows/build_on_pr.yml
>
Closes #3747 
1. Make build on PR workflow run automatically.
2. Update related documentation.
=> [devops] make build on PR run automatically

.github/workflows/doc_check_on_pr.yml, docs/source/zh-Hans/features/1D_tensor_parallel.md
>
Closes #3753 
As described in #3753 , the merge behavior is unexpected, in this PR:
1. Fix branch merge behavior.
2. Update comments.
=> [devops] fix ci for document check

docs/source/en/features/1D_tensor_parallel.md, docs/source/en/features/2D_tensor_parallel.md, docs/source/en/features/2p5D_tensor_parallel.md, docs/source/en/features/3D_tensor_parallel.md, docs/source/zh-Hans/features/1D_tensor_parallel.md, docs/source/zh-Hans/features/2D_tensor_parallel.md, docs/source/zh-Hans/features/2p5D_tensor_parallel.md, docs/source/zh-Hans/features/3D_tensor_parallel.md
>
#3769
update hybrid parallelism document.
=> [doc] update hybrid parallelism doc

colossalai/booster/mixed_precision/__init__.py, colossalai/booster/mixed_precision/fp16_naive.py
=> [amp] Add naive amp demo

.github/workflows/build_on_pr.yml, colossalai/booster/plugin/torch_ddp_plugin.py, colossalai/checkpoint_io/checkpoint_io_base.py, colossalai/checkpoint_io/utils.py, tests/test_booster/test_plugin/test_low_level_zero_plugin.py, tests/test_checkpoint_io/test_torch_ddp_checkpoint_io.py
>
Closes #3773 
1. torch ddp plugin add save sharded model
2. update related unit test
=> [plugin] torch ddp plugin supports sharded model checkpoint

docs/sidebars.json, docs/source/en/features/cluster_utils.md, docs/source/zh-Hans/features/cluster_utils.md
>
Closes #3762 
Add a tutorial for cluster utils class `DistCoordinator`.
=> [doc] add tutorial for cluster utils

colossalai/amp/torch_amp/_grad_scaler.py, colossalai/auto_parallel/meta_profiler/meta_registry/linear.py, colossalai/auto_parallel/passes/runtime_apply_pass.py, colossalai/auto_parallel/passes/runtime_preparation_pass.py, colossalai/autochunk/trace_flow.py, colossalai/autochunk/trace_indice.py
Not involved
[NFC] fix typo colossalai/amp auto_parallel autochunk 
detail info 
modified:   colossalai/amp/torch_amp/_grad_scaler.py
modified:   colossalai/auto_parallel/meta_profiler/meta_registry/linear.py
modified:   colossalai/auto_parallel/passes/runtime_apply_pass.py
modified:   colossalai/auto_parallel/passes/runtime_preparation_pass.py
modified:   colossalai/autochunk/trace_flow.py
modified:   colossalai/autochunk/trace_indice.py
=> [NFC] fix typo colossalai/amp auto_parallel autochunk 

README.md, applications/Chat/README.md, applications/Chat/examples/README.md, docs/README-zh-Hans.md, examples/tutorial/README.md
=> [chat] add performance and tutorial

colossalai/booster/plugin/gemini_plugin.py, colossalai/booster/plugin/low_level_zero_plugin.py, tests/test_checkpoint_io/test_gemini_checkpoint_io.py, tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py, tests/test_checkpoint_io/test_torch_ddp_checkpoint_io.py, tests/test_checkpoint_io/utils.py
>
Closes #3776 
1. Update low level zero and gemini plugin. Saves optimizer checkpoint on each process with different name.
2. Add warning info.
3. Update unit test.
=> [plugin] a workaround for zero plugins' optimizer checkpoint

colossalai/booster/booster.py, docs/source/en/basics/booster_api.md, docs/source/en/features/cluster_utils.md, docs/source/zh-Hans/basics/booster_api.md, docs/source/zh-Hans/features/cluster_utils.md
>
1. Some methods of booster misses docstring. Added them.
2. Fix autodoc for class. It will show all methods of a class. No need to refer its function.
=> [doc] add booster docstring and fix autodoc

.github/workflows/release_docker_after_merge.yml, .github/workflows/release_docker_after_publish.yml, .github/workflows/report_test_coverage.yml
>
Fixed #3793
This PR refactored the workflow for docker release. The changes include:
1. fix the yaml file format
2. only trigger this workflow when a release is published.
=> [workflow] fixed the docker build workflow

.github/workflows/build_on_pr.yml, .github/workflows/doc_check_on_pr.yml, .github/workflows/doc_test_on_pr.yml, .github/workflows/example_check_on_pr.yml
>
Fixed #3802 
This PR added the pull request workflow conditions to run testing on the develop and feature branches.
=> [workflow] enable testing for develop & feature branch

docs/source/en/basics/booster_plugins.md, docs/source/zh-Hans/basics/booster_plugins.md
>
FSDP plugin does not support sharded model checkpoint now. Add a warning in documentation.
=> [doc] add warning about fsdp plugin

docker/Dockerfile, op_builder/utils.py
fixed #3675
fixed #3690
Fixed the above issues.
=> [Docker] Fix a couple of build issues

colossalai/shardformer/README.md
>
N/A
I have updated the README for the shardformer module under development.
=> [shardformer] updated readme

.github/workflows/build_on_pr.yml, .gitignore, colossalai/booster/booster.py, requirements/requirements-test.txt
>
N/A
Testmon seems not working sometimes, I have added stricter requirements to make it work.
=> [workflow] fixed testmon cache in build CI

colossalai/tensor/d_tensor/sharding_spec.py
=> [dtensor] polish sharding spec docstring

.github/workflows/compatiblity_test_on_dispatch.yml, .github/workflows/compatiblity_test_on_pr.yml, README.md, docs/source/en/get_started/installation.md, docs/source/zh-Hans/get_started/installation.md
>
Fixed #3840
This PR added code and documentation to support installation on CUDA 10.2.
=> [workflow] supported test on CUDA 10.2

docs/source/en/features/nvme_offload.md, docs/source/zh-Hans/features/nvme_offload.md
>
#3730 
update nvme offload documents.
=> [doc] update nvme offload documents.

applications/Chat/evaluate/README.md, applications/Chat/evaluate/config/config_cn.json, applications/Chat/evaluate/eval.py, applications/Chat/evaluate/evaluator.py, applications/Chat/evaluate/gpt_evaluate.py, applications/Chat/evaluate/prompt/evaluation_prompt/evaluation_prompt_cn.json, applications/Chat/evaluate/utils.py
>
1. fix a bug when the config file contains one category but the answer file doesn't contains that category
2. fix Chinese prompt file
3. support gpt-3.5-turbo and gpt-4 evaluation
4. polish and update README
=> [evaluation] improvement on evaluation

examples/language/gpt/gemini/test_ci.sh, examples/language/gpt/gemini/train_gpt_demo.py
>
#3867 
update gemini examples that train with booster.
=> [example] update gemini examples

colossalai/amp/naive_amp/mixed_precision_mixin/__init__.py, colossalai/amp/naive_amp/mixed_precision_mixin/base.py, colossalai/amp/naive_amp/mixed_precision_mixin/bf16.py, colossalai/amp/naive_amp/mixed_precision_mixin/fp16.py, colossalai/zero/low_level/low_level_optim.py, tests/test_zero/test_low_level/test_grad_acc.py, tests/test_zero/test_low_level/test_zero1_2.py
>
Closes #3863 
1. Implement mixed precision mixin class described in #3863 . FP16 and BF16 are supported now.
2. Add bf16 support for low level zero optimizer.
3. Update related tests.
=> [bf16] implement mixed precision mixin and add bf16 support for low level zero

colossalai/zero/gemini/gemini_ddp.py, colossalai/zero/gemini/gemini_optimizer.py, tests/test_zero/test_gemini/test_optim.py
>
#3839 
1. Add bf16 support for gemini
2. Update related tests
3. Update docstring
=> [bf16] add bf16 support for gemini

colossalai/booster/plugin/gemini_plugin.py, colossalai/booster/plugin/low_level_zero_plugin.py
>
#3839 
add bf16 support for low level zero and gemini plugins
=> [bf16] add bf16 support for plugins

.github/workflows/README.md, .github/workflows/build_on_pr.yml
=> [devops] improving testmon cache

colossalai/shardformer/README.md
>
Update shardformer readme about how to define new policy
=> [shardformer] update README

.github/workflows/build_on_pr.yml
>
Testmon cache CI uses `mkdir /github/home/testmon_cache/_pull` which may be executed in each run. This may cause file exists error. Updated by `mkdir -p /github/home/testmon_cache/_pull`
=> [devops] hotfix CI about testmon cache

colossalai/cli/launcher/run.py, examples/language/palm/README.md, examples/language/palm/run.sh, examples/language/palm/test_ci.sh, examples/language/palm/train.py
>
Modify palm example with the new booster API
=> [example] Modify palm example with the new booster API

colossalai/trainer/_trainer.py, colossalai/utils/data_sampler/data_parallel_sampler.py, colossalai/utils/model/utils.py, colossalai/utils/profiler/legacy/comm_profiler.py, colossalai/utils/profiler/legacy/pcie_profiler.py, colossalai/utils/profiler/legacy/prof_utils.py, colossalai/utils/rank_recorder/README.md, colossalai/utils/rank_recorder/rank_recorder.py, colossalai/zero/gemini/chunk/chunk.py, colossalai/zero/gemini/chunk/manager.py, colossalai/zero/gemini/memory_tracer/chunk_memstats_collector.py, colossalai/zero/gemini/memory_tracer/memory_monitor.py, colossalai/zero/gemini/utils.py, colossalai/zero/legacy/gemini/ophooks/utils.py, colossalai/zero/legacy/gemini/tensor_utils.py
Not involved
fix typo with colossalai/trainer utils zero 
detail info 
modified:   colossalai/trainer/_trainer.py
modified:   colossalai/utils/data_sampler/data_parallel_sampler.py
modified:   colossalai/utils/model/utils.py
modified:   colossalai/utils/profiler/legacy/comm_profiler.py
modified:   colossalai/utils/profiler/legacy/pcie_profiler.py
modified:   colossalai/utils/profiler/legacy/prof_utils.py
modified:   colossalai/utils/rank_recorder/README.md
modified:   colossalai/utils/rank_recorder/rank_recorder.py
modified:   colossalai/zero/gemini/chunk/chunk.py
modified:   colossalai/zero/gemini/chunk/manager.py
modified:   colossalai/zero/gemini/memory_tracer/chunk_memstats_collector.py
modified:   colossalai/zero/gemini/memory_tracer/memory_monitor.py
modified: …
=> [nfc] fix typo with colossalai/trainer utils zero

colossalai/shardformer/policies/autopolicy.py, colossalai/shardformer/policies/basepolicy.py, colossalai/shardformer/policies/bert.py, colossalai/shardformer/policies/gpt2.py, colossalai/shardformer/shard/sharder.py, colossalai/shardformer/shard/slicer.py, colossalai/shardformer/test/test.py
>
Add support to GPT2, and modify shard and slicer code to support multihead attention layer
=> [shardformer] add gpt2 policy and modify shard and slicer to support

colossalai/initialize.py, colossalai/zero/gemini/memory_tracer/utils.py, colossalai/zero/legacy/init_ctx/init_context.py, colossalai/zero/legacy/sharded_model/sharded_model_v2.py, colossalai/zero/low_level/_utils.py, colossalai/zero/low_level/low_level_optim.py
Not involved
[nfc] fix typo colossalai/zero
detail info 
modified:   colossalai/initialize.py
modified:   colossalai/zero/gemini/memory_tracer/utils.py
modified:   colossalai/zero/legacy/init_ctx/init_context.py
modified:   colossalai/zero/legacy/sharded_model/sharded_model_v2.py
modified:   colossalai/zero/low_level/_utils.py
modified:   colossalai/zero/low_level/low_level_optim.py
=> [nfc] fix typo colossalai/zero

colossalai/device/README.md, colossalai/device/device_mesh.py, colossalai/lazy/lazy_init.py, colossalai/tensor/comm_spec.py, colossalai/tensor/d_tensor/RAEDME.md, colossalai/tensor/d_tensor/__init__.py, colossalai/tensor/d_tensor/comm_spec.py, colossalai/tensor/d_tensor/d_tensor.py, colossalai/tensor/d_tensor/layout.py, colossalai/tensor/d_tensor/layout_converter.py, tests/test_device/test_device_mesh.py, tests/test_device/test_init_logical_pg.py, tests/test_lazy/lazy_init_utils.py, tests/test_lazy/test_distribute.py, tests/test_tensor/test_dtensor/test_comm_spec.py, tests/test_tensor/test_dtensor/test_dtensor.py, tests/test_tensor/test_dtensor/test_layout_converter.py, tests/test_tensor/test_shape_consistency.py, tests/test_tensor/test_sharded_linear.py, tests/test_tensor/test_sharding_spec.py
>
Fixed #3921 
This PR updated the API usage and documentation of DTensor.
=> [dtensor] updated api and doc

docs/source/en/advanced_tutorials/parallelize_your_training_like_Megatron.md, docs/source/zh-Hans/advanced_tutorials/parallelize_your_training_like_Megatron.md, examples/images/dreambooth/README.md, examples/language/bert/README.md, examples/language/gpt/gemini/train_gpt_demo.py, examples/language/gpt/titans/model/embed.py, examples/language/opt/opt_train_demo.py, examples/language/palm/train.py
Not involved
fix typo examples and docs
detail info 
modified:   docs/source/en/advanced_tutorials/parallelize_your_training_
like_Megatron.md
modified:   docs/source/zh-Hans/advanced_tutorials/parallelize_your_trai
ning_like_Megatron.md
modified:   examples/images/dreambooth/README.md
modified:   examples/language/bert/README.md
modified:   examples/language/gpt/gemini/train_gpt_demo.py
modified:   examples/language/gpt/titans/model/embed.py
modified:   examples/language/opt/opt_train_demo.py
modified:   examples/language/palm/train.py
=> [nfc] fix typo examples and docs

colossalai/booster/plugin/gemini_plugin.py, colossalai/checkpoint_io/index_file.py, colossalai/zero/gemini/gemini_ddp.py
>
Fixed #3933 
This PR fixed the logic to handle the parameter shard block in the Gemini's model state dict to avoid empty checkpoint shard.
=> [gemini] fixed the gemini checkpoint io

tests/kit/model_zoo/registry.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_batch_norm_handler.py, tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_output_handler.py, tests/test_tensor/test_dtensor/test_layout_converter.py
Not involved
fix typo tests/
detail info 
modified:   tests/kit/model_zoo/registry.py
modified:   tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_batch_norm_handler.py
modified:   tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_output_handler.py
modified:   tests/test_tensor/test_dtensor/test_layout_converter.py
=> [nfc] fix typo tests/

.github/workflows/scripts/generate_leaderboard_and_send_to_lark.py
Not involved
fix typo .github/workflows/scripts/
modified:   .github/workflows/scripts/generate_leaderboard_and_send_to_lark.py
Make code easier to read
=> fix typo .github/workflows/scripts/

colossalai/elixir/search/simulator.py, op_builder/__init__.py, op_builder/elixir_simulator.py, setup.py, tests/test_elixir/test_src/test_move.py
>
Fixed #3938 
I have moved the `elixir.simulator` to `op_builder` to support both AOT and JIT build of the CPP extension.
=> [elixir] moved simulator build to op_builder

.github/workflows/build_on_pr.yml, .github/workflows/compatiblity_test_on_pr.yml, .github/workflows/doc_check_on_pr.yml, .github/workflows/doc_test_on_pr.yml, .github/workflows/example_check_on_pr.yml
>
Fixed #3959 .
This PR added the `concurrency` config into the github yaml to cancel previous jobs when a PR is synchronized. This will ensure that a PR only has one job in queue and redundant jobs will be cancelled.
Documentation: https://docs.github.com/en/actions/using-jobs/using-concurrency
=> [workflow] cancel duplicated workflow jobs

applications/Chat/coati/dataset/prompt_dataset.py, applications/Chat/coati/dataset/sft_dataset.py, applications/Chat/coati/experience_maker/naive.py, applications/Chat/coati/models/base/__init__.py, applications/Chat/coati/models/base/actor.py, applications/Chat/coati/models/generation.py, applications/Chat/coati/models/utils.py, applications/Chat/coati/trainer/ppo.py, applications/Chat/coati/trainer/strategies/base.py, applications/Chat/coati/trainer/strategies/colossalai.py, applications/Chat/coati/trainer/strategies/ddp.py, applications/Chat/coati/trainer/strategies/naive.py, applications/Chat/examples/test_ci.sh, applications/Chat/tests/test_checkpoint.py
=> [chat] refactor actor class

colossalai/device/device_mesh.py, tests/test_device/test_device_mesh.py
>
Fixed #3989 
This PR added support for device mesh init from process group.
=> [device] support init device mesh from process group

colossalai/booster/plugin/gemini_plugin.py, colossalai/booster/plugin/torch_ddp_plugin.py, colossalai/booster/plugin/torch_fsdp_plugin.py, colossalai/checkpoint_io/checkpoint_io_base.py, colossalai/checkpoint_io/general_checkpoint_io.py, colossalai/checkpoint_io/index_file.py, colossalai/checkpoint_io/utils.py, tests/test_checkpoint_io/test_general_checkpoint_io.py
>
#3951 #3961 
As is discussed in #3961, I implemented saving/loading feature of sharded optimizers for GeneralCheckpointIO class.
Broadly speaking, the implementation logic is quite similar to saving/loading sharded models. On top of that, I did a lot of arrangements to adapt the design of sharded models to sharded optimizers. To avoid OOM errors during loading sharded optimizers, I borrowed the implementation of Optimizer.load_state_dict() in source code of pytorch and modified it to our cases. This feature for specific plugins …
=> [checkpointio] General Checkpointing of Sharded Optimizers

colossalai/booster/booster.py, colossalai/booster/mixed_precision/fp16_torch.py, colossalai/booster/mixed_precision/mixed_precision_base.py, colossalai/booster/plugin/gemini_plugin.py, colossalai/booster/plugin/low_level_zero_plugin.py, colossalai/booster/plugin/plugin_base.py, colossalai/booster/plugin/torch_ddp_plugin.py, colossalai/booster/plugin/torch_fsdp_plugin.py, tests/test_autochunk/test_autochunk_diffuser/test_autochunk_unet.py
=> [booster] make optimizer argument optional for boost

colossalai/shardformer/policies/bert.py, colossalai/shardformer/shard/sharder.py, tests/test_shardformer/test_model/test_shard_bert.py
fixed #4010 
integrate shardformer with dist layer on bert
=> [shardformer] integrate with dist layer

colossalai/booster/booster.py, colossalai/booster/plugin/torch_ddp_plugin.py, colossalai/checkpoint_io/checkpoint_io_base.py, colossalai/checkpoint_io/general_checkpoint_io.py, colossalai/checkpoint_io/utils.py, tests/test_checkpoint_io/test_torch_ddp_checkpoint_io.py
>
#3986
Adapted the newly developed feature: sharded optimizers checkpointing to TorchDDPPlugin.
Tidied up arguments passing in several booster IO methods.
=> [checkpointio] sharded optimizers checkpointing feature adapted for DDP plugin

colossalai/shardformer/layer/layers.py, colossalai/tensor/d_tensor/api.py
>
Fixed #4017 
This PR added non-inplace tensor sharding with DTensor. 
=> [shardformer] removed inplace tensor sharding

colossalai/shardformer/policies/basepolicy.py, colossalai/shardformer/policies/bert.py, colossalai/shardformer/shard/shard_config.py, colossalai/shardformer/shard/sharder.py, colossalai/shardformer/shard/shardformer.py, tests/test_shardformer/test_model/test_shard_bert.py
>
fix bert and gpt downstream with new api
=> [shardformer] fix bert and gpt downstream with new api

colossalai/shardformer/policies/autopolicy.py, colossalai/shardformer/policies/basepolicy.py, colossalai/shardformer/policies/llama.py, colossalai/shardformer/shard/shard_config.py, colossalai/shardformer/shard/sharder.py, colossalai/shardformer/shard/shardformer.py, tests/test_shardformer/test_model/test_shard_bert.py, tests/test_shardformer/test_model/test_shard_llama.py, tests/test_shardformer/test_model/test_shard_t5.py
>
Fixed #4037 
This PR refactored the llama policy to align with the new API.
=> [shardformer] adapted llama to the new API

colossalai/shardformer/README.md, colossalai/shardformer/layer/layers.py, colossalai/shardformer/policies/autopolicy.py, colossalai/shardformer/policies/basepolicy.py, colossalai/shardformer/policies/t5.py, colossalai/shardformer/shard/sharder.py, colossalai/testing/__init__.py, colossalai/testing/comparison.py, tests/test_shardformer/test_model/test_shard_llama.py, tests/test_shardformer/test_model/test_shard_t5.py
>
Fixed #4044
This PR adapted the T5 policy to the latest API and updated the tests.
=> [shardformer] supported T5 and its variants

colossalai/shardformer/layer/embedding1d.py, colossalai/shardformer/policies/llama.py, colossalai/shardformer/policies/t5.py, colossalai/shardformer/shard/sharder.py, colossalai/testing/comparison.py, tests/kit/model_zoo/registry.py, tests/kit/model_zoo/transformers/__init__.py, tests/kit/model_zoo/transformers/llama.py, tests/kit/model_zoo/transformers/t5.py, tests/test_booster/test_mixed_precision/test_fp16_torch.py, tests/test_booster/test_plugin/test_gemini_plugin.py, tests/test_booster/test_plugin/test_low_level_zero_plugin.py, tests/test_booster/test_plugin/test_torch_ddp_plugin.py, tests/test_booster/test_plugin/test_torch_fsdp_plugin.py, tests/test_fx/test_tracer/test_hf_model/test_hf_diffuser.py, tests/test_fx/test_tracer/test_timm_model/test_timm_model.py, tests/test_fx/test_tracer/test_torchaudio_model/test_torchaudio_model.py, tests/test_lazy/lazy_init_utils.py, tests/test_lazy/test_distribute.py, tests/test_shardformer/test_model/_utils.py, tests/test_shardformer/test_model/test_shard_llama.py, tests/test_shardformer/test_model/test_shard_t5.py
>
Fixed #4044 
Fixed #4037
This PR is a continuation of #4045  and #4036 
This PR adapted the T5 and LLaMA tests to use the `tests/kit/model_zoo`. The changes can be summarized as:
1. added a `loss_fn` in the model_zoo to compute a dummy loss from the model output
2. extracted the common functions for `test_model`
3. integrated `model_zoo` to `test_model`
=> [shardformer] adapted T5 and LLaMa test to use kit

colossalai/shardformer/layer/linear_conv.py, colossalai/shardformer/policies/gpt2.py, tests/test_shardformer/test_layer/test_linearconv_1d.py, tests/test_shardformer/test_model/test_shard_gpt2.py
>
fixed #4066 
add linearconv1d test
=> [shardformer] add linearconv1d test

colossalai/shardformer/layer/_operation.py, colossalai/shardformer/layer/embedding.py, colossalai/shardformer/layer/linear.py, colossalai/shardformer/layer/linear_conv.py, colossalai/shardformer/layer/parallel_module.py, colossalai/tensor/d_tensor/__init__.py, colossalai/tensor/d_tensor/api.py, tests/test_shardformer/test_layer/test_linear_1d.py, tests/test_shardformer/test_layer/test_linearconv_1d.py, tests/test_shardformer/test_model/test_shard_gpt2.py
>
Fixed #4061 .
This PR added support checkpointing loading and saving for linear conv 1D.
=> [shardformer] supported fused qkv checkpoint

colossalai/shardformer/layer/__init__.py, colossalai/shardformer/layer/layernorm.py, colossalai/shardformer/layer/linear.py, colossalai/shardformer/policies/bert.py, colossalai/shardformer/shard/shard_config.py, tests/test_shardformer/test_layer/test_layernorm.py, tests/test_shardformer/test_layer/test_linearconv_1d.py, tests/test_shardformer/test_model/_utils.py
>
fixed #4071 
add layernorm and fit it to all supported models
=> [shardformer] Add layernorm

applications/Chat/benchmarks/benchmark_opt_lora_dummy.py, applications/Chat/coati/trainer/ppo.py, applications/Chat/coati/trainer/rm.py, applications/Chat/coati/trainer/sft.py, applications/Chat/coati/trainer/strategies/base.py, applications/Chat/coati/trainer/strategies/colossalai.py, applications/Chat/coati/trainer/strategies/ddp.py, applications/Chat/coati/trainer/strategies/naive.py, applications/Chat/examples/test_ci.sh, applications/Chat/examples/train_prompts.py, applications/Chat/examples/train_reward_model.py, applications/Chat/examples/train_sft.py, applications/Chat/tests/test_checkpoint.py
=> [chat] refactor strategy class with booster api

colossalai/booster/plugin/gemini_plugin.py, colossalai/zero/gemini/chunk/search_utils.py, colossalai/zero/gemini/chunk/utils.py, colossalai/zero/gemini/gemini_ddp.py, tests/test_auto_parallel/test_offload/test_perf.py, tests/test_auto_parallel/test_tensor_shard/test_compatibility_with_gemini.py, tests/test_checkpoint_io/test_gemini_checkpoint_io.py, tests/test_tensor/test_tp_with_zero.py, tests/test_zero/test_gemini/test_fwd_bwd.py, tests/test_zero/test_gemini/test_gemini_use_rmt.py, tests/test_zero/test_gemini/test_grad_clip.py, tests/test_zero/test_gemini/test_inference.py, tests/test_zero/test_gemini/test_optim.py, tests/test_zero/test_gemini/test_search.py, tests/test_zero/test_gemini/test_zeroddp_state_dict.py, tests/test_zero/test_gemini/test_zeroddp_state_dict_shard.py, tests/test_zero/test_gemini/test_zerooptim_state_dict.py
>
#4052
Since the chunk_size attribute in Gemini should be used in number of elements, the modification proposed in #4052 can't be adopted.
Instead, to avoid confusion, arguments including `search_range_mb`, `min_chunk_size_mb` and `search_interval_bytes` should be renamed to `search_range_m`, `min_chunk_size_m` and `search_interval`. In this way, there should be no doubt that chunk_size takes number of elements as its unit rather than number of bytes.
Also, some tests are modified due to this renaming of arguments.
Tell us more …
=> [gemini] Fix a bug in chunk configuration searching

applications/Chat/evaluate/metrics.py, applications/Chat/evaluate/unieval/evaluator.py, applications/Chat/evaluate/utils.py
>
fix chat evaluation with possible zero denominator and delete removing articles of preprocessing process
=> [chat]: fix chat evaluation possible bug

colossalai/shardformer/layer/__init__.py, colossalai/shardformer/layer/layernorm.py, colossalai/shardformer/policies/bert.py, tests/test_shardformer/test_layer/test_layernorm.py
=> [shardformer] refactored layernorm

applications/Chat/coati/trainer/strategies/colossalai.py, docs/source/en/advanced_tutorials/parallelize_your_training_like_Megatron.md, docs/source/en/features/zero_with_chunk.md, docs/source/zh-Hans/advanced_tutorials/parallelize_your_training_like_Megatron.md, docs/source/zh-Hans/features/zero_with_chunk.md, examples/community/roberta/pretraining/run_pretraining.py, examples/language/gpt/gemini/train_gpt_demo.py
>
The argument renaming in #4056 is not comprehensive. Some examples & docs need to use the renamed arguments, but they are out of the scope of unit tests, so I'm making this complement PR.
=> [hotfix] fix argument naming in docs and examples

colossalai/testing/pytest_wrapper.py
>
Fixed #3962
This PR moved `import pytest` to the function body so that it will not affect users who use the CLI.
=> [testing] move pytest to be inside the function

colossalai/pipeline/stage_manager.py, tests/test_pipeline/test_stage_manager.py
>
Closes #4092 
Add pipeline stage manager
=> [pipeline] add stage manager

examples/images/resnet/.gitignore, examples/images/resnet/README.md, examples/images/resnet/eval.py, examples/images/resnet/requirements.txt, examples/images/resnet/test_ci.sh, examples/images/resnet/train.py
This PR copies the examples of resent from new_api to image and add some docstrings to it.
=> [examples] copy resnet example to image

colossalai/shardformer/policies/autopolicy.py, colossalai/shardformer/policies/opt.py, tests/kit/model_zoo/transformers/opt.py, tests/test_fx/test_tracer/test_hf_model/hf_tracer_utils.py, tests/test_fx/test_tracer/test_hf_model/test_hf_opt.py, tests/test_shardformer/test_model/_utils.py, tests/test_shardformer/test_model/test_shard_opt.py
>
shardformer support opt models
=> [shardformer] shardformer support opt models

colossalai/shardformer/README.md, colossalai/shardformer/layer/__init__.py, colossalai/shardformer/layer/dropout.py, colossalai/shardformer/layer/linear.py, colossalai/shardformer/layer/qkv_fused_linear.py, colossalai/shardformer/layer/utils.py, colossalai/shardformer/policies/autopolicy.py, colossalai/shardformer/policies/basepolicy.py, colossalai/shardformer/policies/bert.py, colossalai/shardformer/policies/bloom.py, colossalai/shardformer/policies/gpt2.py, colossalai/shardformer/policies/t5.py, colossalai/shardformer/policies/vit.py, colossalai/shardformer/shard/sharder.py, tests/kit/model_zoo/transformers/__init__.py, tests/kit/model_zoo/transformers/bloom.py, tests/kit/model_zoo/transformers/gpt.py, tests/test_shardformer/test_layer/test_dropout.py, tests/test_shardformer/test_layer/test_qkv_fused_linear_1d.py, tests/test_shardformer/test_model/test_shard_bloom.py
>
Fixed #4074 
This PR added the bloom policy and numerical tests. The work can be summarized as below:
1. refactored the policy to support method replacement
2. refactored the dropout module to support both replicated input and parallelized input
3. added support for bloom model
=> [shardformer] supported bloom model

docs/source/en/basics/booster_api.md, docs/source/en/features/mixed_precision_training_with_booster.md, docs/source/en/get_started/run_demo.md, docs/source/zh-Hans/basics/booster_api.md, docs/source/zh-Hans/features/mixed_precision_training_with_booster.md, docs/source/zh-Hans/get_started/run_demo.md
>
This PR updates and revises some typos and errs in existing docs. Details can be found in https://n4fyd3ptax.feishu.cn/sheets/RpncsG6pPhk7lutV8Cxcb4DRnkd
=> [doc] update and revise some typos and errs in docs

applications/Chat/README.md, applications/Chat/benchmarks/benchmark_opt_lora_dummy.py, applications/Chat/coati/trainer/__init__.py, applications/Chat/coati/trainer/base.py, applications/Chat/coati/trainer/callbacks/base.py, applications/Chat/coati/trainer/ppo.py, applications/Chat/coati/trainer/rm.py, applications/Chat/coati/trainer/sft.py, applications/Chat/coati/trainer/strategies/colossalai.py, applications/Chat/coati/trainer/utils.py, applications/Chat/examples/README.md, applications/Chat/examples/community/peft/train_peft_prompts.py, applications/Chat/examples/test_ci.sh, applications/Chat/examples/train_prompts.py, applications/Chat/examples/train_prompts.sh, applications/Chat/examples/train_reward_model.py, applications/Chat/examples/train_sft.py
=> [chat] refactor trainer class

colossalai/interface/optimizer.py, colossalai/pipeline/schedule/__init__.py, colossalai/pipeline/schedule/_utils.py, colossalai/pipeline/schedule/base.py, colossalai/pipeline/schedule/one_f_one_b.py, tests/test_pipeline/test_schedule/test_pipeline_schedule_utils.py
>
Closes #4114 
Implement 1f1b pipeline schedule with new components
=> [pipeline] refactor 1f1b schedule

colossalai/shardformer/layer/__init__.py, colossalai/shardformer/layer/normalization.py, colossalai/shardformer/policies/basepolicy.py, colossalai/shardformer/policies/bert.py, colossalai/shardformer/policies/bloom.py, colossalai/shardformer/policies/gpt2.py, colossalai/shardformer/policies/llama.py, colossalai/shardformer/policies/opt.py, colossalai/shardformer/policies/t5.py, colossalai/shardformer/policies/vit.py, colossalai/shardformer/shard/shard_config.py, tests/test_shardformer/test_model/_utils.py
>
Fixed #4113 
This PR added support for fused normalization for our existing models.
=> [shardformer] supported fused normalization

colossalai/shardformer/shard/shard_config.py, colossalai/shardformer/shard/sharder.py, colossalai/shardformer/shard/shardformer.py, tests/test_shardformer/test_model/_utils.py, tests/test_shardformer/test_model/test_shard_bert.py, tests/test_shardformer/test_model/test_shard_bloom.py, tests/test_shardformer/test_model/test_shard_gpt2.py, tests/test_shardformer/test_model/test_shard_llama.py, tests/test_shardformer/test_model/test_shard_opt.py, tests/test_shardformer/test_model/test_shard_t5.py, tests/test_shardformer/test_with_torch_ddp.py
>
Fixed #4102 
This PR refactored the shardformer API to support compatibility with the PyTorch DDP. We can just pass the tensor parallel group to Shardformer so that process group initialization is disentangled from shardformer itself.
=> [shardformer] integrate with data parallelism

colossalai/shardformer/policies/autopolicy.py, colossalai/shardformer/policies/basepolicy.py, colossalai/shardformer/policies/bert.py, colossalai/shardformer/policies/gpt2.py, colossalai/shardformer/policies/llama.py, colossalai/shardformer/policies/opt.py, colossalai/shardformer/policies/t5.py, colossalai/shardformer/policies/vit.py, colossalai/shardformer/shard/shard_config.py
>
Fixed #4108 
This PR moved the `import transformers` from the top of the file to the function body to support implicit import, avoiding import errors for users who do not have `transformers` installed.
=> [shardformer] import huggingface implicitly

colossalai/shardformer/_utils.py, colossalai/shardformer/policies/bert.py, colossalai/shardformer/policies/bloom.py, colossalai/shardformer/policies/opt.py, colossalai/shardformer/policies/t5.py, colossalai/shardformer/shard/sharder.py, tests/kit/model_zoo/registry.py, tests/test_shardformer/test_model/test_shard_bert.py, tests/test_shardformer/test_model/test_shard_bloom.py, tests/test_shardformer/test_model/test_shard_gpt2.py, tests/test_shardformer/test_model/test_shard_llama.py, tests/test_shardformer/test_model/test_shard_opt.py, tests/test_shardformer/test_model/test_shard_t5.py, tests/test_shardformer/test_model/test_shard_vit.py
>
Fixed #4123
This PR added more testing for embedding gradient and fixed some policies which caused incorrect numerical results.
=> [shardformer] added embedding gradient check

colossalai/shardformer/README.md, colossalai/shardformer/examples/data.py, colossalai/shardformer/examples/shardformer_benchmark.py, colossalai/shardformer/examples/shardformer_benchmark.sh, colossalai/shardformer/shard/shard_config.py
>
#4110 
write an shardformer example with bert finetuning
=> [shardformer]  write an shardformer example with bert finetuning

colossalai/shardformer/README.md, colossalai/shardformer/examples/shardformer_benchmark.py, colossalai/shardformer/policies/basepolicy.py, colossalai/shardformer/policies/bert.py, colossalai/shardformer/policies/bloom.py, colossalai/shardformer/policies/gpt2.py, colossalai/shardformer/policies/llama.py, colossalai/shardformer/policies/opt.py, colossalai/shardformer/policies/t5.py, colossalai/shardformer/policies/vit.py, colossalai/shardformer/shard/shard_config.py, colossalai/shardformer/shard/sharder.py, colossalai/shardformer/shard/shardformer.py, tests/test_shardformer/test_model/_utils.py, tests/test_shardformer/test_with_torch_ddp.py
>
Fixed #4136 
This PR refactored some APIs and documentations.
1. change `shardformer.shard_model` to `shardformer.optimize` as we can allow the user not to use tensor parallelism, but just use optimization such as fused kernels. `optimize` would be more generic and understandable.
2. Updated docstring
3. Updated the documentation with the `Development notes` section and updated some other sections with minor changes
4. updated the architecture diagram in public assets
=> [shardformer] refactored some doc and api

colossalai/checkpoint_io/utils.py
Not involved
fix "CheckpointIndexFile" is not defined" 
modified:   colossalai/checkpoint_io/utils.py  line 371
Before adjustment
=> [nfc] fix : CheckpointIndexFile is not defined

colossalai/booster/booster.py, colossalai/booster/plugin/gemini_plugin.py, colossalai/booster/plugin/low_level_zero_plugin.py, colossalai/booster/plugin/plugin_base.py, colossalai/booster/plugin/torch_ddp_plugin.py, colossalai/booster/plugin/torch_fsdp_plugin.py, colossalai/zero/low_level/low_level_optim.py, tests/test_zero/test_low_level/test_grad_acc.py
>
fixed #4128 
Support the low level zero plugin with `no_sync` when it comes to zero1.
=> [zero]support no_sync method for zero1 plugin
