hpcaitech/ColossalAI

- docs/run_demo.md
The current document on the website has an inconsistency of the filename with our current version of code, seemingly due to that the code had been modified. Now this inconsistency has been fixed.
> fixed the inconsistency between the document and the code

- docs/add_your_parallel.md
- docs/add_your_parallel_zh.md
- docs/amp.md
- docs/amp_zh.md
- docs/config_zh.md
- docs/index_en.rst
- docs/installation_zh.md
- docs/model.md
- docs/model_zh.md
- docs/parallelization.md
- docs/parallelization_zh.md
- docs/run_demo.md
- docs/run_demo_zh.md
- docs/trainer_engine.md
- docs/trainer_engine_zh.md
- docs/zero.md
- docs/zero_zh.md
Chinese documents have been added into the repo and can be accessed by first going to the docs/.build/html folder and using `open ./index.html`.
Some modifications were made to English documents as well, as listed below:
- Changed Colossal-AI in the documents to ColossalAI.
- Fixed some typos and inconsistencies in the docs.
- Rephrased some statements so that they make better sense.
> added Chinese documents and fixed some typos in English documents

- setup.py
get_cuda_bare_metal_version() is defined twice in setup.py.
> remove redundancy func in setup

- setup.py
get_cuda_bare_metal_version() is defined twice in setup.py. And pyprof is not used.
> remove redundancy func in setup (#19)

- examples/vit-b16/README.md
- add explanation of files for ViT 32K example.
> add explanation for ViT example (#35)

- colossalai/nn/layer/parallel_1d/__init__.py
- colossalai/nn/layer/parallel_1d/_transformer.py
- colossalai/nn/layer/parallel_1d/_utils.py
- colossalai/nn/layer/parallel_1d/_vit.py
- colossalai/nn/layer/parallel_1d/layers.py
- colossalai/nn/loss/__init__.py
- colossalai/nn/loss/cross_entropy_1d.py
- colossalai/nn/loss/cross_entropy_2d.py
- colossalai/trainer/hooks/_metric_hook.py
- colossalai/trainer/metric.py
- model_zoo/vit/parallel_1d/vit.py
- tests/test_layers/test_1d/common.py
- tests/test_layers/test_1d/test_1d.py
- tests/test_layers/test_1d/test_layer.py
- tests/test_models/test_vision_transformer/configs/vit_1d.py
- tests/test_models/test_vision_transformer/test_vit_1d/test_vit_1d.py
- Modify 1d basic layers
- Add layers for transformers/ViT
- Add ViT model zoo
- Add 1D Accuracy, 1D FusedLayerNorm(untested), 1D CrossEntropy(untested)
> Integrate 1d tensor parallel in Colossal-AI

- examples/vit-b16/README.md
Explain how to run on single machine and add some descriptions for our python files.
> add some details in vit-b16 example (#43)

- examples/vit-b16/README.md
We provide some python scripts to build TFRecord dataset from the raw Imagenet-1K dataset.
> add how to build tfrecord dataset

- colossalai/nn/layer/parallel_2p5d/__init__.py
- colossalai/nn/layer/parallel_2p5d/_operation.py
- colossalai/nn/layer/parallel_2p5d/_transformer.py
- colossalai/nn/layer/parallel_2p5d/_vit.py
- colossalai/nn/layer/parallel_2p5d/layers.py
updated layer files on 2.5d to get a similar accuracy on imagenet-1k dataset
> Update 2.5d layer code

- colossalai/utils/activation_checkpoint.py
Enable offloading activation checkpoint to CPU memory.
Usage:
```python
from colossalai.utils import checkpoint
checkpoint(model.forward, *args, cpu_offload=True)
```
> add activation checkpoint offload

- colossalai/builder/pipeline.py
- colossalai/communication/p2p.py
- colossalai/communication/utils.py
- colossalai/context/parallel_context.py
- colossalai/engine/schedule/__init__.py
- colossalai/engine/schedule/_pipeline_schedule.py
- colossalai/utils/__init__.py
- colossalai/utils/common.py
Add interleaved pipeline. Usage:
```python
from colossalai.builder import PipelineModelInitializer
from colossalai.engine.schedule import InterleavedPipelineSchedule
model = PipelineModelInitializer(model_cfg, num_model_chunks).initialize()
if isinstance(model, list):
model = torch.nn.ModuleList(model)
schedule = InterleavedPipelineSchedule(num_microbatches, num_model_chunks)
```
> add interleaved pipeline

- colossalai/nn/layer/parallel_2d/_operation.py
- Improve performance by overlaping computation and communication in 2d operation
> overlap computation and communication in 2d operations

- colossalai/amp/naive_amp/__init__.py
- colossalai/builder/__init__.py
- colossalai/builder/pipeline.py
- colossalai/communication/p2p.py
- colossalai/engine/schedule/_pipeline_schedule.py
- colossalai/initialize.py
Interleaved pipeline with naive AMP will hang at the start of training, due to the dtype of buffer in P2P communication is wrong. I fixed this bug.
> Fix interleaved pipeline naive amp

- colossalai/amp/apex_amp/__init__.py
- colossalai/zero/__init__.py
- colossalai/zero/zero_redundancy_optimizer_level_3.py
- tests/test_zero_data_parallel/test_zero_level_3.py
- tests/test_zero_tensor_parallel/test_vit_2d_level_3.py
1. fixed zero level 3 bug in type casting
2. fixed unit testing of zero level 3
3. minor fix for apex amp as it should be only imported when used
> fixed zero level 3 dtype bug

- colossalai/amp/naive_amp/_fp16_optimizer.py
- colossalai/amp/torch_amp/_grad_scaler.py
- colossalai/constants.py
- colossalai/context/parallel_context.py
- colossalai/context/parallel_mode.py
- colossalai/context/process_group_initializer/__init__.py
- colossalai/context/process_group_initializer/initializer_model.py
- colossalai/utils/common.py
- tests/test_context/test_2d_init.py
- tests/test_context/test_2p5d_init.py
- tests/test_context/test_3d_init.py
1. added model parallel intializer for amp and clip grad features
2. modified parallel context to add this initializer by default
3. added unit testing for model parallel group
> added model parallel process group for amp and clip grad

- colossalai/engine/schedule/_pipeline_schedule.py
Add a argument `tensor_shape` for `PipelineSchedule` and `InterleavedPipelineSchedule`. You can set this argument to a `Union[torch.Size, List[int], Tuple[int]]` if the tensor shapes transmitted along pipeline are the same and fixed during training. By setting this, the communication will be further reduced.
> pipeline can receive tensor shape

- benchmark/cifar/train.py
- benchmark/gpt2/configs/gpt2_1d.py
- benchmark/gpt2/configs/gpt2_2d.py
- benchmark/gpt2/configs/gpt2_2p5d.py
- benchmark/gpt2/configs/gpt2_3d.py
- benchmark/gpt2/configs/gpt2_vanilla.py
- benchmark/gpt2/data.py
- benchmark/gpt2/train.py
- benchmark/imagenet100/train.py
- benchmark/imagenet1k/train.py
- model_zoo/gpt/__init__.py
- model_zoo/gpt/gpt.py
- model_zoo/vit/vit.py
- Added GPT models
- Added GPT2 benchmark
> GPT model & benchmark

- colossalai/engine/schedule/_pipeline_schedule.py
- colossalai/nn/layer/parallel_1d/layers.py
- colossalai/nn/layer/parallel_2d/_operation.py
- colossalai/nn/layer/wrapper/pipeline_wrapper.py
- colossalai/trainer/hooks/_metric_hook.py
- model_zoo/gpt/gpt.py
1. Pipeline schedule need re-compute batch size if using tensor parallel
2. `GPTBlock` use checkpoint
3. Some layer will raise exception if not using bias
4. Add `register_parameter` for `PipelineSharedModuleWrapper`
> fix layers/schedule for hybrid parallelization (#111)

- docker/Dockerfile
added a dockerfile for building a docker image for colossalai
> added docker image

- colossalai/constants.py
- colossalai/context/parallel_context.py
- colossalai/context/parallel_mode.py
- colossalai/context/process_group_initializer/__init__.py
- colossalai/context/process_group_initializer/initializer_moe.py
- colossalai/context/random/__init__.py
- colossalai/context/random/_helper.py
- colossalai/context/random/seed_manager.py
- colossalai/engine/gradient_handler/__init__.py
- colossalai/engine/gradient_handler/_moe_gradient_handler.py
- colossalai/engine/schedule/_base_schedule.py
- colossalai/global_variables.py
- colossalai/initialize.py
- colossalai/nn/layer/moe/__init__.py
- colossalai/nn/layer/moe/_operation.py
- colossalai/nn/layer/moe/layers.py
- colossalai/nn/layer/vanilla/__init__.py
- colossalai/nn/layer/vanilla/layers.py
- colossalai/nn/loss/__init__.py
- colossalai/nn/loss/loss_moe.py
- colossalai/nn/lr_scheduler/cosine.py
- colossalai/utils/common.py
- model_zoo/helper.py
- model_zoo/moe/models.py
- model_zoo/moe/util.py
- added moe parallel functions
- example and memory optimization will be updated soon
> Added MoE parallel

- .github/workflows/document.yml
When `docs` and `colossalai` have changes, the documents will be updated and deployed automatically.
> add workflow for deploying doc

- colossalai/zero/__init__.py
Try import deepspeed when using zero
> Raise exception when missing required packages when using ZeRO

- colossalai/nn/layer/colossalai_layer/dropout.py
- colossalai/nn/layer/colossalai_layer/embedding.py
- colossalai/nn/layer/colossalai_layer/linear.py
- colossalai/nn/layer/colossalai_layer/normalization.py
- colossalai/nn/layer/parallel_1d/_operation.py
- colossalai/nn/layer/parallel_1d/_utils.py
- colossalai/nn/layer/parallel_1d/layers.py
- colossalai/nn/layer/parallel_2d/_operation.py
- colossalai/nn/layer/parallel_2d/layers.py
- colossalai/nn/layer/parallel_2p5d/_operation.py
- colossalai/nn/layer/parallel_2p5d/layers.py
- colossalai/nn/layer/parallel_3d/_operation.py
- colossalai/nn/layer/parallel_3d/layers.py
- colossalai/nn/layer/vanilla/layers.py
- colossalai/nn/loss/loss_2d.py
- colossalai/nn/loss/loss_2p5d.py
- colossalai/nn/loss/loss_3d.py
- colossalai/nn/metric/accuracy_2d.py
- colossalai/nn/metric/accuracy_2p5d.py
- colossalai/nn/metric/accuracy_3d.py
- colossalai/trainer/hooks/_base_hook.py
- colossalai/trainer/hooks/_checkpoint_hook.py
- colossalai/trainer/hooks/_log_hook.py
- colossalai/trainer/hooks/_lr_scheduler_hook.py
- colossalai/trainer/hooks/_metric_hook.py
Update the documentation of layer integration
> Update layer integration documentation

- examples/widenet_tiny_cifar10_moe/README.md
- examples/widenet_tiny_cifar10_moe/config.py
- examples/widenet_tiny_cifar10_moe/train.py
- model_zoo/moe/models.py
- added moe parallel example on cifar10
> Added moe parallel example

- README.md
- docker/Dockerfile
- added documentation on how to build and run colossalai in docker
- fixed dockerfile for internet connection problem in China
> added docker documentation

- examples/vit_b16_imagenet_data_parallel/dataloader/imagenet_dali_dataloader.py
- examples/vit_b16_imagenet_data_parallel/dataloader/rand_augment.py
- examples/vit_b16_imagenet_data_parallel/train.py
Added the random augment to dali dateloader, which achieves +4.1% ACC with +10s/epoch
> Added rand augment and update the dataloader

- .gitmodules
The previous url was linked to my repository, now it is linked to the official repository
> fixed submodule url

- colossalai/initialize.py
> fixed ddp bug on torch 1.8

- README.md
- colossalai/utils/data_sampler/data_parallel_sampler.py
fixed utils docstring and add example to readme
> fixed utils docstring and add example to readme

- .flake8
Inherited this config from [patrick star](https://github.com/Tencent/PatrickStar)
> added flake8 config

- .github/workflows/PR_CI.yml
- README.md
- docker/Dockerfile
- requirements/requirements-zero.txt
- setup.py
When installing, it can build CUDA extension automatically base in your environment.
> update setup and workflow

- colossalai/zero/_zero3_utils.py
- colossalai/zero/param_manager.py
- colossalai/zero/reduce_scatter.py
- colossalai/zero/zero_stage3_develop.py
I leave some TODOs in comments of `colossalai/zero/zero_stage3_develop.py` and `colossalai/zero/param_manager.py`.
> Implement naive zero3

- .pre-commit-config.yaml
- colossalai/global_variables.py
- colossalai/kernel/cuda_native/csrc/layer_norm_cuda_kernel.cu
- colossalai/kernel/cuda_native/csrc/moe_cuda.cpp
- colossalai/kernel/cuda_native/csrc/moe_cuda_kernel.cu
- colossalai/nn/layer/moe/__init__.py
- colossalai/nn/layer/moe/_operation.py
- colossalai/nn/layer/moe/layers.py
- colossalai/nn/layer/moe/utils.py
- setup.py
- tests/test_moe/short_test.py
- tests/test_moe/test_top1.py
- tests/test_moe/test_top2.py
- Add cuda kernel to save memory and speed up
- Fix wrong evaluation in MoE layer
- Add unit test for MoE
> Optimized MoE layer and fixed some bugs

- .pre-commit-config.yaml
- colossalai/global_variables.py
- colossalai/kernel/cuda_native/csrc/layer_norm_cuda_kernel.cu
- colossalai/kernel/cuda_native/csrc/moe_cuda.cpp
- colossalai/kernel/cuda_native/csrc/moe_cuda_kernel.cu
- colossalai/nn/layer/moe/__init__.py
- colossalai/nn/layer/moe/_operation.py
- colossalai/nn/layer/moe/experts.py
- colossalai/nn/layer/moe/layers.py
- colossalai/nn/layer/moe/utils.py
- model_zoo/moe/models.py
- setup.py
- tests/test_moe/short_test.py
- tests/test_moe/test_top1.py
- tests/test_moe/test_top2.py
- Decreased moe tests;
- Added FFNExperts and ViTMoE model
> Optimized MoE layer and fixed some bugs;

- colossalai/zero/shard_param/shard_param.py
Some minor typos were found while I was reading the code. A bit trivial but good to be correct.
> fixed typo in ShardParam

- colossalai/engine/ophooks/__init__.py
- colossalai/engine/ophooks/_shard_grad_ophook.py
- colossalai/zero/shard_param/shard_param.py
- colossalai/zero/sharded_model/reduce_scatter.py
- colossalai/zero/sharded_model/sharded_grad.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- tests/test_zero_data_parallel/common.py
- tests/test_zero_data_parallel/test_shard_model_v2.py
- tests/test_zero_data_parallel/test_zero_dev_3_mp4.py
Implemented a complete SharedModel FWD/BWD process
This PR uses the newly implemented hook mechanism. 
Specifically, OpHook is used for the management of param.data, and BaseParamHookMgr is used for the reduction and management of param.grad.
> add sharded grad and refactor grad hooks

- colossalai/zero/shard_param/__init__.py
- colossalai/zero/shard_param/shard_param.py
- colossalai/zero/sharded_param/__init__.py
- colossalai/zero/sharded_param/sharded_param.py
- tests/test_zero_data_parallel/test_shard_param.py
1. rename shard_param -> sharded_param.
2. Initialize a sharded param from scratch by its shape.
> Polish sharded parameter

- colossalai/engine/_base_engine.py
- colossalai/engine/ophooks/_memtracer_ophook.py
- colossalai/utils/timer.py
- tests/test_config/test_load_config.py
Another PR for my primary memory tracer
> feature: primary memory tracer

- colossalai/engine/ophooks/_memtracer_ophook.py
- colossalai/zero/init_ctx/init_context.py
- colossalai/zero/shard_utils/base_shard_strategy.py
- colossalai/zero/sharded_param/sharded_param.py
- tests/components_to_test/nested_model.py
- tests/components_to_test/repeated_computed_layer.py
- tests/components_to_test/resnet.py
- tests/test_engine/test_engine.py
- tests/test_zero_data_parallel/test_init_context.py
- tests/test_zero_data_parallel/test_shard_param.py
1. help polishing non_distributed_component_funcs. return a function to build the model and optim.
2. add rm_torch_payload_on_the_fly for ZeroInitContext. Do not rm the torch param payload when adapting to ShardedParamV2.
> [zero] update zero context init with the updated test utils

- colossalai/engine/ophooks/__init__.py
- colossalai/engine/ophooks/zero_hook.py
- colossalai/zero/init_ctx/init_context.py
- colossalai/zero/shard_utils/tensor_shard_strategy.py
- colossalai/zero/sharded_model/_zero3_utils.py
- colossalai/zero/sharded_model/sharded_model.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_param/sharded_param.py
- tests/test_zero_data_parallel/common.py
- tests/test_zero_data_parallel/test_init_context.py
- tests/test_zero_data_parallel/test_shard_model_v2.py
- tests/test_zero_data_parallel/test_shard_param.py
- tests/test_zero_data_parallel/test_sharded_model_with_ctx.py
- tests/test_zero_data_parallel/test_sharded_optim_v2.py
- tests/test_zero_data_parallel/test_state_dict.py
1. Refactor `ShardedParamV2`, as `grad` is never gathered. I think we can just use a `tensor` to store the `grad` , which meets our requirements well.
2. Refactor `ShardedModelV2` using `ShardedParamV2`.
3. Fix bugs， like circular import in `zero_hook.py`.
4. Rename typos.
> [zero] Update sharded model v2 using sharded param v2

- colossalai/nn/layer/parallel_3d/_operation.py
- colossalai/nn/layer/parallel_3d/layers.py
> fix format for dir-[parallel_3d]

- colossalai/engine/ophooks/_memtracer_ophook.py
The time interval will be automatically adjusted according to the stats info in warmup stage.
> [profiler] add adaptive sampling to memory profiler

- colossalai/amp/torch_amp/__init__.py
- colossalai/engine/_base_engine.py
- colossalai/initialize.py
- criterion is no longer required in `colossalai.initialize`
- updated the type hinting
> [fix] set criterion as optional in colossalai initialize

- colossalai/amp/naive_amp/grad_scaler/__init__.py
- colossalai/amp/naive_amp/grad_scaler/base_grad_scaler.py
- colossalai/amp/naive_amp/grad_scaler/constant_grad_scaler.py
- colossalai/amp/naive_amp/grad_scaler/dynamic_grad_scaler.py
- re-organized the grad scaler used in naive amp
- will refactor the naive fp16 optimizer in a separate PR
> [fp16] refactored grad scaler

- .github/workflows/build.yml
- tests/components_to_test/bert.py
- tests/test_engine/test_engine.py
- tests/test_zero_data_parallel/test_shard_model_v2.py
1. Fix bert unit test: disable dropout
2. Enable test sharded model v2
> [zero] fix bert unit test

- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- tests/test_zero_data_parallel/common.py
- tests/test_zero_data_parallel/test_shard_model_v2.py
- tests/test_zero_data_parallel/test_sharded_optim_v2.py
1. Update sharded optim v2 with new sharded model v2
2. Fix some bugs about wrong grad shape when dp size = 1
> [zero] update sharded optim v2

- colossalai/context/process_group_initializer/initializer_3d.py
fix format ColossalAI\colossalai\context\process_group_initializer\initializer_3d.py
> fix format ColossalAI\colossalai\context\process_group_initializer\initializer_3d.py

- tests/test_zero_data_parallel/test_sharded_optim_v2_with_cpu_adam.py
1. Test `ShardedOptimV2` with `CPUAdam`. Grad and fp32 master param are offloaded to CPU.
> [zero] add test sharded optim with cpu adam

- colossalai/context/parallel_context.py
…untime1\ColossalAI\colossalai\context\parallel_context.py
> fix format

- colossalai/context/random/_helper.py
- colossalai/context/random/seed_manager.py
Change the code to flake8 style
> flake8 style change

- colossalai/nn/layer/utils/common.py
- colossalai/utils/__init__.py
- colossalai/utils/activation_checkpoint.py
- tests/test_utils/test_activation_checkpointing.py
> Added activation offload

- README-zh-Hans.md
- colossalai/amp/naive_amp/__init__.py
- colossalai/amp/naive_amp/_fp16_optimizer.py
- colossalai/amp/naive_amp/_utils.py
- colossalai/amp/naive_amp/grad_scaler/base_grad_scaler.py
- colossalai/amp/naive_amp/grad_scaler/dynamic_grad_scaler.py
- colossalai/amp/naive_amp/naive_amp.py
- colossalai/initialize.py
- colossalai/zero/sharded_optim/sharded_optim.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- tests/test_amp/test_naive_fp16.py
- refactored fp16 optimizer to resolve copyright issue
> [amp] refactored fp16 optimizer

- CHANGE_LOG.md
- fix typo, `Unifed` -> `Unified` below Added
> fix typo in CHANGE_LOG.md

- colossalai/utils/profiler/comm_profiler.py
- colossalai/utils/profiler/pcie_profiler.py
- colossalai/utils/profiler/prof_utils.py
- The output of profiler is better looked now
- Fixed the result of PCIE profiler
> polished output format for communication profiler and pcie profiler

- model_zoo/gpt/gpt.py
This PR fixes the first problem mentioned in #425 . The bug occurs because the attention mask is not processed on pipeline stages whichever is not the first stage.
> fixed gpt attention mask in pipeline

- colossalai/amp/naive_amp/_fp16_optimizer.py
This PR fixes the second bug mentioned in #425 . This bug occurs because the naive amp optimizer did not check  if the `tensor.grad` is None.
The DynamicGradScaler is refactored in `naive_amp/grad_scaler` folder. Thus, it is removed from the optimizer file.
> fixed fp16 optimizer none grad bug

- README-zh-Hans.md
- README.md
CodeBeat and CodeFactor are both tools to evaluate code quality. Their function overlaps so only one is needed. CodeBeat is much slower than CodeFactor and could take hours for evaluation of a single PR. Thus, we keep CodeFactor as our evaluation tool. We need to maintain the A rating for our code quality review.
> replace codebeat with codefactor on readme

- .github/workflows/assign_reviewer.yml
- .github/workflows/build.yml
- .github/workflows/compatibility_test.yml
- .github/workflows/release_test.yml
- .github/workflows/submodule.yml
- removed invalid CI run on develop branch
- separated release to test pypi into an independent workflow as this is run on main instead of develop
> [devops] update github CI with the current git workflow

- colossalai/nn/optimizer/cpu_adam.py
- colossalai/zero/__init__.py
Make our customized CPUADAM more general. It did not run it on CUDA. Now it is possible.
> [zero] hybrid cpu adam

- tests/test_data_pipeline_tensor_parallel/test_cifar_with_data_pipeline_tensor.py
- tests/test_engine/test_engine.py
- tests/test_trainer/test_pipeline/test_p2p.py
- tests/test_trainer/test_pipeline/test_pipeline_schedule.py
- tests/test_trainer/test_trainer_with_non_pipe_schedule.py
- tests/test_trainer/test_trainer_with_pipe_schedule.py
Reduce the test problem size to save time as part of the efforts to solve #443 
The time cost change (in seconds):
- `test_trainer_with_pipe_schedule.py`:  38 -> 15
- `test_trainer_with_non_pipe_schedule.py`: 16 -> 5
- `test_pipeline_schedule.py`: 16 -> 3
- `test_cifar_with_data_pipeline_tensor.py`: 40 -> 27
> [test] optimize engine and trainer test

- colossalai/initialize.py
- colossalai/zero/__init__.py
- colossalai/zero/init_ctx/init_context.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- tests/test_zero_data_parallel/common.py
- tests/test_zero_data_parallel/test_shard_model_v2.py
- tests/test_zero_data_parallel/test_sharded_optim_v2.py
- tests/test_zero_data_parallel/test_sharded_optim_with_sync_bn.py
- tests/test_zero_data_parallel/test_state_dict.py
- tests/test_zero_data_parallel/test_zero_engine.py
Reverts hpcaitech/ColossalAI#453
> Revert "[zero] update sharded optim and fix zero init ctx"

- tests/test_amp/test_naive_fp16.py
- tests/test_zero_data_parallel/test_shard_model_v2.py
- tests/test_zero_data_parallel/test_sharded_optim_v2.py
Compare the zero and naive amp with apex O2 for fairness
> [test] fixed amp convergence comparison test

- .github/workflows/release.yml
- .github/workflows/release_test.yml
The release workflow was skipped due to this bug.
> [devops] fixed workflow bug

- colossalai/core.py
- colossalai/engine/gradient_handler/_moe_gradient_handler.py
- colossalai/nn/layer/moe/_operation.py
- colossalai/nn/layer/moe/experts.py
- colossalai/nn/layer/moe/layers.py
- colossalai/nn/layer/moe/utils.py
- colossalai/nn/loss/loss_moe.py
- colossalai/utils/moe.py
- use dist process group instead of ParallelMode in moe layer.py
- add comments for experts construction functions
> [MOE] redirect moe_env from global_variables to core

- colossalai/zero/init_ctx/init_context.py
`ZeroInitContext` didn't receive a dp process group, which leads to creating wrong shard when using ZeRO and model parallel together.
> [zero] zero init ctx receives a dp process group

- README-zh-Hans.md
- README.md
Experiment about Colossal-AI with ZeRO vs. Pytorch
> add experimental visualisation regarding ColossalAI with ZeRO

- colossalai/testing/__init__.py
- colossalai/testing/utils.py
- Added `rerun_on_exception` function to re-run a method upon detection of an exception. This is useful for the `Address already in use` error in our CI.
- Fixed the docstring of `parameterize` function.
> [test] added rerun on exception for testing

- README-zh-Hans.md
- README.md
adding visualisation of Colossal-AI with ZeRO vs. PyTorch
> Update Experiment result about Colossal-AI with ZeRO

- colossalai/engine/ophooks/zero_hook.py
- colossalai/utils/commons/bucket_tensor_copy.py
- colossalai/zero/init_ctx/init_context.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_model/utils.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- colossalai/zero/sharded_param/__init__.py
- colossalai/zero/sharded_param/sharded_param.py
- tests/test_utils/test_bucket_tensor_copy.py
- tests/test_zero_data_parallel/common.py
- tests/test_zero_data_parallel/test_init_context.py
- tests/test_zero_data_parallel/test_shard_param.py
rename .data -> sharded_data_tensor in ShardedParamV2.
If we use param.data, it is misleading. People tend to believe it's a torch.Tensor. But actually its a ShardedTensor...
> [zero] polish sharded param name

- colossalai/zero/sharded_optim/sharded_optim_v2.py
Move codes about *moving fp32 shards h2d* in `step()` to `_maybe_move_fp32_shards()`.
> [zero] polish sharded optimizer v2

- colossalai/zero/sharded_model/sharded_model_v2.py
`ShardedModel` manages ophooks individually. We can utilize full features of ophooks even without `Engine`.
> [zero] sharded model manages ophooks individually

- .github/workflows/compatibility_test.yml
Please do not merge this PR for now.
> [devops] remove tsinghua source for pip

- colossalai/kernel/cuda_native/csrc/multi_tensor_adam.cu
- colossalai/kernel/cuda_native/csrc/type_shim.h
- colossalai/nn/optimizer/fused_adam.py
- tests/test_optimizer/unittest_cpu_adam.py
- tests/test_optimizer/unittest_fused_adam.py
- tests/test_optimizer/unittest_fused_adam_kernel.py
now our fused adam supports the hybrid of p and d dtype.
> [cuda] modify the fused adam, support hybrid of fp16 and fp32

- colossalai/nn/optimizer/hybrid_adam.py
- tests/test_optimizer/unittest_cpu_adam.py
- tests/test_optimizer/unittest_fused_adam_kernel.py
- tests/test_optimizer/unittest_hybrid_adam.py
Added hybrid adam. Passed the test.
removed loss scale in adam which may be against using habit.
> [zero]added hybrid adam, removed loss scale in adam

- colossalai/zero/sharded_param/sharded_param.py
- tests/test_zero_data_parallel/test_shard_param.py
A PR towards tracing non-model data memory usage inside an iteration.
> [zero] get memory usage for sharded param

- colossalai/logging/logger.py
Show the file name and line number when logging.
> [logging] polish logger format

- colossalai/engine/ophooks/zero_hook.py
- colossalai/zero/sharded_model/_utils.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_param/sharded_param.py
- colossalai/zero/sharded_param/sharded_tensor.py
- colossalai/zero/sharded_param/tensorful_state.py
- tests/test_zero_data_parallel/test_shard_param.py
implement PatrickStar stateful tensor.
Towards a dynamic CPU-GPU layout of param fp16 and grad fp16 data.
> [zero] add stateful tensor

- colossalai/engine/ophooks/zero_hook.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- colossalai/zero/sharded_param/sharded_param.py
- colossalai/zero/sharded_param/sharded_tensor.py
- colossalai/zero/sharded_param/tensorful_state.py
- tests/test_zero_data_parallel/test_shard_param.py
The state of grads are not set correctly.
> [zero] label state for param fp16 and grad

- colossalai/engine/ophooks/zero_hook.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- colossalai/zero/sharded_param/sharded_param.py
- tests/test_zero_data_parallel/common.py
- tests/test_zero_data_parallel/test_shard_param.py
Fix #550 . However, I haven't manage the state of grad currently.
> [zero] hijack p.grad in sharded model

- colossalai/engine/ophooks/zero_hook.py
- colossalai/utils/memory_tracer/model_data_memtracer.py
- colossalai/zero/init_ctx/init_context.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_model/utils.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- tests/test_moe/test_moe_zero_init.py
- tests/test_zero_data_parallel/common.py
- tests/test_zero_data_parallel/test_init_context.py
The old name col_ is misleading to colomn_XXX
> [polish] rename col_attr -> colo_attr

- colossalai/kernel/cuda_native/csrc/layer_norm_cuda.cpp
> [format]colossalai/kernel/cuda_native/csrc/layer_norm_cuda.cpp

- colossalai/utils/memory_utils/utils.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- colossalai/zero/sharded_param/sharded_param.py
- tests/test_zero_data_parallel/test_shard_param.py
Make fp16/32 grad and fp32 param `StatefulTensor` and trace their states.
> [zero] trace states of fp16/32 grad and fp32 param

- colossalai/utils/memory_tracer/memstats_collector.py
fix the scale bugs.
add sampling time
> [zero] add sampling time for memstats collector

- tests/test_utils/test_tensor_move.py
change the import path and running GPU
> [zero] test zero tensor utils

- colossalai/nn/layer/parallel_1d/layers.py
https://github.com/hpcaitech/ColossalAI/issues/600
> Add tensor parallel input check

- colossalai/utils/__init__.py
- colossalai/utils/checkpointing.py
- Updated checkpoint save/load utils
> [model checkpoint] checkpoint utils

- colossalai/nn/layer/base_layer.py
- colossalai/nn/layer/colossalai_layer/_utils.py
- colossalai/nn/layer/colossalai_layer/dropout.py
- colossalai/nn/layer/colossalai_layer/embedding.py
- colossalai/nn/layer/colossalai_layer/linear.py
- colossalai/nn/layer/colossalai_layer/normalization.py
Reworked unified layers for ease of save/load states
- Added a base unified module class
- Updated initialization of unified layers
> [model checkpoint][hotfix] unified layers for save&load

- colossalai/nn/layer/parallel_2d/layers.py
Updated saving/loading for 2d layers
> Feature/checkpoint 2D

- colossalai/nn/layer/parallel_1d/__init__.py
- colossalai/nn/layer/parallel_1d/layers.py
Updated saving/loading for 1d layers
> Feature/checkpoint 1D

- colossalai/communication/collective.py
- Updated communication ops for cpu tensors
- Added scatter_object_list from torch
> [model checkpoint] CPU communication ops

- colossalai/nn/layer/parallel_2p5d/layers.py
Updated saving/loading for 2.5d layers
> Feature/checkpoint 2.5D

- colossalai/nn/layer/parallel_3d/layers.py
Updated saving/loading for 3d layers
> Feature/Checkpoint 3D

- colossalai/trainer/hooks/__init__.py
- colossalai/trainer/hooks/_checkpoint_hook.py
> [model checkpoint] checkpoint hook

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/proposal.yml
> [GitHub] Add prefix and label in issue template

- colossalai/utils/activation_checkpoint.py
motivation: See https://github.com/hpcaitech/ColossalAI/issues/643
I have fixed the activation offload.
For gpt2-xl, with a batch size of 32, the memory_allocated decreased from more than 18G to below 14G.
> [zero] fixed the activation offload

- colossalai/kernel/cuda_native/csrc/cpu_adam.cpp
- colossalai/nn/optimizer/__init__.py
- colossalai/nn/optimizer/cpu_adam.py
- colossalai/nn/optimizer/hybrid_adam.py
- colossalai/nn/optimizer/utils.py
- tests/test_moe/test_moe_zero_optim.py
* add cpu adam counter for all cpu adam
* fixed updating error in adam kernel
> fixed bugs in CPU adam

- colossalai/communication/utils.py
[NFC] polish colossalai/communication/utils.py code style
> [NFC] polish colossalai/communication/utils.py code style

- colossalai/zero/init_ctx/init_context.py
Reverts hpcaitech/ColossalAI#645
> Revert "[zero] polish init context"

- colossalai/utils/activation_checkpoint.py
- tests/test_moe/test_moe_zero_optim.py
- tests/test_utils/test_activation_checkpointing.py
* using hybrid adam may cause a problem which can cause unitest fails.
> remove hybrid adam in test_moe_zero_optim

- colossalai/utils/memory_tracer/memstats_collector.py
- colossalai/utils/memory_tracer/model_data_memtracer.py
- colossalai/zero/init_ctx/init_context.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- tests/test_moe/test_moe_zero_init.py
fixed #650 
GPT 8B batch size = 32
> [hotfix] fix a bug in model data stats tracing

- README-zh-Hans.md
- README.md
> update GPT-2 experiment result 

- .github/workflows/build.yml
- .github/workflows/compatibility_test.yml
Fixed the workflow problem mentioned in #671 .
> [ci] replace the ngc docker image with self-built pytorch image

- .github/workflows/compatibility_test.yml
Fixed the workflow mentioned in #677 .
> [ci] fixed compatibility workflow

- colossalai/zero/init_ctx/init_context.py
- tests/test_moe/test_moe_zero_init.py
- tests/test_moe/test_moe_zero_model.py
- tests/test_moe/test_moe_zero_optim.py
- tests/test_zero_data_parallel/test_init_context.py
- tests/test_zero_data_parallel/test_shard_model_v2.py
- tests/test_zero_data_parallel/test_sharded_optim_v2.py
- tests/test_zero_data_parallel/test_state_dict.py
- adapt model weight initialization for methods in Pytorch nn.init
> [zero] fix init bugs in zero context

- .github/workflows/compatibility_test.yml
This PR is for #690 . The option list can only be used when this PR is merged into main, but it still works fine when manually triggering the workflow on the `hotfix/ci-compatibility` branch.
> [ci] update workflow trigger condition and support options

- .github/workflows/compatibility_test.yml
In #691 , the option list was not showing because the field is missing in the yaml file. It has been fixed in this PR.
> [ci] added missing field in workflow

- .github/workflows/build.yml
- .github/workflows/compatibility_test.yml
- requirements/requirements-test.txt
> [hotfix] update requirements-test

- colossalai/nn/layer/moe/utils.py
- colossalai/nn/optimizer/cpu_adam.py
- colossalai/zero/init_ctx/init_context.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- tests/test_moe/test_moe_zero_init.py
- tests/test_moe/test_moe_zero_model.py
- tests/test_moe/test_moe_zero_optim.py
- tests/test_zero_data_parallel/common.py
* adapt post grad hooks for not-shard parameters
* adapt optimizer for not-shard parameters
* offload gradients for not-replicated parameters
> [zero] improve adaptability for not-shard parameters

- colossalai/context/parallel_context.py
- colossalai/initialize.py
Implemented method 3 mentioned in #722 .
> [util] support detection of number of processes on current node

- colossalai/communication/collective.py
This fixed #720  as part of the efforts to tackle #688 .
The screenshot of successful test is shown below.
> [util] fixed communication API with PyTorch 1.9

- colossalai/amp/torch_amp/_grad_scaler.py
This fixed #734 as part of the effort to tackle #733 .
The screenshot of the successful unit test is shown below.
> [bug] fixed grad scaler compatibility with torch 1.8

- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/utils/__init__.py
- colossalai/zero/utils/tensor_placement_policy.py
using global variable is not recommanded.
> [zero] use factory pattern for tensor_placement_policy

- colossalai/nn/layer/colossalai_layer/normalization.py
- colossalai/nn/layer/parallel_1d/layers.py
- colossalai/nn/layer/parallel_2d/layers.py
- colossalai/nn/layer/parallel_2p5d/layers.py
- colossalai/nn/layer/parallel_3d/_operation.py
- colossalai/nn/layer/parallel_3d/layers.py
- colossalai/nn/layer/vanilla/__init__.py
- colossalai/nn/layer/vanilla/layers.py
> [hotfix] layernorm

- colossalai/zero/utils/tensor_placement_policy.py
- tests/test_zero/test_stateful_tensor_mgr.py
> [hotfix] fix test_stateful_tensor_mgr

- colossalai/testing/__init__.py
- colossalai/testing/utils.py
> [test] added a decorator for address already in use error with backward compatibility

- colossalai/context/parallel_context.py
> [compatibility] used backward-compatible API for global process group

- colossalai/trainer/hooks/_checkpoint_hook.py
Added saving by iter for ckpt hook.
Fixed the ckpt hook bugs with DDP.
> [hotfix] fix the ckpt hook bugs when using DDP

- colossalai/nn/layer/parallel_2d/_operation.py
- colossalai/nn/layer/parallel_2p5d/_operation.py
Dim shape check should be put before we really prepare to chunk it.
https://github.com/hpcaitech/ColossalAI/issues/669
> change the check assert in split batch 2d

- colossalai/amp/naive_amp/grad_scaler/base_grad_scaler.py
- colossalai/amp/naive_amp/grad_scaler/dynamic_grad_scaler.py
- colossalai/zero/sharded_model/sharded_model_v2.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
- colossalai/zero/sharded_param/sharded_param.py
- tests/test_zero/test_stateful_tensor_mgr.py
* solve memory leak when using reuse_fp16_shard
* fix type hint in gradient scaler
* add verbose to control the logger in ShardedOptimizerV2
> [hotfix] fix bugs in zero

- colossalai/trainer/hooks/_commons_.py
- colossalai/trainer/hooks/_log_hook.py
- colossalai/trainer/hooks/_metric_hook.py
Throughput hook show Tflops metric.
> [log] add tflops logs

- colossalai/trainer/hooks/_commons_.py
- colossalai/trainer/hooks/_log_hook.py
- colossalai/trainer/hooks/_metric_hook.py
Reverts hpcaitech/ColossalAI#792
> Revert "[log] add tflops logs"

- colossalai/cli/check/__init__.py
- colossalai/cli/check/check_installation.py
- colossalai/cli/cli.py
Added a CLI to check if Colossal-AI is built correctly.
Sample output for `colossalai check --help`
Sample output for `colossalai check -i`
> [cli] added check installation cli

- colossalai/tensor/_ops/linear.py
- colossalai/tensor/colo_tensor.py
- colossalai/zero/sharded_param/sharded_tensor.py
- colossalai/zero/sharded_param/tensorful_state.py
- tests/test_tensor/test_linear_tp.py
I initialized some code for applying ColoTensor on 1D row TP.
The detailed implementation is waiting for @Wesley-Jzy to fulfilling.
The goal is to let users use TP without replacing Linear with col.Linear. They just need to define the shard_spec of the weight of Linear. Colossal automatically calls the parallel Linear for it.
Related to #557
> [WIP] Applying ColoTensor on TP-1D-row Linear.

- tests/test_data/test_cifar10_dataset.py
- tests/test_data/test_data_parallel_sampler.py
- tests/test_data/test_deterministic_dataloader.py
This commit is missed out in the previous PR #833 , the screenshot of successful unit testing is shown in the previous PR.
> [unittest] refactored unit tests for change in dependency

- colossalai/builder/pipeline.py
- colossalai/initialize.py
> modefied the pp build for ckpt adaptation

- colossalai/communication/collective.py
- colossalai/communication/p2p.py
- colossalai/communication/ring.py
- colossalai/communication/utils.py
Improved the docstring and type hinting for functions/classes exposed to the user so that it looks better on the ReadTheDocs.
> [doc] improved docstring in the communication module

- colossalai/logging/__init__.py
- colossalai/logging/logger.py
Improved the docstring and type hinting for functions/classes exposed to the user so that it looks better on the ReadTheDocs.
> [doc] improved docstring in the logging module

- colossalai/amp/apex_amp/__init__.py
- colossalai/amp/apex_amp/apex_amp.py
- colossalai/amp/naive_amp/__init__.py
- colossalai/amp/naive_amp/_fp16_optimizer.py
- colossalai/amp/naive_amp/_utils.py
- colossalai/amp/naive_amp/grad_scaler/base_grad_scaler.py
- colossalai/amp/naive_amp/grad_scaler/constant_grad_scaler.py
- colossalai/amp/naive_amp/grad_scaler/dynamic_grad_scaler.py
- colossalai/amp/torch_amp/torch_amp.py
Improved the docstring for functions/classes exposed to the user so that it looks better on the ReadTheDocs.
> [doc] improved docstring in the amp module

- colossalai/context/parallel_context.py
- colossalai/context/process_group_initializer/initializer_2p5d.py
> [usability] improved error messages in the context module

- colossalai/tensor/colo_tensor.py
- tests/test_tensor/test_op.py
1. Wrap function in the torch_tensor to ColoTensor
2. Add a unit test
3. Fix return in __torch_functions__
> [tensor] wrap function in the torch_tensor to ColoTensor

- colossalai/tensor/__init__.py
- colossalai/tensor/_ops/layernorm.py
- colossalai/tensor/_ops/linear.py
- colossalai/tensor/colo_tensor.py
- colossalai/tensor/spec.py
- tests/test_tensor/test_linear_tp.py
- tests/test_tensor/test_model.py
1. add gather() and ShardPattern for ColoTensor
2. refine linear code
3. add gather for layernorm
> [tensor] refine linear and add gather for laynorm

- colossalai/tensor/_ops/embedding.py
- colossalai/tensor/colo_tensor.py
- tests/components_to_test/simple_net.py
- tests/test_tensor/test_embedding_tp.py
- tests/test_tensor/test_model.py
1. add embedding tp1d row
2. add unit test
3. add embedding to simple_net test
> [Tensor] add embedding tp1d row

- colossalai/tensor/_ops/loss.py
- tests/components_to_test/simple_net.py
- tests/test_tensor/test_model.py
1. reuse col_nn 1d vocab loss in ColoTensor
2. add test in simple_net
> [Tensor] add 1d vocab loss

- setup.py
Support sm70 for all cuda extensions.
> [setup] update cuda ext cc flags

- colossalai/utils/model/colo_init_context.py
- tests/test_tensor/test_model.py
https://github.com/hpcaitech/ColossalAI/issues/924
1. handle post assignment for ColoInitContext
2. add unit test
> [Tensor] fix init context

- colossalai/kernel/cuda_native/csrc/kernels/include/block_reduce.h
[NFC] polish colossalai/kernel/cuda_native/csrc/kernels/include/block_reduce.h code style
> [NFC] polish colossalai/kernel/cuda_native/csrc/kernels/include/block_reduce.h code styl

- colossalai/kernel/cuda_native/csrc/kernels/include/context.h
[NFC] polish colossalai/kernel/cuda_native/csrc/kernels/include/context.h code style
> [NFC] polish colossalai/kernel/cuda_native/csrc/kernels/include/context.h code style

- README-zh-Hans.md
- README.md
update results on a single GPU
highlight quick view
update install
> [NFC] update results on a single GPU, highlight quick view

- colossalai/cli/benchmark/__init__.py
- colossalai/cli/benchmark/utils.py
- colossalai/cli/launcher/multinode_runner.py
Removed the unused imports which can cause import errors.
> [cli] remove unused imports

- tests/components_to_test/__init__.py
- tests/components_to_test/gpt.py
- tests/test_tensor/_utils/_util.py
- tests/test_tensor/test_addmm_tp.py
- tests/test_tensor/test_embedding_tp.py
- tests/test_tensor/test_gpt.py
- tests/test_tensor/test_linear_tp.py
- tests/test_tensor/test_model.py
1. Move GPT model definition in `test_gpt` to `components_to_test`.
2. Move some common functions to `_utils`.
> [unit test] refactor test tensor

- colossalai/nn/parallel.py
- tests/test_tensor/test_gpt.py
1. impl ColoDDP for ColoTensor
2. refactor `test_gpt` to test DP+TP hybrid parallel
> [tensor] impl ColoDDP for ColoTensor

- .github/workflows/build.yml
- .github/workflows/release_bdist.yml
- docker/Dockerfile
All docker image are now collated in the official docker hub and the dockerfiles are put in [here](https://github.com/hpcaitech/Oh-My-Dockerfile/tree/main)
> [ci] update the docker image name

- colossalai/tensor/__init__.py
- colossalai/tensor/colo_parameter.py
- colossalai/tensor/distspec.py
- colossalai/tensor/module_utils.py
- colossalai/tensor/modules/__init__.py
- colossalai/tensor/modules/colo_module.py
- colossalai/tensor/modules/embedding.py
- colossalai/utils/model/colo_init_context.py
- tests/test_tensor/test_module_spec.py
1. Add ColoEmbedding
2. Add test on Bert
3. Add check shared param in different layer
4. Add check_module unit test
> [Tensor] add module check and bert test

- colossalai/zero/sharded_model/sharded_model_v2.py
> [hotfix] fix import error in sharded model v2

- colossalai/registry/__init__.py
Remove duplication “losses” registry
> Remove duplication registry

- colossalai/gemini/gemini_mgr.py
- colossalai/gemini/memory_tracer/memstats_collector.py
- colossalai/gemini/placement_policy.py
- colossalai/nn/parallel/data_parallel.py
- colossalai/tensor/chunk.py
- colossalai/zero/utils/zero_hook_v2.py
- colossalai/zero/zero_optimizer.py
- tests/test_tensor/test_zero.py
- tests/test_tensor/test_zero_optim.py
Only `placement_policy="cuda"` is supported now. "cpu" and "auto" will be supported in the next PR.
> [gemini] zero supports gemini

- .github/workflows/build_gpu_8.yml
Fixed the if condition in the 8-gpu auto testing workflow.
> [workflow] fixed 8-gpu test workflow

- colossalai/amp/naive_amp/naive_amp.py
Fixed issue #1084  by including dict for type casting.
> [amp] included dict for type casting of model output

- tests/test_data_pipeline_tensor_parallel/test_cifar_with_data_pipeline_tensor.py
Fixed the `test_cifar_with_data_pipeline_tensor` test case which reported error in the latest [8-gpu automatic test run](https://github.com/hpcaitech/ColossalAI/runs/6871725014?check_suite_focus=true). 
The test case runs fine after the fix as shown below.
> [test] fixed hybrid parallel test case on 8 GPUs

- colossalai/tensor/colo_parameter.py
kwargs may contain tensors, we should pass all tensor arguments to autograd function
> [hotfix] fix colo parameter torch function

- colossalai/nn/parallel/data_parallel.py
Cast floating point inputs of ColoDDPV2 to fp16.
Cast floating point outputs of ColoDDPV2 to fp32.
> [hotfix] cast colo ddp v2 inputs/outputs

- colossalai/kernel/cuda_native/csrc/multi_tensor_sgd_kernel.cu
- colossalai/nn/optimizer/fused_sgd.py
Old fused SGD only supports (fp16 grad, fp16 param, fp16 momentum) and (fp32 grad, fp32 param, fp32 momentum), it also supports (fp16 grad, fp32 param, fp32 momentum) now, which is essential when using ColoDDPV2.
> [optim] fused SGD supports ColoDDPV2

- colossalai/tensor/spec.py
Add `__repr__` to tensor spec and parallel action for better debugging experience.
> [tensor] added __repr__ to spec

- colossalai/nn/parallel/__init__.py
- colossalai/nn/parallel/data_parallel.py
- colossalai/zero/zero_optimizer.py
- tests/test_ddp/test_ddp_ignore_params.py
- tests/test_ddp/test_ddp_state_dict.py
- tests/test_tensor/test_zero_optim.py
1. ColoDDP supports overwriting default process group
2. Rename ColoDDPV2 to ZeroDDP
3. Add docstring for them
> [ddp] refactor ColoDDP and ZeroDDP

- .github/workflows/draft_github_release_post.yml
Fixed issues regarding permission and API rate request limit.
> [workflow] fixed release post workflow

- colossalai/fx/proxy.py
- tests/test_fx/test_tracer/test_hf_model/test_hf_bert.py
> [fx] added testing for all bert variants

- colossalai/fx/proxy.py
- colossalai/fx/tracer/_tracer_utils.py
- colossalai/fx/tracer/meta_patch/patched_function.py
- colossalai/fx/tracer/tracer.py
- tests/test_fx/test_coloproxy.py
- tests/test_fx/test_tracer/test_hf_model/test_hf_bert.py
- tests/test_fx/test_tracer/test_hf_model/test_hf_gpt.py
- tests/test_fx/test_tracer/test_hf_model/utils.py
So far only GPTForSequenceClassification does not work for some unknown reasons. This is not very important as GPT is not designed for classification but I will fix this soon.
> [fx] added testing for all gpt variants

- colossalai/fx/passes/shard_1d_pass.py
Temporarily used 1d_linear_pass which puts materialization inside pass.
> [fx] temporarily used 1d_linear_pass

- colossalai/fx/tracer/meta_patch/patched_function.py
- colossalai/fx/tracer/meta_patch/patched_module.py
- tests/test_fx/test_coloproxy.py
- tests/test_fx/test_tracer/test_timm_model/test_timm_model.py
> [fx] added timm model tracing testing

- tests/test_fx/test_tracer/test_timm_model/test_timm_model.py
This PR fixes the results misalignment of the timm models. The result misalignment occurs because that the model is traced in training mode, thus `torch.nn.functional.batch_norm` does not yield consistent outputs.
> [fx] fixed timm tracing result misalignment

- tests/test_fx/test_tracer/test_hf_model/test_hf_t5.py
- tests/test_fx/test_tracer/test_hf_model/utils.py
Fixed the tracing problem on OPT/T5 models. The root cause is explained in #1226 .
> [fx] fixed huggingface OPT and T5 results misalignment

- colossalai/utils/common.py
- colossalai/zero/sharded_optim/sharded_optim_v2.py
> [hotfix] fix sharded optim step and clip_grad_norm

- colossalai/fx/proxy.py
- colossalai/fx/tracer/tracer.py
- tests/test_fx/test_tracer/test_hf_model/test_hf_t5.py
This fixed tracing issue when T5 uses apex based normalization layer.
> [fx] fixed tracing with apex-based T5 model

- colossalai/nn/lr_scheduler/__init__.py
> [NFC] polish colossalai/nn/lr_scheduler/__init__.py

- .github/workflows/compatibility_test.yml
> [workflow] disable p2p SHM for compatibility CI on rtx3080

- colossalai/gemini/chunk.py
- colossalai/utils/checkpoint/module_checkpoint.py
- colossalai/utils/checkpoint/utils.py
- tests/test_utils/test_colo_checkpoint.py
* [polish] polish code in chunk.py
* [hotfix] fix a running error in test_colo_checkpoint.py
> [hotfix] fix a running error in test_colo_checkpoint.py

- colossalai/fx/tracer/meta_patch/patched_function/torch_ops.py
- tests/test_fx/test_tracer/test_patched_op.py
Added the patch for the torch operator (torch.max) and data movement (cpu and cuda) with meta backend.
> [fx] patched torch.max and data movement operator

- tests/test_fx/test_tracer/test_torchaudio_model/test_torchaudio_tacotron.py
- tests/test_fx/test_tracer/test_torchaudio_model/test_torchaudio_transformer.py
- tests/test_fx/test_tracer/test_torchaudio_model/test_torchaudio_wave2vec.py
- tests/test_fx/test_tracer/test_torchaudio_model/torchaudio_utils.py
The conformer tracing test failed due to a change in the function signature, this PR fixed this problem so that this test can be passed.
> [fx] fixed torchaudio conformer tracing

- colossalai/gemini/ag_chunk.py
Add AgChunk for later update plan.
The unitest will be merged from the next pull request.
> [zero] add AgChunk

- colossalai/gemini/update/__init__.py
- colossalai/gemini/update/search_utils.py
- tests/test_gemini/update/test_search.py
A new allocation algorithm for a uniform chunk size for parameters in different dp groups.
> [zero] add chunk size searching algorithm for parameters in different groups

- colossalai/utils/common.py
- tests/test_fx/test_codegen/test_activation_checkpoint_codegen.py
The previous PR #1439 introduced a test which interfered with other tests. This PR fixed this problem.
> [test] fixed the activation codegen test

- .github/workflows/compatibility_test.yml
Added steps on TensorNVMe to the workflow for compatibility test.
> [workflow] added TensorNVMe to compatibility test

- colossalai/auto_parallel/solver/sharding_strategy.py
Standardized the code structure in the auto parallel format.
> [autoparallel] standardize the code structure

- colossalai/auto_parallel/solver/conv_handler.py
- colossalai/auto_parallel/solver/dot_handler.py
- colossalai/auto_parallel/solver/operator_handler.py
- colossalai/auto_parallel/solver/sharding_strategy.py
- tests/test_auto_parallel/test_dot_handler.py
Added dot handler, and refactored its implementation to align with #1467 .
> [autoparallel] added dot handler

- README-zh-Hans.md
- README.md
Adding experimental results of xTrimoMultimer.
> [doc] update readme with the new xTrimoMultimer project

- colossalai/device/device_mesh.py
- colossalai/tensor/shape_consistency.py
- tests/test_tensor/test_comm_spec_apply.py
- tests/test_tensor/test_shape_consistency_apply.py
If the communication happens among all devices of the device mesh, we should do this communication in a flatten device mesh in one stage instead of doing it in each axis separately.
> [tensor]add 1D device mesh

- colossalai/nn/parallel/layers/cache_embedding/cache_mgr.py
- colossalai/nn/parallel/layers/cache_embedding/freq_aware_embedding.py
- tests/test_layers/test_cache_embedding.py
> shrink freq_cnter size.

- colossalai/fx/proxy.py
This will not cause any conflicts and should be merged.
> [hotfix] fix coloproxy typos.

- colossalai/auto_parallel/solver/__init__.py
- colossalai/auto_parallel/solver/graph_analysis.py
- colossalai/fx/passes/utils.py
- tests/test_auto_parallel/test_liveness_analysis.py
This PR Added liveness analysis based on the computation graph. The following context clarifies what is included in this PR.
A live variable is a variable whose lifecycle is still in effect (not terminated yet). In other words, if there is a node in a graph 
and it will not be visited again during traversal, it is no longer a live variable. In the context of deep learning, a live variable can be an input, activation or a weight parameter.
In this PR, we travel the computation graph node by node. Each node is transformed into one line of code and thus we deem each node as a stage. Information such as live variables and memory cost is stored with respect to each stage.
```
c = a + b  # node 0 -> stage 0
e = c + d  # node 1 -> stage 1
```
In a stage (node), what are the live variables …
> [autoparallel] added liveness analysis

- colossalai/auto_parallel/solver/constants.py
- colossalai/auto_parallel/solver/conv_handler.py
- colossalai/auto_parallel/solver/cost_graph.py
- colossalai/auto_parallel/solver/operator_handler.py
- colossalai/auto_parallel/solver/sharding_strategy.py
- colossalai/auto_parallel/solver/strategies_constructor.py
- tests/test_auto_parallel/test_cost_graph.py
- tests/test_auto_parallel/test_strategies_constructor.py
This PR provieds a StrategiesConstructor class to analysis the graph, it will traverse all the nodes in the graph and append the StrategiesVector into LeafStrategies and StrategyMap. These two datastructure will be fed into solver to find the best strategies combination.
> [autoparellel]add strategies constructor

- colossalai/pipeline/rpc/PipelineBase.py
- tests/test_pipeline/rpc_test_utils.py
- tests/test_pipeline/test_cuda_rpc_optimizer.py
- adjust main loop to prevent busy waiting
- integrate ste into main loop to avoid extra cuda memory cost by threading of stepping
> [pipeline/tuning] improve dispatch performance both time and space cost

- colossalai/nn/_ops/embedding.py
> [NFC] polish colossalai/nn/_ops/embedding.py code style

- tests/components_to_test/gpt.py
Polished code format for
- tests/components_to_test/gpt.py
> [NFC] polish test component gpt code style

- colossalai/auto_parallel/solver/op_handler/dot_handler.py
- colossalai/auto_parallel/solver/op_handler/strategy_generator.py
Completed all strategy generations for the matmul operations which do not require broadcasting.
> [autoparallel] added all non-bcast matmul strategies

- colossalai/auto_parallel/solver/op_handler/__init__.py
- colossalai/auto_parallel/solver/op_handler/dot_handler.py
- colossalai/auto_parallel/solver/op_handler/operator_handler.py
- tests/test_auto_parallel/test_solver_with_mlp.py
1. Update the cost computation methods of DotHandler V1.
2. build test to use solver on MLP model.
> [autoparallel] adapt solver with mlp

- colossalai/auto_parallel/solver/op_handler/dot_handler_v2.py
- colossalai/auto_parallel/solver/op_handler/node_handler.py
- colossalai/auto_parallel/solver/sharding_strategy.py
- colossalai/auto_parallel/solver/strategy/__init__.py
- colossalai/auto_parallel/solver/strategy/matmul_strategy_generator.py
- colossalai/auto_parallel/solver/strategy/strategy_generator.py
- tests/test_auto_parallel/test_linear_handler_v2.py
This PR implemented the strategy generator for linear operation. This PR can be summarized as follows:
1. create a module called strategy which stores the related classes and functions for sharding strategy and generators
2. implemented the generators for linear operations
> [autoparallel] implemented linear projection strategy generator

- colossalai/auto_parallel/solver/op_handler/dot_handler_v2.py
- colossalai/auto_parallel/solver/strategy/matmul_strategy_generator.py
- colossalai/auto_parallel/solver/strategy/strategy_generator.py
- tests/test_auto_parallel/test_node_handler/test_bmm_handler.py
This PR adds handler for `torch.bmm` and `torch.Tensor.bmm`.
> [autoparallel] added node handler for bmm

- colossalai/__init__.py
update version to 0.1.10 for [issue 175](https://github.com/hpcaitech/ColossalAI-Examples/issues/175)
> update version to 0.1.10

- colossalai/auto_parallel/solver/op_handler/__init__.py
- colossalai/auto_parallel/solver/op_handler/layer_norm_handler_v2.py
- colossalai/auto_parallel/solver/strategy/__init__.py
- colossalai/auto_parallel/solver/strategy/layer_norm_generator.py
- tests/test_auto_parallel/test_node_handler/test_layer_norm_handler_v2.py
This PR adds handler for **torch.nn.LayerNorm**.
> [autoparallel] add layer norm handler v2

- .github/workflows/scripts/build_colossalai_wheel.py
> [NFC] polish  .github/workflows/scripts/build_colossalai_wheel.py code

- .isort.cfg
- .pre-commit-config.yaml
- .style.yapf
* add isort 
* change white space length in yapf style
* add pre-commit hooks
> [pre-commit] update pre-commit

- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_addbmm_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_batch_norm_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_binary_elementwise_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bmm_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_conv_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_layer_norm_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_linear_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py
This PR mainly add numerical test for handlers.
Note: The assert function used in numerical test will generate a warning message instead of stopping the program execution. Therefore, test passing do NOT mean getting numerically close results.
> [autoparallel] add numerical test for handlers

- colossalai/auto_parallel/tensor_shard/node_handler/strategy/conv_strategy_generator.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_conv_handler.py
This PR fixed the conv node strategies which fail the numerical test. Two main changes are:
**1. Correct the communication logical axis
2. Consider the cases if 'others' and 'bias' are non-param tensors.**
> [autoparallel] fix conv handler numerical test

- colossalai/constants.py
- colossalai/context/parallel_mode.py
- colossalai/context/process_group_initializer/initializer_3d.py
- colossalai/global_variables.py
- colossalai/nn/layer/parallel_1d/_operation.py
- colossalai/nn/layer/parallel_1d/layers.py
- colossalai/nn/layer/parallel_3d/_operation.py
- colossalai/nn/layer/parallel_3d/_utils.py
- colossalai/nn/layer/parallel_3d/layers.py
- docker/Dockerfile
- tests/test_layers/test_3d/checks_3d/check_layer_3d.py
- tests/test_layers/test_3d/checks_3d/common.py
- tests/test_layers/test_3d/test_3d.py
- Polished tensor parallel implementation
- Achieved the same 1D throughput as the latest Megatron
> [tensorparallel] Updated TP layers

- colossalai/kernel/cuda_native/flash_attention.py
- tests/test_utils/test_flash_attention.py
abort TRITON_AVAILABLE, merge into HAS_TRITON
> [flashatt] polish code and fix test

- colossalai/kernel/cuda_native/flash_attention.py
- tests/test_utils/test_flash_attention.py
add q_k_v, q_kv and qkv function for flash attention
> [kernel] more flexible flashatt interface

- colossalai/amp/naive_amp/_fp16_optimizer.py
- [NFC] polish colossalai/amp/naive_amp/_fp16_optimizer.py code style
> [NFC] polish colossalai/amp/naive_amp/_fp16_optimizer.py code style

- .github/workflows/draft_github_release_post.yml
> [NFC] polish .github/workflows/draft_github_release_post.yml code style

- colossalai/amp/torch_amp/_grad_scaler.py
polish colossalai/amp/torch_amp/_grad_scaler.py code style
> [NFC] polish colossalai/amp/torch_amp/_grad_scaler.py code style

- colossalai/nn/layer/colossalai_layer/linear.py
- colossalai/nn/layer/vanilla/__init__.py
- colossalai/nn/layer/vanilla/layers.py
- Added skip_bias_add for non-tp linear
- Updated format of involved files
> [tensorparallel] Added skip_bias_add for non-tp linear

- colossalai/utils/model/lazy_init_context.py
- tests/test_fx/test_complete_workflow.py
The current `LazyInitContext` is implemented in `colossalai/utils/model/lazy_init_context`. However, when we create the init the module with meta tensor backend, the materialization has a bug which leads to meta tensors not actually being rematerialized to real-value tensors.
This PR fixed the bug mentioned above and improved the test case by checking whether the tensor is meta before rematerialization and whether the tensor is real after rematerialization.
> [utils] fixed lazy init context

- tests/test_amp/test_torch_fp16.py
This pr add a torch amp unit test, compare torch amp and apex amp.
> [amp] add torch amp test

- examples/tutorial/auto_parallel/auto_ckpt_demo.ipynb
- examples/tutorial/auto_parallel/bench_utils.py
cc @Cypher30 please help me debug these files.
> [sc] add examples for auto checkpoint.

- colossalai/fx/__init__.py
- colossalai/fx/passes/__init__.py
- colossalai/fx/passes/meta_info_prop.py
Add a simple API for `metainfo_trace`. I can't design a good function name, can discuss if necessary.
> [fx] metainfo_trace as an API.

- examples/images/diffusion/README.md
- examples/images/diffusion/configs/train_colossalai_cifar10.yaml
- examples/images/diffusion/environment.yaml
- examples/images/diffusion/ldm/data/cifar10.py
- examples/images/diffusion/requirements.txt
> [example] add cifar10 dadaset for diffusion

- colossalai/amp/naive_amp/__init__.py
[[NFC] polish colossalai/amp/naive_amp/__init__.py code style](https://github.com/hpcaitech/ColossalAI/commit/09a1c4399493b9fd81dcd5472d585ce5ba5660d8)
> [NFC] polish colossalai/amp/naive_amp/__init__.py code style

- colossalai/nn/layer/parallel_1d/layers.py
- colossalai/nn/layer/parallel_3d/_operation.py
- colossalai/nn/layer/parallel_3d/layers.py
- Fixed 1d linear before classifier
- Added layernorm jit
- Fixed format
> [tensorparallel] fixed tp layers

- colossalai/kernel/cuda_native/__init__.py
- colossalai/kernel/cuda_native/flash_attention.py
- tests/test_utils/test_flash_attention.py
- Added MaskedFlashAttention for easier use
- Added unittest for the new api
> [kernel] Updated flash attention API

- colossalai/logging/logger.py
- Prevented our logger hijacking other loggers' formats after colossalai has been imported
> [hotfix] Fixed logger

- examples/images/diffusion/README.md
- examples/images/diffusion/configs/train_colossalai.yaml
- examples/images/diffusion/configs/train_colossalai_cifar10.yaml
- examples/images/diffusion/configs/train_ddp.yaml
- examples/images/diffusion/configs/train_pokemon.yaml
- examples/images/diffusion/environment.yaml
- examples/images/diffusion/ldm/models/autoencoder.py
- examples/images/diffusion/ldm/models/diffusion/classifier.py
- examples/images/diffusion/ldm/models/diffusion/ddpm.py
- examples/images/diffusion/main.py
- examples/images/diffusion/requirements.txt
- examples/images/diffusion/scripts/img2img.py
- examples/images/diffusion/scripts/txt2img.py
- update lightning version for stable diffusion
> update lightning version

- examples/images/diffusion/README.md
- update model download in README
> update model download in README

- colossalai/nn/optimizer/gemini_optimizer.py
- colossalai/nn/optimizer/hybrid_adam.py
- colossalai/nn/optimizer/zero_optimizer.py
- colossalai/nn/parallel/gemini_parallel.py
- colossalai/zero/__init__.py
- examples/language/gpt/README.md
- examples/language/gpt/run.sh
- examples/language/gpt/train_gpt_demo.py
- examples/language/opt/run_clm.py
- examples/tutorial/opt/opt/run_clm.py
- tests/test_gemini/update/test_optim.py
- tests/test_gemini/update/test_zerooptim_state_dict.py
- tests/test_tensor/test_tp_with_zero.py
Simplify the Gemini Optimizer
original:
```
optimizer = HybridAdam(model.parameters(), lr=1e-3)
zero_optim = ZeroOptimizer(optimizer, model, initial_scale=1)
```
Now
```
zero_optim = GeminiAdamOptimizer(model, lr=1e-3, initial_scale=1)
```
> [Gemini] add GeminiAdamOptimizer

- colossalai/device/__init__.py
- colossalai/device/calc_pipeline_strategy.py
- colossalai/device/profile_alpha_beta.py
- tests/test_device/test_alpha_beta.py
**What's new?**
Given a list of 1D devices, return $\alpha$ and $\beta$
> [autoparallel] Add alpha beta

- colossalai/nn/_ops/element_wise.py
What this PR is for:
1. fix the bug that Gemini can not work for vgg, alexnet.
What did I do
1. the bug comes from inplace relu OP, so I do some special trick for them....
> [hotfix] make Gemini work for conv DNN

- .github/workflows/release_bdist.yml
This PR fixed the typo in the command for creating condarc file.
> [workflow] fixed the typo in condarc

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/proposal.yml
- add optional affiliation information tips
> [GitHub] update issue template

- colossalai/auto_parallel/passes/runtime_preparation_pass.py
- colossalai/auto_parallel/tensor_shard/node_handler/experimental/view_generator.py
- colossalai/auto_parallel/tensor_shard/node_handler/linear_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_view_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py
1. This PR add runtime pass for the experimental view handler. It will convert the arguments for view operator to adapt the distributed runtime.
2. Fix bugs in linear handler and view handler.
3. Add numerical tests for view handler.
4. Add more test cases which cover convolution and linear as previous node of view node, two target shapes.
This PR and previous PR just handle the view case, other reshape operation will be covered in future PR.
> [autoparallel] add runtime pass and numerical test for view handler

- colossalai/gemini/memory_tracer/param_tracer_wrapper.py
- colossalai/gemini/ophooks/param_trace_hook.py
- colossalai/gemini/tensor_utils.py
- tests/test_gemini/test_param_tracer.py
> free and allocate cuda memory by tensor.storage, add grad hook

- colossalai/auto_parallel/tensor_shard/constants.py
- colossalai/auto_parallel/tensor_shard/sharding_strategy.py
- colossalai/auto_parallel/tensor_shard/solver/cost_graph.py
- colossalai/auto_parallel/tensor_shard/solver/solver.py
- colossalai/auto_parallel/tensor_shard/utils/reshape.py
- tests/test_auto_parallel/test_tensor_shard/test_solver_self_attention_block.py
1. update the node merge rule.
2. update the CostGrpah class and Solver class to adapt the latest interface.
3. update the reshape utils to deal with the corner case.
4. upload the self-attention test file to reproduce the search result.
> [autoparallel] adapt solver with self attention

- colossalai/auto_parallel/tensor_shard/node_handler/linear_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_linear_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_solver_with_gpt_related_module.py
1. This PR integrates GPT2Model test with all gpt2 related modules, such as GPT2Block, GPT2Attention.
2. Fix a bug which leads to linear handler crashing. The reason could refer to the comment in #2089.
3. Add  test cases related the bug mentioned above to check whether the bug has been fixed.
> [autoparallel] complete gpt related module search

- colossalai/pipeline/rpc/_pipeline_base.py
- tests/test_pipeline/rpc_test_utils.py
- tests/test_pipeline/test_middleware_1f1b.py
Fix the data race introduced by adding DAG Topo for scheduler.
> [Pipeline Middleware] fix data race in Pipeline Scheduler for DAG

- colossalai/pipeline/rpc/_pipeline_base.py
- colossalai/pipeline/rpc/_pipeline_schedule.py
- colossalai/pipeline/rpc/utils.py
- tests/test_pipeline/rpc_test_utils.py
- tests/test_pipeline/test_middleware_1f1b.py
> [PP Middleware] Add bwd and step for PP middleware

- colossalai/gemini/memory_tracer/memory_stats.py
- colossalai/gemini/ophooks/runtime_mem_tracer_hook.py
- tests/test_gemini/update/test_gemini_use_rmt.py
Memstats maintain the mapping between preop timesteps and params.
> [Gemini] mapping of preop timestep and param

- colossalai/gemini/memory_tracer/param_runtime_order.py
- tests/test_gemini/update/test_gemini_use_rmt.py
We have to use the original logic to search the chunk size. Otherwise, the unittest will hang.
> [Gemini] hotfix the unittest bugs

- colossalai/auto_parallel/tensor_shard/node_handler/__init__.py
- colossalai/auto_parallel/tensor_shard/node_handler/softmax_handler.py
- colossalai/auto_parallel/tensor_shard/node_handler/strategy/__init__.py
- colossalai/auto_parallel/tensor_shard/node_handler/strategy/softmax_generator.py
- colossalai/auto_parallel/tensor_shard/node_handler/unary_elementwise_handler.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_softmax_handler.py
This PR implements softmax handler to generator strategies for F.softmax or nn.Softmax operation.
The basic rule is if the softmax_dim has been shard, we will recover that dimension to replicated status. Otherwise, we just do softmax with the current ShardingSpec.
For example:
input with ShardingSpec (R, S0, S1, R)
output = F.softmax(input, dim=1)
The softmax strategy following this input ShardingSpec is RRS1R -> RRS1R
You could see the dimension 1 has been recovered to 'R'.
> [autoparallel] implement softmax handler

- colossalai/kernel/cuda_native/flash_attention.py
- tests/test_utils/test_flash_attention.py
- Added new interfaces from xformers
> [kernel] Updated attention kernels

- colossalai/utils/model/colo_init_context.py
Also change post_process_colo_init_ctx() to use in dreambooth
> Update coloinit_ctx to support meta_tensor

- colossalai/fx/_meta_registrations.py
fix the NoneType bug in rnn tracing
> [meta] register meta func for rnn

- examples/language/palm/README.md
- examples/language/palm/data/README.md
- examples/language/palm/palm_pytorch/__init__.py
- examples/language/palm/palm_pytorch/autoregressive_wrapper.py
- examples/language/palm/palm_pytorch/palm_pytorch.py
- examples/language/palm/train.py
- tests/test_gemini/update/test_convert_torch_module.py
Add PaLM-Pytorch. It is the baseline and later we will add GeminiDPP for it.
> [example] add palm pytorch version

- colossalai/nn/layer/parallel_3d/_operation.py
> [hotfix] fixed layernorm3d type hints

- examples/images/diffusion/README.md
> [NFC] fix a typo 'stable-diffusion-typo-fine-tune'

- colossalai/nn/_ops/addmm.py
…ossalAI/issues/2170. Basically, it will fix TypeError: colo_addmm() got an unexpected keyword argument 'out' for 2D tensor parallelism. 
The patch is related to the issue "https://github.com/hpcaitech/ColossalAI/issues/2170"
> [hotfix] add kwargs for colo_addmm

- colossalai/fx/passes/adding_split_node_pass.py
- colossalai/pipeline/rpc/_pipeline_base.py
- colossalai/pipeline/rpc/_pipeline_schedule.py
- colossalai/pipeline/rpc/utils.py
> [Pipeline Middleware ] Fix deadlock when num_microbatch=num_stage

- colossalai/auto_parallel/passes/runtime_preparation_pass.py
- tests/test_auto_parallel/test_tensor_shard/test_gpt/gpt_modules.py
- tests/test_auto_parallel/test_tensor_shard/test_gpt/test_runtime_with_gpt_modules.py
- tests/test_auto_parallel/test_tensor_shard/test_gpt/test_solver_with_gpt_module.py
1. This PR integrates all gpt related tests into a folder named 'test_gpt'. 
2. All the solver strategy tests are integrated into test_solver_with_gpt_modules.py.
3. All the runtime numerical tests  are integrated into test_runtime_with_gpt_modules.py.
4. All the gpt modules which are reused in both test files are integrated into gpt_modules.py.
> [autoparallel] integrate_gpt_related_tests

- tests/test_auto_parallel/test_tensor_shard/test_gpt/gpt_modules.py
- tests/test_auto_parallel/test_tensor_shard/test_gpt/test_gpt2_performance.py
1. To compare the performance with the gpt2 demo in CAI, GPT2LMHeadModel is added into gpt2_modules.py. 
2. Add gpt2 performance test in this PR, we could use this test to measure the auto parallel system performance on gpt2 model.
> [autoparallel] add gpt2 performance test

- colossalai/context/parallel_context.py
…://github.com/hpcaitech/ColossalAI/issues/2199. 
https://github.com/hpcaitech/ColossalAI/issues/2199
> [hotfix] Fixing the bug related to ipv6 support. 

- colossalai/auto_parallel/passes/runtime_preparation_pass.py
- colossalai/auto_parallel/tensor_shard/node_handler/binary_elementwise_handler.py
- colossalai/auto_parallel/tensor_shard/node_handler/strategy/getitem_generator.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_getitem_handler.py
In getitem operator use cases, if the getitem index is int or list of int, those dimensions should be removed from output tensor, and if the getitem index is slice or list of slices, those dimensions will be kept in output tensor. However, we do not distinguish this two different cases in previous implementation.
In this PR, getitem handler will process the above cases correctly. And numerical tests are added into getitem unit test to cover the above cases.
> [autoparallel] update getitem handler

- colossalai/logging/logger.py
> [logger] hotfix #2109, missing _FORMAT

- examples/images/diffusion/README.md
This PR updated the `README.md` for the stable diffusion example, such that it contains detailed instructions on how to use Docker to run our example.
> [doc] updated the stable diffussion on docker usage

- colossalai/auto_parallel/tensor_shard/initialize.py
- tests/test_auto_parallel/test_tensor_shard/test_gpt/test_gpt2_performance.py
This PR implements a initialization API called 'autoparallelize' to encapsulate the auto-parallel initialization steps into one function.
The gpt2 performance test is updated with the above API as an example to show API usage.
> [autoparallel] autoparallel initialize

- colossalai/pipeline/rpc/_pipeline_base.py
> [Pipeline Middleware] Reduce comm redundancy by getting accurate output

- colossalai/zero/sharded_optim/low_level_optim.py
Fix issue [2249](https://github.com/hpcaitech/ColossalAI/issues/2249).
> [zero] polish low level zero optimizer

- colossalai/communication/collective.py
- colossalai/nn/layer/parallel_3d/_operation.py
- colossalai/nn/layer/parallel_3d/layers.py
- tests/test_layers/test_3d/checks_3d/check_layer_3d.py
- Optimized allgather & reducescatter usage
- Optimized 3D linear
- Improvement 5~7%
> [hotfix] Improved allgather & reducescatter for 3D

- colossalai/cli/benchmark/__init__.py
[NFC] polish colossalai/cli/benchmark/__init__.py code style
> [NFC] polish colossalai/cli/benchmark/__init__.py code style

- examples/language/gpt/benchmark_gemini.sh
- examples/language/gpt/run_gemini.sh
- examples/language/gpt/train_gpt_demo.py
* added the policy option in benchmark.sh
* updated the version check
> [example] update gemini benchmark bash

- examples/images/diffusion/configs/Teyvat/train_colossalai_teyvat.yaml
- examples/images/diffusion/configs/train_colossalai.yaml
- examples/images/diffusion/configs/train_colossalai_cifar10.yaml
- examples/images/diffusion/configs/train_pokemon.yaml
- examples/images/dreambooth/README.md
- examples/images/dreambooth/train_dreambooth_colossalai.py
- update README for dreamblooth
> Feature/diffusion update diffusion,Dreamblooth

- examples/images/dreambooth/train_dreambooth_colossalai.py
accelerator.num_processes -> gpc.get_world_size(ParallelMode.DATA)
> Fix a typo in train_dreambooth_colossalai.py

- colossalai/nn/parallel/data_parallel.py
- colossalai/nn/parallel/utils.py
- examples/images/dreambooth/train_dreambooth_colossalai.py
- tests/test_gemini/update/test_get_torch_model.py
* added `get_static_torch_model` function. users can get a static torch model used for saving checkpoints or numeric checks.
* updated the unit test of `get_static_torch_model`
* polished the dreambooth training script
> [gemini] add get static torch model

- colossalai/auto_parallel/tensor_shard/deprecated/constants.py
- colossalai/auto_parallel/tensor_shard/deprecated/graph_analysis.py
- colossalai/auto_parallel/tensor_shard/deprecated/op_handler/batch_norm_handler.py
- colossalai/auto_parallel/tensor_shard/deprecated/op_handler/unary_elementwise_handler.py
- colossalai/auto_parallel/tensor_shard/utils/factory.py
This reverts commit 1f8ab6f1f55f7a26d2584361646e244a8dd0f123.
> Revert "[NFC] polish code format (#2367)"

- colossalai/auto_parallel/tensor_shard/deprecated/constants.py
- colossalai/auto_parallel/tensor_shard/deprecated/graph_analysis.py
- colossalai/auto_parallel/tensor_shard/deprecated/op_handler/batch_norm_handler.py
- colossalai/auto_parallel/tensor_shard/deprecated/op_handler/embedding_handler.py
- colossalai/auto_parallel/tensor_shard/deprecated/op_handler/unary_elementwise_handler.py
- colossalai/auto_parallel/tensor_shard/utils/factory.py
Reverts hpcaitech/ColossalAI#2370
> Revert "[NFC] polish code format"

- colossalai/tensor/param_op_hook.py
- examples/images/diffusion/ldm/modules/diffusionmodules/util.py
Fix `NotImplementedError: Some torch function is incompatible because of its complcated inputs.` when training diffusers.
* add a ignore step for no grad tensors
* change the original checkpoint function in diffuser to torch checkpint function
> [hotfix] fix implement error in diffusers

- colossalai/cli/check/check_installation.py
The CLI's installation check command is outdated as the CUDA extensions can be built during runtime now.
```bash
colossalai check -i
```
Fixed #2394
This PR refactored the `check_installation.py` file such that it is updated for AOT kernel build detection. Meanwhile, some notes are added to the console output to help the user to understand what the output means.
Sample outputs:
1. With AOT CUDA kernel build
2. Without AOT CUDA kernel build
> [cli] updated installation check cli for aot/jit build

- colossalai/nn/parallel/data_parallel.py
- colossalai/nn/parallel/utils.py
- tests/test_gemini/update/test_grad_clip.py
- tests/test_gemini/update/test_optim.py
- tests/test_gemini/update/test_zeroddp_state_dict.py
- tests/test_tensor/test_tp_with_zero.py
* polished the code
* made `_get_shallow_copy_model` more robust
* removed useless code in testings
> [polish] polish code for get_static_torch_model

- .github/workflows/build.yml
- .gitignore
- requirements/requirements-test.txt
This PR modified the workflow file such that it generates a coverage report, and this report will be directed to the Github PR page as a comment.
> [worfklow] added coverage test

- .github/workflows/README.md
- README-zh-Hans.md
- README.md
This PR added `README.md` for all workflows, which serves as usage reference and future development archive.
> [doc] added documentation for CI/CD

- .github/workflows/auto_example_check.yml
- examples/README.md
Fixed #2426 
This PR refactored the `README.md` with more structured language and better markdown format, improving the readability and clarity of the documentation.
> [example] improved the clarity yof the example readme

- colossalai/cli/launcher/multinode_runner.py
Fixed #2441 
This PR added more items to the error log if colossalai run fails.
> [cli] provided more details if colossalai run fail

- .github/workflows/draft_github_release_post.yml
- .github/workflows/release_docker.yml
This PR refactored the `if` statement for the release-related workflows to ensure that they are only executed when the pull request is merged instead of closed.
> [workflow] fixed the on-merge condition check

- colossalai/pipeline/rpc/_pipeline_base.py
- colossalai/pipeline/rpc/_pipeline_schedule.py
- examples/language/gpt/experiments/pipeline_parallel/train_gpt_pp.py
1. Add GPipe Scheduler.
2. Fix lifecycle.
3. Replace the optimizer to a more stable one for test.
4. Fix offset-based rpc.
> [Pipeline] Polish PP Middleware

- colossalai/context/parallel_context.py
Reverts hpcaitech/ColossalAI#2408
> Revert "Fix a typo in parallel_context.py"

- colossalai/amp/naive_amp/grad_scaler/dynamic_grad_scaler.py
- colossalai/zero/sharded_optim/_utils.py
- tests/test_zero/low_level_zero/test_grad_acc.py
- tests/test_zero/low_level_zero/test_zero1_2.py
- tests/test_zero/low_level_zero/test_zero_init.py
- tests/test_zero/low_level_zero/test_zero_tp.py
* polished dynamic gradient scaler
* fix teh feature gradient clipping in the hybrid parallelism
> [zero] fix gradient clipping in hybrid parallelism

- colossalai/nn/optimizer/zero_optimizer.py
- colossalai/nn/parallel/__init__.py
- colossalai/nn/parallel/zero_wrapper.py
- colossalai/zero/sharded_optim/low_level_optim.py
- tests/test_zero/low_level_zero/test_grad_acc.py
- tests/test_zero/low_level_zero/test_zero1_2.py
- tests/test_zero/low_level_zero/test_zero_tp.py
I added two wrapper functions to unify current ZeRO APIs. In these functions, users can simply set the arguement `zero_stage` to switch to different types of ZeRO implementation.
> [zero] add zero wrappers

- colossalai/nn/parallel/data_parallel.py
- colossalai/nn/parallel/gemini_parallel.py
- colossalai/nn/parallel/utils.py
It should fix the above problem when using Lightning.
> [hotfix] fix lightning error

- colossalai/fx/_meta_registrations.py
- colossalai/fx/profiler/opcount.py
Support some op's flop and meta. Some changes are introduced by the precommit code format.
> [fx] support unet metainfo prop

- .github/pull_request_template.md
This PR added the PR template to standardize the development workflow.
> [doc] added pull  request template

- .github/pull_request_template.md
>
Fixed #2555 
This PR fixed a minor typo in the PR template.
> [doc] fixed the typo in pr template

- CHANGE_LOG.md
>
Fixed #2551 .
This PR added a comment to the `CHANGE_LOG.md` to redirect users to the github release page.
> [doc] updated the CHANGE_LOG.md for github release page

- colossalai/tensor/colo_parameter.py
- colossalai/tensor/colo_tensor.py
- colossalai/tensor/compute_spec.py
- colossalai/tensor/distspec.py
- colossalai/tensor/process_group.py
- colossalai/utils/model/colo_init_context.py
> [polish] polish ColoTensor and its submodules

- .github/workflows/report_leaderboard_to_lark.yml
>
Fixed #2566 
This PR fixed the typos stated in #2566 to make sure the workflow runs correctly.
> [workflow] fixed typos in the leaderboard workflow

- README-zh-Hans.md
- README.md
- examples/tutorial/README.md
- examples/tutorial/fastfold/README.md
> [tutorial] polish README

- .github/pull_request_template.md
>
Fixed #2576 .
This PR updated the PR template such that the example of issue link does not take effect.
> [doc] fixed issue link in pr template

- .github/workflows/compatiblity_test_on_dispatch.yml
- .github/workflows/compatiblity_test_on_pr.yml
- .github/workflows/compatiblity_test_on_schedule.yml
>
Fixed #2559 
Fixed #2541 
This PR refactored the file name and workflow name for the compatibility test.
> [workflow] refactored compatibility test workflow for maintenability

- .github/workflows/report_leaderboard_to_lark.yml
- .github/workflows/scripts/generate_leaderboard_and_send_to_lark.py
>
Fixed #2571.
This PR counts the discussion stats to the user engagement leaderboard to better reflect the team members' efforts to cope with the enquiries/requests/questions from the community.
> [workflow] added discussion stats to community report

- .github/workflows/example_check_on_schedule.yml
>
Fixed #2588 .
This PR fixed the typos in the example check workflow. 
The workflow has been tested and the screenshot is shown below.
> [workflow] fixed the typo in the example check workflow

- .github/workflows/report_test_coverage.yml
>
Fixed #2610 
This PR fixed the test coverage report problem.
> [workflow] fixed test coverage report

- requirements/requirements.txt
>
Fixed #2617 
This PR added torch to the `requirements.txt` so that read the docs can build the docs.
> [build] fixed the doc build process

- README-zh-Hans.md
- README.md
>
Fixed #2622 .
This PR updated the link to the latest build badge.
> [doc] fixed broken badge

- examples/tutorial/opt/inference/requirements.txt
>
This PR added `energonai` to the `requirements.txt` in the `opt/inference` example.
> [tutorial] added energonai to opt inference requirements

- examples/language/gpt/README.md
Resolved #2590 
Update the list of distributed plans for the Gemini example in language. Add a reference to an issue that is answered with differences between distributed methods.
> [example] Polish README.md

- .github/workflows/build_on_schedule.yml
>
Fixed #2580 
This PR is a continuation of #2574 to fix the gpu memory check condition, which is run the build and test if every GPU has no more than 10GB memory used at the time of the workflow.
> [workflow] fixed gpu memory check condition

- docs/source/en/Colossal-Auto/feature/layout_converting_management.md
- docs/source/zh-Hans/Colossal-Auto/feature/layout_converting_management.md
> [Docs] layout converting management

- README.md
- colossalai/nn/optimizer/README.md
- examples/tutorial/README.md
> [doc] add CVPR tutorial

- .github/workflows/scripts/generate_leaderboard_and_send_to_lark.py
>
This PR fixed the user engagement ranking as the previous code did not sort the list.
> [workflow] fixed communtity report ranking

- colossalai/utils/model/colo_init_context.py
>
Fixed #2682 
Ensure parameters are `ColoParameter` when using `ColoInitContext`.
> [gemini] fix colo_init_context

- colossalai/zero/sharded_optim/low_level_optim.py
> [hotfix] only append parameters with gradients

- README-zh-Hans.md
- README.md
> [doc] update auto parallel paper link

- colossalai/context/moe_context.py
> [NFC] polish colossalai/context/moe_context.py code style

- colossalai/context/process_group_initializer/initializer_pipeline.py
> [NFC] polish pipeline process group code style

- README-zh-Hans.md
- README.md
> [doc] add ChatGPT

- README-zh-Hans.md
- README.md
> [doc] resize figure

- colossalai/engine/gradient_handler/utils.py
>
> Summarize your work here: To polish colossalai/engine/gradient_handler/utils.py code style
> [NFC] polish colossalai/engine/gradient_handler/utils.py code style

- colossalai/auto_parallel/passes/runtime_preparation_pass.py
- tests/test_auto_parallel/test_tensor_shard/test_compatibility_with_ddp.py
- tests/test_auto_parallel/test_tensor_shard/test_compatibility_with_gemini.py
>
Test compatibility for gemini and auto parallel.
> [autoparallel] test compatibility for gemini and auto parallel

- colossalai/cli/launcher/__init__.py
> [NFC] polish colossalai/cli/launcher/__init__.py code style

- .github/workflows/build_on_pr.yml
>
Fixed #2710 
This PR fixed the tensor-nvme caching in build CI.
> [workflow] fixed tensor-nvme build caching

- .github/workflows/run_chatgpt_examples.yml
- .github/workflows/run_chatgpt_unit_tests.yml
>
NA
Add ChatGPT CI for unit testing and running examples.
> [devops] add chatgpt ci

- README.md
- applications/ChatGPT/README.md
> [doc] add open-source contribution invitation

- colossalai/auto_parallel/passes/runtime_preparation_pass.py
> [autoparallel] fix parameters sharding bug

- applications/ChatGPT/benchmarks/README.md
`open #2718 `
fix typo: change --nproc_pero_node to --nproc_per_node
> [doc] fix typo

- colossalai/cli/cli.py
> [NFC] polish colossalai/cli/cli.py code style

- applications/ChatGPT/chatgpt/trainer/rm.py
>
fixed #2739 
fix the typo bug of value_head 
> [chatgpt]fix train_rm bug with lora

- README-zh-Hans.md
- README.md
> [doc] update example and OPT serving link

- applications/ChatGPT/chatgpt/trainer/strategies/colossalai.py
>
NA
We found when using `.from_pretrained()` and enabling `shard_init` of `ColossalAIStrategy`, a shape mismatch error occurs when initializing model. Because the shape of on-the-fly sharded weight is different from the shape of weight from checkpoint.
We temporarily disable this arg and will support it in the future.
> [chatgpt] disable shard init for colossalai

- examples/images/diffusion/README.md
- examples/images/dreambooth/README.md
>
fix #2761
- fix pip install colossal
> [example/image/diffusion]: fix pip install colossal

- applications/ChatGPT/README.md
>
#2722 
Update readme of ChatGPT to describe how to save/load checkpoint.
> [chatgpt] update readme about checkpoint

- colossalai/nn/optimizer/zero_optimizer.py
- tests/test_gemini/update/test_zerooptim_state_dict.py
> [hotfix] add correct device for fake_param

- README-zh-Hans.md
- README.md
> [doc] update OPT serving

- .github/workflows/release_nightly_on_schedule.yml
>
fixed #2809 
Fixed nightly release CD running on forked repo.
However, I am not sure I am fixing it right... Review NEEDED.
> [CI/CD] fix nightly release CD running on forked repo

- LICENSE
- colossalai/auto_parallel/README.md
- colossalai/auto_parallel/tensor_shard/solver/solver.py
- colossalai/device/device_mesh.py
- docs/source/en/Colossal-Auto/get_started/introduction.md
- docs/source/en/Colossal-Auto/get_started/run_demo.md
> [hotfix] add copyright for solver and device mesh

- examples/language/bert/run_gemini.sh
- examples/language/bert/test_ci.sh
- examples/language/bert/train_bert_demo.py
> [exmaple] add bert and albert

- colossalai/engine/schedule/_pipeline_schedule.py
> [NFC] polish colossalai/engine/schedule/_pipeline_schedule.py code style

- applications/ChatGPT/tests/test_checkpoint.py
- applications/ChatGPT/tests/test_data.py
>
NA
Add an unit test to check whether save/load checkpoint is OK.
> [chatgpt] add test checkpoint

- LICENSE
- colossalai/kernel/cuda_native/flash_attention.py
>
N/A
This PR  removed the flash attention file from the kernel module, instead, we should install from the trition repository.
> [triton] added copyright information for flash attention

- colossalai/cli/check/check_installation.py
>
Fixed #2847 
This PR added more checks for version parsing in `colossalai check -i` to make sure the command does not fail on some corner cases mentioned in #2847 .
> [cli] handled version check exceptions

- examples/tutorial/opt/inference/README.md
>
fix typo in opt inference tutorial
> [doc] fix typo in opt inference tutorial

- colossalai/gemini/chunk/manager.py
- colossalai/gemini/chunk/search_utils.py
> [hotfix] fix chunk size can not be divided

- colossalai/nn/parallel/data_parallel.py
>
Rename "_pre_bacward" method of ZeroDDP to "_pre_backward".
> [nn/parallel/data_parallel.py]: Rename "_pre_bacward" method of ZeroDDP to "_pre_backward"

- applications/ChatGPT/chatgpt/nn/bloom_rm.py
- applications/ChatGPT/chatgpt/nn/gpt_rm.py
- applications/ChatGPT/chatgpt/nn/opt_rm.py
- applications/ChatGPT/examples/train_reward_model.py
- applications/ChatGPT/examples/train_rm.sh
>
fixed #2794 
fixed #2825 
support rm training with GPT-2 and OPT model
> [chatgpt]gpt-2& opt rm training support

- colossalai/auto_parallel/tensor_shard/utils/factory.py
- tests/test_auto_parallel/test_tensor_shard/test_find_repeat_block.py
>
The solving time for auto-parallel intra-op solver is unacceptable for LLMs as the number of layers increasing.
We could do following steps to reduce the solving time for LLMs:
1. Find largest repeated blocks.
2. Use an alias set to force all repeated blocks sharing a same distributed training strategies.
This PR implements a method to find the largest repeated blocks to solve the first issue.
> [autoparallel] find repeat blocks

- colossalai/zero/sharded_optim/bookkeeping/gradient_store.py
- colossalai/zero/sharded_optim/low_level_optim.py
>
It's not that important, but it seems more appropriate to call a method to modify the contents than to directly refer to the private member variable (_averaged_gradients) in self._grad_store. And very minor refactoring.
> [zero] trivial zero optimizer refactoring

- README-zh-Hans.md
- README.md
- docs/source/en/get_started/installation.md
- docs/source/zh-Hans/get_started/installation.md
- examples/tutorial/README.md
> [doc] add os scope, update tutorial install and tips

- examples/language/gpt/README.md
> [doc] update installation for GPT

- colossalai/utils/common.py
>
It's not the important part, but I've made exceptions more specific in the freeport search.
> [utils] Specify the free port search exception.

- .github/workflows/doc_check_on_pr.yml
- .github/workflows/doc_test_on_pr.yml
- .github/workflows/doc_test_on_schedule.yml
- docs/requirements-doc-test.txt
- docs/source/en/get_started/installation.md
>
Fixed #2928 
This PR added the documentation test workflow.
> [workflow] added auto doc test on PR

- docs/README.md
>
Fixed #2934 
Fixed #2651 
This PR added the README for our documentation system.
> [doc] added readme for documentation

- README-zh-Hans.md
- README.md
- applications/ChatGPT/README.md
- docs/source/en/get_started/installation.md
- docs/source/zh-Hans/get_started/installation.md
> [doc] add env scope

- colossalai/auto_parallel/tensor_shard/node_handler/strategy/reshape_generator.py
- colossalai/tensor/comm_spec.py
> [hotfix] add shard dim to aviod backward communication error

- applications/ChatGPT/examples/README.md
- applications/ChatGPT/examples/inference.py
- applications/ChatGPT/examples/inference.sh
>
fixed #2870 #2915 #
Add a demo of inference in Chatgpt/examples
> [chatgpt]add inference example

- colossalai/tensor/d_tensor/d_tensor.py
- colossalai/tensor/d_tensor/layout.py
- tests/test_tensor/test_dtensor.py
> [DTensor] implementation of dtensor

- applications/ChatGPT/examples/README.md
> [doc] fix chatgpt inference typo

- applications/ChatGPT/README.md
- applications/ChatGPT/examples/README.md
- applications/ChatGPT/requirements.txt
>
- fix README for chatGPT
- add github broad for chatgpt 
> [ChatGPT] fix README

- applications/ChatGPT/chatgpt/nn/reward_model.py
- applications/ChatGPT/chatgpt/trainer/rm.py
- applications/ChatGPT/examples/train_reward_model.py
>
fixed #2877 
fix lora bug
change the name 'body' back to 'model' to ensure the critic can be initialize from RM
change epoch default to 1 
> [chatgpt]fix lora bug

- README-zh-Hans.md
- README.md
> [doc] update news

- applications/ChatGPT/chatgpt/trainer/base.py
- applications/ChatGPT/chatgpt/trainer/strategies/base.py
- applications/ChatGPT/chatgpt/trainer/strategies/ddp.py
- applications/ChatGPT/chatgpt/trainer/strategies/sampler.py
- applications/ChatGPT/examples/test_ci.sh
- applications/ChatGPT/examples/train_dummy.py
- applications/ChatGPT/examples/train_prompts.py
- applications/ChatGPT/tests/test_data.py
>
Closes #2970 
Chatgpt inference (making experience) support DP.
> [chatgpt] making experience support dp

- applications/ChatGPT/chatgpt/nn/reward_model.py
- applications/ChatGPT/chatgpt/trainer/rm.py
- applications/ChatGPT/examples/train_reward_model.py
>
fix lora gemini conflict in RM training
> [chatgpt] fix lora gemini conflict in RM training

- op_builder/README.md
- op_builder/builder.py
- op_builder/utils.py
- setup.py
>
Fixed #2885 
This PR refactored the kernel builder module with the following changes:
1. moved all utility functions to the `utils.py`
2. added docstring for all utility functions
3. updated the readme
4. added caching for loaded kernel
5. added more error messages
> [kernel] cached the op kernel and fixed version check

- op_builder/utils.py
N/A
Prevents `TypeError: category must be a Warning subclass, not 'str'`.
> [misc] Remove extraneous comma

- README-zh-Hans.md
- README.md
- REFERENCE.md
- docs/source/en/concepts/paradigms_of_parallelism.md
- docs/source/en/features/nvme_offload.md
- docs/source/en/features/zero_with_chunk.md
- docs/source/zh-Hans/concepts/paradigms_of_parallelism.md
- docs/source/zh-Hans/features/nvme_offload.md
- docs/source/zh-Hans/features/zero_with_chunk.md
> [doc] added reference to related works

- README-zh-Hans.md
- README.md
- colossalai/nn/optimizer/README.md
- examples/tutorial/README.md
> [doc] add ISC tutorial

- applications/ChatGPT/chatgpt/nn/reward_model.py
- applications/ChatGPT/chatgpt/trainer/rm.py
- applications/ChatGPT/examples/README.md
- applications/ChatGPT/examples/inference.py
- applications/ChatGPT/examples/train_reward_model.py
>
fixed #2978 
fix bloom loading bug in inference demo
> [chatgpt]fix inference model load

- colossalai/tensor/d_tensor/layout.py
- colossalai/tensor/d_tensor/misc.py
- colossalai/tensor/d_tensor/sharding_spec.py
- tests/test_tensor/test_dtensor/test_dtensor.py
- tests/test_tensor/test_dtensor/test_sharding_spec.py
> [DTensor] refactor sharding spec

- tests/test_auto_parallel/test_ckpt_solvers/test_C_solver_consistency.py
- tests/test_auto_parallel/test_ckpt_solvers/test_ckpt_torchvision.py
- tests/test_auto_parallel/test_ckpt_solvers/test_linearize.py
- tests/test_tensor/test_dtensor/test_dtensor_sharding_spec.py
> [hotfix] skip auto checkpointing tests

- README-zh-Hans.md
- README.md
- docs/source/en/get_started/installation.md
- docs/source/zh-Hans/get_started/installation.md
- setup.py
>
Fixed #3018
This PR aims to make it clear that Windows is not supported yet to the user, some changes include:
1. Added OS check in `setup.py`
2. Added extra notes to README and documentation.
> [doc] specified operating system requirement

- examples/language/opt/run_gemini.sh
- examples/language/opt/train_gemini_opt.py
>
fixed #2758
This commit add an “shardinit” option in opt example to overcome OOM problem caused by naive model initialization.
> support shardinit option to avoid OPT OOM initializing problem

- examples/language/opt/train_gemini_opt.py
> [example] fix redundant note

- .github/workflows/doc_build_after_merge.yml
>
Fixed #3071 .
This PR fixed the name for the doc build workflow and updated the trigger condition.
> [workflow] fixed doc build trigger condition

- docs/README.md
>
Fixed #3081 
This PR fixed some typos in the `docs/READM.md` with the help of `ChatGPT` and `Grammarly`.
> [doc] fixed typos in docs/README.md

- examples/images/diffusion/README.md
- examples/images/diffusion/docker/Dockerfile
- examples/images/diffusion/test_ci.sh
>
- fix README
- fix docker file
- fix ci
> [diffusers] fix ci and docker

- applications/ChatGPT/chatgpt/models/base/actor.py
- applications/ChatGPT/chatgpt/models/base/critic.py
- applications/ChatGPT/chatgpt/models/bloom/bloom_critic.py
- applications/ChatGPT/chatgpt/models/gpt/gpt_critic.py
- applications/ChatGPT/chatgpt/models/opt/opt_critic.py
>
- add a choice for wether use action mask
> [chatgpt]add flag of action mask in critic

- examples/tutorial/fp8/mnist/README.md
- examples/tutorial/fp8/mnist/main.py
Adds a sample script to use the [TransformerEngine](https://github.com/NVIDIA/TransformerEngine) API for a simple classification task on the MNIST dataset with FP8 capability.
> [NVIDIA] Add FP8 example using TE

- examples/tutorial/fp8/mnist/README.md
> [tutorial] update notes for TransformerEngine

- applications/ChatGPT/chatgpt/models/lora.py
- applications/ChatGPT/chatgpt/trainer/strategies/colossalai.py
- applications/ChatGPT/chatgpt/trainer/strategies/ddp.py
>
fix the bug that we do not merge lora weight before save ckpt;
fix the bug that lora_eval has conflict with gemini 
> [chatgpt] fix lora save bug

- README-zh-Hans.md
- README.md
> [doc] add Intel cooperation for biomedicine

- applications/ChatGPT/chatgpt/models/opt/opt_critic.py
fix #3106
Rewrite kargs to kwargs
> [chatgpt] type miss of kwargs

- setup.py
Fixes https://github.com/hpcaitech/ColossalAI/issues/2874, please see my comments on this issue for rationale behind this PR.
Also, further context on the DeepSpeed side: https://github.com/microsoft/DeepSpeed/pull/2963, https://github.com/microsoft/DeepSpeed/issues/2904
Please see this PR for more context on the issue this PR attempts to solve: https://github.com/microsoft/DeepSpeed/pull/2963
Tagging @FrankLeeeee
> prevent op_builder being installed in site-pkgs

- applications/ChatGPT/chatgpt/models/gpt/gpt_actor.py
- applications/ChatGPT/chatgpt/models/gpt/gpt_critic.py
- applications/ChatGPT/chatgpt/models/opt/opt_critic.py
>
fix lora support for gpt
fix opt-critic typo
> [chatgpt] fix lora support for gpt

- applications/ChatGPT/examples/train_dummy.py
- applications/ChatGPT/examples/train_prompts.py
>
fixed #3076
fixed #3061 
fixed #3063 
fix train dummy
fix train prompt
support new ci & fixed inference bug
fix ckpt saving
> [chatgpt]Fix examples

- .github/workflows/run_chatgpt_examples.yml
- .github/workflows/run_chatgpt_unit_tests.yml
>
Fixed #3127 
This PR added a command to purge the extension cache before running the test. This is required as the outdated cache will result in the extension build hanging.
> [workflow] purged extension cache before GPT test

- docker/Dockerfile
Fixes #3005
This PR makes few changes to improve the overall quality of the docker image 🐳 . For reference more annotations can be found [here](https://github.com/opencontainers/image-spec/blob/main/annotations.md)
> [docker] Add opencontainers image-spec to `Dockerfile`

- tests/kit/model_zoo/__init__.py
- tests/kit/model_zoo/registry.py
- tests/kit/model_zoo/torchvision/__init__.py
- tests/kit/model_zoo/torchvision/torchvision.py
- tests/test_fx/test_tracer/test_torchvision_model/test_torchvision_model.py
>
part of efforts for #3049 
This PR added the `torchvision` models into the test model set.
> [test] added torchvision models to test model zoo
