hpcaitech/ColossalAI

- tests/kit/model_zoo/__init__.py
- tests/kit/model_zoo/transformers/__init__.py
- tests/kit/model_zoo/transformers/albert.py
- tests/kit/model_zoo/transformers/bert.py
- tests/kit/model_zoo/transformers/gpt.py
- tests/kit/model_zoo/transformers/opt.py
- tests/kit/model_zoo/transformers/t5.py
- tests/test_fx/test_tracer/test_hf_model/test_hf_albert.py
- tests/test_fx/test_tracer/test_hf_model/test_hf_bert.py
- tests/test_fx/test_tracer/test_hf_model/test_hf_gpt.py
- tests/test_fx/test_tracer/test_hf_model/test_hf_opt.py
- tests/test_fx/test_tracer/test_hf_model/test_hf_t5.py
>
part of efforts for #3049 
This PR added the `transformers` models into the test model set.
> [test] added transformers models to test model zoo

- applications/ChatGPT/chatgpt/trainer/ppo.py
>
Closes #3088 
Fix generate kwargs overwriting
> [chatgpt] fix trainer generate kwargs

- applications/ChatGPT/chatgpt/dataset/sft_dataset.py
- applications/ChatGPT/chatgpt/trainer/sft.py
> [chatgpt] unnify  datasets

- tests/test_fx/test_tracer/test_torchaudio_model/test_torchaudio_model.py
- tests/test_utils/test_lazy_init/test_distribute.py
> [hotfix] skip torchaudio tracing test

- requirements/requirements.txt
>
This PR prevents users from installing torch 2.x when running `pip install .`
https://github.com/hpcaitech/ColossalAI/issues/2802
> [hotfix] limit torch version

- colossalai/nn/_ops/_utils.py
> [NFC] polish code style

- colossalai/fx/proxy.py
> [NFC] policy colossalai/fx/proxy.py code style

- colossalai/amp/__init__.py
> [NFC] polish colossalai/amp/__init__.py code style

- colossalai/context/parallel_context.py
> [NFC] polish colossalai/context/parallel_context.py code style

- applications/Chat/README.md
> add cite for datasets

- colossalai/cli/benchmark/models.py
> [NFC] polish colossalai/cli/benchmark/models.py code style

- colossalai/context/process_group_initializer/initializer_data.py
> [NFC] polish initializer_data.py code style

- applications/Chat/examples/README.md
- applications/Chat/examples/train_prompts.py
>
polish prompts training in chat
> [chat]polish prompts training

- README.md
- applications/Chat/README.md
- docs/README-zh-Hans.md
> [doc] add ColossalChat news

- applications/Chat/README.md
> [chat] polish readme link

- applications/Chat/README.md
> add authors

- README.md
- docs/README-zh-Hans.md
> [doc] add Intel cooperation news

- colossalai/fx/_compatibility.py
- colossalai/fx/profiler/opcount.py
> [hotfix] meta_tensor_compatibility_with_torch2

- applications/Chat/README.md
fixed #3337 
correcting a few obvious typos and grammars errors in the README of Chat to improve the readability. 
The last two are not applicable. The check mark is to meet the requirement. 
> [chat] correcting a few obvious typos and grammars errors

- colossalai/context/random/__init__.py
> [NFC] polish colossalai/context/random/__init__.py code style

- colossalai/engine/gradient_handler/__init__.py
> [NFC] polish colossalai/engine/gradient_handler/__init__.py code style

- requirements/requirements.txt
Make requirement file compatible with pytorch 2.0
> [hotfix] fix torch 2.0 compatibility in installation denpendencies

- examples/images/diffusion/README.md
- Changes to the "Step 3" (XFormers) section: rewording, fixed badly formatted URL ;
- Misc (minor) typo, grammar and formatting fixes based on a diagonal reading.
> [doc] polish diffusion example

- applications/Chat/coati/models/bloom/bloom_lm.py
- applications/Chat/coati/models/gpt/gpt_lm.py
- applications/Chat/coati/models/opt/opt_lm.py
#3355 
Add forward function in bloom_lm, gpt_lm and opt_lm to support sft training.
> [Coati] fix sft training for bloom, gpt and opt

- applications/Chat/coati/trainer/ppo.py
>
fixed #3446 
Fix save_model indent error in ppo trainer
> [Chat] fix save_model indent error in ppo trainer

- applications/Chat/examples/train_prompts.sh
> [coati] fix stage3 PPO sample sh command

- examples/images/diffusion/configs/Teyvat/train_colossalai_teyvat.yaml
- examples/images/diffusion/configs/train_colossalai.yaml
- examples/images/diffusion/configs/train_colossalai_cifar10.yaml
- examples/images/diffusion/configs/train_ddp.yaml
- examples/images/diffusion/ldm/models/autoencoder.py
- examples/images/diffusion/ldm/models/diffusion/classifier.py
- examples/images/diffusion/ldm/models/diffusion/ddpm.py
- examples/images/diffusion/main.py
- examples/images/diffusion/scripts/img2img.py
- examples/images/diffusion/scripts/inpaint.py
- examples/images/diffusion/scripts/knn2img.py
- examples/images/diffusion/scripts/sample_diffusion.py
- examples/images/diffusion/scripts/tests/test_checkpoint.py
- examples/images/diffusion/scripts/txt2img.py
Reverts hpcaitech/ColossalAI#3378
The code needs further feedback, test, and suggestions.
> Revert "[WIP] polish code style of stable diffusion example"

- README.md
- applications/README.md
- docs/README-zh-Hans.md
- docs/source/en/get_started/installation.md
- docs/source/zh-Hans/get_started/installation.md
- examples/README.md
> [doc] add requirement and highlight application

- applications/README.md
>
It's easy for users to think that we don't support them yet. Add them after migrating them from example to application
https://github.com/hpcaitech/ColossalAI/tree/main/examples/images
> [doc] hide diffusion in application path

- applications/Chat/examples/train_sft.py
>
Add zero2 with cpu offloading strategy for sft training.
> [chat] add zero2 cpu strategy for sft training

- examples/images/diffusion/configs/Inference/v2-inference-v.yaml
- examples/images/diffusion/configs/Inference/v2-inference.yaml
- examples/images/diffusion/configs/Inference/v2-inpainting-inference.yaml
- examples/images/diffusion/configs/Inference/v2-midas-inference.yaml
- examples/images/diffusion/configs/Inference/x4-upscaling.yaml
- examples/images/diffusion/configs/Teyvat/train_colossalai_teyvat.yaml
- examples/images/diffusion/configs/train_colossalai.yaml
- examples/images/diffusion/configs/train_colossalai_cifar10.yaml
- examples/images/diffusion/configs/train_ddp.yaml
- examples/images/diffusion/ldm/models/autoencoder.py
- examples/images/diffusion/ldm/models/diffusion/classifier.py
- examples/images/diffusion/ldm/models/diffusion/ddpm.py
- examples/images/diffusion/main.py
- examples/images/diffusion/scripts/tests/test_checkpoint.py
- examples/images/diffusion/train_colossalai.sh
> [WIP] Diffusion Code Polishment

- colossalai/utils/model/experimental.py
>
1. LazyTensor supports deepcopy
2. Fix clone for LazyTensor. As the source lazy tensor may be materialized before the cloned tensor, the source tensor cannot be materialized twice. We should check the type of source tensor.
> [lazyinit] fix clone and deepcopy

- applications/Chat/examples/train_rm.sh
> [chat] fix reward model sh

- .github/workflows/run_chatgpt_examples.yml
- applications/Chat/coati/models/gpt/gpt_actor.py
- applications/Chat/coati/models/gpt/gpt_critic.py
- applications/Chat/examples/test_ci.sh
> [chat]chat update ci

- applications/Chat/README.md
> [coati] fix install cmd

- applications/Chat/README.md
- applications/Chat/evaluate/README.md
- applications/Chat/evaluate/evaluate.py
- applications/Chat/evaluate/evaluate.sh
- applications/Chat/evaluate/format_questions.py
- applications/Chat/evaluate/format_questions.sh
- applications/Chat/evaluate/generate_answers.py
- applications/Chat/evaluate/generate_answers.sh
- applications/Chat/evaluate/generate_gpt35_answers.py
- applications/Chat/evaluate/generate_gpt35_answers.sh
- applications/Chat/evaluate/merge.py
- applications/Chat/evaluate/utils.py
>
Add evaluate feature for Chat application.
> [Chat] Add evaluate feature for Chat application

- applications/Chat/coati/experience_maker/base.py
- applications/Chat/coati/models/lora.py
- applications/Chat/coati/ray/src/detached_trainer_ppo.py
- applications/Chat/coati/ray/src/experience_maker_holder.py
- applications/Chat/coati/replay_buffer/utils.py
- applications/Chat/coati/trainer/callbacks/performance_evaluator.py
- applications/Chat/coati/trainer/ppo.py
- applications/Chat/examples/README.md
- applications/Chat/examples/community/peft/README.md
- applications/Chat/examples/community/peft/easy_dataset.py
Not involved
Optimization Code some spelling errors were corrected
please check my fix is right.
> Optimization Code some spelling errors were corrected

- .github/workflows/run_chatgpt_examples.yml
- .github/workflows/run_chatgpt_unit_tests.yml
>
1. Fix chat CI paths
2. Fix chat CI condition
> [devops] fix chat ci

- applications/Chat/coati/trainer/ppo.py
> [proposal#3624](https://github.com/hpcaitech/ColossalAI/issues/3624)
Remove duplicate functions that exist within ppo.py
> Del: Remove duplicate functions

- applications/Chat/examples/README.md
- applications/Chat/examples/test_ci.sh
- applications/Chat/examples/train_prompts.py
- applications/Chat/examples/train_prompts.sh
>
fixed #3643
Add explanation for pretrain dataset and instruction.
> [Doc] enhancement on README.md for chat examples

- applications/Chat/evaluate/evaluate.py
- applications/Chat/evaluate/generate_gpt35_answers.py
Not involved
fix spelling error with applications/Chat/evaluate/evaluate.py
and 
applications/Chat/evaluate/generate_gpt35_answers.py
> fix spelling error with applications/Chat/evaluate/

- examples/tutorial/new_api/glue_bert/README.md
- examples/tutorial/new_api/glue_bert/data.py
- examples/tutorial/new_api/glue_bert/finetune.py
- examples/tutorial/new_api/glue_bert/test_ci.sh
>
Add finetune bert with booster example.
> [example] add finetune bert with booster example

- colossalai/tensor/dist_spec_mgr.py
> N/A
This commit refactors the `handle_trans_spec` method in the `DistSpecManager` class to improve code readability and maintainability. 
Changes made:
1. Replaced the string concatenation method for selecting forward and backward transformation handles with a dictionary lookup. 
- Previously, the code used string concatenation and `getattr` to dynamically call the appropriate transformation function. This approach was less readable and could lead to potential errors if the transformation function names were changed or if new functions were added.
- Added a dictionary `trans_funcs` that maps tuples of old and new distributed specification placements to the corresponding transformation functions (`_r2r`, `_r2s`, `_s2r`, `_s2s`).
- Used the dictionary to look up the appropriate forward …
> [tensor] Refactor handle_trans_spec in DistSpecManager

- examples/language/gpt/experiments/auto_parallel/README.md
> [auto] fix install cmd

- .github/workflows/doc_test_on_pr.yml
> [devops] fix doc test on pr

- docs/source/en/basics/colotensor_concept.md
- docs/source/en/basics/configure_parallelization.md
- docs/source/en/basics/define_your_config.md
- docs/source/en/basics/engine_trainer.md
- docs/source/en/basics/initialize_features.md
- docs/source/en/basics/model_checkpoint.md
- docs/source/zh-Hans/basics/colotensor_concept.md
- docs/source/zh-Hans/basics/configure_parallelization.md
- docs/source/zh-Hans/basics/define_your_config.md
- docs/source/zh-Hans/basics/engine_trainer.md
- docs/source/zh-Hans/basics/initialize_features.md
- docs/source/zh-Hans/basics/model_checkpoint.md
>
add deprecated warnings on Basic section markdown documents
add recommended pages for reader to access updated info (pages will be created later)
> [doc] add deprecated warning on doc Basics section

- docs/sidebars.json
- docs/source/en/features/gradient_clipping.md
- docs/source/en/features/gradient_clipping_with_booster.md
- docs/source/zh-Hans/features/gradient_clipping.md
- docs/source/zh-Hans/features/gradient_clipping_with_booster.md
>
#3730
update gradient clipping document.
> [doc] update gradient cliping document

- colossalai/booster/booster.py
>
Fixed #3796 
Refactored the booster API for markdown formatting.
> fixed the example docstring for booster

- applications/Chat/evaluate/eval.py
- applications/Chat/evaluate/evaluator.py
- applications/Chat/evaluate/metrics.py
- applications/Chat/requirements.txt
>
#3714 
**Add/Modify files:
eval.py 
evaluator.py
metrics.py
requirements.txt**
> [evaluation] add add function for automatic evaluation

- .github/workflows/doc_build_after_merge.yml
>
Fixed #3814 
Change the event trigger to allow for doc build for PRs from forked repos.
> [workflow] enblaed doc build from a forked repo

- applications/Chat/evaluate/README.md
> [evaluate] update readme.md for evaluation pipeline

- applications/Chat/evaluate/config/config_cn.json
> [evaluate] remove GPT-4 config

- applications/Chat/evaluate/sample/questions.json
> [evaluate] remove sample folder

- colossalai/elixir/wrapper/module.py
- colossalai/elixir/wrapper/optimizer.py
> [elixir] update buffer size calculation

- colossalai/cli/launcher/run.py
>
Modify torch version requirement to adapt torch 2.0
> [hotfix] Modify torch version requirement to adapt torch 2.0

- .github/workflows/build_on_pr.yml
>
Testmon cache for each PR should be deleted when the PR is closed, no matter whether it's merged. This PR fix this problem
> [devops] hotfix testmon cache clean logic

- .github/workflows/release_docker_after_publish.yml
>
Fixed #3560 
This PR added the docker latest tag to publish to Docker hub.
> [workflow] added docker latest tag for release

- docs/sidebars.json
- docs/source/en/features/lazy_init.md
- docs/source/zh-Hans/features/lazy_init.md
>
Add tutorial about lazy initialization for both English and Chinese.
> [doc] add lazy init tutorial

- colossalai/elixir/README.md
- colossalai/elixir/__init__.py
>
closes #3945 
This PR polished the readme for the `Elixir` module.
> [elixir] updated readme

- .github/workflows/build_on_pr.yml
>
Fixed #3981 .
This PR fixed the bash if then code to avoid exit code 1 if the condition is false.
> [workflow] fixed the directory check in build

- colossalai/shardformer/layer/dist_crossentropy.py
- colossalai/shardformer/policies/autopolicy.py
- colossalai/shardformer/policies/llama.py
- tests/test_shardformer/test_model/test_shard_llama.py
>
> Support llama model using colossalai shardformer script.
> [shardformer] support llama model using shardformer

- colossalai/tensor/d_tensor/RAEDME.md
> [shardformer] fix an error in readme

- applications/Chat/coati/ray/experience_maker_holder.py
- applications/Chat/coati/ray/lora_constructor.py
- applications/Chat/coati/trainer/strategies/colossalai.py
Not involved
fix typo applications/Chat/coati/
modified:   applications/Chat/coati/ray/experience_maker_holder.py
modified:   applications/Chat/coati/ray/lora_constructor.py
modified:   applications/Chat/coati/trainer/strategies/colossalai.py
Make code easier to read
> [nfc] fix typo applications/Chat/coati/

- colossalai/shardformer/README.md
>
N/A
This PR updated the documentation of the `shardformer` module.
> [shardformer] updated doc

- tests/test_checkpoint_io/test_general_checkpoint_io.py
>
N/A, only fix format
This PR fixed the codefactor format report via `pre-commit`.
> [test] fixed codefactor format report

- examples/language/gpt/gemini/train_gpt_demo.py
>
fixed #4027 
This PR fixes a typo in gpt gemini example.
And I have examined all other usages of `low level zero`.
> [example] fix bucket size in example of gpt gemini

- .github/workflows/build_on_pr.yml
>
Closes #4042 
Fix syntax error and bugs
> [devops] fix build on pr ci

- colossalai/cluster/__init__.py
- colossalai/cluster/process_group_mesh.py
- tests/test_cluster/test_process_group_mesh.py
>
Closes #4038 
Add process group mesh class and corresponding unit test.
> [cluster] add process group mesh

- .github/workflows/scripts/generate_leaderboard_and_send_to_lark.py
>
N/A
This PR extends weekly report to all public repositories.
> [workflow] cover all public repositories in weekly report

- .github/workflows/report_test_coverage.yml
>
N/A
This PR added the status check for the `Build on PR` workflow to the test coverage report workflow to ensure only successful build will produce the coverage report.
> [workflow] added status check for test coverage workflow

- examples/language/gpt/titans/train_gpt.py
> fix #3852 path error

- docs/source/en/advanced_tutorials/meet_gemini.md
- docs/source/zh-Hans/advanced_tutorials/train_vit_with_hybrid_parallelism.md
- docs/source/zh-Hans/features/mixed_precision_training.md
- docs/source/zh-Hans/features/mixed_precision_training_with_booster.md
Not involved
fix typo docs/
detail info 
modified:   docs/source/en/advanced_tutorials/meet_gemini.md
modified:   docs/source/zh-Hans/advanced_tutorials/train_vit_with_hybrid_parallelism.md
modified:   docs/source/zh-Hans/features/mixed_precision_training.md
modified:   docs/source/zh-Hans/features/mixed_precision_training_with_booster.md
> [nfc] fix typo docs/

- colossalai/engine/_base_engine.py
Not involved
[nfc] fix  ColossalaiOptimizer is not defined
modified:   colossalai/engine/_base_engine.py
Before adjustment
> [nfc] fix  ColossalaiOptimizer is not defined

- colossalai/kernel/jit/bias_dropout_add.py
Not involved
fix Tensor is not defined
modified:   colossalai/kernel/jit/bias_dropout_add.py
Before adjustment
please check 
> [nfc] fix Tensor is not defined

- colossalai/shardformer/layer/embedding.py
- colossalai/shardformer/policies/basepolicy.py
- colossalai/shardformer/policies/bert.py
- colossalai/shardformer/policies/bloom.py
- colossalai/shardformer/policies/gpt2.py
- colossalai/shardformer/policies/llama.py
- colossalai/shardformer/policies/opt.py
- colossalai/shardformer/policies/t5.py
- colossalai/shardformer/shard/shard_config.py
- tests/test_shardformer/test_model/_utils.py
- tests/test_shardformer/test_model/test_shard_bert.py
- tests/test_shardformer/test_model/test_shard_bloom.py
- tests/test_shardformer/test_model/test_shard_gpt2.py
- tests/test_shardformer/test_model/test_shard_llama.py
- tests/test_shardformer/test_model/test_shard_opt.py
- tests/test_shardformer/test_model/test_shard_t5.py
>
Fixed #4143
This PR made tensor parallelism optional so that for small models, we can basically use other optimizations without the need for parallelization.
> [shardformer] made tensor parallelism configurable

- colossalai/cli/launcher/run.py
>
Closes #4164 
Fix launch command
> [cli] hotfix launch command for multi-nodes

- colossalai/_analyzer/fx/codegen.py
- colossalai/auto_parallel/checkpoint/ckpt_solver_base.py
- colossalai/auto_parallel/checkpoint/ckpt_solver_rotor.py
- colossalai/auto_parallel/passes/meta_info_prop.py
- colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py
- colossalai/auto_parallel/tensor_shard/solver/strategies_constructor.py
- tests/test_auto_parallel/test_tensor_shard/test_2stage_solver.py
- tests/test_auto_parallel/test_tensor_shard/test_2stage_solver_on_gpt.py
- tests/test_auto_parallel/test_tensor_shard/test_2stage_solver_on_resnet.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bias_linear_function_node.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bias_linear_module_node.py
- tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_getitem_handler.py
> [autoparallel] integrate 2-stage solver

- docker/Dockerfile
>
N/A
This PR added support for password less SSH and RDMA to our Docker image.
> [docker] added ssh and rdma support for docker

- examples/language/llama/README.md
- examples/language/llama/benchmark.py
- examples/language/llama/pretrain.py
> [example] polish code and readme of llama

- examples/language/llama/README.md
> modify readme

- colossalai/shardformer/policies/gpt2.py
- tests/test_shardformer/test_model/test_shard_gpt2.py
- tests/test_shardformer/test_model/test_shard_gpt2_pipeline.py
>
#4200
- Support pipeline forward for transformers.GPT2LMHeadModel
- Support pipeline forward for transformers.GPT2ForTokenClassification
- Support pipeline forward for transformers.GPT2ForSequenceClassification
- Refactoring module_policy/get_held_layers methods in gpt2 policy
-  Add relevant tests
> [pipeline] add pipeline forward for variants of gpt2

- examples/language/llama/README.md
> [example] add llama benchmark

- README.md
- docs/README-zh-Hans.md
- examples/language/llama/README.md
> [news] add llama pretraining

- applications/Chat/coati/models/base/actor.py
> [NFC] polish applications/Chat/coati/models/base/actor.py code style

- applications/Chat/examples/ray/mmmt_prompt.py
> [NFC] policy applications/Chat/examples/ray/mmmt_prompt.py code style

- applications/Chat/coati/dataset/sft_dataset.py
> [NFC] polish applications/Chat/coati/dataset/sft_dataset.py code style

- colossalai/auto_parallel/tensor_shard/node_handler/strategy/unary_elementwise_generator.py
> [NFC] polish unary_elementwise_generator.py code style

- colossalai/auto_parallel/passes/runtime_preparation_pass.py
> [NFC] polish runtime_preparation_pass style

- applications/Chat/examples/train_reward_model.py
> [NFC] polish applications/Chat/examples/train_reward_model.py code style

- applications/Chat/coati/trainer/utils.py
> [nfc] fix format of application/Chat/coati/trainer/utils.py

- colossalai/booster/plugin/gemini_plugin.py
- colossalai/tensor/process_group.py
- colossalai/zero/gemini/chunk/chunk.py
- colossalai/zero/gemini/chunk/search_utils.py
- colossalai/zero/gemini/chunk/utils.py
- colossalai/zero/gemini/gemini_ddp.py
- examples/language/llama/benchmark.py
>
Support hierarchical Gemini which combines zero-3 and naive ddp.
> [gemini] support gemini-dp

- colossalai/shardformer/layer/__init__.py
- colossalai/shardformer/layer/embedding.py
- colossalai/shardformer/layer/linear.py
- colossalai/shardformer/layer/normalization.py
- colossalai/shardformer/layer/qkv_fused_linear.py
- colossalai/shardformer/policies/bert.py
- colossalai/shardformer/policies/bloom.py
- colossalai/shardformer/policies/gpt2.py
- colossalai/shardformer/policies/llama.py
- colossalai/shardformer/policies/opt.py
- colossalai/shardformer/policies/t5.py
- colossalai/shardformer/shard/sharder.py
- colossalai/tensor/d_tensor/api.py
- requirements/requirements-test.txt
- tests/kit/model_zoo/torchrec/__init__.py
- tests/test_shardformer/test_layer/test_embedding.py
- tests/test_shardformer/test_layer/test_layernorm.py
- tests/test_shardformer/test_layer/test_linear_1d.py
- tests/test_shardformer/test_layer/test_qkv_fused_linear_1d.py
- tests/test_shardformer/test_layer/test_vocab_parallel_embedding_1d.py
- tests/test_shardformer/test_model/_utils.py
- tests/test_shardformer/test_model/test_shard_bert.py
- tests/test_shardformer/test_model/test_shard_bloom.py
- tests/test_shardformer/test_model/test_shard_gpt2.py
- tests/test_shardformer/test_model/test_shard_llama.py
- tests/test_shardformer/test_model/test_shard_opt.py
- tests/test_shardformer/test_model/test_shard_t5.py
>
Closes #4249 
1. Support inplace sharding
2. Update policies
3. Fix unit test and check model checkpoint
> [shardformer] support inplace sharding

- requirements/requirements-test.txt
> [feature/zero] fix zero branch transformers version for CI

- examples/language/llama/attn.py
- examples/language/llama/benchmark.py
> [example] support flash attn 2 for llama

- colossalai/shardformer/README.md
- colossalai/shardformer/_utils.py
- colossalai/shardformer/layer/__init__.py
- colossalai/shardformer/layer/embedding.py
- colossalai/shardformer/layer/qkv_fused_linear.py
- colossalai/shardformer/modeling/sam.py
- colossalai/shardformer/policies/autopolicy.py
- colossalai/shardformer/policies/chatglm.py
- colossalai/shardformer/policies/sam.py
- colossalai/shardformer/policies/vit.py
- colossalai/shardformer/policies/whisper.py
- tests/kit/model_zoo/transformers/__init__.py
- tests/kit/model_zoo/transformers/chatglm.py
- tests/kit/model_zoo/transformers/chatglm2_6b/configuration_chatglm.py
- tests/kit/model_zoo/transformers/chatglm2_6b/modeling_chatglm.py
- tests/kit/model_zoo/transformers/sam.py
- tests/kit/model_zoo/transformers/vit.py
- tests/kit/model_zoo/transformers/whisper.py
- tests/test_shardformer/test_layer/test_gpt2_qkv_fused_linear_1d.py
- tests/test_shardformer/test_layer/test_qkv_fused_linear_1d.py
- tests/test_shardformer/test_model/test_shard_chatglm.py
- tests/test_shardformer/test_model/test_shard_sam.py
- tests/test_shardformer/test_model/test_shard_vit.py
- tests/test_shardformer/test_model/test_shard_whisper.py
>
merge feature/shardformer-models branch to  feature/flash-attention-shardformer branch
> [shardformer] merge feature/shardformer-models branch to feature/flash-attention-shardformer branch.

- .github/workflows/build_on_pr.yml
> [ci] support testmon core pkg change detection

- colossalai/shardformer/modeling/t5.py
- colossalai/shardformer/policies/t5.py
- tests/test_shardformer/test_model/test_shard_t5_pipeline.py
>
closed #4247
- rewrite policies and pipeline forward methods for T5Model and T5ForConditionalGeneration
> [pipeline] add pipeline support for all T5 models

- tests/test_booster/test_plugin/test_gemini_plugin.py
- tests/test_booster/test_plugin/test_low_level_zero_plugin.py
- tests/test_lazy/test_distribute.py
- tests/test_lazy/test_models.py
- tests/test_shardformer/test_model/test_pure_pipeline.py
> [hotfix] fix gemini and zero test

- colossalai/shardformer/modeling/bert.py
- colossalai/shardformer/modeling/bloom.py
- colossalai/shardformer/modeling/gpt2.py
- colossalai/shardformer/policies/opt.py
- tests/test_shardformer/test_model/test_pure_pipeline.py
>
- fix the misconfiguration of setting return_dict to False in bert.py and bloom.py under shardformer/modeling
- fix import warning in opt.py
- fix test_pure_pipeline test in test_shardformer
> [pipeline] fix return_dict & fix pure_pipeline_test

- examples/language/llama/benchmark.py
>
#439 
Fix the llama example benchmark, 3D-CPU parallelism doesn't enable offload.
> [example]fix llama example benchmark

- requirements/requirements-test.txt
- tests/test_pipeline/test_schedule/test_oneF_oneB.py
>
Add a unit test for 1F1B schedule.
> [pipeline] add unit test for 1f1b

- applications/Chat/coati/models/utils.py
> [chat] fix compute_approx_kl

- colossalai/zero/gemini/gemini_optimizer.py
>
#4393
- fix the bug mentioned in #4393
- remove unnecessary garbage collection 
> [gemini] fix tensor storage cleaning in state dict collection

- colossalai/booster/plugin/gemini_plugin.py
- colossalai/zero/__init__.py
- colossalai/zero/gemini/__init__.py
- colossalai/zero/gemini/gemini_ddp.py
- colossalai/zero/gemini/gemini_optimizer.py
- colossalai/zero/gemini/memory_tracer/memory_stats.py
- colossalai/zero/gemini/utils.py
- colossalai/zero/wrapper.py
- examples/community/roberta/pretraining/run_pretraining.py
- examples/language/palm/train.py
- examples/tutorial/opt/opt/requirements.txt
- examples/tutorial/opt/opt/run_clm.py
- tests/test_checkpoint_io/test_gemini_checkpoint_io.py
- tests/test_checkpoint_io/test_gemini_torch_compability.py
- tests/test_zero/test_gemini/test_fwd_bwd.py
- tests/test_zero/test_gemini/test_gemini_use_rmt.py
- tests/test_zero/test_gemini/test_grad_clip.py
- tests/test_zero/test_gemini/test_inference.py
- tests/test_zero/test_gemini/test_optim.py
- tests/test_zero/test_gemini/test_zeroddp_state_dict.py
- tests/test_zero/test_gemini/test_zeroddp_state_dict_shard.py
- tests/test_zero/test_gemini/test_zerooptim_state_dict.py
>
1. Replace ZeroDDP with GeminiDDP to make the naming and inheritance relationship clearer.
2. Make GeminiOptimizer inherit optimizer wrapper.
> [gemini] refactor gemini optimizer and gemini ddp

- tests/test_shardformer/test_model/test_shard_bloom.py
- tests/test_shardformer/test_model/test_shard_chatglm.py
- tests/test_shardformer/test_model/test_shard_gpt2.py
- tests/test_shardformer/test_model/test_shard_llama.py
- tests/test_shardformer/test_model/test_shard_opt.py
- tests/test_shardformer/test_model/test_shard_vit.py
>
#4406 
update bloom/llama/vit/chatglm tests for checking all optimizations.
> [shardformer] update bloom/llama/vit/chatglm tests for checking all optimizations.

- colossalai/booster/plugin/hybrid_parallel_plugin.py
- tests/test_shardformer/test_model/_utils.py
- tests/test_shardformer/test_model/test_shard_bert.py
- tests/test_shardformer/test_model/test_shard_bloom.py
- tests/test_shardformer/test_model/test_shard_chatglm.py
- tests/test_shardformer/test_model/test_shard_gpt2.py
- tests/test_shardformer/test_model/test_shard_llama.py
- tests/test_shardformer/test_model/test_shard_opt.py
- tests/test_shardformer/test_model/test_shard_t5.py
- tests/test_shardformer/test_model/test_shard_vit.py
>
closed #4422
- Support tp+dp for shardformer models, where dp is optimized using ddp
- Add relevant tests
> [shardformer] support DDP in HybridPlugin/add tp+dp tests

- .github/workflows/build_on_pr.yml
- .github/workflows/compatiblity_test_on_dispatch.yml
- .github/workflows/compatiblity_test_on_pr.yml
- .github/workflows/compatiblity_test_on_schedule.yml
- applications/Chat/tests/test_dataset.py
- applications/Chat/tests/test_models.py
- pytest.ini
- tests/test_config/test_load_config.py
- tests/test_context/test_hybrid_parallel.py
- tests/test_data/test_cifar10_dataset.py
- tests/test_data/test_data_parallel_sampler.py
- tests/test_data/test_deterministic_dataloader.py
- tests/test_utils/test_activation_checkpointing.py
>
Closes #4451 
Update pytest markers and ci
> [devops] add large-scale distributed test marker

- docs/source/en/features/zero_with_chunk.md
- docs/source/zh-Hans/features/zero_with_chunk.md
>
Update the document of gemini.
> [doc] update gemini doc

- examples/tutorial/opt/opt/run_clm.py
- examples/tutorial/opt/opt/test_ci.sh
> [hotfix] fix opt tutorial example

- colossalai/zero/low_level/bookkeeping/gradient_store.py
- colossalai/zero/low_level/low_level_optim.py
- colossalai/zero/low_level/readme.md
- tests/test_zero/test_low_level/test_grad_acc.py
>
fixed #4510 
This PR support gradient accumulation when using zero2
> [zero]support zero2 with gradient accumulation

- .github/workflows/run_chatgpt_examples.yml
- .github/workflows/run_chatgpt_unit_tests.yml
> [coati] update ci

- colossalai/inference/tensor_parallel/modeling/llama.py
> [code-refactor]change coding style

- colossalai/inference/tensor_parallel/modeling/bloom.py
- colossalai/inference/tensor_parallel/modeling/llama.py
> [infer]Fix bugs in llama and bloom

- colossalai/booster/plugin/low_level_zero_plugin.py
- colossalai/checkpoint_io/general_checkpoint_io.py
- colossalai/checkpoint_io/utils.py
- colossalai/zero/low_level/low_level_optim.py
>
1. Hoffix memory leak problem of zero optim checkpoint io.
2. Refactor load_sharded_optimizer method of zero plugin to reduce peak memory usage.
3. Add map location when loading checkpoint, which can save cuda memory usage and avoid potential momory leak.
> [checkpointio] optimize zero optim checkpoint io

- README.md
- docs/README-zh-Hans.md
> [DOC] hotfix/llama2news

- tests/test_shardformer/test_model/test_shard_gpt2.py
>
This test will hang in CI. Temporarily skip it.
> [test] ignore gpt2 shardformer test

- examples/inference/bench_bloom.py
> [bench] revise bloom benchmark

- colossalai/shardformer/modeling/gpt2.py
- colossalai/shardformer/modeling/vit.py
- examples/images/vit/README.md
- examples/images/vit/args.py
- examples/images/vit/data.py
- examples/images/vit/run_benchmark.sh
- examples/images/vit/run_demo.sh
- examples/images/vit/test_ci.sh
- examples/images/vit/vit_benchmark.py
- examples/images/vit/vit_train_demo.py
>
- update vit example for hybrid parallel plugin, including benchmark, demo and test_ci
> [example] update vit example for hybrid parallel plugin

- .github/workflows/compatiblity_test_on_pr.yml
- .github/workflows/example_check_on_pr.yml
>
For jobs using matrix, its concurrency group should contains its matrix identifier, otherwise they will cancel each other.
> [devops] fix concurrency group

- docs/source/en/features/shardformer.md
- docs/source/zh-Hans/features/shardformer.md
>
update seq parallel document
> [shardformer] update seq parallel document

- docs/sidebars.json
> [doc] add shardformer doc to sidebar

- examples/tutorial/new_api/cifar_resnet/train.py
- examples/tutorial/new_api/cifar_vit/train.py
- examples/tutorial/new_api/glue_bert/finetune.py
- examples/tutorial/new_api/glue_bert/test_ci.sh
> [fix] fix weekly runing example

- colossalai/booster/plugin/gemini_plugin.py
- colossalai/booster/plugin/hybrid_parallel_plugin.py
- colossalai/booster/plugin/low_level_zero_plugin.py
- colossalai/booster/plugin/torch_ddp_plugin.py
- colossalai/booster/plugin/torch_fsdp_plugin.py
- colossalai/cluster/dist_coordinator.py
- docs/source/en/features/shardformer.md
- docs/source/zh-Hans/features/shardformer.md
>
- fix format of docstring example codes
- improve the importing of ChatGLM
- polish shardformer document
> [doc] polish shardformer doc

- applications/Colossal-LLaMA-2/README.md
> [doc] Update TODO in README of Colossal-LLaMA-2

- colossalai/nn/lr_scheduler/cosine.py
add last_epoch in CosineAnnealingWarmupLR
> add last_epoch in CosineAnnealingWarmupLR

- tests/test_gptq/test_gptq_linear.py
> [NFC] polish tests/test_gptq/test_gptq_linear.py code style

- colossalai/inference/tensor_parallel/engine.py
>
Fixed embedding calculation error caused by input data type, tokenizer type related bug, and code formatting issues.
> [infer]Fixed embedding calculation error caused by input data type, tokenizer type related bug, and code formatting issues.

- colossalai/kernel/triton/custom_autotune.py
- colossalai/kernel/triton/gptq_triton.py
>
- Add autotune for gptq kernel. 
- Avoid import gptq kernel  to require auto_gptq 
> [infer] add autotune for gptq kernel

- applications/Chat/examples/requirements.txt
- applications/Chat/requirements-test.txt
- applications/Chat/requirements.txt
> [fix]downgrade colossalai

- colossalai/kernel/cuda_native/csrc/smoothquant/binding.cpp
- colossalai/kernel/cuda_native/csrc/smoothquant/linear.cu
- colossalai/kernel/cuda_native/csrc/smoothquant/linear.h
- op_builder/smoothquant.py
- tests/test_smoothquant/test_smoothquant_linear.py
>
- add silu linear fusion for smoothquant llama mlp 
> [inference] add silu linear fusion for smoothquant llama mlp 

- colossalai/booster/plugin/low_level_zero_plugin.py
>
fixed #4857 
Fix a typo in document of booster low_level_zero plugin
> [doc]: typo in document of booster low_level_zero plugin

- examples/language/palm/README.md
> Minor typo in README

- README.md
- applications/Colossal-LLaMA-2/README.md
> Update modelscope link in README.md

- tests/test_infer/test_llama_infer.py
>
- Fix test bug for llama inference
> [Bug fix] fix test llama for inference

- colossalai/nn/optimizer/cpu_adam.py
> [doc] add reminder for issue encountered with hybrid adam

- colossalai/kernel/cuda_native/csrc/cpu_adam.cpp
- colossalai/kernel/cuda_native/csrc/cpu_adam.h
- colossalai/nn/optimizer/cpu_adam.py
- colossalai/nn/optimizer/hybrid_adam.py
- tests/test_optimizer/test_adam_kernel.py
- tests/test_optimizer/test_adam_optim.py
>
support pure fp16 for cpu adam
> [kernel] support pure fp16 for cpu adam

- colossalai/kernel/cuda_native/csrc/cpu_adam.cpp
- colossalai/kernel/cuda_native/csrc/cpu_adam.h
- tests/test_zero/test_gemini/test_grad_clip.py
- tests/test_zero/test_gemini/test_optim.py
> [kernel] fix cpu adam kernel for pure fp16 and update tests

- colossalai/inference/continous_batching/layers/attention.py
> [infer]Add ”adapted from“ annotation

- colossalai/booster/plugin/gemini_plugin.py
- colossalai/booster/plugin/low_level_zero_plugin.py
- colossalai/zero/gemini/chunk/chunk.py
- colossalai/zero/gemini/chunk/manager.py
- colossalai/zero/gemini/gemini_ddp.py
- colossalai/zero/gemini/gemini_optimizer.py
- docs/source/en/features/gradient_accumulation_with_booster.md
- docs/source/zh-Hans/features/gradient_accumulation_with_booster.md
- tests/components_to_test/bert.py
- tests/test_booster/test_plugin/test_low_level_zero_plugin.py
- tests/test_zero/test_gemini/test_grad_accum.py
>
resolved #4806
relevant issues include: #4590, #4719, #4785
support gradient accumulation for gemini and add relevant test
> [gemini] support gradient accumulation

- colossalai/inference/README.md
- colossalai/shardformer/README.md
- docs/source/en/basics/booster_plugins.md
Not involved
[nfc] fix some typo with colossalai/ docs/ etc.
> [nfc] fix some typo with colossalai/ docs/ etc.

- .github/workflows/example_check_on_schedule.yml
- examples/language/bert/finetune.py
> [hotfix] Cache HuggingFace model weights during testing (1st try)

- colossalai/zero/gemini/chunk/chunk.py
- colossalai/zero/gemini/gemini_ddp.py
- tests/test_zero/test_gemini/test_grad_accum.py
- tests/test_zero/test_gemini/test_grad_clip.py
>
closed #5000, #4610
fix bug when gradient accumulation and gradient clipping are both enabled for Gemini Plugin, and add relevant tests
> [hotfix] fix grad accumulation plus clipping for gemini

- .github/CODEOWNERS
> [misc] add code owners

- applications/Chat/examples/community/peft/train_peft_prompts.py
- applications/Chat/examples/community/peft/train_peft_sft.py
- applications/Chat/examples/inference.py
- applications/Chat/examples/train_prompts.py
- applications/Chat/examples/train_reward_model.py
- applications/Chat/examples/train_sft.py
>
The EOS in the ColossalChat directory have inconsistencies, which would lead to the stored checkpoints being unable to continue normal training, resulting in errors in the embedding index.
> fix wrong EOS token in ColossalChat

- examples/language/llama2/finetune.py
>
closes #5034 
fix llama example' loss error when using gemini plugin
> [exampe] fix llama example' loss error when using gemini plugin

- .gitmodules
> [misc] remove outdated submodule

- examples/inference/benchmark_vllm.py
> [example] add vllm inference benchmark

- colossalai/inference/README.md
- examples/inference/README.md
- examples/inference/example.py
>
Re-write the user guide for running inference examples and the overall development document of Colossal-Inference.
> [doc] Update the user guide and the development document in Colossal-Inference

- colossalai/inference/engine/engine.py
- colossalai/inference/engine/modeling/llama.py
- colossalai/inference/kv_cache/kvcache_manager.py
- examples/inference/benchmark_llama.py
- examples/inference/example.py
>
This slightly improves performance.
Before this PR:
After this PR:
> [inference] decouple pp logic for llama

- colossalai/inference/engine/policies/llama.py
> [hotfix]Refactor rmsnorm fix

- colossalai/inference/engine/modeling/chatglm2.py
- colossalai/inference/engine/policies/chatglm2.py
- colossalai/inference/engine/policies/llama.py
>
This PR fixes the import err of chatglm rmsnorm
> [hotfix]fix chatglm rmsnorm 

- colossalai/booster/mixed_precision/fp16_torch.py
- colossalai/booster/plugin/hybrid_parallel_plugin.py
- colossalai/device/device_mesh.py
- colossalai/legacy/amp/torch_amp/torch_amp.py
- colossalai/legacy/utils/activation_checkpoint.py
- colossalai/shardformer/layer/utils.py
- colossalai/testing/utils.py
- colossalai/utils/device.py
- examples/language/llama2/benchmark.py
>
add npu support for hybrid plugin and llama
> [npu] add npu support for hybrid plugin and llama

- colossalai/shardformer/modeling/llama.py
>
remove duplicate import in llama
https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/shardformer/modeling/llama.py#L404
> [shardformer] remove duplicate import in llama

- docs/source/en/features/lazy_init.md
- docs/source/en/features/pipeline_parallel.md
- docs/source/zh-Hans/features/lazy_init.md
Not involved
fix typo change lazy_iniy to lazy_init
> [nfc] fix typo change lazy_iniy to lazy_init

- tests/test_infer/test_model_accuracy.py
>
Maintain inference test: add model forward accuracy test which compares logits produced by a single model forward.
> [inference] Add model forward accuracy test

- colossalai/shardformer/layer/_operation.py
- colossalai/tensor/d_tensor/comm_spec.py
- Fixed unnormal memory usage of shardformer module replacement when using tensor parallelism
> [hotfix] Fixed shardformer initialization memory error

- colossalai/utils/memory.py
> [hotfix]: add NPU TODO mark

- README.md
- docs/README-zh-Hans.md
- examples/language/openmoe/README.md
> [doc] add moe news

- README.md
> [doc] updated paper citation

- applications/Colossal-LLaMA-2/README.md
- applications/ColossalEval/README.md
- applications/ColossalQA/README.md
Not involved
fix typo change JOSNL TO JSONL etc.
> [nfc] fix typo change JOSNL TO JSONL etc.

- applications/ColossalQA/examples/webui_demo/README.md
> [doc] fix colossalqa document

- applications/ColossalQA/colossalqa/memory.py
- applications/ColossalQA/examples/webui_demo/server.py
> [colossalqa] fix pangu api

- applications/ColossalEval/README.md
- applications/ColossalEval/colossal_eval/dataset/__init__.py
- applications/ColossalEval/colossal_eval/dataset/agieval.py
- applications/ColossalEval/colossal_eval/dataset/base.py
- applications/ColossalEval/colossal_eval/dataset/ceval.py
- applications/ColossalEval/colossal_eval/dataset/cmmlu.py
- applications/ColossalEval/colossal_eval/dataset/gaokaobench.py
- applications/ColossalEval/colossal_eval/dataset/gsm.py
- applications/ColossalEval/colossal_eval/dataset/mmlu.py
- applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/dataset_evaluator.py
- applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/metrics.py
- applications/ColossalEval/colossal_eval/models/huggingface.py
- applications/ColossalEval/colossal_eval/utils/conversation.py
- applications/ColossalEval/examples/dataset_evaluation/inference.py
- applications/ColossalEval/examples/dataset_evaluation/inference.sh
- applications/ColossalEval/examples/gpt_evaluation/inference.py
- applications/ColossalEval/examples/gpt_evaluation/inference.sh
- applications/ColossalEval/requirements.txt
- applications/ColossalEval/setup.py
>
Support GSM, Data Leakage Evaluation and Tensor Parallel
> [ColossalEval] Support GSM, Data Leakage Evaluation and Tensor Parallel

- applications/Chat/README.md
>
polish readme in application/chat
> [doc] Polish readme in application/chat

- .github/workflows/build_on_pr.yml
- .github/workflows/build_on_schedule.yml
- .github/workflows/doc_test_on_pr.yml
- .github/workflows/doc_test_on_schedule.yml
- .github/workflows/example_check_on_dispatch.yml
- .github/workflows/example_check_on_pr.yml
- .github/workflows/example_check_on_schedule.yml
> [devops] update torch versoin in ci

- colossalai/shardformer/modeling/llama.py
- colossalai/shardformer/policies/llama.py
>
#5205 
Fix flash attention. Avoid using aten::is_nonzero to reduce runtime.
> [shardformer] fix flash attention.

- applications/Colossal-LLaMA-2/README.md
> [doc] Update README.md of Colossal-LLAMA2

- README.md
I want to make the leaderboard format more clearly and straightforward so I unified the column names to make more sense for each row and added a new column name, i.e., "Model", for those evaluated models.
> [doc] Make leaderboard format more uniform and good-looking

- README.md
- applications/Colossal-LLaMA-2/README.md
- docs/README-zh-Hans.md
> [doc] add Colossal-LLaMA-2-13B

- colossalai/pipeline/p2p.py
- colossalai/pipeline/schedule/interleaved_pp.py
- colossalai/pipeline/schedule/one_f_one_b.py
- tests/test_pipeline/test_p2p_communication.py
>
A follow up of https://github.com/hpcaitech/ColossalAI/pull/5017
It can handle the more general objects to send.
And use `send_forward_recv_backward`, it shall fix the error in MoE test
> [pipeline] A more general _communicate in p2p

- .github/workflows/build_on_pr.yml
- .github/workflows/build_on_schedule.yml
- tests/kit/model_zoo/transformers/chatglm2.py
- tests/test_booster/test_plugin/test_3d_plugin.py
- tests/test_booster/test_plugin/test_gemini_plugin.py
> [ci] fixed booster test

- applications/ColossalMoE/infer.py
- colossalai/moe/routers.py
> [moe] update capacity computing

- applications/ColossalEval/README.md
Not involved
fix typo in  applications/ColossalEval/README.md
> [fix] fix typo in  applications/ColossalEval/README.md

- .github/workflows/build_on_schedule.yml
> [workflow] fixed incomplete bash command

- examples/language/llama2/pretrain.py
> [example]fix llama2 pretrain script

- tests/test_booster/test_plugin/test_3d_plugin.py
> [hotfix] fix 3d plugin test

- colossalai/inference/utils.py
>
fixed #5283
#5283 missing utils.py, and we fixed in this PR.
- [xI have performed a self-review of my code
> [Inference/fix]Add utils.py for Rotary Embedding

- applications/ColossalQA/colossalqa/chain/retrieval_qa/base.py
> [NFC] polish ColossalQA

- colossalai/moe/manager.py
- colossalai/tensor/comm_spec.py
- colossalai/tensor/d_tensor/api.py
- colossalai/tensor/moe_tensor/api.py
- colossalai/tensor/moe_tensor/moe_info.py
- colossalai/utils/timer.py
- colossalai/zero/gemini/gemini_optimizer.py
- colossalai/zero/low_level/bookkeeping/bucket_store.py
- colossalai/zero/low_level/bookkeeping/gradient_store.py
- colossalai/zero/low_level/low_level_optim.py
- docs/source/en/basics/booster_api.md
- examples/tutorial/auto_parallel/README.md
Not involved
Fixed some typos, most of which are not related to code logic.
detail info
modified:   colossalai/moe/manager.py
modified:   colossalai/tensor/comm_spec.py
modified:   colossalai/tensor/d_tensor/api.py
modified:   colossalai/tensor/moe_tensor/api.py
modified:   colossalai/tensor/moe_tensor/moe_info.py
modified:   colossalai/utils/timer.py
modified:   colossalai/zero/gemini/gemini_optimizer.py
modified:   colossalai/zero/low_level/bookkeeping/bucket_store.py
modified:   colossalai/zero/low_level/bookkeeping/gradient_store.py
modified:   colossalai/zero/low_level/low_level_optim.py
modified:   docs/source/en/basics/booster_api.md
modified:   examples/tutorial/auto_parallel/README.md
> [fix] fix some typo

- applications/ColossalMoE/colossal_moe/models/mixtral_checkpoint.py
>
Fix checkpoint synchronization
> [moe] fix mixtral checkpoint io

- colossalai/kernel/triton/rms_layernorm.py
- tests/test_infer_ops/triton/test_rmsnorm_triton.py
> [Inference] Update rms norm kernel, benchmark with vLLM

- .github/workflows/build_on_schedule.yml
- .github/workflows/example_check_on_dispatch.yml
- .github/workflows/example_check_on_pr.yml
- .github/workflows/example_check_on_schedule.yml
- .github/workflows/run_chatgpt_examples.yml
- .github/workflows/run_chatgpt_unit_tests.yml
- .github/workflows/run_colossalqa_unit_tests.yml
> [workflow] updated CI image

- colossalai/accelerator/npu_accelerator.py
> [accelerator] fixed npu api

- extensions/README.md
- extensions/base_extension.py
> [doc] added docs for extensions

- extensions/README.md
- extensions/cuda_extension.py
- extensions/flash_attention/flash_attention_dao_cuda.py
- extensions/flash_attention/flash_attention_xformers_cuda.py
- extensions/triton_extension.py
Not involved
[fix] fix typo under extensions/
detail info
modified:   extensions/README.md
modified:   extensions/cuda_extension.py
modified:   extensions/flash_attention/flash_attention_dao_cuda.py
modified:   extensions/flash_attention/flash_attention_xformers_cuda.py
modified:   extensions/triton_extension.py
> [fix] fix typo under extensions/

- colossalai/shardformer/policies/falcon.py
- colossalai/shardformer/policies/llama.py
- colossalai/shardformer/policies/mistral.py
- colossalai/shardformer/policies/opt.py
- colossalai/shardformer/policies/t5.py
- colossalai/shardformer/policies/vit.py
- colossalai/shardformer/policies/whisper.py
- examples/language/openmoe/model/openmoe_policy.py
Not involved
fix typo change dosen't to doesn't
> [fix] fix typo change dosen't to doesn't

- colossalai/inference/config.py
- colossalai/inference/core/engine.py
- colossalai/inference/modeling/models/nopadding_llama.py
- colossalai/inference/modeling/models/padding_llama.py
- colossalai/inference/modeling/policy/__init__.py
- colossalai/inference/modeling/policy/nopadding_llama.py
- colossalai/inference/modeling/policy/padding_llama.py
- colossalai/inference/struct.py
- tests/test_infer_ops/triton/test_xine_copy.py
> [Inference]Add Nopadding Llama Modeling

- applications/ColossalMoE/colossal_moe/models/mixtral_policy.py
> [moe] fix mixtral forward default value

- colossalai/kernel/triton/no_pad_rotary_embedding.py
- tests/test_infer_ops/triton/test_rotary_embdding_unpad.py
- tests/test_infer_ops/triton/test_xine_copy.py
>
fused copy kv cache into rotary embedding
> [Inference] Kernel Fusion, fused copy kv cache into rotary embedding

- extensions/cpp_extension.py
> [extension] fixed exception catch

- applications/ColossalMoE/colossal_moe/models/mixtral_checkpoint.py
- applications/ColossalMoE/tests/test_moe_checkpoint.py
> [moe] fix mixtral optim checkpoint

- applications/Chat/coati/dataset/sft_dataset.py
- applications/Chat/examples/train_sft.sh
> [Chat] fix sft loss nan

- colossalai/inference/config.py
- tests/test_infer/test_inference_engine.py
> [inference] simplified config verification

- colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
- colossalai/zero/gemini/gemini_optimizer.py
- extensions/cuda_extension.py
- tests/test_checkpoint_io/test_gemini_checkpoint_io.py
- tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py
>
NA
Gemini and hybrid parallel plugins save outdated param groups. This PR fix this issue.
> [checkpointio] fix gemini and hybrid parallel optim checkpoint

- colossalai/inference/core/request_handler.py
- colossalai/inference/struct.py
- tests/test_infer/test_config_and_struct.py
> [inference] removed redundancy init_batch

- colossalai/inference/README.md
- colossalai/inference/__init__.py
- colossalai/inference/core/__init__.py
- colossalai/inference/core/engine.py
- colossalai/inference/core/request_handler.py
- colossalai/inference/kv_cache/block_cache.py
- colossalai/inference/kv_cache/kvcache_manager.py
- requirements/requirements.txt
> [doc] updated inference readme

- applications/Colossal-LLaMA-2/colossal_llama2/dataset/loader.py
- applications/Colossal-LLaMA-2/train.py
- applications/Colossal-LLaMA-2/train_sft.py
- colossalai/booster/plugin/dp_plugin_base.py
- colossalai/booster/plugin/gemini_plugin.py
- colossalai/booster/plugin/hybrid_parallel_plugin.py
> [llama] fix dataloader for hybrid parallel

- applications/Colossal-LLaMA-2/colossal_llama2/utils/flash_attention_patch.py
> [llama] add flash attn patch for npu

- applications/Colossal-LLaMA-2/colossal_llama2/utils/neftune_patch.py
- applications/Colossal-LLaMA-2/train.py
> [llama] fix neftune & pbar with start_step

- applications/ColossalEval/colossal_eval/models/chatglm.py
- applications/ColossalEval/colossal_eval/models/huggingface.py
- applications/ColossalEval/examples/dataset_evaluation/inference.py
> [eval] update llama npu eval

- applications/Colossal-LLaMA-2/train.py
- colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
> [llama] polish training script and fix optim ckpt

- colossalai/nn/lr_scheduler/delayed.py
- tests/test_optimizer/test_lr_scheduler.py
> [lr-scheduler] fix load state dict and add test

- applications/Colossal-LLaMA-2/train.py
> [llama] fix memory issue

- applications/Colossal-LLaMA-2/inference_example.py
- applications/Colossal-LLaMA-2/train.py
- colossalai/zero/gemini/gemini_ddp.py
> [llama] fix training and inference scripts

- docs/source/zh-Hans/features/1D_tensor_parallel.md
> [docs/source/zh-Hans/features/1D_tensor_parallel.md] Fix typo

- colossalai/auto_parallel/meta_profiler/meta_registry/binary_elementwise_ops.py
fixes #5391 
Fixes a wrong import statement in `colossalai/auto_parallel/meta_profiler/meta_registry/binary_elementwise_ops.py`, as described in issue #5391.
> [ColossalAuto] Fix wrong import statement

- colossalai/inference/batch_bucket.py
- colossalai/inference/core/engine.py
- colossalai/inference/struct.py
- examples/inference/run_benchmark.sh
- tests/test_infer/test_batch_bucket.py
>
Fixed errors caused by the input prompts are not in the form of a list and the input model is not on the GPU.
pytest:
> [Fix/Inference] Fix format of input prompts and input model  in inference engine

- setup.py
> [extension] hotfix jit extension setup

- colossalai/booster/plugin/torch_fsdp_plugin.py
- tests/test_checkpoint_io/test_torch_fsdp_checkpoint_io.py
>
resolved https://github.com/hpcaitech/ColossalAI/issues/5328
> [fsdp] impl save/load shard model/optimizer

- .github/workflows/release_nightly_on_schedule.yml
- .github/workflows/scripts/update_setup_for_nightly.py
- setup.py
> [setup] fixed nightly release

- colossalai/shardformer/modeling/llama.py
- colossalai/shardformer/shard/shard_config.py
>
add switch to enable gathering llama logits
> [shardformer]gather llama logits

- applications/Colossal-LLaMA-2/requirements.txt
> [Colossal-LLaMA-2] Workable version fix

- .github/workflows/release_test_pypi_before_merge.yml
> [workflow] added pypi channel

- README.md
- docs/README-zh-Hans.md
> [doc] fix blog link

- applications/Colossal-LLaMA-2/inference_example.py
> Fix sft single turn inference example

- README.md
- applications/README.md
- docs/README-zh-Hans.md
> [doc] sora release

- examples/images/diffusion/ldm/modules/midas/midas/dpt_depth.py
fixed #5419 
change code like this  
```
from .blocks import FeatureFusionBlock_custom, Interpolate, _make_encoder
from vit import forward_vit
```
> fix import error

- examples/language/openmoe/benchmark/benchmark_cai.py
- examples/language/openmoe/benchmark/benchmark_fsdp.py
- examples/language/openmoe/infer.py
- examples/language/openmoe/train.py
> N/A
Correct typos in the OpenMoE example under `examples/language/openmoe`, where the model source on Hugging Face should be hpcai-tech instead of hpcaitech.
- [] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
> [hotfix] fix typo of OpenMoE model source

- colossalai/shardformer/layer/_operation.py
- colossalai/shardformer/layer/normalization.py
- colossalai/shardformer/modeling/bloom.py
- colossalai/shardformer/modeling/chatglm2_6b/modeling_chatglm.py
- colossalai/shardformer/modeling/gptj.py
- colossalai/shardformer/modeling/llama.py
- colossalai/shardformer/modeling/opt.py
- colossalai/shardformer/modeling/t5.py
Not involved
fix typo change enabel to enable under colossalai/shardformer/
detail info 
modified:   colossalai/shardformer/layer/_operation.py
modified:   colossalai/shardformer/layer/normalization.py
modified:   colossalai/shardformer/modeling/bloom.py
modified:   colossalai/shardformer/modeling/chatglm2_6b/modeling_chatglm.py
modified:   colossalai/shardformer/modeling/gptj.py
modified:   colossalai/shardformer/modeling/llama.py
modified:   colossalai/shardformer/modeling/opt.py
modified:   colossalai/shardformer/modeling/t5.py
> [fix] fix typo change enabel to enable under colossalai/shardformer/

- applications/ColossalQA/colossalqa/prompt/README.md
Fix typo s/infered/inferred/
I think there is no need for an issue, but I can if it's really important :)
> chore: Fix typo s/infered/inferred/

- applications/Colossal-LLaMA-2/colossal_llama2/utils/stream_chat_patch.py
- applications/Colossal-LLaMA-2/stream_chat_example.py
>
> add stream chat patch
> add an example for stream chat
> [colossal-llama2] add stream chat examlple for chat version model

- extensions/csrc/cuda/activation_kernel.cu
- extensions/csrc/cuda/colossal_inference_C_frontend.cpp
- extensions/csrc/cuda/include/mp_type_traits.h
- extensions/csrc/cuda/type_shim.h
- extensions/inference/inference_ops_cuda.py
- tests/test_infer/test_ops/cuda/test_silu_and_mul.py
>
This PR do the following things:
1. add mp_type_traits to help mix precision calculation
2. add silu_and_mul kernel
1. add vectorize traits and related ld&st&cal support for further optimization
2. profiling for model improvement at last version with vec ld&st&cal
3. refactor the inference architecture such as namespace. file structure and so on
4. we should make our kernel more reusable by abstracting certain generalized components
> 【Inference】Add silu_and_mul for infer

- applications/Colossal-LLaMA-2/train.py
> [colossal-llama2] fix tensor data update for gemini loss calculation

- extensions/csrc/cuda/pybind/layer_norm.cpp
- extensions/moe/moe_cuda.py
>
This PR fix include path error
> fix include path

- extensions/csrc/cuda/rms_layernorm_kernel.cu
- tests/test_infer/test_inference_engine.py
…rtial specialization is not allowed in Cpp) and luckily pass e2e precision test
>
> [Inference] fix rmsnorm template function invocation problem

- .gitmodules
- examples/language/grok-1/README.md
- examples/language/grok-1/grok1_policy.py
- examples/language/grok-1/inference.py
- examples/language/grok-1/inference_tp.py
- examples/language/grok-1/requirements.txt
- examples/language/grok-1/run_inference_fast.sh
- examples/language/grok-1/run_inference_slow.sh
- examples/language/grok-1/test_ci.sh
- examples/language/grok-1/utils.py
> [example] add grok-1 inference

- colossalai/inference/config.py
Small Patch, Fix PR https://github.com/hpcaitech/ColossalAI/pull/5434
> [fix] PR #5354

- tests/test_shardformer/test_model/test_shard_chatglm2.py
- tests/test_shardformer/test_model/test_shard_t5.py
> [test] fix shardformer tests

- examples/language/grok-1/inference.py
- examples/language/grok-1/inference_tp.py
>
Tokenizer-related files have been added to HuggingFace Hub [hpcai-tech/grok-1](https://huggingface.co/hpcai-tech/grok-1). Refer to https://huggingface.co/hpcai-tech/grok-1/discussions/4
> [fix] Grok-1 use tokenizer from the same pretrained path

- extensions/csrc/common/micros.h
- extensions/csrc/cuda/funcs/op_functor.h
- extensions/csrc/cuda/include/block_reduce.h
- extensions/csrc/cuda/layer_norm_kernel.cu
- extensions/csrc/cuda/moe_kernel.cu
- extensions/csrc/cuda/multi_tensor_apply.cuh
- extensions/csrc/cuda/multi_tensor_l2norm_kernel.cu
- extensions/csrc/cuda/multi_tensor_lamb_kernel.cu
- extensions/csrc/cuda/rms_layernorm_kernel.cu
>
This PR do the following things 
1、Delete deprecated api usage
2、Add op_functor for cuda types
3、Add reduce utils
TODO 
1、 use op functor to do calculation for cuda types
2、use using in .cu or .cpp to delete longer namespace prefix of utils
3、rewrite reduce_max_into_lanes
> [Inference] Add Reduce Utils

- colossalai/booster/plugin/hybrid_parallel_plugin.py
- colossalai/zero/low_level/_utils.py
- colossalai/zero/low_level/low_level_optim.py
- tests/test_zero/test_low_level/test_grad_acc.py
- tests/test_zero/test_low_level/test_zero1_2.py
> [Zero] some optimizations for Zero1/2 (cpu offloading, large scale, etc)

- colossalai/shardformer/modeling/falcon.py
- colossalai/shardformer/policies/falcon.py
> [shardformer/modeling/falcon]: Upgrade transformers from version 4.33.0 to version 4.36.0 for the falcon model, the code changes including `forward` function of `FalconAttention`, `FalconDecoderLayer` and `FalconModel`. 
Remove the version restriction of transformers in falcon policy.
> [shardformer] update falcon model

- colossalai/shardformer/modeling/gpt2.py
[shardformer/modeling/gpt2]: Upgrade transformers from version 4.33.0 to version 4.36.0 for the gpt2 model, including the `gpt2_model_forward` function.
> [shardformer] update gpt2

- colossalai/inference/README.md
- colossalai/inference/spec/README.md
>
part of #5245 
Add readme as well as usage case.
> [doc] Add inference/speculative-decoding README

- examples/language/grok-1/inference.py
- examples/language/grok-1/inference_tp.py
- examples/language/grok-1/utils.py
Not involved
fix typo s/get_defualt_parser /get_default_parser
detail info
modified:   examples/language/grok-1/inference.py
modified:   examples/language/grok-1/inference_tp.py
modified:   examples/language/grok-1/utils.py
> [fix] fix typo s/get_defualt_parser /get_default_parser

- colossalai/inference/modeling/models/nopadding_llama.py
>
Fix 
1) CUDA kernels are not supporting verification for now, fall back to not use CUDA kernels if both `use_cuda_kernel` and `use_dpec_dec` are set to true.
2) reference before assignment in llama modeling
> [Fix] Llama Modeling Control with Spec-Dec

- colossalai/zero/low_level/bookkeeping/bucket_store.py
- colossalai/zero/low_level/low_level_optim.py
- requirements/requirements.txt
merge this commit :https://github.com/hpcaitech/ColossalAI/commit/3788fefc7a24ae4da18a29ca69e6d3b1473d306c to the transformers update branch, to fix the backward shape error
> [cherry-pick] merge#5596 to the transformers update branch

- colossalai/_analyzer/fx/codegen.py
- colossalai/auto_parallel/offload/base_offload_module.py
- colossalai/auto_parallel/offload/region.py
- colossalai/autochunk/autochunk_codegen.py
- colossalai/fx/codegen/activation_checkpoint_codegen.py
- colossalai/shardformer/shard/grad_ckpt_config.py
- colossalai/shardformer/shard/shard_config.py
- examples/language/gpt/hybridparallelism/data.py
* fix no pad token bug
* fixed some auto parallel codegen bug, but might not run on torch 2.1
---------
>
> cherry-pick the commit “Fix examples no pad token & auto parallel codegen bug; (#5606)” and fix pipeline grad ckpt #5620

- extensions/csrc/cuda/fused_rotary_emb_and_cache_kernel.cu
- tests/test_infer/test_ops/cuda/test_rotary_embdding_unpad.py
> [Fix/Inference]Fix CUDA Rotary Rmbedding GQA

- tests/kit/model_zoo/transformers/llama.py
- tests/test_shardformer/test_model/test_shard_llama.py
> [test] fix llama model test

- examples/inference/benchmark_llama.py
- examples/inference/benchmark_llama3.py
- examples/inference/run_benchmark.sh
> [Fix/Inference]Fix vllm benchmark

- tests/kit/model_zoo/transformers/llama.py
> [test] fix llama test

- colossalai/zero/gemini/gemini_ddp.py
> [gemini] fix buffer cast

- colossalai/shardformer/layer/normalization.py
- colossalai/shardformer/shard/shard_config.py
> [hotfix] Fixed fused layernorm bug without apex

- colossalai/shardformer/modeling/opt.py
> [shardformer] remove useless code.

- colossalai/shardformer/policies/gptj.py
> [shardformer] fix gptj

- tests/test_lazy/test_models.py
> [lazyinit] skip whisper test

- README.md
- docs/README-zh-Hans.md
> [news] llama3 and open-sora v1.1

- examples/language/llama/benchmark.py
- examples/language/llama/data_utils.py
- examples/language/llama/model_utils.py
- examples/language/llama/performance_evaluator.py
> [hotfix] Fix path issue 

- .github/workflows/release_docker_after_publish.yml
> [devops] fix release docker ci

- extensions/csrc/funcs/cast_functor.h
- extensions/csrc/kernel/cuda/context_kv_cache_memcpy_kernel.cu
- extensions/csrc/kernel/cuda/flash_decoding_attention_kernel.cu
- extensions/csrc/kernel/cuda/utils/vec_copy.h
>
This PR add quant kvcache support for context_kv_cache_memcpy
> [Inference/Feat] Feat quant kvcache step2

- extensions/csrc/kernel/cuda/decode_kv_cache_memcpy_kernel.cu
> [Inference/Feat] Add quant kvcache support for decode_kvcache_memcpy

- examples/language/gpt/hybridparallelism/finetune.py
> [Hotfix] Fix missing pad token in GPT example

- colossalai/booster/plugin/hybrid_parallel_plugin.py
- colossalai/zero/low_level/bookkeeping/base_store.py
- colossalai/zero/low_level/bookkeeping/bucket_store.py
- colossalai/zero/low_level/bookkeeping/gradient_store.py
- colossalai/zero/low_level/low_level_optim.py
- tests/test_booster/test_plugin/test_low_level_zero_plugin.py
- tests/test_shardformer/test_model/test_shard_llama.py
>
remove registered hooks
remove registered gradients hooks
> [zero]remove registered gradients hooks

- .github/ISSUE_TEMPLATE/bug-report.yml
> [misc] Add an existing issue checkbox in bug report

- colossalai/inference/core/request_handler.py
- colossalai/inference/logit_processors.py
- tests/test_infer/test_inference_engine.py
>
Adapt temperature processing logic, and tests have been conducted on Baichuan2-13B and llama3 accordingly.
**pytest:**
**Inference Test:**
***Baichuan2-13B:***
temperature(1.0)
temperature(0.7)
temperature(0.5)
***llama3***
temperature(1.0)
temperature(0.7)
temperature(0.5)
> [Inference]Adapt temperature processing logic

- colossalai/inference/config.py
- colossalai/inference/core/engine.py
- colossalai/inference/core/request_handler.py
- colossalai/inference/logit_processors.py
- colossalai/inference/struct.py
- tests/test_infer/test_inference_engine.py
>
This PR support the logic related to ignoring EOS token.
**pytest:**
**Benchmark Test:**
***ignore_eos_token_id=False***
***ignore_eos_token_id=True***
> [Inference] Support the logic related to ignoring EOS token

- colossalai/zero/gemini/chunk/manager.py
- colossalai/zero/gemini/chunk/utils.py
- colossalai/zero/gemini/gemini_ddp.py
- colossalai/zero/gemini/gemini_optimizer.py
- tests/test_zero/test_gemini/test_fwd_bwd.py
>
remove registered gradients hooks
> [gemini]remove registered gradients hooks

- colossalai/inference/config.py
- colossalai/inference/kv_cache/kvcache_manager.py
> [Inference/Feat] Add quant kvcache interface

- docs/source/en/get_started/installation.md
- docs/source/zh-Hans/get_started/installation.md
> [misc] Update PyTorch version in docs

- colossalai/inference/flash_decoding_utils.py
- colossalai/inference/modeling/models/nopadding_baichuan.py
- colossalai/inference/modeling/models/nopadding_llama.py
- examples/inference/benchmark_ops/benchmark_flash_decoding_attention.py
- extensions/csrc/kernel/cuda/flash_decoding_attention_kernel.cu
- extensions/csrc/kernel/cuda/fused_rotary_emb_and_cache_kernel.cu
- extensions/pybind/inference/inference.cpp
- tests/test_infer/test_kernels/cuda/test_flash_decoding_attention.py
> [Inference/Kernel] Add PagedAttetionv2: support seq length split across thread block

- extensions/csrc/kernel/cuda/decode_kv_cache_memcpy_kernel.cu
- extensions/csrc/kernel/cuda/fused_rotary_emb_and_cache_kernel.cu
- extensions/csrc/kernel/cuda/get_cos_and_sin_kernel.cu
- extensions/csrc/kernel/cuda/scaled_masked_softmax_kernel.cu
- extensions/csrc/kernel/cuda/scaled_upper_triang_masked_softmax_kernel.cu
- extensions/csrc/kernel/cuda/utils/vec_copy.h
> [Inference] Delete duplicated copy_vector

- colossalai/inference/core/async_engine.py
- colossalai/inference/core/engine.py
- colossalai/inference/server/api_server.py
- colossalai/inference/server/completion_service.py
- examples/inference/client/run_locust.sh
> [Inference] Fix API server, test and example

- setup.py
> [Inference] Fix Setup.py

- colossalai/zero/gemini/placement_policy.py
> [gemini] prefetch for auto policy

- colossalai/zero/gemini/gemini_mgr.py
> [chore] fix init error

- colossalai/zero/gemini/chunk/chunk.py
- colossalai/zero/gemini/gemini_hook.py
- colossalai/zero/gemini/gemini_mgr.py
- tests/test_zero/test_gemini/test_fwd_bwd.py
- tests/test_zero/test_gemini/test_grad_accum.py
- tests/test_zero/test_gemini/test_grad_clip.py
- tests/test_zero/test_gemini/test_optim.py
- tests/test_zero/test_gemini/test_zeroddp_state_dict.py
- tests/test_zero/test_gemini/test_zerooptim_state_dict.py
> [bug] fix early return

- .github/workflows/build_on_pr.yml
>
Temporary fix for CI. We'll:
1. optimize the compilation process to decrement the build time of `colossalai`
2. clean and optimize the unit tests
> [ci] Temporary fix for build on pr

- requirements/requirements-test.txt
> [NFC] Remove redundancy in requirements for tests

- README.md
- colossalai/inference/README.md
- docs/README-zh-Hans.md
> [inference] release

- tests/test_infer/test_continuous_batching.py
>
Part of fixing CI running time. This PR reduces the running time of inference test `test_continuous_batching` by removing unnecessary configs/args and using smaller dummy model for test usage.
Time reduced from > 150 sec to < 50 sec
> [Fix] Fix running time of test_continuous_batching

- examples/language/llama/benchmark.py
- examples/language/performance_evaluator.py
> [Gemini] add some code for reduce-scatter overlap, chunk prefetch in llama benchmark.

- examples/language/llama/benchmark.py
- examples/language/performance_evaluator.py
> [Gemini]Prefetch benchmark

- colossalai/shardformer/policies/llama.py
> [shardformre] fix llama policy

- docker/Dockerfile
> [misc] update dockerfile

- .github/workflows/release_docker_after_publish.yml
> [devops] fix docker ci

- colossalai/shardformer/modeling/llama.py
>
fix llama flash attention forward.
> [hotfix] fix llama flash attention forward.

- colossalai/nn/optimizer/__init__.py
>
Getting dist logger out of function may initialize it before initializing process group, which leads to wrong rank.
> [misc] fix dist logger

- extensions/cuda_extension.py
- setup.py
> [install]fix setup

- requirements/requirements.txt
> [misc] update requirements

- colossalai/shardformer/modeling/llama.py
- colossalai/shardformer/modeling/qwen2.py
> [shardformer] fix import

- colossalai/zero/gemini/gemini_hook.py
> [gemini] quick fix on possible async operation

- colossalai/zero/low_level/low_level_optim.py
- colossalai/zero/low_level/low_level_strategy.py
> [zero] align api with previous version

- .github/workflows/build_on_pr.yml
>
Remove building on PR when edited to avoid skip issue
> [Fix] Remove building on PR when edited to avoid skip issue

- colossalai/inference/core/engine.py
- colossalai/inference/modeling/models/glide_llama.py
- colossalai/inference/spec/struct.py
- examples/inference/llama/README.md
>
Fix inference engine test - spec-dec. Now Glide Llama Model is compatible with transformers 4.39
> [Fix] Fix spec-dec Glide LlamaModel for compatibility with transformers

- colossalai/booster/plugin/hybrid_parallel_plugin.py
- colossalai/moe/load_balance.py
- colossalai/zero/low_level/bookkeeping/gradient_store.py
- colossalai/zero/low_level/low_level_optim.py
- tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
- tests/test_optimizer/_utils.py
- tests/test_optimizer/test_dist_adafactor.py
- tests/test_optimizer/test_dist_came.py
- tests/test_optimizer/test_dist_lamb.py
- tests/test_shardformer/test_hybrid_parallel_grad_clip_norm/test_zero_optimizer.py
- tests/test_shardformer/test_model/test_shard_command.py
- tests/test_shardformer/test_model/test_shard_llama.py
> [zero] modify api

- colossalai/zero/gemini/gemini_ddp.py
> [gemini] fix missing return

- README.md
- docs/README-zh-Hans.md
> [doc] opensora v1.2 news

- README.md
- docs/README-zh-Hans.md
> [doc] fix open sora model weight link

- README.md
- applications/Colossal-LLaMA/README.md
- applications/ColossalEval/README.md
- applications/README.md
- docs/README-zh-Hans.md
- examples/README.md
> [doc] add GPU cloud playground

- colossalai/shardformer/modeling/llama.py
fix shard former modeling_llama, remove some args
> fix shardformer modeling_llama

- colossalai/zero/low_level/low_level_optim.py
> [zero] remove redundant memebr init

- colossalai/zero/low_level/bookkeeping/tensor_bucket.py
- colossalai/zero/low_level/low_level_optim.py
> [zero] use bucket during allgather

- colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
- colossalai/checkpoint_io/moe_checkpoint.py
- colossalai/cluster/process_group_mesh.py
> [Feature] remove useless code, modify the pg mesh implementation

- colossalai/shardformer/modeling/deepseek.py
- colossalai/shardformer/policies/auto_policy.py
- colossalai/shardformer/policies/deepseek.py
- colossalai/shardformer/policies/mixtral.py
- tests/test_moe/test_moe_checkpoint.py
> [Feature] deepseek support & unit test

- colossalai/shardformer/modeling/qwen2.py
>
add gradient ckpt for qwen2 
> [Shardformer] change qwen2 modeling into gradient checkpointing style

- docs/source/en/features/distributed_optimizers.md
- docs/source/en/features/shardformer.md
- docs/source/zh-Hans/features/distributed_optimizers.md
- docs/source/zh-Hans/features/shardformer.md
> [doc] Update llama + sp compatibility; fix dist optim table

- colossalai/zero/low_level/low_level_optim.py
> [hotfix] fix the bug that large tensor exceed the maximum capacity of TensorBucket

- colossalai/quantization/bnb.py
> [quant] fix bitsandbytes version check

- examples/language/gpt/hybridparallelism/finetune.py
- examples/language/opt/opt_benchmark.py
- examples/language/opt/opt_train_demo.py
> [Examples] add lazy init to OPT and GPT examples

- colossalai/cluster/dist_coordinator.py
fix #5933
Simple bug, fixed. BTW, I have searched the whole project for `os.environ.get`, other places seem fine.
> [Hotfix] convert env param to int

- colossalai/zero/low_level/low_level_optim.py
> [Hotfix] Fix ZeRO typo

- colossalai/zero/low_level/low_level_optim.py
> [zero] hotfix update master params

- applications/ColossalChat/README.md
- applications/ColossalChat/examples/README.md
> [hotfix] Remove unused plan section

- applications/ColossalEval/colossal_eval/dataset/agieval.py
- applications/ColossalEval/colossal_eval/dataset/base.py
- applications/ColossalEval/colossal_eval/dataset/ceval.py
- applications/ColossalEval/colossal_eval/dataset/cmmlu.py
- applications/ColossalEval/colossal_eval/dataset/colossalai.py
- applications/ColossalEval/colossal_eval/dataset/cvalues.py
- applications/ColossalEval/colossal_eval/dataset/gaokaobench.py
- applications/ColossalEval/colossal_eval/dataset/longbench.py
- applications/ColossalEval/colossal_eval/dataset/mmlu.py
- applications/ColossalEval/colossal_eval/dataset/mtbench.py
- applications/ColossalEval/colossal_eval/dataset/safetybench_en.py
- applications/ColossalEval/colossal_eval/dataset/safetybench_zh.py
- applications/ColossalEval/colossal_eval/models/huggingface.py
- applications/ColossalEval/colossal_eval/utils/conversation.py
- applications/ColossalEval/examples/dataset_evaluation/inference.py
>
* Replaced manual data loading with DistributedDataLoader.
* Fixed bug for using shardformer TP.
* Optimized pipeline. 
> [feat] Dist Loader for Eval

- docs/source/en/basics/launch_colossalai.md
- docs/source/zh-Hans/basics/launch_colossalai.md
> [Docs] clarify launch port

- colossalai/quantization/fp8.py
- tests/test_fp8/test_fp8_linear.py
> [fp8] add fp8 linear

- colossalai/quantization/fp8.py
> [fp8] fix all to all single test.

- .github/workflows/example_check_on_pr.yml
- colossalai/quantization/fp8.py
> [test ci]Feature/fp8 comm

- colossalai/quantization/fp8.py
> [fp8] update torch.compile for linear_fp8 to >= 2.4.0

- colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
add use_fp8 option for MoeHybridParallelPlugin
> [fp8] add use_fp8 option for MoeHybridParallelPlugin

- colossalai/booster/plugin/low_level_zero_plugin.py
> [plugin] (revert) add cast inputs option for zero

- colossalai/shardformer/policies/llama.py
Fixed the wrong identation that cause the fwd func to not get replaced.
> [Hotfix] Fix llama fwd replacement bug 

- colossalai/booster/plugin/low_level_zero_plugin.py
> [plugin] hotfix zero plugin

- applications/Colossal-LLaMA/train.py
> [Hotfix] Auto Fused Norm

- colossalai/quantization/fp8.py
resolved #6025
torch.compile fails. 
Add unsqueeze to scale to make it work
> [FP8] Unsqueeze scale to make it compatible with torch.compile

- colossalai/booster/plugin/hybrid_parallel_plugin.py
> [fp8] fix linear hook

- colossalai/shardformer/modeling/mixtral.py
- colossalai/shardformer/policies/mixtral.py
> [fp8] fix missing fp8_comm flag in mixtral

- README.md
- docs/README-zh-Hans.md
> release FP8 news

- README.md
- docs/README-zh-Hans.md
> add funding news

- colossalai/pipeline/schedule/zero_bubble_pp.py
- colossalai/pipeline/stage_manager.py
- tests/test_pipeline/test_pipeline_utils/test_t5_pipeline_utils.py
- tests/test_pipeline/test_pipeline_utils/test_whisper_pipeline_utils.py
- tests/test_pipeline/test_schedule/test_zerobubble_pp.py
> [HotFix] Fix stage_index in zerobubble test;

- colossalai/shardformer/layer/attn.py
- colossalai/shardformer/layer/utils.py
>
Improve comments on comm overlap
> [Ring Attention] Improve comments & method arg naming

- colossalai/utils/safetensors.py
> [ckpt] add safetensors utils

- extensions/cpp_extension.py
- extensions/cuda_extension.py
> [extension] hotfix compile check

- README.md
- docs/README-zh-Hans.md
> [doc] sora solution news

- colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
- colossalai/utils/__init__.py
- colossalai/utils/common.py
- colossalai/zero/gemini/gemini_ddp.py
> [checkpointio] fix hybrid plugin model save

- colossalai/shardformer/layer/attn.py
- tests/test_shardformer/test_layer/test_ring_attn.py
> [hotfix] fix flash attn window_size err

- colossalai/checkpoint_io/utils.py
> [checkpointio] fix performance issue

- README.md
> add hpc cloud intro

- colossalai/zero/low_level/low_level_optim.py
> [hotfix] fix zero comm buffer init

- docs/sidebars.json
- docs/source/en/get_started/bonus.md
- docs/source/zh-Hans/get_started/bonus.md
> [doc] add bonus event

- README.md
- docs/README-zh-Hans.md
> [news] release colossalai for sora

- .github/ISSUE_TEMPLATE/bug-report.yml
>
Hopefully reduces hassle of maintainers
> [Issue template] Add checkbox asking for details to reproduce error

- colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
- colossalai/cluster/process_group_mesh.py
- colossalai/lazy/lazy_init.py
- colossalai/shardformer/modeling/deepseek_v3.py
- colossalai/shardformer/policies/auto_policy.py
- colossalai/shardformer/policies/deepseek_v3.py
- colossalai/shardformer/shard/shard_config.py
- examples/language/deepseek/benchmark.py
- examples/language/performance_evaluator.py
- tests/kit/model_zoo/transformers/__init__.py
- tests/kit/model_zoo/transformers/deepseek_v3.py
- tests/test_shardformer/test_model/_utils.py
- tests/test_shardformer/test_model/test_shard_deepseek_v3.py
> [feature] support ep for deepseek v3

- README.md
- docs/README-zh-Hans.md
> [doc] DeepSeek V3/R1 news

- applications/ColossalChat/coati/distributed/README.md
- applications/ColossalChat/coati/distributed/comm.py
- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/coati/distributed/inference_backend.py
- applications/ColossalChat/coati/distributed/launch.py
- applications/ColossalChat/coati/distributed/producer.py
- applications/ColossalChat/coati/distributed/utils.py
- applications/ColossalChat/rl_example.py
> [chat] add distributed impl

- applications/ColossalChat/coati/distributed/comm.py
> [feature] fit non tensor broadcast

- applications/ColossalChat/examples/training_scripts/lora_finetune.py
- colossalai/booster/plugin/gemini_plugin.py
- colossalai/booster/plugin/hybrid_parallel_plugin.py
- colossalai/booster/plugin/torch_ddp_plugin.py
- colossalai/booster/plugin/torch_fsdp_plugin.py
- colossalai/checkpoint_io/general_checkpoint_io.py
- colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
- colossalai/checkpoint_io/moe_checkpoint.py
- colossalai/checkpoint_io/utils.py
- colossalai/interface/model.py
> [hotfix] fix lora load

- applications/ColossalChat/coati/dataset/loader.py
- applications/ColossalChat/rl_example.py
> [feat] Add custom prompt

- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/rl_example.py
> [feat] Add final save at the end

- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/rl_example.py
> [hotfix] fix checkpoint naming; add num_epoch parameter

- applications/ColossalChat/coati/distributed/grpo_consumer.py
> [hotfix] Fix save issue

- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/coati/distributed/grpo_consumer.py
- applications/ColossalChat/coati/distributed/launch.py
- applications/ColossalChat/coati/distributed/producer.py
- applications/ColossalChat/rl_example.py
> [fix] Fix tp & pp; Fix dataloader

- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/coati/distributed/launch.py
- applications/ColossalChat/coati/distributed/producer.py
- applications/ColossalChat/rl_example.py
> [Feat] support hybrid parallel model sync

- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/coati/distributed/launch.py
- applications/ColossalChat/coati/distributed/producer.py
- applications/ColossalChat/rl_example.py
> [feat] Sync shard model

- .gitignore
- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/coati/distributed/grpo_consumer.py
- applications/ColossalChat/coati/distributed/inference_backend.py
- applications/ColossalChat/coati/distributed/launch.py
- applications/ColossalChat/coati/distributed/producer.py
- applications/ColossalChat/coati/distributed/reward/reward_fn.py
- applications/ColossalChat/coati/distributed/utils.py
- applications/ColossalChat/rl_example.py
> [fix] revert reward update and evaluation

- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/coati/distributed/inference_backend.py
- applications/ColossalChat/coati/distributed/producer.py
- applications/ColossalChat/coati/distributed/utils.py
> [hotfix] Pad seq

- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/coati/distributed/grpo_consumer.py
> [hotfix] Handle empty indexes

- .gitignore
- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/coati/distributed/grpo_consumer.py
- applications/ColossalChat/coati/distributed/inference_backend.py
- applications/ColossalChat/coati/distributed/launch.py
- applications/ColossalChat/coati/distributed/producer.py
- applications/ColossalChat/coati/distributed/reward/reward_fn.py
- applications/ColossalChat/coati/distributed/utils.py
- applications/ColossalChat/rl_example.py
> [feat] Support evaluation during training

- .gitignore
- applications/ColossalChat/coati/distributed/grpo_consumer.py
- applications/ColossalChat/coati/distributed/launch.py
- applications/ColossalChat/coati/distributed/producer.py
- applications/ColossalChat/coati/distributed/reward/reward_fn.py
- applications/ColossalChat/rl_example.py
> [feat] upgrade reward functions

- applications/ColossalChat/coati/distributed/grpo_consumer.py
> [hotfix] fix empty index

- colossalai/shardformer/modeling/mistral.py
- colossalai/shardformer/policies/mistral.py
- tests/test_shardformer/test_model/test_shard_mistral.py
> [upgrade]upgrade mistral

- applications/ColossalChat/coati/distributed/launch.py
- applications/ColossalChat/coati/distributed/producer.py
- applications/ColossalChat/rl_example.py
> [hotfix] fix default eval setting.

- colossalai/shardformer/modeling/gptj.py
- colossalai/shardformer/modeling/t5.py
https://github.com/hpcaitech/ColossalAI/issues/6281
Upgrade transformers version from 4.39.3 to 4.51.3.
This PR is for gptj model.
Test:
> Upgrade gptj

- colossalai/shardformer/policies/falcon.py
> fix falcon

- tests/test_shardformer/test_model/test_shard_deepseek.py
> [Fix] remove deepseek test config

- tests/test_lazy/test_models.py
> [fix]fix_lazy_init for deepseek model in transformers

- applications/ColossalChat/coati/distributed/grpo_consumer.py
> [hotfix] Fix pp memory issue.

- applications/ColossalChat/coati/distributed/consumer.py
- applications/ColossalChat/coati/distributed/grpo_consumer.py
> [Fix] Add L2 Regularization
