hpcaitech/ColossalAI

colossalai/shardformer/README.md
colossalai/shardformer/layer/loss.py
colossalai/shardformer/policies/basepolicy.py
colossalai/shardformer/shard/sharder.py

Not involved
fix some typo colossalai/shardformer
detail info
modified:   colossalai/shardformer/README.md
modified:   colossalai/shardformer/layer/loss.py
modified:   colossalai/shardformer/policies/basepolicy.py
modified:   colossalai/shardformer/shard/sharder.py
Make code easier to read
please check

[nfc] fix some typo colossalai/shardformer

---

.github/workflows/build_on_pr.yml
.github/workflows/build_on_schedule.yml

>
N/A
Show the duration of the slowest N tests so that we know which tests to optimize. For `build on pr`, we show the slowest 10 tests to avoid the message from spamming the log. For `build on schedule`, we should durations for all tests as a complete report.

[workflow] show test duration

---

.github/workflows/build_on_schedule.yml
requirements/requirements-test.txt

>
Part of the efforts for #4131 
This PR added xformer to test requirement list.
- [] 🌝 Yes, I do.

[shardformer] supported flash attention test dependency

---

tests/test_utils/test_flash_attention.py

>
#4177 
fix flash attention utils test

[shardformer] fix flash attention utils test

---

colossalai/zero/low_level/low_level_optim.py
tests/test_zero/test_low_level/test_zero_ckpt.py

>
closed #4154 
Provide interface of low level zero's state_dict and load_state_dict.

[zero] add state dict for low level zero

---

colossalai/pipeline/policy/base.py
colossalai/shardformer/policies/auto_policy.py
colossalai/shardformer/policies/base_policy.py
colossalai/shardformer/policies/bert.py
tests/test_pipeline/test_policy/test_bert_for_pretraining_model.py
tests/test_pipeline/test_policy/test_bert_lmhead_model.py
tests/test_pipeline/test_policy/test_bert_model.py
tests/test_pipeline/test_policy/test_bloom_model.py
tests/test_shardformer/test_layer/test_layernorm.py

>
closes #4190 
This pr moves the components of bert model forward into shardformer

[pipeline] move bert related pipeline components to shardformer

---

colossalai/lazy/lazy_init.py
colossalai/shardformer/layer/embedding.py
colossalai/shardformer/layer/linear.py
colossalai/shardformer/layer/normalization.py
colossalai/shardformer/layer/qkv_fused_linear.py
colossalai/shardformer/policies/bert.py
colossalai/shardformer/policies/bloom.py
colossalai/shardformer/policies/gpt2.py
colossalai/shardformer/policies/llama.py
colossalai/shardformer/policies/opt.py
colossalai/shardformer/policies/t5.py
colossalai/shardformer/shard/sharder.py
tests/test_shardformer/test_layer/test_embedding.py
tests/test_shardformer/test_layer/test_layernorm.py
tests/test_shardformer/test_layer/test_linear_1d.py
tests/test_shardformer/test_layer/test_qkv_fused_linear_1d.py
tests/test_shardformer/test_layer/test_vocab_parallel_embedding_1d.py
tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_bert.py
tests/test_shardformer/test_model/test_shard_bloom.py
tests/test_shardformer/test_model/test_shard_gpt2.py
tests/test_shardformer/test_model/test_shard_llama.py
tests/test_shardformer/test_model/test_shard_opt.py
tests/test_shardformer/test_model/test_shard_t5.py
tests/test_shardformer/test_with_torch_ddp.py

>
Closes #4201
Support lazy init for both TP and PP.

[shardformer] support lazy init

---

docker/Dockerfile

>
N/A, a continuation of #4192 
This PR fixed the docker build error due to ninja-build.

[docker] fixed ninja build command

---

colossalai/shardformer/policies/base_policy.py
colossalai/shardformer/policies/bert.py
colossalai/shardformer/shard/sharder.py
tests/kit/model_zoo/torchrec/__init__.py
tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_bert_pipeline.py

>
#4190 
This PR add bert pipeline into shardformer and tests the pipeline forward.

[pipeline] Bert pipeline for shardformer and its tests

---

colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/zero/low_level/low_level_optim.py
colossalai/zero/low_level/readme.md
tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py

[zero] support shard optimizer state dict of zero

---

colossalai/booster/plugin/gemini_plugin.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/utils.py
colossalai/zero/gemini/gemini_optimizer.py
docs/source/en/basics/booster_api.md
docs/source/en/basics/booster_checkpoint.md
docs/source/en/basics/booster_plugins.md
docs/source/zh-Hans/basics/booster_api.md
docs/source/zh-Hans/basics/booster_checkpoint.md
docs/source/zh-Hans/basics/booster_plugins.md
tests/test_checkpoint_io/test_gemini_checkpoint_io.py
tests/test_checkpoint_io/test_gemini_torch_compability.py

>
resolved #4035
Implement sharded optimizer checkpointing feature.
For detailed design, please refer to #4140

[checkpointio] Sharded Optimizer Checkpoint for Gemini Plugin

---

colossalai/shardformer/layer/linear.py
colossalai/shardformer/policies/gpt2.py
colossalai/shardformer/shard/sharder.py
tests/test_shardformer/test_model/test_shard_gpt2.py
tests/test_shardformer/test_model/test_shard_gpt2_pipeline.py

>
#4200
Support pipeline forward for transformers.GPT2Model and add relevant tests.

[pipeline] Add Pipeline Forward for GPT2Model Shardformer

---

colossalai/shardformer/policies/base_policy.py

>
The default value of `sub_module_replacement` and `method_replacement` is None, current code may lead to error.

[shardformer] fix base policy

---

colossalai/shardformer/_utils.py
colossalai/shardformer/layer/__init__.py
colossalai/shardformer/layer/qkv_fused_linear.py
colossalai/shardformer/modeling/sam.py
colossalai/shardformer/policies/autopolicy.py
colossalai/shardformer/policies/sam.py
tests/kit/model_zoo/transformers/__init__.py
tests/kit/model_zoo/transformers/sam.py
tests/test_shardformer/test_layer/test_gpt2_qkv_fused_linear_1d.py
tests/test_shardformer/test_layer/test_qkv_fused_linear_1d.py
tests/test_shardformer/test_model/test_shard_sam.py

>
fixed #4230 
support SAM model and add add fused qkv linear for nn.Linear

[shardformer] support SAM

---

colossalai/shardformer/README.md
colossalai/shardformer/layer/embedding.py
colossalai/shardformer/policies/autopolicy.py
colossalai/shardformer/policies/whisper.py
tests/kit/model_zoo/transformers/__init__.py
tests/kit/model_zoo/transformers/whisper.py
tests/test_shardformer/test_model/test_shard_whisper.py

>
fixed #4211
support whisper model

[shardformer] support whisper

---

colossalai/booster/mixed_precision/mixed_precision_base.py
colossalai/shardformer/README.md

[NFC] Fix format for mixed precision

---

colossalai/cli/benchmark/utils.py

>
> format change: polish colossalai/cli/benchmark/utils.py code style

[NFC] Polish format for benchmark utils

---

applications/Chat/coati/trainer/base.py

[NFC] polish applications/Chat/coati/trainer/base.py code style

---

tests/test_fx/test_tracer/test_hf_model/hf_tracer_utils.py
tests/test_fx/test_tracer/test_hf_model/test_hf_bert.py
tests/test_fx/test_tracer/test_hf_model/test_hf_gpt.py
tests/test_shardformer/test_model/test_pure_pipeline.py

[bugs] hot fix some testing bugs for new models

---

colossalai/communication/utils.py
colossalai/fx/profiler/experimental/profiler_module/embedding.py

fix: format

---

colossalai/zero/low_level/low_level_optim.py

>
closed #4220 
Use fp16/bf16 for step comm.
Optimize the step time.

[zero] optimize the optimizer step time

---

applications/Chat/inference/server.py

[NFC] polish applications/Chat/inference/server.py code style

---

applications/Chat/coati/models/generation.py

[NFC] polish applications/Chat/coati/models/generation.py code style

---

colossalai/shardformer/policies/auto_policy.py
colossalai/shardformer/policies/gpt2.py
tests/kit/model_zoo/torchrec/__init__.py
tests/kit/model_zoo/transformers/gpt.py
tests/test_shardformer/test_model/test_shard_gpt2_pipeline.py

>
resolved #4200
- support shardformer policy & pipeline forward for GPT2ForQuestionAnswering
- change logger to transformers's logger

[pipeline] support shardformer for GPT2ForQuestionAnswering & complete pipeline support for GPT2

---

colossalai/lazy/lazy_init.py
requirements/requirements-test.txt
tests/test_lazy/lazy_init_utils.py
tests/test_lazy/test_models.py

[lazy] support init on cuda

---

colossalai/shardformer/README.md
colossalai/shardformer/modeling/blip2.py
colossalai/shardformer/modeling/sam.py
colossalai/shardformer/policies/autopolicy.py
colossalai/shardformer/policies/blip2.py
tests/kit/model_zoo/transformers/__init__.py
tests/kit/model_zoo/transformers/blip2.py
tests/test_booster/test_plugin/test_gemini_plugin.py
tests/test_booster/test_plugin/test_low_level_zero_plugin.py
tests/test_lazy/test_distribute.py
tests/test_shardformer/test_model/test_shard_blip2.py

>
fixed #4242 
support blip2 model

[shardformer] support Blip2

---

colossalai/shardformer/modeling/vit.py
colossalai/shardformer/policies/auto_policy.py
colossalai/shardformer/policies/vit.py
tests/kit/model_zoo/transformers/__init__.py
tests/kit/model_zoo/transformers/vit.py
tests/test_shardformer/test_model/test_shard_vit.py
tests/test_shardformer/test_model/test_shard_vit_pipeline.py

>
fixed #4285 
support pipeline for vit model

[shardformer] support pipeline base vit model 

---

colossalai/shardformer/README.md
colossalai/shardformer/modeling/blip2.py
colossalai/shardformer/modeling/sam.py
colossalai/shardformer/policies/autopolicy.py
colossalai/shardformer/policies/blip2.py
colossalai/shardformer/policies/chatglm.py
colossalai/shardformer/policies/vit.py
tests/kit/model_zoo/transformers/__init__.py
tests/kit/model_zoo/transformers/blip2.py
tests/kit/model_zoo/transformers/chatglm.py
tests/test_booster/test_plugin/test_gemini_plugin.py
tests/test_booster/test_plugin/test_low_level_zero_plugin.py
tests/test_lazy/test_distribute.py
tests/test_shardformer/test_model/test_shard_blip2.py

[shardformer] merge blip2/chatglm 

---

colossalai/shardformer/layer/_operation.py
colossalai/shardformer/layer/linear.py
tests/test_shardformer/test_layer/test_linear_1d.py

>
fixed #4335 
add sequence parallel linear col/row support

[sequence parallel] add sequence parallel linear col/row support

---

applications/Chat/coati/dataset/conversation.py
applications/Chat/coati/dataset/sft_dataset.py
applications/Chat/examples/README.md
applications/Chat/examples/generate_conversation_dataset.py
applications/Chat/examples/train_sft.py

>
Support session-based training.

[Chat] support session-based training

---

applications/Chat/coati/models/bloom/triton_attention_forward.py
applications/Chat/coati/trainer/strategies/tp/policy.py
colossalai/kernel/triton/ops.py
colossalai/kernel/triton/qkv_matmul_kernel.py
colossalai/kernel/triton/softmax_kernel.py
tests/test_kernels/test_self_attention.py
tests/test_kernels/test_softmax.py

>
add kernel and policy for bloom attention

[Kernel&Policy]add kernel and policy for bloom attention

---

applications/Chat/coati/models/bloom/triton_attention_forward.py
applications/Chat/requirements.txt
colossalai/kernel/triton/ops.py
colossalai/kernel/triton/qkv_matmul_kernel.py

>
fix issues for compute attention_bloom

[Kernel]fix issues for compute attention_bloom

---

colossalai/cli/launcher/hostinfo.py

>
fixed #4318 
The error msg in the issue shows that each node thinks it is the localhost, and here is the question.
I print the `localaddrs` and `hostaddrs` of the second node:
```
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.1.1', 22)), 
(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.1.1', 22)), 
(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('127.0.1.1', 22)), 
(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.0.64', 22)), …
```

[hotfix] fix localhost measurement

---

examples/images/diffusion/requirements.txt

There are 1 security vulnerabilities found in gradio 3.11
- [CVE-2023-25823](https://www.oscs1024.com/hd/CVE-2023-25823)
Upgrade gradio from 3.11 to 3.34.0 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

[hotfix] upgrade gradio to 3.34.0

---

colossalai/shardformer/layer/embedding.py
tests/kit/model_zoo/transformers/bert.py
tests/kit/model_zoo/transformers/bloom.py
tests/kit/model_zoo/transformers/gpt.py
tests/kit/model_zoo/transformers/opt.py
tests/kit/model_zoo/transformers/whisper.py
tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_bert.py
tests/test_shardformer/test_model/test_shard_blip2.py
tests/test_shardformer/test_model/test_shard_bloom.py
tests/test_shardformer/test_model/test_shard_gpt2.py
tests/test_shardformer/test_model/test_shard_llama.py
tests/test_shardformer/test_model/test_shard_opt.py
tests/test_shardformer/test_model/test_shard_sam.py
tests/test_shardformer/test_model/test_shard_t5.py
tests/test_shardformer/test_model/test_shard_vit.py
tests/test_shardformer/test_model/test_shard_whisper.py

>
fixed #4368 
Hotfix/fix some model test and refactor check util api
TODO: gpt2 test has some bugs, skip in this pr

[test] Hotfix/fix some model test and refactor check util api

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
tests/kit/model_zoo/transformers/gpt.py
tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_gpt2.py

… test
>
- create several utility functions for testing, so that test codes can be shorter and clearer

[shardformer] add util functions for shardformer tests/fix sync_shared_param

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/kernel/cuda_native/flash_attention.py
colossalai/kernel/cuda_native/scaled_softmax.py
colossalai/shardformer/layer/_operation.py
colossalai/shardformer/layer/linear.py
colossalai/shardformer/layer/qkv_fused_linear.py
colossalai/shardformer/modeling/gpt2_seq.py
colossalai/shardformer/policies/base_policy.py
colossalai/shardformer/policies/gpt2.py
colossalai/shardformer/shard/shard_config.py
requirements/requirements-test.txt
tests/kit/model_zoo/__init__.py
tests/kit/model_zoo/transformers/gpt.py
tests/test_shardformer/test_layer/test_gpt2_qkv_fused_linear_1d.py
tests/test_shardformer/test_layer/test_linear_1d.py
tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_gpt2.py
tests/test_utils/test_flash_attention.py

>
fixed #4383 
Support sequence parallel for gpt2

[shardformer/sequence parallel] Support sequence parallel for gpt2

---

requirements/requirements-test.txt
requirements/requirements.txt
tests/test_utils/test_flash_attention.py

>
update coloattention tests for checking outputs and gradients.

[Coloattention] update coloattention tests for checking outputs and gradients

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
requirements/requirements-test.txt
requirements/requirements.txt
tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_gpt2.py

>
#4390 
test GPT-2 to check flash attention 2 in conjunction with pipeline and amp.

[shardformer]  test gpt2 for all optimizations.

---

colossalai/shardformer/layer/_operation.py
colossalai/shardformer/layer/linear.py
tests/kit/model_zoo/__init__.py
tests/test_shardformer/test_layer/test_linear_1d.py

>
fixed #4400 
Overlap input gather and grad computation during col backward, support linear so far

[shardformer/sequence parallel] Overlap input gather and grad computation during col backward

---

tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_gpt2.py

>
fix, test gpt2 for AMP+TP
#4390 

[shardformer]fix, test gpt2 for AMP+TP

---

colossalai/zero/low_level/bookkeeping/bucket_store.py
colossalai/zero/low_level/low_level_optim.py
tests/test_zero/test_low_level/test_zero1_2.py

>
fixed #4402 
This PR adds stream synchronization and improves the tensor bucket for async adding param and reducing grad.

[hotfix] fix unsafe calculation in zero

---

colossalai/cluster/process_group_mesh.py
colossalai/pipeline/p2p.py
colossalai/pipeline/schedule/interleaved_pp.py
colossalai/pipeline/stage_manager.py
tests/test_pipeline/test_schedule/test_interleaved.py
tests/test_pipeline/test_stage_manager.py

>
closed #4447 
1. This PR mainly supports interleaved schedule with the new coordinate.
2. Weaken the p2p ops. Things like examing if the first/last stage should be done in schedule.
3. Support a ring group, e.g. the prev_rank of rank0 is the last rank, and the next_rank of the last rank is rank0.
4. Remove useless codes.

[shardformer] support interleaved pipeline

---

examples/images/resnet/README.md
examples/images/resnet/train.py

>
- Update resnet example to fit gemini plugin.
- Update training result

[example] update resnet example result

---

examples/language/bert/README.md
examples/language/bert/finetune.py

>
- Update bert exampe to fit gemini.
- Add finetune result.

[example] update bert example result

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
tests/test_shardformer/test_model/test_shard_bert.py
tests/test_shardformer/test_model/test_shard_bloom.py
tests/test_shardformer/test_model/test_shard_chatglm.py
tests/test_shardformer/test_model/test_shard_gpt2.py
tests/test_shardformer/test_model/test_shard_llama.py
tests/test_shardformer/test_model/test_shard_opt.py
tests/test_shardformer/test_model/test_shard_t5.py
tests/test_shardformer/test_model/test_shard_vit.py

>
#4453
- support tp+zero for hybridplugin & add relevant tests
- support input type cast for hybridplugin

[shardformer] support tp+zero for shardformer

---

examples/images/dreambooth/test_ci.sh
examples/images/dreambooth/train_dreambooth_colossalai.py
examples/images/dreambooth/train_dreambooth_colossalai_lora.py
examples/images/vit/vit_benchmark.py
examples/images/vit/vit_train_demo.py
examples/language/gpt/gemini/run_gemini.sh
examples/language/gpt/gemini/test_ci.sh
examples/language/gpt/gemini/train_gpt_demo.py
examples/language/opt/opt_benchmark.py
examples/language/opt/opt_train_demo.py
examples/language/palm/train.py

>
Update images and language examples related to gemini (besides diffusion, as diffusion example uses lightning).

[example] update gemini related examples

---

tests/kit/model_zoo/transformers/bert.py
tests/test_booster/test_plugin/test_gemini_plugin.py
tests/test_shardformer/test_model/test_shard_gpt2.py

[hotfix] fix bert in model zoo

---

colossalai/shardformer/modeling/gpt2.py
colossalai/shardformer/policies/opt.py

[shardformer/sequence parallel] not support opt of seq-parallel, add warning and fix a bug in gpt2 pp

---

tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_bert.py
tests/test_shardformer/test_model/test_shard_bloom.py
tests/test_shardformer/test_model/test_shard_chatglm2.py
tests/test_shardformer/test_model/test_shard_gpt2.py
tests/test_shardformer/test_model/test_shard_llama.py
tests/test_shardformer/test_model/test_shard_opt.py
tests/test_shardformer/test_model/test_shard_t5.py
tests/test_shardformer/test_model/test_shard_vit.py
tests/test_shardformer/test_model/test_shard_whisper.py

>
This PR adds test for all models that support 3d parallelism now

[shardformer]tests for 3d parallel

---

LICENSE
colossalai/gptq/__init__.py
colossalai/gptq/cai_gptq/__init__.py
colossalai/gptq/cai_gptq/cai_quant_linear.py
colossalai/gptq/cai_gptq/gptq_op.py
colossalai/gptq/cai_gptq/gptq_triton.py
colossalai/kernel/cuda_native/csrc/gptq/column_remap.cu
colossalai/kernel/cuda_native/csrc/gptq/column_remap.cuh
colossalai/kernel/cuda_native/csrc/gptq/cu_compat.cuh
colossalai/kernel/cuda_native/csrc/gptq/cuda_buffers.cu
colossalai/kernel/cuda_native/csrc/gptq/cuda_buffers.cuh
colossalai/kernel/cuda_native/csrc/gptq/hip_compat.cuh
colossalai/kernel/cuda_native/csrc/gptq/linear_gptq.cpp
colossalai/kernel/cuda_native/csrc/gptq/matrix.cuh
colossalai/kernel/cuda_native/csrc/gptq/q4_matmul.cu
colossalai/kernel/cuda_native/csrc/gptq/q4_matmul.cuh
colossalai/kernel/cuda_native/csrc/gptq/q4_matrix.cu
colossalai/kernel/cuda_native/csrc/gptq/q4_matrix.cuh
colossalai/kernel/cuda_native/csrc/gptq/tuning.h
colossalai/kernel/cuda_native/csrc/gptq/util.cuh
op_builder/gptq.py
tests/test_gptq/test_gptq_linear.py

[gptq] faster gptq cuda kernel

---

colossalai/shardformer/modeling/llama.py
colossalai/shardformer/policies/auto_policy.py
colossalai/shardformer/policies/llama.py
colossalai/shardformer/shard/shard_config.py
colossalai/shardformer/shard/sharder.py
tests/kit/model_zoo/torchrec/__init__.py
tests/test_infer/_utils.py
tests/test_infer/test_llama_infer.py

>
This PR creates a llama infer demo as inference  template.

[infer] Infer/llama demo

---

colossalai/kernel/triton/token_attention_kernel.py
tests/test_kernels/triton/test_token_attn_1.py
tests/test_kernels/triton/test_token_attn_2.py
tests/test_kernels/triton/test_token_attn_fwd.py
tests/test_kernels/triton/test_token_softmax.py

[Kernels]  add inference token attention kernel

---

colossalai/pipeline/schedule/one_f_one_b.py
colossalai/zero/low_level/low_level_optim.py
tests/kit/model_zoo/torchrec/__init__.py
tests/test_shardformer/test_model/test_shard_bert.py
tests/test_shardformer/test_model/test_shard_bloom.py
tests/test_shardformer/test_model/test_shard_gpt2.py
tests/test_shardformer/test_model/test_shard_llama.py
tests/test_shardformer/test_model/test_shard_opt.py
tests/test_shardformer/test_model/test_shard_t5.py
tests/test_shardformer/test_model/test_shard_vit.py
tests/test_shardformer/test_model/test_shard_whisper.py

>
This PR add zero1 + pp and corresponding tests for all supported models, left some questions to be fixed

[shardformer] zero1+pp and the corresponding tests

---

colossalai/pipeline/schedule/_utils.py
tests/test_shardformer/test_model/_utils.py

>
Fixed several bugs after updating the version of transformers from 4.30.2 to 4.32.0:
- fix check_output_hidden_states in testing utils
- fix the merging of loss in merge_batch of pipeline

[shardformer] fix emerged bugs after updating transformers

---

colossalai/shardformer/layer/_operation.py
colossalai/shardformer/layer/qkv_fused_linear.py
colossalai/shardformer/policies/base_policy.py
colossalai/shardformer/policies/gpt2.py
tests/test_shardformer/test_layer/test_gpt2_qkv_fused_linear_1d.py

>
fixed #4534
Add overlap support for gpt2

[shardformer] Add overlap support for gpt2

---

examples/images/diffusion/requirements.txt

There are 1 security vulnerabilities found in streamlit 0.73.1
- [CVE-2022-35918](https://www.oscs1024.com/hd/CVE-2022-35918)
Upgrade streamlit from 0.73.1 to 1.11.1 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

[example] upgrade streamlit to 1.11.1

---

.github/workflows/build_on_pr.yml
.github/workflows/compatiblity_test_on_pr.yml
.github/workflows/doc_check_on_pr.yml
.github/workflows/doc_test_on_pr.yml
.github/workflows/example_check_on_pr.yml

>
Current CI won't cancel previous runs which will waste a lot of time. This PR allows CI to cancel previous runs.

[devops] cancel previous runs in the PR

---

colossalai/shardformer/shard/sharder.py
tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py
tests/test_shardformer/test_model/test_shard_chatglm2.py
tests/test_shardformer/test_model/test_shard_gpt2.py
tests/test_shardformer/test_model/test_shard_opt.py

>
- Fix the bug of not replacing embedding layers when pp is enabled.

[shardformer] fix submodule replacement bug when enabling pp

---

colossalai/inference/tensor_parallel/kvcache_manager.py
colossalai/inference/tensor_parallel/modeling/bloom.py

>
- Fix doctoring/comments for inference

[NFC] Fix docstring in kv cache manager and bloom modeling

---

colossalai/inference/tensor_parallel/modeling/llama.py

[NFC] Fix docstring in llamal modeling

---

colossalai/gptq/cai_gptq/cai_quant_linear.py
colossalai/gptq/gptq_tp.py
colossalai/gptq/models/__init__.py
colossalai/gptq/models/bloom.py
colossalai/gptq/models/llama.py
examples/inference/gptq_llama.py
tests/test_gptq/test_gptq_linear.py

[gptq] add gptq tensor parallel

---

colossalai/inference/tensor_parallel/modeling/llama.py
colossalai/shardformer/modeling/llama.py

[Infer] check import vllm

---

colossalai/inference/README.md

>
This PR is used to add installation req for colossal-inference 

[DOC] add installation req

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/utils.py
colossalai/zero/gemini/gemini_ddp.py
colossalai/zero/gemini/gemini_optimizer.py
tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py

>
#4477
- Support sharded saving for optimizers of HybridParallelPlugin
- Support sharded loading for optimizers of HybridParallelPlugin
- Add relevant tests
- Refactor some util functions iof checkpointIO

[shardformer] support sharded optimizer checkpointIO of HybridParallelPlugin

---

colossalai/inference/README.md
colossalai/inference/tensor_parallel/modeling/llama.py
colossalai/inference/tensor_parallel/policies/llama.py
colossalai/shardformer/modeling/llama.py

>
This PR is used to add rms_norm ops into colossalai's tensor parallel policy 

[Feature] rms-norm transfer into inference llama.py 

---

colossalai/inference/tensor_parallel/modeling/llama.py
colossalai/shardformer/modeling/llama.py

[Infer] reset to previous llama attention forward

---

colossalai/inference/README.md

>
add benchmarking of llama and bloom

[doc] complete README of colossal inference

---

colossalai/inference/README.md

[doc]update readme

---

.github/workflows/build_on_pr.yml
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/utils.py
tests/test_checkpoint_io/test_huggingface_compatibility.py
tests/test_checkpoint_io/test_hybrid_huggingface_compatibility.py

>
#4568 #4547
- support from_pretrained when loading model with HybridParallelPlugin
- add Huggingface compatibility tests
- support folder cleaning when saving sharded model/optimizer

[shardformer] support from_pretrained when loading model with HybridParallelPlugin

---

colossalai/zero/low_level/low_level_optim.py
tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
tests/test_zero/test_low_level/test_zero_ckpt.py

>
fixed #4528
described in the issue.

[zero]fix zero ckptIO with offload

---

op_builder/utils.py

>
`torch.cuda.get_arch_list()` here:
https://github.com/hpcaitech/ColossalAI/blob/5187c96b7c04ac6c794a58044533c874fa24e206/op_builder/utils.py#L200
will get the available GPU arch for the current PyTorch lib. For example, the PyTorch 2.0 is built by the hopper arch GPU, it will return a list:
`['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'sm_90']`
However, my GPU is an ampere arch GPU, return a list includes `sm_90` here will cause an compile error like:
nvcc fatal   : Unsupported gpu architecture 'compute_90'.
Therefore, I think the valid arch returned here should be >= `sm60` but <= `sm86`, which is the max …

[Fix] Fix compile error

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/pipeline/schedule/one_f_one_b.py
tests/test_pipeline/test_schedule/test_oneF_oneB.py

>
Current 1f1b schedule only receives `num_microbatches`. This is hard to set in some cases. Now it also receives `microbatch_size`.

[pipeline] 1f1b schedule receive microbatch size

---

colossalai/inference/tensor_parallel/modeling/llama.py
colossalai/inference/tensor_parallel/policies/llama.py
tests/test_infer/test_bloom_infer.py
tests/test_infer/test_infer_engine.py
tests/test_infer/test_kvcache_manager.py
tests/test_infer/test_llama_infer.py
tests/test_infer_ops/triton/test_llama_context_attention.py
tests/test_infer_ops/triton/utils.py

[BUG FIX]Fix test engine in CI and non-vllm kernels llama forward 

---

colossalai/inference/tensor_parallel/modeling/llama.py
colossalai/inference/tensor_parallel/policies/llama.py
colossalai/kernel/triton/__init__.py
colossalai/kernel/triton/rms_norm.py
tests/test_infer/test_bloom_infer.py
tests/test_infer/test_infer_engine.py
tests/test_infer/test_kvcache_manager.py
tests/test_infer/test_llama_infer.py
tests/test_infer_ops/triton/test_llama_context_attention.py
tests/test_infer_ops/triton/utils.py

[Kernel]Rmsnorm fix

---

examples/language/llama2/README.md

[doc] add llama2 benchmark

---

colossalai/pipeline/schedule/_utils.py
colossalai/pipeline/schedule/one_f_one_b.py
colossalai/shardformer/policies/chatglm2.py
tests/kit/model_zoo/torchrec/__init__.py
tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_bert.py

>
This PR fixes pytree flatten caused bugs

[shardformer] Pytree fix

---

colossalai/inference/tensor_parallel/policies/bloom.py
colossalai/kernel/triton/__init__.py
colossalai/kernel/triton/fused_layernorm.py
tests/test_infer/test_bloom_infer.py
tests/test_infer_ops/triton/test_layernorm.py

>
- Add triton layer norm kernel used by inference
- Revise bloom inference policy and apply triton layer norm replacement
- (trivial) modify bloom test model path

[kernel] Add triton layer norm & replace norm for bloom

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/shardformer/layer/_operation.py

- [] I have created an issue for this PR for traceability
>
Add overlap optional for HybridParallelPlugin
- [] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))

[shardformer] Add overlap optional for HybridParallelPlugin

---

colossalai/shardformer/README.md
examples/language/bert/README.md

>
#4584 
adding fine-tuned result of bert to shardformer's readme.

[shardformer] adding fine-tuned result of bert to readme.

---

colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/interface/__init__.py
colossalai/interface/model.py
colossalai/zero/low_level/low_level_optim.py
tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py

>
Master params are not synchronized after loading model checkpoint. This PR fix this problem.

[zero] hotfix master param sync

---

tests/test_checkpoint_io/test_plugins_huggingface_compatibility.py
tests/test_shardformer/test_model/test_shard_gpt2.py

[test] fix gemini checkpoint and gpt test

---

colossalai/inference/README.md
examples/inference/bench_bloom.py

- Add bloom benchmark for inference
- update readme with benchmark results
- revise readme - llama benchmark results

[bench] Add bloom inference benchmark

---

colossalai/inference/tensor_parallel/engine.py
colossalai/inference/tensor_parallel/kvcache_manager.py
colossalai/shardformer/modeling/llama.py
colossalai/shardformer/shard/shard_config.py
tests/test_infer/test_infer_engine.py

>
This PR hot fix some bugs and typos

[Inference] Hot fix some bugs and typos

---

colossalai/shardformer/modeling/llama.py
tests/test_infer_ops/triton/test_bloom_context_attention.py
tests/test_infer_ops/triton/test_copy_kv_dest.py
tests/test_infer_ops/triton/test_layernorm_triton.py
tests/test_infer_ops/triton/test_llama_context_attention.py
tests/test_infer_ops/triton/test_rotary_embedding.py
tests/test_infer_ops/triton/test_token_attn_1.py

[typo]Comments fix

---

colossalai/inference/tensor_parallel/engine.py
examples/inference/bench_bloom.py
examples/inference/bench_llama.py
tests/test_infer/test_bloom_infer.py
tests/test_infer/test_infer_engine.py
tests/test_infer/test_llama_infer.py

>
Fix based on comments in https://github.com/hpcaitech/ColossalAI/pull/4577
- revise TPInferEngine methods, hide the creation and calling of shardformer from users
- modify engine test, bloom and llama tests based on engine change
- modify llama/bloom benchmark based on engine change 

[Fix] Revise TPInferEngine, inference tests and benchmarks

---

colossalai/booster/booster.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/pp_plugin_base.py
colossalai/pipeline/schedule/base.py
colossalai/pipeline/schedule/interleaved_pp.py
colossalai/pipeline/schedule/one_f_one_b.py
examples/language/bert/finetune.py
tests/test_pipeline/test_schedule/test_interleaved.py
tests/test_pipeline/test_schedule/test_oneF_oneB.py

>
- set optimizer argument to optional in execute_pipeline, since optimizer is not needed in evaluation
- move logging message to dist_logger when initializing booster

[pipeline] set optimizer to optional in execute_pipeline

---

colossalai/inference/pipeline/modeling/llama.py
colossalai/inference/pipeline/policy/llama_ppinfer.py

>
support llama pipeline inference

[Pipeline inference] support llama pipeline inference

---

.github/workflows/build_on_pr.yml
.github/workflows/compatiblity_test_on_dispatch.yml
.github/workflows/compatiblity_test_on_pr.yml
.github/workflows/compatiblity_test_on_schedule.yml
.github/workflows/doc_check_on_pr.yml
.github/workflows/doc_test_on_pr.yml
.github/workflows/example_check_on_pr.yml

>
- Jobs in one workflow file should have different concurrency group, otherwise they will cancel each other.
- Installation of tensornvme and colossalai in compatibility test is wrong.
Fix these problems in this PR.

[devops] fix concurrency group and compatibility test

---

colossalai/inference/tensor_parallel/engine.py
examples/inference/bench_bloom.py
examples/inference/bench_llama.py
tests/test_infer/test_bloom_infer.py
tests/test_infer/test_infer_engine.py
tests/test_infer/test_llama_infer.py

>
- revise TPInferEngine for inference based on feedbacks

[Infer] Fix TPInferEngine init & inference tests, benchmarks

---

examples/inference/bench_bloom.py
examples/inference/bench_llama.py

>
- Use args instead of absolute paths for inference benchmarks

[Infer/nfc] Add args for inference benchmarks

---

colossalai/inference/tensor_parallel/engine.py
examples/inference/bench_bloom.py
examples/inference/bench_llama.py
tests/test_infer/test_bloom_infer.py
tests/test_infer/test_infer_engine.py
tests/test_infer/test_llama_infer.py

- Instead of calling `optimize_model()` by users, we now optimize the original model in engine init and only keep the optimized model in engine.

[Fix] optimize/shard model in TPInferEngine init

---

colossalai/shardformer/modeling/gpt2.py
tests/kit/model_zoo/transformers/gpt.py
tests/test_booster/test_plugin/test_gemini_plugin.py
tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_gpt2.py

>
fix GPT2DoubleHeadsModel test failed.

[shardformer]fix gpt2 double head

---

colossalai/moe/__init__.py
colossalai/moe/experts.py
colossalai/moe/layers.py
colossalai/moe/routers.py
tests/test_moe/test_moe_router.py

[moe]: add top k router

---

colossalai/booster/booster.py
docs/source/en/basics/booster_api.md
docs/source/en/basics/booster_checkpoint.md
docs/source/en/basics/booster_plugins.md
docs/source/zh-Hans/basics/booster_api.md
docs/source/zh-Hans/basics/booster_checkpoint.md
docs/source/zh-Hans/basics/booster_plugins.md

>
#4628
- Rewrite some docstrings in booster.py
- Update user documents of booster, including booster_api.md, booster_checkpoint.md and booster_plugins.md

[doc] Update booster user documents.

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/checkpoint_io/__init__.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py

[hotfix] fix typo in hybrid parallel io

---

colossalai/moe/routers.py
examples/language/openmoe/model/modeling_openmoe.py

[moe]: modify router loss, polish code

---

examples/language/llama2/README.md

>
Many users have reported OOM bug when running llama example script, such as #4578
Add explanation on how to solve the OOM error.

[doc] add potential solution for OOM in llama2 example

---

colossalai/shardformer/modeling/gpt2.py

[shardformer] fix GPT2DoubleHeadsModel

---

colossalai/kernel/triton/llama_act_combine_kernel.py
colossalai/moe/_operation.py
colossalai/moe/experts.py
colossalai/moe/layers.py
examples/language/openmoe/infer.py
examples/language/openmoe/model/modeling_openmoe.py
tests/test_kernels/test_llama_act_combine.py

* store rotary embedding in llama, speed up ~10%
* use act combine kernel in mlp activation, speed up ~5%

[moe] speed up embed and mlp

---

colossalai/gptq/cai_gptq/cai_quant_linear.py
colossalai/gptq/gptq_tp.py
colossalai/inference/tensor_parallel/engine.py
colossalai/inference/tensor_parallel/policies/bloom.py
colossalai/inference/tensor_parallel/policies/llama.py
colossalai/shardformer/shard/shard_config.py
examples/inference/gptq_bloom.py
examples/inference/gptq_llama.py
tests/test_gptq/test_gptq_linear.py

>
Combine gptq and kv cache manager.
TODO: change replace linear module to shardformer.

[gptq] combine gptq and kv cache manager

---

colossalai/inference/tensor_parallel/modeling/bloom.py
colossalai/inference/tensor_parallel/modeling/llama.py
colossalai/inference/tensor_parallel/policies/bloom.py
colossalai/inference/tensor_parallel/policies/llama.py
colossalai/kernel/__init__.py
colossalai/kernel/triton/__init__.py

>
- Triton kernels were imported and added to `colossalai.kernel.__init__.py`, and thus importing `colossalai.kernel` without triton installed would cause import error. 
- Move triton kernel imports from kernel init to kernel.triton init

[hotfix] Fix import error: colossal.kernel without triton installed

---

colossalai/shardformer/README.md
colossalai/shardformer/policies/whisper.py

>
to fix whisper test failed due to significant accuracy differences.

[shardformer] to fix whisper test failed due to significant accuracy differences.

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/shardformer/README.md
colossalai/shardformer/shard/shard_config.py
docs/source/en/basics/booster_api.md
docs/source/en/basics/booster_plugins.md
docs/source/en/features/1D_tensor_parallel.md
docs/source/en/features/shardformer.md
docs/source/zh-Hans/basics/booster_api.md
docs/source/zh-Hans/basics/booster_plugins.md
docs/source/zh-Hans/features/1D_tensor_parallel.md
docs/source/zh-Hans/features/shardformer.md

>
resolved #4628 #4649
- Add user document for Shardformer
- Update tensor parallel user documents (1d/2d/2.5d/3d) by removing lagacy usages
- Polish docstring of ShardConfig

[doc] Add user document for Shardformer

---

docs/source/en/features/pipeline_parallel.md
docs/source/zh-Hans/features/pipeline_parallel.md

>
#4691 
update pipeline parallel document

[shardformer] update pipeline parallel document

---

colossalai/booster/plugin/hybrid_parallel_plugin.py

>
resolved #4717 
add custom policy arg in hybrid parallel plugin 

[shardformer] add custom policy in hybrid parallel plugin

---

docs/source/en/basics/booster_checkpoint.md
docs/source/zh-Hans/basics/booster_checkpoint.md

>
add explanation for the loading issue mentioned in #4578

[doc] explaination of loading large pretrained models

---

colossalai/kernel/triton/__init__.py

>
fixed #4739 
update triton kernel init

[kernel] update triton init

---

colossalai/moe/routers.py
examples/language/openmoe/benchmark/benchmark_train.py
examples/language/openmoe/benchmark/benchmark_train.sh
examples/language/openmoe/benchmark/utils.py
examples/language/openmoe/model/modeling_openmoe.py

[moe]: add flash attention & optimize top2 router

---

docs/source/en/basics/booster_plugins.md
docs/source/zh-Hans/basics/booster_plugins.md

[doc] explain suitable use case for each plugin

---

colossalai/amp/naive_amp/mixed_precision_optimizer.py
colossalai/booster/booster.py
colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/booster/plugin/torch_ddp_plugin.py
colossalai/booster/plugin/torch_fsdp_plugin.py
colossalai/checkpoint_io/checkpoint_io_base.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/utils.py
colossalai/interface/optimizer.py
colossalai/zero/gemini/gemini_ddp.py
colossalai/zero/low_level/low_level_optim.py
tests/test_checkpoint_io/test_plugins_huggingface_compatibility.py

>
resolved #4711
resolved #4751 
- rewrite the logic of updating master params in load_sharded_model of HybridPlugin's checkpointIO, disentangle hybrid plugin and its checkpointIO
- rewrite the logic of unwrapping models/optimizers during loading/saving.
- fix the bug mentioned in #4751

[shardformer] fix master param sync for hybrid plugin/rewrite unwrapping logic

---

colossalai/legacy/__init__.py
examples/community/roberta/pretraining/arguments.py
examples/images/vit/args.py
examples/images/vit/run_benchmark.sh
examples/images/vit/run_demo.sh
examples/images/vit/test_ci.sh
examples/language/gpt/titans/train_gpt.py
examples/language/opt/args.py
examples/language/opt/run_benchmark.sh
examples/language/opt/run_demo.sh
examples/language/opt/test_ci.sh
examples/language/palm/run.sh
examples/language/palm/test_ci.sh
examples/language/palm/train.py

>
- some examples use get_default_parser function, which has been moved to legacy

[bug] fix get_default_parser in examples

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
colossalai/moe/manager.py
colossalai/tensor/moe_tensor/api.py
colossalai/tensor/moe_tensor/moe_info.py
examples/language/openmoe/model/llama_policy.py
examples/language/openmoe/model/modeling_openmoe.py
examples/language/openmoe/model/openmoe_policy.py
examples/language/openmoe/test_ci.sh
examples/language/openmoe/train.py
examples/language/openmoe/train.sh

support hybrid parallel with pp + dp + ep
* add custom shard policy for openmoe
* add moe hybrid plugin which modifies some init settings of original hybrid plguin
* updata parallel process group mesh in moe
* use layernorm kernel and jit fuse in shardformer

[moe] support hybrid parallel

---

applications/Chat/coati/models/lora.py
applications/Chat/examples/train_prompts.py
applications/Chat/examples/train_reward_model.py
applications/Chat/examples/train_sft.py

[chat]: add lora merge weights config

---

colossalai/inference/pipeline/engine.py
colossalai/inference/pipeline/microbatch_manager.py
colossalai/pipeline/p2p.py
colossalai/pipeline/schedule/generate.py

[pipeline inference] Fix the blocking of communication when ppsize is 2

---

colossalai/cli/launcher/run.py

🚨 Issue number
fixed #4714 
This pull request addresses the following bug:
Bug Description: When the Torch version is greater than 2.0, the colossal run generates a command that is suitable for versions below 1.9.

[bug] Fix the version check bug in colossalai run when generating the cmd.

---

colossalai/inference/continous_batching/layers/attention.py
colossalai/inference/tensor_parallel/engine.py
colossalai/inference/tensor_parallel/utils.py
examples/inference/bench_llama_continous_batching.py
examples/inference/test_continous_batching.py
tests/test_infer/test_bloom_infer.py
tests/test_infer/test_infer_engine.py
tests/test_infer/test_kvcache_manager.py
tests/test_infer/test_llama_infer.py

[infer]Add Continous batching and pageattention

---

colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
docs/source/en/basics/booster_plugins.md
docs/source/zh-Hans/basics/booster_plugins.md
tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py

>
resolved #4767 
support unsharded checkpoint for hybrid parallel

[checkpointio] support unsharded checkpointIO for hybrid parallel

---

.github/workflows/build_on_pr.yml
.github/workflows/build_on_schedule.yml
.github/workflows/compatiblity_test_on_dispatch.yml
.github/workflows/compatiblity_test_on_pr.yml
.github/workflows/compatiblity_test_on_schedule.yml
colossalai/booster/booster.py
colossalai/interface/pretrained.py
colossalai/lazy/lazy_init.py
colossalai/lazy/pretrained.py
tests/test_checkpoint_io/test_gemini_checkpoint_io.py
tests/test_lazy/test_from_pretrained.py

>
Closes #4296 
Support `from_pretrained()` for lazy init context. This must be used with booster.

[lazy] support from_pretrained

---

applications/Colossal-LLaMA-2/README.md

change filename:
pretraining.py -> trainin.py
there is no file named pretraing.py. wrong writing
>

[hotfix] change llama2 Colossal-LLaMA-2 script filename

---

colossalai/lazy/lazy_init.py
docs/sidebars.json
docs/source/en/basics/booster_api.md
docs/source/en/features/lazy_init.md
docs/source/zh-Hans/basics/booster_api.md
docs/source/zh-Hans/features/lazy_init.md

[doc] add lazy init docs

---

colossalai/zero/low_level/_utils.py

>
fix norm type error in zero optimizer

[bug] fix norm type error in zero optimizer

---

colossalai/shardformer/policies/base_policy.py
colossalai/zero/low_level/bookkeeping/bucket_store.py

>
Correct several erroneous code comments

[polish code] Correct several erroneous code comments

---

op_builder/gptq.py

[NFC] Fix format for gptq

---

colossalai/inference/pipeline/benchmark/benchmark.py
colossalai/inference/pipeline/benchmark/run.sh
colossalai/inference/pipeline/engine.py
colossalai/pipeline/p2p.py
colossalai/pipeline/schedule/generate.py

[Pipeline inference] Refactor code, add docsting, fix bug

---

colossalai/inference/pipeline/README.md

>
- [ x I have added docstrings for all the functions/methods I implemented

[Pipeline inference] Add pipeline inference docs

---

applications/Colossal-LLaMA-2/README.md
applications/ColossalEval/README.md

>
1. Add Qwen-7B, internlm-20b results in ColossalEval.
2. Add original in Qwen-7B results in Colossal Llama.

[feature] Update Colossal Llama and ColossalEval readme.

---

applications/README.md

[doc] Update ColossalChat README

---

colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
colossalai/moe/checkpoint.py
examples/language/openmoe/benchmark/benchmark_cai.py
examples/language/openmoe/benchmark/benchmark_cai.sh
examples/language/openmoe/benchmark/benchmark_fsdp.py
examples/language/openmoe/benchmark/benchmark_fsdp.sh
examples/language/openmoe/model/modeling_openmoe.py
examples/language/openmoe/model/openmoe_policy.py
examples/language/openmoe/test_ci.sh
examples/language/openmoe/train.py
tests/test_moe/test_moe_checkpoint.py

* update benchmark scrpits
* fix some bugs
* update pp layer distribution
* update ckpt io

[moe] update benchmark scripts and ckpt io

---

colossalai/inference/tensor_parallel/modeling/__init__.py
colossalai/kernel/triton/__init__.py
examples/inference/serving/ray_serve/Colossal_Inference_rayserve.py
examples/inference/serving/ray_serve/README.md
examples/inference/serving/ray_serve/send_request.py
examples/inference/serving/ray_serve/send_requests.py

- This PR adds necessary files for Colossal Inference serving with Ray Serve. Steps of deployment were added into README.
- This demo is used for testing and demonstrating the usage of Colossal Inference from colossalai.inference.tensor_parallel with ray serve. Serving for multiple-gpu inference is supported (e.g. tensor parallel with colossalai).

[Infer] Serving example w/ ray-serve (multiple GPU case)

---

colossalai/inference/tensor_parallel/modeling/__init__.py
colossalai/inference/tensor_parallel/modeling/_utils.py
colossalai/inference/tensor_parallel/modeling/llama.py
colossalai/inference/tensor_parallel/policies/chatglm2.py
colossalai/inference/tensor_parallel/policies/llama.py
colossalai/kernel/triton/__init__.py
examples/inference/bench_llama.py
examples/inference/gptq_llama.py
tests/test_infer/test_llama_infer.py

>
This PR fix the import bugs and delete useless inits

[inference]fix import bug and delete down useless init

---

colossalai/shardformer/modeling/chatglm2_6b/modeling_chatglm.py
examples/inference/bench_llama.py
tests/test_infer/test_bloom_infer.py
tests/test_infer/test_chatglm2_infer.py
tests/test_infer/test_llama_infer.py
tests/test_infer_ops/triton/test_llama2_token_attn.py

>
- Fix llama, bloom, chatglm2 test bug.
- Fix llama2 attention test bug.

[infer] fix test bug

---

colossalai/moe/_operation.py
colossalai/moe/experts.py
colossalai/moe/layers.py
colossalai/moe/utils.py
examples/language/openmoe/benchmark/benchmark_cai.py
examples/language/openmoe/benchmark/benchmark_cai.sh

* support overlap for expert tp

[moe] support overlap for expert tp

---

colossalai/inference/quant/smoothquant/models/__init__.py
colossalai/inference/quant/smoothquant/models/linear.py
colossalai/inference/quant/smoothquant/models/llama.py
tests/test_smoothquant/test_llama_mlp.py

>
- Add llama mlp for smoothquant
- Refactor llama code

[inference] add llama mlp for smoothquant

---

docs/source/en/basics/booster_plugins.md
docs/source/zh-Hans/basics/booster_plugins.md
tests/kit/model_zoo/torchrec/torchrec.py

…ng correspoding docs)
>
Remove the redundant code for model output transformation in `torchrec` models.
Update the `Booster Plugins` document to clarify the current supporting models of the low_level_zero plugin.

[test] remove the redundant code of model output transformation in torchrec

---

colossalai/checkpoint_io/utils.py
colossalai/zero/gemini/gemini_optimizer.py
tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py

>
Torch 2.0 replaces `_hook_for_profile()` with `_patch_step_function()`. We should update optimizer checkpoint io.

[checkpointio] hotfix torch 2.0 compatibility

---

tests/test_shardformer/test_model/_utils.py

>
fixed #4888 
When enabling sequence parallelism during testing, the test fails. This pull request aims to address and rectify this issue.

[hotfix] fix bug in sequence parallel test

---

colossalai/booster/plugin/gemini_plugin.py
colossalai/nn/optimizer/cpu_adam.py
colossalai/nn/optimizer/hybrid_adam.py
colossalai/testing/comparison.py
colossalai/zero/gemini/chunk/chunk.py
colossalai/zero/gemini/chunk/manager.py
colossalai/zero/gemini/gemini_ddp.py
colossalai/zero/gemini/gemini_optimizer.py
colossalai/zero/gemini/utils.py
tests/test_checkpoint_io/test_gemini_checkpoint_io.py
tests/test_checkpoint_io/test_gemini_torch_compability.py
tests/test_zero/test_gemini/test_fwd_bwd.py
tests/test_zero/test_gemini/test_grad_clip.py
tests/test_zero/test_gemini/test_optim.py
tests/test_zero/test_gemini/test_zeroddp_state_dict.py

>
Closes #4871
Support AMP O3 for gemini by adding `master_weights` argument.

[gemini] support amp o3 for gemini

---

colossalai/amp/naive_amp/mixed_precision_optimizer.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/zero/low_level/_utils.py
colossalai/zero/low_level/bookkeeping/gradient_store.py
colossalai/zero/low_level/low_level_optim.py
tests/test_shardformer/test_hybrid_parallel_grad_clip_norm/test_amp_optimizer.py
tests/test_shardformer/test_hybrid_parallel_grad_clip_norm/test_naive_optimizer.py
tests/test_shardformer/test_hybrid_parallel_grad_clip_norm/test_zero_optimizer.py

>
Add clip_grad_norm for hybrid_parallel_plugin

[feature] Add clip_grad_norm for hybrid_parallel_plugin

---

colossalai/nn/lr_scheduler/delayed.py
tests/test_checkpoint_io/test_general_checkpoint_io.py
tests/test_zero/test_gemini/test_zerooptim_state_dict.py

>
fixed #4829
fix bug when saving lr_scheduler under torch 2.0
this bug is caused by torch 2.0 modifying the base class of learning scheduler from `_LRScheduler` to `LRScheduler`

[hotfix] fix lr scheduler bug in torch 2.0

---

colossalai/moe/experts.py

[moe] support sparse mm

---

colossalai/inference/dynamic_batching/io_struct.py
colossalai/inference/manager.py
colossalai/inference/test_async.py
tests/test_infer/test_dynamic_batching/test_forward.py

>
This PR holds the input(encode) and output(including decode) logic and will change the loop into async style to make it controllable

[inference] Async dynamic batching 

---

colossalai/inference/quant/smoothquant/models/base_model.py
colossalai/inference/quant/smoothquant/models/llama.py
examples/inference/smoothquant_llama.py

>
- Delete some useless code.
- Add some comments.
- Refactor code.

[inference] refactor code for smoothquant 

---

colossalai/inference/tensor_parallel/engine.py
colossalai/inference/tensor_parallel/modeling/_utils.py
colossalai/inference/tensor_parallel/modeling/llama.py
colossalai/kernel/triton/__init__.py
tests/test_infer/test_llama2_infer.py

[inference] add llama2 support

---

colossalai/inference/dynamic_batching/io_struct.py
colossalai/inference/manager.py
colossalai/inference/test_async.py
tests/test_infer/test_dynamic_batching/test_forward.py

Reverts hpcaitech/ColossalAI#4901

Revert "[inference]Re push async dynamic batching"

---

colossalai/shardformer/modeling/gptj.py
colossalai/shardformer/policies/auto_policy.py
colossalai/shardformer/policies/gptj.py
tests/kit/model_zoo/registry.py
tests/kit/model_zoo/transformers/__init__.py
tests/kit/model_zoo/transformers/gpt.py
tests/kit/model_zoo/transformers/gptj.py
tests/test_shardformer/test_model/test_shard_gptj.py

[shardformer] support GPTJ auto model sharding (except lazy init)

---

applications/Colossal-LLaMA-2/colossal_llama2/utils/flash_attention_patch.py

To be compatible with the new change in the Transformers library, where a new argument 'padding_mask' was added to forward function of attention layer. https://github.com/huggingface/transformers/pull/25598
>
fixed https://github.com/hpcaitech/ColossalAI/issues/4903#issue-1941151274
Add **kwargs to the original attention_forward function, letting flash_attention_patch be compatible with the new change in Transformers library.

[hotfix] fix bug in flash_attention_patch.py

---

colossalai/moe/experts.py
colossalai/moe/layers.py
colossalai/moe/load_balance.py
colossalai/moe/manager.py
tests/test_moe/test_moe_load_balance.py

* support load balance for moe
* add a unit test

[moe] support load balance

---

colossalai/kernel/cuda_native/csrc/cpu_adam.cpp
colossalai/kernel/cuda_native/csrc/cpu_adam.h
colossalai/nn/optimizer/cpu_adam.py
colossalai/nn/optimizer/hybrid_adam.py
tests/test_optimizer/test_adam_kernel.py
tests/test_optimizer/test_adam_optim.py
tests/test_zero/test_gemini/test_grad_clip.py
tests/test_zero/test_gemini/test_optim.py

[kernel] support pure fp16 for cpu adam and update gemini optim tests

---

colossalai/moe/_operation.py
examples/language/openmoe/benchmark/benchmark_cai.py

* support bf16 to avoid overflow
* update benchmark
* support mock dataset
* use tokenizor in dataset
* add load balance option

[moe] support bf16 and update benchmark

---

colossalai/legacy/context/parallel_context.py
colossalai/legacy/tensor/process_group.py
colossalai/shardformer/modeling/vit.py
tests/test_shardformer/test_model/_utils.py
tests/test_shardformer/test_model/test_shard_vit.py
tests/test_zero/test_gemini/test_optim.py

>
1. Fix vit modelling for pipeline
2. Fix gemini optimizer test for torch 2.0
3. Fix launch

[hotfix] fix torch 2.0 compatibility

---

colossalai/nn/optimizer/cpu_adam.py
tests/test_zero/test_low_level/test_zero1_2.py

>
Add a test on using no master_weights in low level zero plugin.

[test] add no master test for low level zero plugin

---

colossalai/inference/async_engine.py
colossalai/inference/manager.py
colossalai/inference/tensor_parallel/engine.py
tests/test_infer/test_dynamic_batching/config.yaml
tests/test_infer/test_dynamic_batching/test_async_engine.py
tests/test_infer/test_dynamic_batching/test_ray_dist.py

[hot fix] add assertion for config (Dynamic Batching)

---

colossalai/inference/quant/smoothquant/models/base_model.py
colossalai/inference/quant/smoothquant/models/linear.py
colossalai/inference/quant/smoothquant/models/llama.py
colossalai/inference/tensor_parallel/engine.py
colossalai/kernel/triton/gptq_triton.py
colossalai/kernel/triton/smooth_attention.py
examples/inference/gptq_llama.py

>
- Add reference for quant function 
- Fix gptq tensor parallel bug

[inference] add reference and fix some bugs

---

colossalai/moe/__init__.py
colossalai/moe/_operation.py
colossalai/moe/experts.py
colossalai/moe/layers.py
colossalai/moe/load_balance.py
colossalai/moe/manager.py
colossalai/moe/routers.py
colossalai/moe/utils.py
colossalai/zero/low_level/low_level_optim.py
examples/language/openmoe/benchmark/benchmark_cai.py
examples/language/openmoe/benchmark/benchmark_cai.sh
examples/language/openmoe/benchmark/benchmark_fsdp.py
examples/language/openmoe/benchmark/benchmark_fsdp.sh
examples/language/openmoe/benchmark/hostfile.txt
examples/language/openmoe/infer.py
examples/language/openmoe/model/modeling_openmoe.py
examples/language/openmoe/train.py
tests/test_moe/moe_utils.py
tests/test_moe/test_grad_handler.py
tests/test_moe/test_kernel.py
tests/test_moe/test_moe_checkpoint.py
tests/test_moe/test_moe_ep_tp.py
tests/test_moe/test_moe_group.py
tests/test_moe/test_moe_load_balance.py

* polish code
* add hybrid zero2 support

[moe] polish code

---

examples/inference/_utils.py
examples/inference/bench_bloom.py
examples/inference/bench_chatglm2.py
examples/inference/bench_llama.py
examples/inference/gptq_bloom.py
examples/inference/gptq_llama.py

>
This PR adds bench chatglm2 script

[Inference]ADD Bench Chatglm2 script

---

colossalai/moe/checkpoint.py
examples/language/openmoe/benchmark/benchmark_cai.py
examples/language/openmoe/infer.py
examples/language/openmoe/model/modeling_openmoe.py
examples/language/openmoe/test_ci.sh
examples/language/openmoe/train.py
tests/test_moe/test_moe_checkpoint.py

* update train script
* better openmoe arg interface

[moe] update train script

---

examples/community/roberta/preprocessing/Makefile
op_builder/cpu_adam.py
op_builder/gptq.py
op_builder/multi_head_attn.py
op_builder/scaled_masked_softmax.py

Building the extentions of ColossalAI with Pytorch 2.1 requires c++17. Related installation files are fixed to support this by adding `-std=c++17`.

[hotfix] Updated c++17 compiler flags

---

applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/dataset_evaluator.py
applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/metrics.py
applications/ColossalEval/colossal_eval/models/huggingface.py

[ColossalEval] fix ColossalEval

---

colossalai/inference/README.md

[doc]Update doc for colossal-inference

---

.github/workflows/build_on_pr.yml
colossalai/cluster/process_group_mesh.py
colossalai/tensor/d_tensor/layout_converter.py

[hotfix] Fix the bug where process groups were not being properly released.

---

colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py

>
fix the bug mentioned in #4944

[hotfix] fix the bug of repeatedly storing param group

---

LICENSE
colossalai/booster/booster.py
colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/booster/plugin/plugin_base.py
colossalai/booster/plugin/torch_ddp_plugin.py
colossalai/booster/plugin/torch_fsdp_plugin.py
colossalai/checkpoint_io/checkpoint_io_base.py
colossalai/checkpoint_io/general_checkpoint_io.py
requirements/requirements-test.txt
tests/test_lora/test_torch_ddp_lora.py

>
Implement basic Lora features for booster APIs; Support Lora for TorchDDP Plugin and add relevant tests.

[lora] add lora APIs for booster, support lora for TorchDDP

---

docs/source/en/basics/booster_plugins.md
docs/source/zh-Hans/basics/booster_plugins.md

[doc] add supported feature diagram for hybrid parallel plugin

---

colossalai/inference/hybridengine/engine.py
colossalai/inference/tensor_parallel/kvcache_manager.py
colossalai/pipeline/schedule/generate.py
tests/test_infer/test_hybrid_llama.py

[inference] support only TP

---

colossalai/inference/__init__.py
colossalai/inference/hybridengine/engine.py
colossalai/inference/hybridengine/modeling/bloom.py
colossalai/inference/hybridengine/modeling/llama.py
colossalai/inference/hybridengine/polices/__init__.py
colossalai/inference/hybridengine/polices/bloom.py
colossalai/inference/hybridengine/polices/llama.py
tests/test_infer/test_hybrid_bloom.py

[Merge pp with bloom into tp] add support for bloom

---

colossalai/inference/tensor_parallel/engine.py
colossalai/inference/tensor_parallel/modeling/chatglm2.py
colossalai/inference/tensor_parallel/policies/chatglm2.py
colossalai/shardformer/layer/linear.py
colossalai/shardformer/modeling/chatglm2_6b/modeling_chatglm.py
colossalai/shardformer/policies/chatglm2.py
colossalai/shardformer/shard/sharder.py
tests/test_infer/test_chatglm2_infer.py

>
Fix bug in chatglm2 tp inference

[Inference] Fix bug in ChatGLM2 Tensor Parallelism

---

colossalai/inference/hybridengine/engine.py
colossalai/inference/hybridengine/modeling/__init__.py
colossalai/inference/hybridengine/polices/llama.py
colossalai/inference/quant/__init__.py
colossalai/inference/quant/gptq/__init__.py
colossalai/inference/quant/gptq/gptq_manager.py
colossalai/inference/quant/smoothquant/models/__init__.py
colossalai/inference/quant/smoothquant/models/base_model.py
colossalai/inference/quant/smoothquant/models/linear.py
colossalai/inference/quant/smoothquant/models/llama.py
colossalai/inference/quant/smoothquant/models/parallel_linear.py
colossalai/shardformer/shard/shard_config.py
examples/inference/hybrid_gptq_llama.py
examples/inference/hybrid_smoothquant_llama.py
tests/test_infer/test_hybrid_bloom.py
tests/test_infer/test_hybrid_llama.py

>
- Refactor GPTQ Llama
- Refactor Smoothquant Llama

[refactor] refactor gptq and smoothquant llama

---

colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
colossalai/inference/tensor_parallel/engine.py
colossalai/moe/__init__.py
colossalai/moe/checkpoint.py
colossalai/moe/experts.py
colossalai/moe/manager.py
colossalai/tensor/moe_tensor/api.py
examples/language/openmoe/benchmark/benchmark_cai.py
examples/language/openmoe/benchmark/benchmark_fsdp.py
examples/language/openmoe/requirements.txt
examples/language/openmoe/train.py
tests/test_moe/test_grad_handler.py
tests/test_moe/test_kernel.py
tests/test_moe/test_moe_checkpoint.py
tests/test_moe/test_moe_ep_tp.py
tests/test_moe/test_moe_group.py
tests/test_moe/test_moe_hybrid_zero.py
tests/test_moe/test_moe_load_balance.py
tests/test_moe/test_moe_zero_fwd_bwd.py
tests/test_moe/test_moe_zero_optim.py

>
* support optimizer checkpoint
* update test script

[moe] support optimizer checkpoint

---

applications/ColossalEval/colossal_eval/dataset/__init__.py
applications/ColossalEval/colossal_eval/dataset/mtbench.py
applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/dataset_evaluator.py
applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/gpt_judge.py
applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/metrics.py
applications/ColossalEval/colossal_eval/models/huggingface.py
applications/ColossalEval/colossal_eval/utils/conversation.py
applications/ColossalEval/examples/dataset_evaluation/eval_dataset.py
applications/ColossalEval/examples/dataset_evaluation/inference.py

>
Support single judgement for MTBench.

[ColossalEval] Support mtbench

---

colossalai/moe/_operation.py
colossalai/moe/layers.py
colossalai/moe/routers.py
colossalai/moe/utils.py
colossalai/tensor/moe_tensor/moe_info.py
examples/language/openmoe/benchmark/benchmark_cai.py
examples/language/openmoe/model/modeling_openmoe.py
examples/language/openmoe/train.py
tests/test_moe/moe_utils.py
tests/test_moe/test_moe_ep_tp.py
tests/test_moe/test_moe_router.py

[moe]: fix ep/tp tests, add hierarchical all2all

---

colossalai/checkpoint_io/utils.py

>
related issues: #5006 #4759 
This PR addresses a serialization error encountered when saving model states in a Tensor Parallel setup using ColossalAI. Specifically, it resolves the TypeError: cannot pickle 'torch._C._distributed_c10d.ProcessGroup' object that users may encounter under Tensor Parallel size greater than 1.
The fix ensures that all tensors are first moved to CPU before serialization to avoid the pickling issues associated with CUDA tensors. It accommodates both scenarios where Tensor Parallel size is equal to 1 and …

[shardformer] Fix serialization error with Tensor Parallel state saving

---

colossalai/inference/dynamic_batching/ray_dist_init.py
colossalai/inference/hybridengine/polices/llama.py
colossalai/inference/tensor_parallel/engine.py
colossalai/inference/tensor_parallel/policies/bloom.py
colossalai/inference/tensor_parallel/policies/llama.py
colossalai/shardformer/README.md
colossalai/shardformer/policies/auto_policy.py
colossalai/shardformer/shard/shard_config.py
examples/inference/bench_bloom.py
examples/inference/bench_chatglm2.py
examples/inference/bench_llama.py
examples/inference/gptq_bloom.py
examples/inference/gptq_llama.py
examples/inference/serving/ray_serve/Colossal_Inference_rayserve.py
examples/inference/serving/torch_serve/Colossal_Inference_Handler.py
tests/test_infer/_utils.py
tests/test_infer/test_bloom_infer.py
tests/test_infer/test_chatglm2_infer.py
tests/test_infer/test_dynamic_batching/test_dynamic_batching_manager.py
tests/test_infer/test_dynamic_batching/test_offline_dynamic_batching.py
tests/test_infer/test_infer_engine.py
tests/test_infer/test_llama2_infer.py
tests/test_infer/test_llama_infer.py

>
Refactor the shard config: support using extra_kwargs in ShardConfig

[hotfix] Suport extra_kwargs in ShardConfig

---

.github/workflows/build_on_pr.yml
colossalai/inference/hybridengine/polices/llama.py
colossalai/shardformer/README.md
colossalai/shardformer/policies/auto_policy.py
colossalai/shardformer/shard/shard_config.py
examples/inference/bench_bloom.py
examples/inference/bench_chatglm2.py
examples/inference/bench_llama.py
examples/inference/gptq_bloom.py
examples/inference/gptq_llama.py

>
Refactor policy search and quant type controlling in inference.
The task that failed in CI is successfully passed in the local machine (maybe it is due to some problems of CI):

[Refactor] refactor policy search and quant type controlling in inference

---

colossalai/inference/README.md
colossalai/inference/tensor_parallel/modeling/llama.py
colossalai/kernel/triton/context_attention.py
colossalai/kernel/triton/token_attention_kernel.py
examples/inference/bench_llama.py
examples/inference/colossal_llama2_demo.py
examples/inference/colossal_llama2_test.py
requirements/requirements-test.txt
requirements/requirements.txt
tests/test_infer_ops/triton/test_llama_context_attention.py

>
This PR is used to further to update triton kernels into 2.1.0, and also reconstruct triton context-attention kernels to be compatible with triton 2.0.0 and triton 2.1.0. 
Also, added a build script to install relate packages. 

[Kernels]Update triton kernels into 2.1.0

---

colossalai/booster/plugin/gemini_plugin.py
colossalai/utils/device.py
colossalai/zero/gemini/chunk/chunk.py
colossalai/zero/gemini/chunk/manager.py
colossalai/zero/gemini/gemini_ddp.py
colossalai/zero/gemini/gemini_mgr.py
colossalai/zero/gemini/gemini_optimizer.py
examples/language/llama2/benchmark.py
examples/language/llama2/performance_evaluator.py

[npu] gemini support npu

---

colossalai/shardformer/modeling/llama.py

>
#5041 
fix llama error when transformers upgraded.

[shardformer] fix llama error when transformers upgraded.

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/pipeline/schedule/interleaved_pp.py
colossalai/pipeline/stage_manager.py
colossalai/shardformer/modeling/bert.py
colossalai/shardformer/policies/base_policy.py
colossalai/shardformer/policies/bert.py
colossalai/shardformer/shard/shard_config.py
examples/language/bert/data.py
examples/language/bert/finetune.py
tests/test_pipeline/test_schedule/test_interleaved.py

[shardformer]: fix interleaved pipeline for bert model

---

colossalai/moe/_operation.py
colossalai/moe/layers.py
colossalai/moe/utils.py
colossalai/tensor/moe_tensor/api.py
tests/test_moe/test_moe_ep_tp.py

[hotfix]: modify create_ep_hierarchical_group and add test

---

colossalai/kernel/cuda_native/csrc/cpu_adam.h
colossalai/kernel/cuda_native/csrc/cpu_adam_arm.cpp
colossalai/kernel/cuda_native/csrc/cpu_adam_arm.h
colossalai/nn/optimizer/cpu_adam.py
colossalai/nn/optimizer/hybrid_adam.py
op_builder/__init__.py
op_builder/arm_cpu_adam.py
op_builder/builder.py

[kernel] add arm cpu adam kernel

---

colossalai/inference/engine/engine.py
tests/test_infer/test_hybrid_bloom.py
tests/test_infer/test_hybrid_chatglm2.py
tests/test_infer/test_hybrid_llama.py

[hotfix/hybridengine] fix bug when tp*pp size = 1

---

colossalai/kernel/cuda_native/csrc/kernels/cuda_util.cu

>
related issue #5061 
This PR addresses a compilation issue encountered in the ColossalAI project when using the Docker container `nvcr.io/nvidia/pytorch:23.07-py3`. The error involved the Thrust library, specifically, the absence of the `transform_reduce` member in the `thrust` namespace, as reported in the compilation of `cuda_util.cu`.

[hotfix] fix thrust-transform-reduce error

---

docs/source/en/basics/booster_plugins.md
docs/source/zh-Hans/basics/booster_plugins.md

Not involved
[nfc] fix typo: change Pararllel to Parallel in docs/

[nfc] fix typo: change Pararllel to Parallel in docs/

---

docs/source/en/features/lazy_init.md
docs/source/en/features/shardformer.md
docs/source/en/features/zero_with_chunk.md
docs/source/zh-Hans/features/lazy_init.md
docs/source/zh-Hans/features/zero_with_chunk.md

Not involved
fix typo and author name

[nfc] fix typo and author name

---

colossalai/zero/gemini/gemini_optimizer.py

>
#5075 
gather 'gathered_state_shards' in the zero group

[gemini]fix gemini optimzer, saving Shardformer in Gemini got list assignment index out of range

---

colossalai/shardformer/modeling/chatglm2.py
colossalai/shardformer/modeling/gpt2.py
colossalai/shardformer/modeling/llama.py
colossalai/shardformer/modeling/opt.py
colossalai/shardformer/modeling/whisper.py
examples/language/llama2/pretrain.py

>
#5083 
when mask is casual, just don't unpad it.

[shardformer]fix flash attention, when mask is casual, just don't unpad it

---

colossalai/shardformer/README.md
colossalai/shardformer/layer/normalization.py
colossalai/shardformer/modeling/mistral.py
colossalai/shardformer/policies/mistral.py

#4835 #4836 
>
Hi, I added a new policy and model to support Mistral with ShardFormer.
The current policy supports tensor parallel, fused normalization, and flash attention.
Although the minimum version requirement for Mitral is transformers==4.34.0.dev0 currently, it is still very excited to make ColossalAI support such impressive models!!!

Add Mistral support for Shardformer

---

colossalai/shardformer/policies/auto_policy.py
colossalai/shardformer/policies/bloom.py
colossalai/shardformer/policies/falcon.py
colossalai/shardformer/policies/mistral.py
colossalai/shardformer/policies/opt.py
colossalai/shardformer/policies/whisper.py
requirements/requirements-test.txt
tests/kit/model_zoo/transformers/__init__.py
tests/kit/model_zoo/transformers/mistral.py
tests/test_shardformer/test_model/test_shard_mistral.py

fix
>
#5104 
add tests to mistral

[shardformer] add tests to mistral

---

colossalai/shardformer/layer/normalization.py
colossalai/shardformer/modeling/mistral.py
colossalai/shardformer/policies/bloom.py
colossalai/shardformer/policies/falcon.py
colossalai/shardformer/policies/mistral.py
colossalai/shardformer/policies/opt.py
colossalai/shardformer/policies/whisper.py
tests/kit/model_zoo/transformers/__init__.py
tests/kit/model_zoo/transformers/mistral.py
tests/test_shardformer/test_model/test_shard_mistral.py

[hotfix]: polish code and fix typo

---

applications/Colossal-LLaMA-2/README.md
docs/source/zh-Hans/basics/booster_api.md
examples/language/llama2/README.md

Not involved
fix typo change directoty to directory
change  Hybird to  Hybrid 
modified:   applications/Colossal-LLaMA-2/README.md
modified:   docs/source/zh-Hans/basics/booster_api.md
modified:   examples/language/llama2/README.md

[nfc] fix typo change directoty to directory

---

applications/ColossalEval/colossal_eval/dataset/__init__.py
applications/ColossalEval/colossal_eval/dataset/cvalues.py
applications/ColossalEval/colossal_eval/dataset/safetybench_en.py
applications/ColossalEval/colossal_eval/dataset/safetybench_zh.py
applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/metrics.py

* add safetybench and cvalues(responsibility) eval dataset
* Modify code according to review suggestions
---------
>
fixed https://github.com/hpcaitech/ColossalAI/issues/5094
Add two safety evaluation datasets to ColossalEval: SafetyBench(en/zh) and CValues(zh). They are all multiple choices questions.

[FEATURE] Add Safety Eval Datasets to ColossalEval (#5095)

---

colossalai/utils/memory.py
colossalai/zero/gemini/placement_policy.py

[hotfix]: add memory utils to avoid import legacy module

---

colossalai/tensor/colo_parameter.py

>
To fix the "len(grad_args) is 0" error when training GPT-2 with Gemini.

[gemini] fix the "len(grad_args) is 0" error when training GPT-2 with Gemini.

---

applications/Colossal-LLaMA-2/README.md
applications/Colossal-LLaMA-2/colossal_llama2/dataset/conversation.py
applications/Colossal-LLaMA-2/colossal_llama2/dataset/spliced_and_tokenized_dataset.py
applications/Colossal-LLaMA-2/colossal_llama2/utils/neftune_patch.py
applications/Colossal-LLaMA-2/inference_example.py
applications/Colossal-LLaMA-2/prepare_pretrain_dataset.py
applications/Colossal-LLaMA-2/prepare_sft_dataset.py
applications/Colossal-LLaMA-2/train_sft.example.sh
applications/Colossal-LLaMA-2/train_sft.py

>
Add an example of finetuning Colossal-Llama-2.

[Colossal-Llama-2] Add finetuning Colossal-Llama-2 example

---

applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/dataset_evaluator.py
applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/metrics.py
applications/ColossalEval/examples/dataset_evaluation/inference.py
applications/ColossalEval/examples/gpt_evaluation/inference.py

>
Improve logic for selecting metrics.

[ColossalEval] Improve logic for selecting metrics

---

colossalai/shardformer/layer/_operation.py
colossalai/shardformer/layer/linear.py

>
#5198 
support gradients accumulation fusion, the current gradient is accumulated onto the previously computed gradient, all done in a single operation, which helps avoid multiple accesses to global memory and enhances the operator's bandwidth.

[shardformer]support gradients accumulation fusion

---

colossalai/pipeline/schedule/interleaved_pp.py
colossalai/pipeline/schedule/one_f_one_b.py
examples/language/bert/data.py
examples/language/bert/test_ci.sh

[pipeline]: support arbitrary batch size in forward_only mode

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/pipeline/p2p.py
colossalai/pipeline/schedule/interleaved_pp.py
colossalai/pipeline/schedule/one_f_one_b.py
tests/test_pipeline/test_p2p_communication.py

[pipeline]: add p2p fallback order and fix interleaved pp deadlock

---

colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/cluster/process_group_mesh.py

>
#5205 
fix test error that group is not registered when shard the model.

[shardformer] fix test error that group is not registered when shard the model.

---

colossalai/kernel/triton/__init__.py
colossalai/kernel/triton/context_attn_unpad.py
tests/test_infer_ops/triton/test_context_attn_unpad.py

>
Implemented unpadded context attention in #5193 
Add triton kernel for non-padding context attention. Use flash attention V2 implementation based on "FlashAttention-2: Faster Attention with Better Parallelism and Work Partitioning" by Tri Dao, 2023 and modified from triton tutorial https://triton-lang.org/main/getting-started/tutorials/06-fused-attention.html

[kernel] Add triton kernel for context attention without padding

---

colossalai/shardformer/README.md
colossalai/shardformer/_utils.py
colossalai/shardformer/shard/shard_config.py
colossalai/shardformer/shard/sharder.py

Not involved
fix typo colossalai/shardformer/
detail 
modified:   colossalai/shardformer/README.md
modified:   colossalai/shardformer/_utils.py
modified:   colossalai/shardformer/shard/shard_config.py
modified:   colossalai/shardformer/shard/sharder.py

[nfc] fix typo colossalai/shardformer/

---

colossalai/inference/core/request_handler.py
colossalai/inference/modeling/layers/attention.py
tests/test_infer/test_models/test_attention.py

[Inference] Pytorch Attention func, pad&nopad input support

---

README.md
applications/README.md
docs/README-zh-Hans.md

[doc] SwiftInfer release

---

colossalai/accelerator/npu_accelerator.py
colossalai/booster/plugin/gemini_plugin.py

>
This PR cleaned up some legacy code which leads to runtime error.

[hotfix] removed unused flag

---

applications/Colossal-LLaMA-2/README.md

Not involved
fix typo in Colossal-LLaMA-2/README.md
modified:   applications/Colossal-LLaMA-2/README.md

[fix] fix typo in Colossal-LLaMA-2/README.md

---

.github/workflows/build_on_pr.yml
.github/workflows/build_on_schedule.yml
.github/workflows/doc_test_on_schedule.yml
tests/kit/model_zoo/__init__.py
tests/kit/model_zoo/registry.py
tests/test_booster/test_plugin/test_3d_plugin.py
tests/test_booster/test_plugin/test_gemini_plugin.py
tests/test_booster/test_plugin/test_low_level_zero_plugin.py
tests/test_booster/test_plugin/test_torch_ddp_plugin.py
tests/test_booster/test_plugin/test_torch_fsdp_plugin.py
tests/test_checkpoint_io/test_gemini_checkpoint_io.py
tests/test_checkpoint_io/test_gemini_torch_compability.py
tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py
tests/test_checkpoint_io/test_plugins_huggingface_compatibility.py
tests/test_lazy/test_models.py

[workflow] fixed build CI

---

colossalai/kernel/triton/__init__.py
colossalai/kernel/triton/no_pad_rotary_embedding.py
tests/test_infer_ops/triton/test_context_attn_unpad.py
tests/test_infer_ops/triton/test_rotary_embdding_unpad.py

>
continues  #5193 
Add no pad rotary embedding kernel. It should be applied to tensors after `linear projection`, followed by `memcpy`
CO-Contributor: @Xu-Kai 

[Inference] Kernel: no pad rotary embedding

---

tests/kit/model_zoo/registry.py
tests/test_shardformer/test_with_torch_ddp.py

[ci] fixed ddp test

---

colossalai/pipeline/schedule/interleaved_pp.py
colossalai/pipeline/schedule/one_f_one_b.py
examples/language/llama2/benchmark.py
examples/language/llama2/scripts/benchmark_70B/3d.sh
tests/test_pipeline/test_schedule/test_oneF_oneB.py

[hotfix]: add pp sanity check and fix mbs arg

---

colossalai/inference/modeling/layers/attention.py
colossalai/kernel/triton/__init__.py
colossalai/kernel/triton/kvcache_copy.py
tests/test_infer_ops/triton/kernel_utils.py
tests/test_infer_ops/triton/test_kvcache_copy.py

>
Part of #5193 
Add triton kernel for copying new k/v into the blocked kv cache (supposed to be used during decoding stage before attention). 
Pytests under `tests/test_infer_ops/` and `tests/test_infer/`
Comparison between the triton version and previously implemented torch version of cache copy functions:
* constant because of the sequence length during decoding stage is always 1 and cache copy function is unrelated with past kv length.
batch size 4
batch size 16

[kernel] Add KV cache copy kernel during decoding 

---

colossalai/inference/core/request_handler.py
colossalai/inference/kv_cache/kvcache_manager.py
colossalai/inference/struct.py

>
This pr fixes an existing problem of request handler and add a new recycle logic for sequences that can't be fully decoded.
Tell us more if you don't enjoy con[tributing to Colossal-AI.

[Inference] Fix request handler and add recycle logic

---

colossalai/kernel/triton/kvcache_copy.py
tests/test_infer_ops/triton/test_kvcache_copy.py

>
Revise the kvcache copy triton kernel API and fix the notes/comments. Now we use kv sequence lengths (`past_kv_seq_len + seq_len`, in decoding stage, `kv_seq_len = past_kv_seq_len + 1`) as the arg of the kernel to keep compatibility, instead of using context lengths.
Comparison between the triton kernel and the torch operation (in ms) with batch size 16:
| KV_SEQ_LEN | torch_copy_func | triton_copy_func |
|------------|-----------------|------------------|
| 256.0      | 0.892569        | 0.006072         |
| 512.0      | …

[kernel] Revise KVCache copy triton kernel API

---

tests/test_shardformer/test_model/_utils.py

>
Previously the test_config in test_model only set "enable_all_optimization" to True, which intends to enable sequence parallelism in shardformer. However, the if statement retrieves `booster.plugin.enable_sequence_parallelism` which is always False. Thus the test cannot be executed.

[hotfix] Fixed shardformer test execution path when using sequence parallelism

---

colossalai/inference/core/request_handler.py
colossalai/inference/modeling/layers/attention.py
colossalai/inference/modeling/models/llama.py
colossalai/inference/struct.py
examples/inference/benchmark_llama.py
tests/test_infer/test_config_and_struct.py

>
Benchmark using pure PyTorch

[Hotfix] Fix bugs in testing continuous batching

---

colossalai/inference/modeling/models/llama.py
colossalai/kernel/triton/__init__.py
colossalai/kernel/triton/flash_decoding.py
colossalai/kernel/triton/flash_decoding_utils.py
tests/test_infer_ops/triton/kernel_utils.py
tests/test_infer_ops/triton/test_context_attn_unpad.py
tests/test_infer_ops/triton/test_decoding_attn.py

>
Revise and optimize flash-decoding triton kernel which is used with block kv cache (paged attention) during decoding stage.
\* `KV_LEN` is the kv sequence length and `q_len` is always 1.
decoding-block_size-32-batch16
|   KV_LEN  |  Torch   |  Triton  |
|-----------|----------|----------|
|   256.0   | 0.122464 | 0.029888 |
|   512.0   | 0.219200 | 0.047584 |
|  1024.0   | 0.420768 | 0.082432 |
|  2048.0   | 0.818400 | 0.154176 |
|  4096.0   | 1.620720 | 0.297440 |
|  8192.0   | 3.139680 | 0.584672 | …

[kernel/fix] Performance Optimization for Decoding Kernel

---

colossalai/inference/modeling/layers/attention.py
colossalai/kernel/triton/context_attn_unpad.py
colossalai/kernel/triton/flash_decoding.py
tests/test_infer_ops/triton/test_context_attn_unpad.py
tests/test_infer_ops/triton/test_decoding_attn.py

>
- It revises flash attention (context attention) triton kernel API
- Add benchmark for context attention
- Fix part of https://github.com/hpcaitech/ColossalAI/pull/5283 (flash-decoding triton kernel pytest)

[Kernel/Fix] Revise flash attention triton kernel API and add benchmark

---

colossalai/kernel/triton/__init__.py
colossalai/kernel/triton/fused_rotary_embedding.py
colossalai/kernel/triton/no_pad_rotary_embedding.py
colossalai/kernel/triton/rotary_cache_copy.py
tests/test_infer_ops/triton/test_fused_rotary_embedding.py
tests/test_infer_ops/triton/test_xine_copy.py

[Inference]Add fused rotary kernel and get cos cache kernel

---

colossalai/kernel/triton/context_attn_unpad.py
colossalai/kernel/triton/flash_decoding.py

>
Fix for illegal memory access when the input batch size is not an exponent of 2. This PR adds a boundary check in batch size dimension for attention. 

[Infer/Hotfix] Fix boundary check of bsz in triton attention kernels

---

colossalai/kernel/triton/fused_rotary_embedding.py
colossalai/kernel/triton/no_pad_rotary_embedding.py
colossalai/kernel/triton/rotary_cache_copy.py
tests/test_infer_ops/triton/test_xine_copy.py

>
Rotary update:
1. 将q,k计算合并，有一定的提升,测试精度无误差
2. rotary cos_sin copy 合并
提升一倍
3. Kernel调参:
Get cos sin
Rotary embedding

[Inference] Accelerate Rotary embedding, aligned to vLLM

---

colossalai/inference/kv_cache/kvcache_manager.py
colossalai/inference/modeling/layers/attention.py
colossalai/inference/modeling/models/nopadding_llama.py
colossalai/inference/modeling/models/padding_llama.py
colossalai/kernel/triton/context_attn_unpad.py
colossalai/kernel/triton/flash_decoding.py
colossalai/kernel/triton/kvcache_copy.py
tests/test_infer/test_kvcache_manager.py
tests/test_infer/test_models/test_attention.py
tests/test_infer_ops/triton/kernel_utils.py
tests/test_infer_ops/triton/test_context_attn_unpad.py
tests/test_infer_ops/triton/test_decoding_attn.py
tests/test_infer_ops/triton/test_kvcache_copy.py
tests/test_infer_ops/triton/test_rmsnorm_triton.py

>
Part of optimization described in #5323 
Modification has been made on the shape of blocked kvcaches and the kernels/functions which are using the caches. 
For now we use KV Cache shape `[num_blocks, num_heads, block_size, head_size]`
Benchmark Llama:
compared with commit e8f0642f2841f6aeb6ed0e6695ff9d9ef14f198b
| in_len | out_len | bsz | Throughput <br>(tokens/sec) | 
|--------|--------|----------|----------|
| 512 | 256 | 16 | 829.26 -> 1028.02 | 
| 512 | 256 | 32 | 1311.72 -> 1689.98 | 
| 512 | 256 | 64 | 1628.61 -> 2108.73 | …

[Infer] Optimize Blocked KVCache And Kernels Using It

---

colossalai/inference/modeling/models/nopadding_llama.py
colossalai/inference/modeling/models/padding_llama.py
colossalai/inference/modeling/policy/nopadding_llama.py
colossalai/inference/modeling/policy/padding_llama.py
colossalai/kernel/triton/rms_layernorm.py
examples/inference/benchmark_llama.py
examples/inference/run_benchmark.sh

>
Part of optimization described in https://github.com/hpcaitech/ColossalAI/issues/5323
pytest:
benchmark:
|--------|---------|-----|--------------------------|
| 256    | 128     | 16  | 1079.76 -> 1115.89        | 
| 256    | 128     | 32  | 1716.22 ->  1717.40     | 
| 256    | 128     | 64  | 2135.06 ->  2129.02     | 
| 1024   | 128     | 16  | 888.97  ->  887.85      |
| 1024   | 128     | 32  | 1144.29 ->  1149.64       | 
| 1024   | 128     | 64  | 1317.76 ->  1323.08      |
Tell us more if you don't enjoy contributing to …

[Inference/opt]Optimize the mid tensor of RMS Norm

---

colossalai/tensor/colo_parameter.py
colossalai/tensor/param_op_hook.py

>
When an op's output is tuple, post op hook maybe not set correctly. This PR fix this issue

[gemini] fix param op hook when output is tuple

---

colossalai/inference/config.py
colossalai/inference/core/engine.py
tests/test_infer/test_inference_engine.py

[inference] added inference template

---

colossalai/inference/modeling/models/nopadding_llama.py
colossalai/inference/modeling/models/padding_llama.py
colossalai/kernel/triton/kvcache_copy.py
tests/test_infer/test_ops/triton/test_kvcache_copy.py

>
pytest:
benchmark:
|--------|---------|-----|--------------------------|
|512 | 128 | 16 | 1172.57 -> 1234.48 |
|512 | 128 | 32 | 1997.11 -> 2057.46 |
|512 | 128 | 64 | 2895.11 -> 2914.11 |
| 1024 | 128 | 16 | 1033.75 -> 1058.00 |
| 1024 | 128 | 32 | 1442.04 -> 1489.55 |
| 1024 | 128 | 64 | 1804.72 -> 1811.30 |

[Inference/opt] Fused KVCahce Memcopy

---

colossalai/inference/config.py
colossalai/inference/core/engine.py

[inference] refactored config

---

colossalai/inference/config.py
colossalai/inference/core/engine.py
examples/inference/benchmark_llama.py
examples/inference/run_benchmark.sh

 [Inference]Support vllm testing in benchmark scripts

---

tests/test_infer/test_ops/triton/test_rmsnorm_triton.py

>
Pytests not passed because of the imports of third-party repo. Fix imports in pytest. 

[Infer/Fix] Fix Dependency in test for RMSNorm Triton Kernel

---

colossalai/kernel/triton/__init__.py
colossalai/kernel/triton/flash_decoding.py
colossalai/kernel/triton/kvcache_copy.py
tests/test_infer/test_ops/triton/kernel_utils.py
tests/test_infer/test_ops/triton/test_decoding_attn.py
tests/test_infer/test_ops/triton/test_kvcache_copy.py
tests/test_infer/test_ops/triton/test_rmsnorm_triton.py

>
Part of #5245 
- This PR revises triton kernels so that the main/large model is able to verify `n` tokens in parallel. It enables 1) the kv-cache-copy kernel to copy multiple tokens for each sequence, and enables 2) decoding attention to receive inputs with `q_len > 1`.
- Add new cases in tests

[Infer] Revise and Adapt Triton Kernels for Spec-Dec

---

colossalai/inference/spec/__init__.py
colossalai/inference/spec/drafter.py
colossalai/inference/spec/struct.py
tests/test_infer/test_drafter.py
tests/test_infer/test_ops/triton/test_rmsnorm_triton.py

>
Part of #5245 
Add the basic version of Drafter model container for Spec-Dec.

[Inference/SpecDec] Add Basic Drafter Model Container

---

applications/ColossalEval/colossal_eval/dataset/agieval.py

Fixed #5421.
Set few_shot_data to None when few shot is disabled, so get_batch_prompt(https://github.com/hpcaitech/ColossalAI/blob/main/applications/ColossalEval/colossal_eval/utils/conversation.py#L182) will skip few shot prefix generation instead of raising an IndexError.

[eval-hotfix]: fix AGIEvalDataset loader to correctly handle few_shot option

---

examples/images/diffusion/README.md
examples/images/diffusion/configs/train_ddp.yaml

>
This pr is aimed to fix stable diffusion inference bug, by simply change config file train_ddp.yaml, and add guide to test pretrain model.

fix stable diffusion inference bug.

---

colossalai/inference/modeling/models/nopadding_llama.py
colossalai/inference/modeling/policy/nopadding_llama.py
examples/inference/benchmark_ops/benchmark_rmsnorm.py
extensions/csrc/cuda/colossal_inference_C_frontend.cpp
extensions/csrc/cuda/rms_layernorm_kernel.cu
extensions/inference/inference_ops_cuda.py
tests/test_infer/test_inference_engine.py
tests/test_infer/test_ops/cuda/test_rms_layernorm.py

>
model benchmark:
| bsz | in_len | out_len | Throughput (tokens/sec) |
|-----|--------|---------|--------------------------|
| 16 | 128 | 128 | 1647.18 -> 1756.82 |
| 32 | 128 | 128 | 3000.20 -> 3058.36 |
| 64 | 128 | 128 | 4954.12 -> 4918.43 |
| 16 | 512 | 128 | 1379.97 -> 1353.25 |
| 32 | 512 | 128 | 2053.62 -> 2036.26 |
| 64 | 512 | 128 | 2689.92 -> 2680.61 |
| 16 | 1024 | 128 | 1024.90 -> 1021.70 |
| 32 | 1024 | 128 | 1347.42 -> 1352.80 |
| 64 | 1024 | 128 | 1610.99 …

[Inference] feat rmsnorm cuda kernel and add unittest, benchmark script

---

applications/ColossalQA/colossalqa/chain/retrieval_qa/base.py
applications/ColossalQA/colossalqa/prompt/prompt.py
applications/ColossalQA/colossalqa/retrieval_conversation_en.py
applications/ColossalQA/colossalqa/retrieval_conversation_universal.py
applications/ColossalQA/colossalqa/retrieval_conversation_zh.py
applications/ColossalQA/examples/retrieval_conversation_chatgpt.py
applications/ColossalQA/examples/retrieval_conversation_en.py
applications/ColossalQA/examples/retrieval_conversation_en_customer_service.py
applications/ColossalQA/examples/retrieval_conversation_universal.py
applications/ColossalQA/examples/retrieval_conversation_zh.py
applications/ColossalQA/examples/webui_demo/RAG_ChatBot.py
colossalai/inference/README.md
colossalai/legacy/inference/README.md
colossalai/legacy/inference/hybridengine/engine.py
colossalai/nn/optimizer/README.md
colossalai/pipeline/schedule/generate.py
examples/images/diffusion/ldm/modules/diffusionmodules/openaimodel.py

Not involved
fix typo s/keywrods/keywords etc.
detail info 
modified:   applications/ColossalQA/colossalqa/chain/retrieval_qa/base.py
modified:   applications/ColossalQA/colossalqa/prompt/prompt.py
modified:   applications/ColossalQA/colossalqa/retrieval_conversation_en.py
modified:   applications/ColossalQA/colossalqa/retrieval_conversation_universal.py
modified:   applications/ColossalQA/colossalqa/retrieval_conversation_zh.py
modified:   applications/ColossalQA/examples/retrieval_conversation_chatgpt.py
modified:   applications/ColossalQA/examples/retrieval_conversation_en.py
modified:   applications/ColossalQA/examples/retrieval_conversation_en_customer_service.py
modified:   applications/ColossalQA/examples/retrieval_conversation_universal.py
modified: …

[hotfix] fix typo s/keywrods/keywords etc.

---

extensions/csrc/common/cuda_type_utils.h
extensions/csrc/cuda/rms_layernorm_kernel.cu

>
below are hidden size = 4096
below are hidden size = 1024

[Kernel] Optimize rmsnorm cuda kernel

---

README.md
docs/README-zh-Hans.md

[doc] release Open-Sora 1.0 with model weights

---

extensions/csrc/common/mp_type_traits.h
extensions/csrc/cuda/activation_kernel.cu
extensions/csrc/cuda/utils/vec_type_traits.h
extensions/csrc/cuda/utils/vector_copy_utils.h

>
This PR add VecTypeTrait and related components for vec ld,st,compute

add vec_type_trait implementation

---

README.md
applications/README.md
docs/README-zh-Hans.md

[doc] update open-sora demo

---

README.md
docs/README-zh-Hans.md
examples/language/grok-1/README.md

[release] grok-1 inference

---

examples/language/grok-1/README.md
examples/language/grok-1/inference.py
examples/language/grok-1/inference_tp.py
examples/language/grok-1/requirements.txt
examples/language/grok-1/run_inference_fast.sh
examples/language/grok-1/run_inference_slow.sh
examples/language/grok-1/utils.py
requirements/requirements.txt

[example] update Grok-1 inference

---

applications/ColossalMoE/train.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/pipeline/schedule/one_f_one_b.py
docs/source/en/advanced_tutorials/train_gpt_using_hybrid_parallelism.md
docs/source/en/advanced_tutorials/train_vit_with_hybrid_parallelism.md
docs/source/en/features/pipeline_parallel.md
docs/source/en/features/shardformer.md
docs/source/zh-Hans/advanced_tutorials/train_gpt_using_hybrid_parallelism.md
docs/source/zh-Hans/advanced_tutorials/train_vit_with_hybrid_parallelism.md
docs/source/zh-Hans/features/pipeline_parallel.md
docs/source/zh-Hans/features/shardformer.md
examples/images/vit/vit_benchmark.py
examples/images/vit/vit_train_demo.py
examples/language/bert/finetune.py
examples/language/gpt/hybridparallelism/finetune.py
examples/language/llama2/finetune.py
examples/language/llama2/pretrain.py
examples/language/openmoe/benchmark/benchmark_cai.py
examples/language/openmoe/train.py
examples/language/opt/opt_train_demo.py
tests/test_booster/test_plugin/test_3d_plugin.py
tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py
tests/test_moe/test_moe_checkpoint.py
tests/test_pipeline/test_schedule/test_interleaved.py
tests/test_pipeline/test_schedule/test_oneF_oneB.py
tests/test_shardformer/test_model/_utils.py

[hotfix] set return_outputs=False in examples and polish code

---

README.md
docs/README-zh-Hans.md
examples/language/grok-1/README.md

[release] grok-1 inference benchmark

---

examples/language/grok-1/README.md
examples/language/grok-1/run_inference_fast.sh
examples/language/grok-1/run_inference_slow.sh

>
Fix typo in model card in grok-1 example.

[fix] Fix grok-1 model card typo

---

.github/workflows/example_check_on_dispatch.yml
.github/workflows/example_check_on_pr.yml
.github/workflows/example_check_on_schedule.yml

[devops] fix example test ci

---

colossalai/legacy/tensor/tensor_spec.py

>
On python 3.11, currently the code reports this failure:
```bash
File "/opt/conda/envs/lab42/lib/python3.11/site-packages/colossalai/legacy/tensor/tensor_spec.py", line 10, in <module>
@dataclass
^^^^^^^^^
File "/opt/conda/envs/lab42/lib/python3.11/dataclasses.py", line 1230, in dataclass
return wrap(cls)
^^^^^^^^^
File "/opt/conda/envs/lab42/lib/python3.11/dataclasses.py", line 1220, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/lab42/lib/python3.11/dataclasses.py", line 958, in _process_class
cls_fields.append(_get_field(cls, …
```

Fix ColoTensorSpec for py11

---

colossalai/inference/core/request_handler.py
colossalai/inference/logit_processors.py

>
This PR optimize request_handler of llama, the result is as following:

[Inference] Optimize request handler of llama

---

colossalai/tensor/d_tensor/layout_converter.py
tests/test_tensor/test_dtensor/test_layout_converter.py

>
The old layout caching only checks if the process group still exists regardless of the final shared shape. Calling a sharding function on tensors with different shapes incorrectly leads to the same sharded shape.
I added sharded shape check into caching.

Fix layout convert caching

---

examples/inference/run_benchmark.sh
extensions/csrc/common/micros.h
extensions/csrc/common/mp_type_traits.h
extensions/csrc/cuda/context_kv_cache_memcpy_kernel.cu
extensions/csrc/cuda/decode_kv_cache_memcpy_kernel.cu

…efinitions have been optimized.
>
pytest:

[Inference] Optimize the writing style of tail processing and the logic related to macro definitions.

---

applications/ColossalMoE/colossal_moe/models/mixtral_policy.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/inference/engine/policies/bloom.py
colossalai/inference/engine/policies/chatglm2.py
colossalai/inference/engine/policies/llama.py
colossalai/pipeline/stage_manager.py
colossalai/shardformer/__init__.py
colossalai/shardformer/modeling/llama.py
colossalai/shardformer/policies/base_policy.py
colossalai/shardformer/policies/bert.py
colossalai/shardformer/policies/bloom.py
colossalai/shardformer/policies/chatglm2.py
colossalai/shardformer/policies/falcon.py
colossalai/shardformer/policies/gpt2.py
colossalai/shardformer/policies/gptj.py
colossalai/shardformer/policies/llama.py
colossalai/shardformer/policies/opt.py
colossalai/shardformer/policies/t5.py
colossalai/shardformer/policies/vit.py
colossalai/shardformer/policies/whisper.py
colossalai/shardformer/shard/__init__.py
colossalai/shardformer/shard/grad_ckpt_config.py
colossalai/shardformer/shard/shard_config.py
examples/language/openmoe/model/openmoe_policy.py
tests/kit/model_zoo/transformers/llama.py
tests/test_pipeline/test_pipeline_utils/test_t5_pipeline_utils.py
tests/test_pipeline/test_pipeline_utils/test_whisper_pipeline_utils.py
tests/test_shardformer/test_model/test_shard_llama.py

[shardformer, pipeline] add `gradient_checkpointing_ratio` and heterogenous shard policy for llama

---

colossalai/inference/modeling/models/nopadding_llama.py
extensions/csrc/cuda/get_cos_and_sin_kernel.cu
extensions/csrc/cuda/pybind/inference.cpp
extensions/inference/inference_ops_cuda.py
tests/test_infer/test_ops/cuda/test_get_cos_and_sin.py

>
pytest:
**Model Benchmark:**
***Total Time Comparison***
| bsz | in_len | out_len | Throughput (tokens/sec) | 
|-----|--------|---------|--------------------------|
| 16   | 128    | 128     | 1793.14 -> 1806.67 | 
| 32  | 128    | 128     | 3099.44 -> 3112.40 | 
| 64  | 128    | 128     | 5006.11 -> 5010.27 | 
| 16   | 512    | 128     | 1394.90 -> 1407.57 | 
| 32  | 512    | 128     | 2060.37 -> 2081.11 | 
| 64  | 512    | 128     | 2746.49 -> 2748.17 | 
**OP Benchmark（batchsize 16，Input len 128，output len 15）:**
***OP CPU …

[Inference/Kernel]Add get_cos_and_sin Kernel

---

colossalai/shardformer/modeling/bloom.py
colossalai/shardformer/policies/bloom.py

> [shardformer/modeling/bloom]: Upgrade transformers from version 4.33.0 to version 4.36.0 for the bloom model, the code changes mainly includes the `causal_mask` construction and the `outputs` for the `gradient_checkpointing` in the forward function of `get_bloom_sequence_parallel_forward_fn`, and the `BloomModel`.

[shardformer] update bloom model

---

colossalai/inference/config.py
colossalai/inference/core/engine.py
colossalai/inference/modeling/models/glide_llama.py
colossalai/inference/modeling/policy/__init__.py
colossalai/inference/modeling/policy/glide_llama.py
colossalai/inference/spec/__init__.py
colossalai/inference/spec/drafter.py
colossalai/inference/spec/struct.py
tests/test_infer/test_drafter.py
tests/test_infer/test_inference_engine.py

>
Part of #5245 
Add implementation and tests of Glide Drafter model.
For batch size 1, testing on gsm8k dataset:
| Method | Tokens/Sec |
|---|---|
| Non-Spec-Dec | ~90 |
| Spec-Dec | ~115 |
| Spec-Dec with GLIDE Model | ~135 |

[SpecDec] Support GLIDE Drafter Model

---

colossalai/inference/modeling/policy/nopadding_llama.py
colossalai/shardformer/shard/shard_config.py

>
Remove unused function (legacy-version) in shard config. 
Revise the usage of method replacement in nopadding llama policy

[Fix/Inference] Remove unused and non-functional functions

---

colossalai/shardformer/shard/shard_config.py

[hotfix] fix incorrect sharding without zero

---

colossalai/shardformer/modeling/mistral.py
colossalai/shardformer/policies/mistral.py

> [shardformer/modeling/mistral]: Upgrade transformers from version 4.33.0 to version 4.36.0 for the mistral model, the code changes including `get_mistral_flash_attention_forward` function, and add the `mistral_model_forward` function to replace the forward function of the mistral model to make the `use_cache` compatible with colossalai.

[shardformer] update mistral model

---

colossalai/shardformer/modeling/gptj.py

[shardformer/modeling/gptj]: Upgrade transformers from version 4.33.0 to version 4.36.0 for the gptj model, including the `gptj_model_forward` function

[shardformer] update gptj model

---

colossalai/shardformer/modeling/opt.py
colossalai/shardformer/policies/opt.py

[shardformer/modeling/gpt2]: Upgrade transformers from version 4.33.0 to version 4.36.0 for the opt model, including the `forward` function of the `OPT` model and remove the restrictions of policies.

[shardformer] update opt model

---

colossalai/shardformer/modeling/t5.py

[shardformer/modeling/t5]: Upgrade transformers from version 4.33.0 to version 4.36.0 for the opt model, including the `t5_stack_forward` function of the `t5` model.

[shardformer] update t5 model

---

colossalai/shardformer/modeling/whisper.py
colossalai/shardformer/policies/whisper.py

[shardformer/modeling/whisper]: Upgrade transformers from version 4.33.0 to version 4.36.0 for the whisper model, including the `whisper_encoder_forward` function, `whisper_decoder_forward ` function,  and remove the restrictions of transformers version in `WhisperPolicy`.

[shardformer] update whisper model

---

colossalai/shardformer/modeling/vit.py

[shardformer/modeling/t5]: Upgrade transformers from version 4.33.0 to version 4.36.0 for the vit model, including the `_encoder_forward` function and the `pp_forward` function.

[shardformer] update vit model

---

colossalai/_analyzer/fx/tracer/tracer.py
colossalai/nn/layer/scaled_softmax.py
examples/tutorial/auto_parallel/auto_parallel_with_resnet.py
examples/tutorial/hybrid_parallel/train.py
examples/tutorial/large_batch_optimizer/train.py
examples/tutorial/opt/opt/run_clm.py
examples/tutorial/sequence_parallel/model/layers/bert_layer.py
examples/tutorial/sequence_parallel/train.py

[hotfix] quick fixes to make legacy tutorials runnable

---

applications/ColossalEval/colossal_eval/evaluate/gpt_evaluate.py
applications/ColossalMoE/train.py
applications/ColossalQA/colossalqa/data_loader/document_loader.py
applications/ColossalQA/colossalqa/local/colossalcloud_llm.py
applications/ColossalQA/colossalqa/local/llm.py
applications/ColossalQA/colossalqa/retrieval_conversation_universal.py
applications/ColossalQA/colossalqa/retriever.py
applications/ColossalQA/colossalqa/utils.py
examples/language/openmoe/model/modeling_openmoe.py
examples/language/openmoe/train.py

Not involved
fix typo s/muiti-node /multi-node etc.
detail info 
modified:   applications/ColossalEval/colossal_eval/evaluate/gpt_evaluate.py
modified:   applications/ColossalMoE/train.py
modified:   applications/ColossalQA/colossalqa/data_loader/document_loader.py
modified:   applications/ColossalQA/colossalqa/local/colossalcloud_llm.py
modified:   applications/ColossalQA/colossalqa/local/llm.py
modified:   applications/ColossalQA/colossalqa/retrieval_conversation_universal.py
modified:   applications/ColossalQA/colossalqa/retriever.py
modified:   applications/ColossalQA/colossalqa/utils.py
modified:   examples/language/openmoe/model/modeling_openmoe.py
modified:   examples/language/openmoe/train.py

[fix] fix typo s/muiti-node /multi-node etc.

---

colossalai/shardformer/modeling/gpt2.py
colossalai/shardformer/policies/gpt2.py
colossalai/shardformer/policies/llama.py
examples/images/vit/vit_benchmark.py
examples/language/llama2/finetune.py
examples/language/llama2/pretrain.py
examples/language/opt/opt_train_demo.py
tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py
tests/test_optimizer/test_dist_lamb.py
tests/test_optimizer/test_nvme.py
tests/test_pipeline/test_schedule/test_interleaved.py
tests/test_pipeline/test_schedule/test_oneF_oneB.py

[hotfix] Improve tester precision by removing ZeRO on vanilla lamb 

---

colossalai/shardformer/modeling/bloom.py
colossalai/shardformer/modeling/falcon.py
colossalai/shardformer/modeling/llama.py
colossalai/shardformer/modeling/mistral.py
colossalai/shardformer/modeling/opt.py
colossalai/shardformer/modeling/t5.py
colossalai/shardformer/modeling/vit.py
colossalai/shardformer/modeling/whisper.py
colossalai/shardformer/policies/mistral.py

[shardformer] fix llama modeling

---

colossalai/zero/low_level/bookkeeping/bucket_store.py
colossalai/zero/low_level/low_level_optim.py
requirements/requirements.txt

[zero] support multiple (partial) backward passes

---

colossalai/_analyzer/fx/codegen.py
colossalai/auto_parallel/offload/base_offload_module.py
colossalai/auto_parallel/offload/region.py
colossalai/autochunk/autochunk_codegen.py
colossalai/fx/codegen/activation_checkpoint_codegen.py
examples/language/gpt/hybridparallelism/data.py

[hotfix] Fix examples no pad token & auto parallel codegen bug;

---

examples/inference/benchmark_ops/benchmark_rmsnorm.py
extensions/csrc/cuda/rms_layernorm_kernel.cu
tests/test_infer/test_ops/cuda/test_rms_layernorm.py

[Inference/Kernel] Feat rmsnorm baichuan2

---

colossalai/shardformer/shard/grad_ckpt_config.py
colossalai/shardformer/shard/shard_config.py

[shardformer] fix pipeline grad ckpt

---

colossalai/inference/batch_bucket.py
colossalai/inference/core/engine.py
colossalai/inference/core/request_handler.py
colossalai/inference/kv_cache/kvcache_manager.py
colossalai/inference/modeling/models/nopadding_llama.py
colossalai/inference/struct.py
colossalai/kernel/triton/no_pad_rotary_embedding.py
tests/test_infer/test_inference_engine.py
tests/test_infer/test_ops/cuda/test_flash_decoding_attention.py

>
1. Fix triton rotary embedding kernels (`rotary_embedding` and `decoding_fused_rotary_embedding`)
2. Fix KVCache alloc shape
3. Sequence max length assignment
4. Sequence status update during Speculative-Decoding
5. Fix pytest (e.g. disable raising ImportError in pytest)
Future TODOs:
1. Fix CUDA kernels - GQA
2. Revise scheduling/Batching as a whole

[Fix/Inference] Fix GQA Triton and Support Llama3

---

colossalai/inference/modeling/policy/nopadding_llama.py
examples/inference/benchmark_llama.py
examples/inference/benchmark_llama3.py
examples/inference/llama_generation.py

>
1. Update Llama3 Config and inference settings in example benchmark.
2. Add llama generation demo script (Llama3)
3. Add a clean-up version of Llama3 benchmark
4. fix init rope in llama policy

[example] Update Llama Inference example

---

colossalai/shardformer/policies/falcon.py
colossalai/shardformer/policies/sam.py
colossalai/shardformer/policies/whisper.py
tests/kit/model_zoo/transformers/whisper.py

[shardformer] fix attn replacement

---

colossalai/context/singleton_meta.py

None
During very large-scale training (especially gpus numer >=1024), it would be a high probability that we get stuck when launching training processes. We found the root cause a deadlock within singleton implementation in multhreading scenarios.

[Fix]: implement thread-safety singleton to avoid deadlock for very large-scale training scenarios

---

colossalai/kernel/triton/context_attn_unpad.py
examples/inference/benchmark_ops/benchmark_context_attn_unpad.py
tests/test_infer/test_ops/triton/test_context_attn_unpad.py

>
New Cache Layout is proposed in this PR https://github.com/hpcaitech/ColossalAI/pull/5643, which improves CUDA Flash Decoding performance.
To modify the whole flows with revised kcache layout (Triton kernel flow and CUDA kernel flows), we're gonna to revise kcache-relatable kernels.
In this PR, support for the new KCache layout is added in context attention triton kernel. The alibi kernel is not updated yet as it's pretty similar to the regular context attention kernel, and it will be refactored and updated as the whole triton …

[kernel] Support new KCache Layout - Context Attention Triton Kernel

---

colossalai/shardformer/modeling/bert.py
colossalai/shardformer/modeling/blip2.py
colossalai/shardformer/modeling/gpt2.py
colossalai/shardformer/modeling/vit.py
colossalai/shardformer/policies/bert.py
colossalai/shardformer/policies/blip2.py
colossalai/shardformer/policies/gpt2.py
colossalai/shardformer/policies/vit.py

[shardformer] support bias_gelu_jit_fused for models

---

colossalai/shardformer/policies/bert.py
colossalai/shardformer/policies/blip2.py
colossalai/shardformer/policies/bloom.py
colossalai/shardformer/policies/falcon.py
colossalai/shardformer/policies/gpt2.py
colossalai/shardformer/policies/gptj.py
colossalai/shardformer/policies/llama.py
colossalai/shardformer/policies/mistral.py
colossalai/shardformer/policies/opt.py
colossalai/shardformer/policies/sam.py
colossalai/shardformer/policies/t5.py
colossalai/shardformer/policies/vit.py
colossalai/shardformer/policies/whisper.py

Added an assertion for the number of attention heads being divisible by the TP size dimension for the Shardformer.

[Shardformer] add assert for num of attention heads divisible by tp_size

---

extensions/csrc/common/mp_type_traits.h
extensions/csrc/funcs/binary_functor.h
extensions/csrc/funcs/cast_functor.h
extensions/csrc/kernel/cuda/context_kv_cache_memcpy_kernel.cu
extensions/csrc/kernel/cuda/flash_decoding_attention_kernel.cu
extensions/csrc/kernel/cuda/fused_rotary_emb_and_cache_kernel.cu
extensions/csrc/kernel/cuda/utils/vec_copy.h

[Inference/Feat] Add kvcache quant support for fused_rotary_embedding_cache_copy

---

extensions/csrc/funcs/cast_functor.h

[Inference] Fix quant bits order

---

colossalai/kernel/triton/context_attn_unpad.py
colossalai/kernel/triton/flash_decoding.py
colossalai/kernel/triton/kvcache_copy.py
colossalai/kernel/triton/no_pad_rotary_embedding.py
examples/inference/benchmark_ops/benchmark_decoding_attn.py
examples/inference/benchmark_ops/benchmark_fused_rotary_embdding_unpad.py
examples/inference/benchmark_ops/benchmark_kv_cache_memcopy.py
tests/test_infer/test_ops/triton/test_decoding_attn.py
tests/test_infer/test_ops/triton/test_kvcache_copy.py
tests/test_infer/test_ops/triton/test_rotary_embdding_unpad.py

>
Add support for new kcache layout(`[num_blocks, num_kv_heads, head_dim // x, block_size, x]`) in relevant triton kernels. Note that this PR only modifies triton kernels in use.
TODO: clean kernel files, remove unused triton kernels.
KV_SEQ_LEN | torch_copy_func | triton_copy_func | triton_new_kcache_layout | cuda_copy_func
-- | -- | -- | -- | --
256.0 | 0.869984 | 0.005952 | 0.008800 | 0.006720
512.0 | 0.866688 | 0.006208 | 0.009088 | 0.006720
1024.0 | 0.872000 | 0.005984 | 0.008832 | 0.006464
2048.0 | 0.868960 | 0.006208 | …

[kernel] Support New KCache Layout - Triton Kernel

---

colossalai/inference/kv_cache/kvcache_manager.py
colossalai/shardformer/policies/llama.py

>
Fix a bug about `kv_head_num` assignment in KVCacheManager, relates with https://github.com/hpcaitech/ColossalAI/pull/5614

[hotfix] Fix KV Heads Assignment in KVCacheManager 

---

colossalai/shardformer/modeling/mistral.py
colossalai/shardformer/modeling/opt.py
colossalai/shardformer/policies/mistral.py
colossalai/shardformer/policies/opt.py

Support parallel output function for shardformer models.

[Shardformer] Add Parallel output for shardformer models

---

examples/language/openmoe/model/modeling_openmoe.py

>
Fix a remaining stuff in #5688 
The issue is caused by refactoring of extension module and the different versions of colossalai installed for example CI tests and unit tests. 

[hotfix] Temporary Fix for OpenMOE Example Import Path

---

colossalai/shardformer/modeling/qwen2.py
colossalai/shardformer/policies/llama.py
colossalai/shardformer/policies/qwen2.py

Fix the num_heads assert for llama model and qwen model, and fix the transformers import in qwen model.
Already tested the test_shard_qwen2.py locally.

[Shardformer]fix the num_heads assert for llama model and qwen model

---

extensions/csrc/kernel/cuda/convert_fp8_kernel.cu
extensions/csrc/kernel/cuda/utils/vec_copy.h
extensions/pybind/inference/inference.cpp
extensions/pybind/inference/inference_ops_cuda.py
tests/test_infer/test_kernels/cuda/test_convert_fp8.py

[Inference/Feat] Add convert_fp8 op for fp8 test in the future

---

colossalai/inference/batch_bucket.py
colossalai/inference/config.py
colossalai/inference/core/engine.py
colossalai/inference/core/request_handler.py
colossalai/inference/logit_processors.py

>
pytest:
**(llama3 8B)Inference Test:**
***repetition_penalty(1.2)***
***repetition_penalty(1.0)***
***repetition_penalty(0.7)***
***no_repeat_ngram_size(1)***
***no_repeat_ngram_size(0)***
***no_repeat_ngram_size(5)***

[Inference]Adapt repetition_penalty and no_repeat_ngram_size

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/nn/optimizer/__init__.py
colossalai/nn/optimizer/distributed_galore.py
colossalai/zero/low_level/low_level_optim.py
docs/source/en/features/distributed_optimizers.md
docs/source/zh-Hans/features/distributed_adafactor.md
docs/source/zh-Hans/features/distributed_optimizers.md
tests/test_optimizer/_utils.py
tests/test_optimizer/test_dist_adafactor.py
tests/test_optimizer/test_dist_came.py
tests/test_optimizer/test_dist_galore.py
tests/test_optimizer/test_dist_lamb.py
tests/test_shardformer/test_model/_utils.py

[misc] update distributed optim docs

---

.github/workflows/doc_test_on_pr.yml
.github/workflows/example_check_on_pr.yml
.github/workflows/example_check_on_schedule.yml

>
Revise example tests timeout value; Add restore ext cache in example build on pr CI.
Future work:
1. Split building of training and inference ops by build args
2. revise extensions

[ci] Fix example tests

---

applications/Colossal-LLaMA/prepare_sft_dataset.py

[Colossal-LLaMA] Fix sft issue for llama2

---

colossalai/inference/config.py
colossalai/inference/core/engine.py
colossalai/inference/core/request_handler.py
colossalai/inference/core/rpc_engine.py
colossalai/inference/executor/rpc_worker.py
colossalai/inference/logit_processors.py
colossalai/inference/sampler.py

[Inference] Fix Inference Generation Config and Sampling

---

colossalai/inference/core/engine.py

[Fix] Add unsupported auto-policy error message

---

colossalai/shardformer/layer/loss.py
colossalai/shardformer/modeling/bloom.py
colossalai/shardformer/modeling/falcon.py
colossalai/shardformer/modeling/gpt2.py
colossalai/shardformer/modeling/llama.py
colossalai/shardformer/modeling/mistral.py
colossalai/shardformer/modeling/opt.py
colossalai/shardformer/policies/bloom.py
colossalai/shardformer/policies/falcon.py

>
Feature Devlopment, No related issue.
Add parallel cross entropy computation to bloom, falcon.

[Shardformer] Add parallel output for shardformer models(bloom, falcon)

---

colossalai/kernel/triton/flash_decoding.py

[Fix] Quick fix on triton kernel code factor

---

examples/inference/llama/benchmark_llama3.py
examples/inference/llama/llama_generation.py

>
In llama example generation and benchmarks, assign dtype when loading checkpoints. Prevent loading with fp32 and converting to fp16, which occupies double amount of host memory. 

[Fix/Example] Fix Llama Inference Loading Data Type

---

colossalai/booster/plugin/gemini_plugin.py
colossalai/zero/gemini/chunk/chunk.py
colossalai/zero/gemini/chunk/manager.py
colossalai/zero/gemini/gemini_ddp.py
tests/test_zero/test_gemini/test_chunkv2.py

>
Previously, enable_async_reduce only overlapped `all_reduce (and rescaling)` and backward computation, but not d2h copy.
This PR reimplements async reduce so that `all_reduce` + `d2h` both can be overlapped with computation.

[gemini] optimize reduce scatter d2h copy

---

extensions/cuda_extension.py

fixes #5534
Added `FORCE_CUDA` environment variable support, to enable building extensions where a GPU device is not present but cuda libraries are.

Allow building cuda extension without a device.

---

tests/kit/model_zoo/transformers/chatglm2.py

[test] fix chatglm test kit

---

colossalai/shardformer/modeling/bloom.py
colossalai/shardformer/modeling/falcon.py

[shardformer] fix modeling of bloom and falcon

---

colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/zero/low_level/low_level_optim.py
colossalai/zero/low_level/low_level_strategy.py
tests/test_moe/moe_utils.py
tests/test_moe/test_moe_zero_fwd_bwd.py
tests/test_moe/test_moe_zero_optim.py
tests/test_zero/test_low_level/test_zero1_2.py

Basically, the original `LowLevelZeroOptimizer` was decoupled into a few classes (`LowLevelZeroOptimizer`, `LowLevelOptStrategyBase`, `LowLevelOptStrategy`, `MoeZeroStrategy`), where each `param_group` and `process_group` are bonded into one `LowLevelOptStrategyBase`.
`LowLevelOptStrategyBase` utilizes previous `XXXStore`s and manages the grad communication and synchronization in low level, and the children classes handle the grad manipulation  (between `working_params` and `master_params`) in tensor level.
In this way, different param_groups might use different zero and comm policies and do not interfere with each other, and they can have their own comm logic.
Other things we can do: refactor `XXXStore`s, previous `XXXStore`s manage all `param_groups` by `group_id`, which is a bit …

[moe/zero] refactor low level optimizer

---

colossalai/zero/low_level/bookkeeping/bucket_store.py
colossalai/zero/low_level/low_level_strategy.py

[zero] remove redundant members in BucketStore

---

colossalai/shardformer/modeling/gpt2.py
colossalai/shardformer/modeling/gptj.py
colossalai/shardformer/modeling/whisper.py
colossalai/shardformer/policies/gptj.py
requirements/requirements.txt

[shardformer]upgrade transformers for gpt2/gptj/whisper

---

colossalai/checkpoint_io/utils.py

[gemini] update transformers for gemini

---

colossalai/checkpoint_io/utils.py
colossalai/inference/modeling/models/glide_llama.py
colossalai/shardformer/modeling/gpt2.py
colossalai/shardformer/modeling/gptj.py
colossalai/shardformer/modeling/llama.py
colossalai/shardformer/modeling/mistral.py
colossalai/shardformer/modeling/whisper.py
colossalai/shardformer/policies/gptj.py
colossalai/shardformer/policies/mistral.py
requirements/requirements.txt
tests/test_infer/test_kernels/cuda/test_rotary_embdding_unpad.py
tests/test_infer/test_kernels/triton/test_rotary_embdding_unpad.py

[shardformer] upgrade transformers to 4.39.3

---

docs/sidebars.json
docs/source/en/features/distributed_optimizers.md
docs/source/zh-Hans/features/distributed_optimizers.md

[misc] Add dist optim to doc sidebar 

---

tests/test_shardformer/test_model/test_shard_command.py

resolved #5834
Change atol in test command-r weight-check to pass 8 GPU pytest

[shardformer] Change atol in test command-r weight-check to pass 8GPU pytest

---

.github/workflows/compatiblity_test_on_dispatch.yml
.github/workflows/compatiblity_test_on_pr.yml
.github/workflows/compatiblity_test_on_schedule.yml
.github/workflows/release_docker_after_publish.yml
.github/workflows/run_chatgpt_examples.yml
.github/workflows/run_chatgpt_unit_tests.yml

[MoE] Resolve .github conflict

---

colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
colossalai/zero/low_level/bookkeeping/bucket_store.py
colossalai/zero/low_level/low_level_optim.py
tests/test_moe/test_moe_zero_fwd_bwd_optim.py

[zero] comments and naming

---

colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/shardformer/modeling/mixtral.py
tests/test_shardformer/test_model/test_shard_llama.py

[test] fix test

---

colossalai/shardformer/policies/deepseek.py

[misc] fix typos

---

colossalai/shardformer/modeling/opt.py

Running examples/language/opt/run_demo.sh throws 
```
File "/home/tanwenxuan/ColossalAI/colossalai/shardformer/modeling/opt.py", line 224, in opt_model_forward
layer_outputs = self._gradient_checkpointing_func(
File "/home/tanwenxuan/.conda/envs/colossalai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'OPTModel' object has no attribute '_gradient_checkpointing_func'. Did you mean: 'gradient_checkpointing_enable'?
```
This is because for OPT, only the decoder has gradient checkpointing (https://github.com/huggingface/transformers/blob/f91c16d270e5e3ff32fdb32ccf286d05c03dfa66/src/transformers/models/opt/modeling_opt.py#L874).
Tell us more if you don't enjoy …

[Hotfix] Fix OPT gradient checkpointing forward 

---

colossalai/pipeline/p2p.py

- Pytorch 2.3.0 added a `group` argument in `_object_to_tensor` function. Updated related use cases in pipeline communication.

[hotfix] Fix object_to_tensor usage when torch>=2.3.0

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/zero/low_level/low_level_optim.py
colossalai/zero/low_level/zero_hook.py
examples/language/performance_evaluator.py
tests/test_zero/test_low_level/test_grad_acc.py
tests/test_zero/test_low_level/test_zero1_2.py

>
Support all-gather overlap with forward.
No-overlap:
Overlap:
GPU Util and SM efficiency is higher.
And according to trace, it's well overlaped:

[zero] support all-gather overlap

---

colossalai/shardformer/modeling/qwen2.py
tests/test_shardformer/test_model/test_shard_qwen2.py

#5853
There is a typo in #5897  and I added the wrong pytest so the build on PR didn't detect that typo. 

[ShardFormer] Fix qwen2 SP typo 

---

applications/ColossalChat/README.md
applications/ColossalChat/coati/dataset/loader.py
applications/ColossalChat/coati/trainer/dpo.py
applications/ColossalChat/coati/trainer/orpo.py
applications/ColossalChat/coati/trainer/rm.py
applications/ColossalChat/coati/trainer/sft.py
applications/ColossalChat/examples/training_scripts/train_dpo.py
applications/ColossalChat/examples/training_scripts/train_orpo.py
applications/ColossalChat/examples/training_scripts/train_rm.py
applications/ColossalChat/examples/training_scripts/train_sft.py
applications/ColossalChat/tests/test_train.sh

[Chat] fix eval: add in training evaluation

---

colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
colossalai/cluster/process_group_mesh.py
colossalai/shardformer/modeling/mixtral.py
colossalai/shardformer/policies/mixtral.py
tests/kit/model_zoo/transformers/mixtral.py
tests/test_shardformer/test_model/test_shard_mixtral.py

[Feature] MoE Ulysses Support

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
examples/language/llama/benchmark.py

[plugin] support all-gather overlap for hybrid parallel

---

colossalai/shardformer/layer/_operation.py

resolve #5920
Currently the FP8 communication in shardformer will have lower accuracy compared with FP16. 
Following [NVIDIA's practice](https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/examples/fp8_primer.html). We have e4m3 forward and e5m2 backward.
| GPT2 finetune(4GPU)     |    Acc |
| :-------- | --------:| 
|FP16  | 0.755 |  
|FP8, e5m2     |   0.737 |  
|FP8, e4m3 forward and e5m2 backward      |    0.752 | 

[Shardformer] Fix Shardformer FP8 communication training accuracy degradation

---

applications/Colossal-LLaMA/prepare_sft_dataset.py

…ssociated with a value
set default value for 'default_conversation'
> 
> `fixed #5930 `
> use ColossalAI-0.4.0 or later, you'll get this error when running prepare_sft_dataset.py 
now I've solved it, I set default value for local variable 'default_conversation'

[FIX BUG] UnboundLocalError: cannot access local variable 'default_conversation' where it is not associated with a value

---

colossalai/quantization/fp8.py
tests/test_fp8/test_fp8_allgather.py

[fp8] support all-gather flat tensor

---

applications/Colossal-LLaMA/train.py

> resolved #5937
For debugging scenarios, saving model files for each epoch would consume a lot of time and disk space, so I think it is necessary to add a parameter for users to choose whether to do so
Now you can use `--skip_save_each_epoch` to skip saving the model checkpoint of each epoch,  just like this:
: )

[Feature] Add a switch to control whether the model checkpoint needs to be saved after each epoch ends

---

colossalai/shardformer/modeling/command.py
colossalai/shardformer/modeling/llama.py
colossalai/shardformer/modeling/mistral.py
colossalai/shardformer/modeling/qwen2.py

[shardformer] hotfix attn mask

---

colossalai/shardformer/layer/attn.py

[shardformer] hotfix attn mask for generation

---

applications/ColossalChat/coati/models/__init__.py
applications/ColossalChat/coati/models/lora.py
applications/ColossalChat/examples/README.md
applications/ColossalChat/examples/training_scripts/lora_config.json
applications/ColossalChat/examples/training_scripts/train_dpo.py
applications/ColossalChat/examples/training_scripts/train_kto.py
applications/ColossalChat/examples/training_scripts/train_orpo.py
applications/ColossalChat/examples/training_scripts/train_ppo.py
applications/ColossalChat/examples/training_scripts/train_rm.py
applications/ColossalChat/examples/training_scripts/train_sft.py
applications/ColossalChat/examples/training_scripts/train_sft.sh
applications/ColossalChat/tests/test_lora.py
applications/ColossalChat/tests/test_train.sh

[Chat] Fix lora

---

applications/ColossalChat/examples/README.md

[hotfix] Update README.md of colossalchat

---

colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/shardformer/policies/auto_policy.py
tests/test_lora/test_lora.py

Make lora support hybrid parallel plugin.

[lora] lora support hybrid parallel plugin

---

colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/zero/low_level/bookkeeping/tensor_bucket.py
colossalai/zero/low_level/low_level_optim.py
tests/test_zero/test_low_level/test_zero1_2.py

>
closed #5960
add fp8 comm for low level zero.
Tested on BERT finetuning.
| Plugin         | Accuracy | F1-score | GPU number |
| -------------- | -------- | -------- | -------- |
| torch_ddp      | 84.4%    | 88.6%    |    2     |
| low level zero-1 + fp8 | 84.3% | 88.5% | 2 |
| low level zero-2 + fp8 | 84.8% | 88.8% | 2 |

[fp8] add fp8 comm for low level zero

---

colossalai/quantization/fp8.py
colossalai/shardformer/layer/_operation.py
colossalai/shardformer/layer/linear.py
colossalai/shardformer/modeling/llama.py
colossalai/shardformer/policies/llama.py
tests/test_fp8/test_fp8_all_to_all.py
tests/test_fp8/test_fp8_all_to_all_single.py
tests/test_fp8/test_fp8_allgather_flat.py
tests/test_fp8/test_fp8_allreduce.py
tests/test_fp8/test_fp8_gather.py
tests/test_fp8/test_fp8_reduce_scatter.py

resolve #5916
Add FP8 support in Llama shardformer and reach loss parity during pretraining task

[Feature] llama shardformer fp8 support

---

colossalai/quantization/fp8.py
tests/test_fp8/test_all_to_all_single.py

[fp8]support all2all fp8

---

colossalai/booster/plugin/fp8_hook.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/quantization/fp8.py
colossalai/tensor/colo_parameter.py
colossalai/tensor/param_op_hook.py
tests/test_fp8/test_fp8_hook.py

[fp8] support fp8 amp for hybrid parallel plugin

---

colossalai/quantization/fp8.py

[fp8] use torch compile (torch >= 2.3.0)

---

colossalai/shardformer/layer/normalization.py

[Hotfix] Avoid fused RMSnorm import error without apex

---

colossalai/shardformer/layer/embedding.py
colossalai/shardformer/layer/linear.py
colossalai/shardformer/layer/qkv_fused_linear.py
colossalai/shardformer/modeling/bert.py
colossalai/shardformer/modeling/bloom.py
colossalai/shardformer/modeling/chatglm2.py
colossalai/shardformer/modeling/command.py
colossalai/shardformer/modeling/gpt2.py
colossalai/shardformer/modeling/gptj.py
colossalai/shardformer/modeling/llama.py
colossalai/shardformer/modeling/qwen2.py
colossalai/shardformer/policies/bert.py
colossalai/shardformer/policies/blip2.py
colossalai/shardformer/policies/bloom.py
colossalai/shardformer/policies/chatglm2.py
colossalai/shardformer/policies/command.py
colossalai/shardformer/policies/falcon.py
colossalai/shardformer/policies/gpt2.py
colossalai/shardformer/policies/gptj.py
colossalai/shardformer/policies/llama.py
colossalai/shardformer/policies/mistral.py
colossalai/shardformer/policies/opt.py
colossalai/shardformer/policies/qwen2.py
colossalai/shardformer/policies/sam.py
colossalai/shardformer/policies/t5.py
colossalai/shardformer/policies/vit.py
colossalai/shardformer/policies/whisper.py

closed #5972
Hybrid parallel plugin and shardformer support fp8 communication, including zero, dp, pp, tp.

[fp8] support hybrid parallel plugin

---

colossalai/quantization/fp8.py
tests/test_fp8/test_fp8_linear.py

[fp8] refactor fp8 linear with compile

---

colossalai/booster/plugin/hybrid_parallel_plugin.py

[Hotfix] Fix sync condition

---

colossalai/booster/plugin/low_level_zero_plugin.py

[plugin] add cast inputs option for zero

---

colossalai/quantization/fp8.py

[fp8] linear perf enhancement

---

colossalai/shardformer/modeling/deepseek.py

[misc] Bypass the huggingface bug to solve the mask mismatch problem

---

colossalai/shardformer/layer/attn.py

>
Schedule the next iteration of KV communication before output rescale, to further hide latency when comm takes longer than compute (e.g. short sequences or inter-node)
**Before this change**
**After**
This is the most compact overlap schedule possible.

[Ring Attention] Overlap kv comm with output rescale

---

colossalai/booster/plugin/low_level_zero_plugin.py

merge feature/fp8_comm to main branch of Colossalai
Merge feature/fp8_comm to main branch of Colossalai

[fp8] merge

---

colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/utils.py
colossalai/inference/core/plugin.py

fix #6019
1. resolve issue: will raise an error on any `unexpected_keys` in `strict` loading
2. reformat the error message. The current code seems to expect a list rather than a string.

[colossalai/checkpoint_io/...] fix bug in load_state_dict_into_model; format error msg

---

colossalai/quantization/fp8.py

[fp8] optimize all-gather

---

colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
colossalai/moe/_operation.py
colossalai/shardformer/modeling/deepseek.py
colossalai/shardformer/modeling/mixtral.py
colossalai/shardformer/policies/deepseek.py
colossalai/shardformer/policies/mixtral.py
examples/language/deepseek/benchmark.py
examples/language/deepseek/data_utils.py
examples/language/deepseek/model_utils.py
examples/language/deepseek/performance_evaluator.py
examples/language/llama/benchmark.py
examples/language/mixtral/benchmark.py
examples/language/mixtral/data_utils.py
examples/language/mixtral/model_utils.py
examples/language/mixtral/performance_evaluator.py
tests/test_moe/moe_utils.py
tests/test_moe/test_moe_checkpoint.py
tests/test_shardformer/test_model/test_shard_deepseek.py
tests/test_shardformer/test_model/test_shard_mixtral.py

[hotfix] moe hybrid parallelism benchmark & follow-up fix

---

colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
colossalai/booster/plugin/torch_ddp_plugin.py
docs/source/en/features/mixed_precision_training_with_booster.md
docs/source/zh-Hans/features/mixed_precision_training_with_booster.md

resolved #6049
Add FP8 training and communication document

[doc] FP8 training and communication document

---

colossalai/kernel/kernel_loader.py
colossalai/shardformer/layer/attn.py

For cases where s_q * s_kv * element size >= 10 GB, dispatch only to the FlashAttentionDaoLoader kernel, and use an empty tensor as a placeholder for the attention_mask. Additionally, only causal and padded causal modes are supported.

[sp] : fix the attention kernel for sp

---

colossalai/shardformer/layer/attn.py

fixed https://github.com/hpcaitech/ColossalAI/pull/6061
Add the lazyload condition for dao flash attention.

[sp] : fix the attention kernel for sp 

---

colossalai/shardformer/modeling/deepseek.py
tests/test_shardformer/test_model/test_shard_deepseek.py

[moe] add parallel strategy for shared_expert && fix test for deepseek

---

colossalai/inference/modeling/policy/nopadding_baichuan.py
colossalai/shardformer/layer/__init__.py
colossalai/shardformer/layer/_operation.py
colossalai/shardformer/layer/linear.py
colossalai/shardformer/layer/qkv_fused_linear.py
colossalai/shardformer/policies/blip2.py
colossalai/shardformer/policies/gpt2.py
colossalai/shardformer/policies/sam.py
tests/test_shardformer/test_layer/test_gpt2_qkv_fused_linear_1d.py
tests/test_shardformer/test_layer/test_qkv_fused_linear_1d.py

[shardformer] fix linear 1d row and support uneven splits for fused qkv linear

---

colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
colossalai/shardformer/layer/_operation.py
colossalai/shardformer/layer/linear.py
colossalai/shardformer/layer/qkv_fused_linear.py
colossalai/shardformer/policies/bert.py
colossalai/shardformer/policies/bloom.py
colossalai/shardformer/policies/chatglm2.py
colossalai/shardformer/policies/gpt2.py
colossalai/shardformer/policies/gptj.py
colossalai/shardformer/shard/shard_config.py
tests/test_shardformer/test_layer/test_gpt2_qkv_fused_linear_1d.py

>
1. remove redundant communication of split-gather style seq parallel
2. save gathered input for ring style seq parallel to avoid extra communication
3. refactor linear 1d
4. remove seq parallel overlap flag, as this communication is removed

[shardformer] optimize seq parallelism

---

applications/ColossalChat/coati/models/loss.py
applications/ColossalChat/coati/models/utils.py
applications/ColossalChat/coati/trainer/dpo.py
applications/ColossalChat/examples/data_preparation_scripts/prepare_dataset.py
applications/ColossalChat/examples/training_scripts/train_dpo.py
applications/ColossalChat/examples/training_scripts/train_sft.py
applications/ColossalChat/tests/test_templating.sh
colossalai/shardformer/modeling/llama.py

[Coati] Train DPO using PP

---

colossalai/pipeline/schedule/interleaved_pp.py
colossalai/pipeline/schedule/one_f_one_b.py

>
Currrent implemention leads to multiple backward passes when outputs have multiple tensors. This PR fix this issue.

[pipeline] hotfix backward for multiple outputs

---

colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/booster/plugin/torch_ddp_plugin.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py

>
Fix the issue when saving lora ckpt using plugin, the saved ckpt is in ColoTensor format thus cannot be successfully loaded using `PeftModel.from_pretrained`.

[hotfix] fix lora ckpt saving format

---

colossalai/amp/naive_amp/mixed_precision_optimizer.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/interface/optimizer.py
colossalai/zero/gemini/gemini_optimizer.py
colossalai/zero/low_level/low_level_optim.py
tests/test_booster/test_plugin/test_3d_plugin.py
tests/test_booster/test_plugin/test_gemini_plugin.py
tests/test_booster/test_plugin/test_low_level_zero_plugin.py

[plugin] support get_grad_norm

---

applications/ColossalChat/README.md

[Hotfix] Update Coati README

---

applications/ColossalChat/coati/reasoner/guided_search/mcts.py
applications/ColossalChat/coati/reasoner/guided_search/prompt_store/base.py
applications/ColossalChat/coati/reasoner/guided_search/prompt_store/qwen.py

[Coati] Refine prompt for better inference

---

colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/zero/low_level/_utils.py
colossalai/zero/low_level/bookkeeping/base_store.py
colossalai/zero/low_level/bookkeeping/tensor_bucket.py
colossalai/zero/low_level/low_level_optim.py
tests/test_zero/test_low_level/test_coll_nd.py
tests/test_zero/test_low_level/test_zero1_2.py
tests/test_zero/test_low_level/test_zero_ckpt.py

[zero] support extra dp

---

colossalai/booster/booster.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/booster/plugin/torch_ddp_plugin.py
colossalai/checkpoint_io/checkpoint_io_base.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/utils.py
colossalai/utils/safetensors.py

[checkpointio] support async model save

---

colossalai/zero/low_level/bookkeeping/bucket_store.py
colossalai/zero/low_level/low_level_optim.py

fixed #6133
Removed redundant memcpy during backward communication. 
Now performance is as expected: 
backward on 1 node: 1.75 s.
backward on 26 nodes: 1.9 s.

[fix] multi-node backward slowdown

---

colossalai/cli/launcher/__init__.py
colossalai/cli/launcher/run.py

[cli] support run as module option

---

.github/workflows/build_on_pr.yml
colossalai/booster/booster.py
colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/torch_fsdp_plugin.py
colossalai/checkpoint_io/checkpoint_io_base.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/moe_checkpoint.py
colossalai/checkpoint_io/utils.py
colossalai/utils/safetensors.py
tests/test_checkpoint_io/test_gemini_checkpoint_io.py
tests/test_checkpoint_io/test_general_checkpoint_io.py
tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py

Add async ckpt api for all the plugin, like save_model, save_optimizer.

[ckpt] Add async ckpt api

---

.github/workflows/build_on_pr.yml
colossalai/booster/booster.py
colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/booster/plugin/torch_ddp_plugin.py
colossalai/booster/plugin/torch_fsdp_plugin.py
colossalai/checkpoint_io/checkpoint_io_base.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/moe_checkpoint.py
colossalai/checkpoint_io/utils.py
colossalai/testing/comparison.py
colossalai/utils/safetensors.py
colossalai/zero/low_level/low_level_optim.py
tests/test_checkpoint_io/test_gemini_checkpoint_io.py
tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
tests/test_checkpoint_io/test_safetensors_async_io.py

[checkpointio] support async save for general/zero

---

applications/Colossal-LLaMA/colossal_llama/dataset/conversation.py
applications/Colossal-LLaMA/colossal_llama/dataset/spliced_and_tokenized_dataset.py
applications/Colossal-LLaMA/colossal_llama/utils/ckpt_io.py
applications/Colossal-LLaMA/train.py
colossalai/lazy/lazy_init.py
colossalai/legacy/communication/p2p.py
colossalai/pipeline/p2p.py
colossalai/pipeline/schedule/interleaved_pp.py
colossalai/pipeline/schedule/one_f_one_b.py
colossalai/shardformer/layer/normalization.py
colossalai/shardformer/modeling/chatglm2.py
colossalai/shardformer/policies/chatglm2.py
colossalai/zero/gemini/gemini_ddp.py
colossalai/zero/gemini/gemini_hook.py
examples/language/bert/benchmark_utils.py
examples/language/bert/finetune.py
examples/language/llama/benchmark.py
extensions/pybind/flash_attention/flash_attention_npu.py

[NPU]support npu

---

colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/nn/optimizer/cpu_adam.py
colossalai/testing/comparison.py
colossalai/utils/safetensors.py
tests/test_checkpoint_io/test_safetensors_async_io.py

[optim] hotfix adam load

---

colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/utils.py

[checkpointio] disable buffering

---

colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/checkpoint_io/checkpoint_io_base.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/utils.py
colossalai/zero/low_level/low_level_optim.py
tests/test_checkpoint_io/test_safetensors_async_io.py

[checkpointio] fix zero optimizer async save memory

---

colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/checkpoint_io/checkpoint_io_base.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/utils.py
colossalai/utils/safetensors.py
colossalai/zero/low_level/bookkeeping/tensor_bucket.py
tests/test_checkpoint_io/test_safetensors_async_io.py
tests/test_optimizer/test_dist_lamb.py

[checkpointio] support debug log

---

requirements/requirements.txt

>
Solve: ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' 
In test machine, peft==0.14 and transformers==4.39 is conflict in import EncoderDecoderCache (which is a new feature in transformers==4.44). So we modify this issue. 
Error detail see: https://github.com/hpcaitech/ColossalAI/actions/runs/12233883342/job/34167440756?pr=6150

[hotfix] fix bug caused by perf version

---

colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/utils.py

[hotfix]fix async io

---

colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
colossalai/booster/plugin/torch_ddp_plugin.py
colossalai/booster/plugin/torch_fsdp_plugin.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/moe_checkpoint.py
colossalai/checkpoint_io/utils.py
colossalai/utils/safetensors.py
colossalai/zero/gemini/gemini_ddp.py
colossalai/zero/gemini/gemini_optimizer.py
tests/test_checkpoint_io/test_gemini_checkpoint_io.py
tests/test_checkpoint_io/test_general_checkpoint_io.py
tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py
tests/test_checkpoint_io/test_torch_ddp_checkpoint_io.py
tests/test_checkpoint_io/test_torch_fsdp_checkpoint_io.py

[checkpointio]support asyncio for all models

---

colossalai/shardformer/layer/normalization.py
docs/source/en/features/distributed_optimizers.md

[Hotfix] hotfix normalization

---

colossalai/utils/safetensors.py

[hotfix] improve compatibility

---

colossalai/booster/booster.py
colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/booster/plugin/torch_ddp_plugin.py
colossalai/booster/plugin/torch_fsdp_plugin.py
colossalai/checkpoint_io/checkpoint_io_base.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/moe_checkpoint.py
colossalai/checkpoint_io/utils.py
tests/test_checkpoint_io/test_gemini_checkpoint_io.py
tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py
tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
tests/test_checkpoint_io/test_safetensors_async_io.py
tests/test_checkpoint_io/test_torch_ddp_checkpoint_io.py

[checkpointio] support non blocking pin load

---

colossalai/booster/plugin/gemini_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/booster/plugin/torch_fsdp_plugin.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/utils.py
tests/conftest.py

>
For a 10B-level DiT model, it reduces load time from ~300s to ~200s (33% speed up).

[checkpointio] support load-pin overlap

---

colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py

fixed #6167 
To prevent #6167, gather the tensor before unpad it if the tensor is both padded and distributed.

[checkpointio] gather tensor before unpad it if the tensor is both padded and distributed

---

.github/workflows/build_on_pr.yml
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
tests/test_pipeline/test_schedule/test_zerobubble_pp.py
tests/test_shardformer/test_model/test_shard_deepseek.py
tests/test_shardformer/test_model/test_shard_mixtral.py

[hotfix] fix hybrid checkpointio for sp+dp

---

colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py

[checkpointio] fix checkpoint for 3d

---

colossalai/shardformer/layer/linear.py
tests/kit/model_zoo/custom/simple_mlp.py
tests/test_optimizer/_utils.py
tests/test_optimizer/test_adam_optim.py
tests/test_optimizer/test_dist_adafactor.py
tests/test_optimizer/test_dist_came.py
tests/test_optimizer/test_dist_galore.py
tests/test_optimizer/test_dist_lamb.py

[CI] Cleanup Dist Optim tests with shared helper funcs 

---

.github/workflows/build_on_pr.yml
.github/workflows/build_on_schedule.yml
.github/workflows/compatiblity_test_on_dispatch.yml
.github/workflows/compatiblity_test_on_pr.yml
.github/workflows/compatiblity_test_on_schedule.yml
colossalai/booster/plugin/hybrid_parallel_plugin.py
colossalai/booster/plugin/low_level_zero_plugin.py
colossalai/booster/plugin/torch_ddp_plugin.py
colossalai/booster/plugin/torch_fsdp_plugin.py
colossalai/checkpoint_io/checkpoint_io_base.py
colossalai/checkpoint_io/general_checkpoint_io.py
colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
colossalai/checkpoint_io/moe_checkpoint.py
colossalai/checkpoint_io/utils.py
colossalai/interface/model.py
colossalai/pipeline/p2p.py
colossalai/shardformer/modeling/deepseek_v3.py
colossalai/shardformer/policies/deepseek_v3.py
examples/language/deepseek/benchmark.py
tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
tests/test_shardformer/test_model/test_shard_deepseek_v3.py

[shardformer] support pipeline for deepseek v3 and optimize lora save

---

colossalai/checkpoint_io/utils.py

[hotfix]fix for async io

---

.github/workflows/run_chatgpt_examples.yml
applications/ColossalChat/README.md
applications/ColossalChat/coati/dataset/loader.py
applications/ColossalChat/examples/training_scripts/lora_finetune.py
applications/ColossalChat/requirements.txt

[application] add lora sft example

---

applications/ColossalChat/coati/experience_maker/naive.py
applications/ColossalChat/coati/trainer/dpo.py
applications/ColossalChat/coati/trainer/grpo.py
applications/ColossalChat/coati/trainer/kto.py
applications/ColossalChat/coati/trainer/orpo.py
applications/ColossalChat/coati/trainer/ppo.py
applications/ColossalChat/coati/trainer/rm.py
applications/ColossalChat/coati/trainer/sft.py

[Chat] fix colossalchat bugs

---

applications/ColossalChat/coati/distributed/consumer.py
applications/ColossalChat/coati/distributed/inference_backend.py
applications/ColossalChat/coati/distributed/utils.py

>
Fit RL style generation by adapting old experience maker code.

[feature] fit RL style generation

---

applications/ColossalChat/examples/README.md

[HotFix] update load lora model Readme;

---

applications/ColossalChat/coati/distributed/consumer.py
applications/ColossalChat/coati/distributed/grpo_consumer.py
applications/ColossalChat/coati/distributed/inference_backend.py
applications/ColossalChat/coati/distributed/launch.py
applications/ColossalChat/coati/distributed/loss.py
applications/ColossalChat/coati/distributed/producer.py
applications/ColossalChat/rl_example.py
colossalai/shardformer/layer/loss.py

[feat] Fix Vllm, logprob, add filtering, temperature annealing, lr descent

---

.gitignore
applications/ColossalChat/coati/distributed/consumer.py
applications/ColossalChat/coati/distributed/grpo_consumer.py
applications/ColossalChat/coati/distributed/inference_backend.py
applications/ColossalChat/coati/distributed/launch.py
applications/ColossalChat/coati/distributed/producer.py
applications/ColossalChat/coati/distributed/reward/reward_fn.py
applications/ColossalChat/coati/distributed/utils.py
applications/ColossalChat/rl_example.py

[feat] Update reward verification

---

colossalai/shardformer/modeling/opt.py
tests/kit/model_zoo/transformers/opt.py

[upgrade]upgrade opt

---

colossalai/shardformer/modeling/vit.py
colossalai/shardformer/modeling/whisper.py
colossalai/shardformer/policies/vit.py
tests/test_infer/test_kernels/cuda/test_rotary_embdding_unpad.py

[upgrade]Upgrade vit

---

colossalai/shardformer/modeling/sam.py

https://github.com/hpcaitech/ColossalAI/issues/6281
Upgrade transformers version from 4.39.3 to 4.51.3.
This PR is for Sam model.
Test:

Upgrade sam

---

colossalai/shardformer/modeling/t5.py

https://github.com/hpcaitech/ColossalAI/issues/6281
Upgrade transformers version from 4.39.3 to 4.51.3.
This PR is for t5 model.
Test result:

Upgrade T5

---

applications/ColossalChat/coati/distributed/launch.py

[fix] fix num update per episode

---

applications/ColossalChat/coati/distributed/consumer.py
applications/ColossalChat/coati/distributed/grpo_consumer.py
applications/ColossalChat/coati/distributed/launch.py
applications/ColossalChat/coati/distributed/producer.py
applications/ColossalChat/requirements.txt
applications/ColossalChat/rl_example.py
colossalai/shardformer/modeling/qwen2.py
requirements/requirements.txt

[feat][npu] Merge form grpo-latest

---

applications/ColossalChat/coati/distributed/consumer.py
applications/ColossalChat/coati/distributed/grpo_consumer.py
applications/ColossalChat/coati/distributed/launch.py
applications/ColossalChat/coati/distributed/producer.py
applications/ColossalChat/coati/distributed/profiling_utils.py
applications/ColossalChat/profiling.sh
applications/ColossalChat/rl_example.py
applications/ColossalChat/visualization.py

[feat[ Support one-behind to reduce bubble time. Add profiling code

---

colossalai/shardformer/layer/attn.py

[Ring Attention] Add more detailed references

---

README.md

update B200 info/img/benchmark
